### DISCUSSION TITLE
Trouble installing / booting Talos from disk

### DISCUSSION THREAD

**Discussion by johnford2002** [siderolabs/talos#10208] [Q&A]
Greetings!

I'm running a small dev lab that runs on HP EliteDesk 800 G4 workstations. I have an instance of netboot.xyz that I'm using to provide PXE network boot. I'm admittedly very new to working with anything related to PXE, but so far, I've had success creating entries for `MAC-xxxxxxxxxxxx.ipxe` and pasting the contents from the Talos Image Factory supplied PXE script.

Here are the contents that I'm currently using:
```
#!ipxe

kernel https://pxe.factory.talos.dev/image/be0a75fe049121ef20f5731862e2bb4a1fb345378fb3cc0a199c0d461bb23bbc/v1.9.1/kernel-amd64 talos.platform=metal console=tty0 init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 printk.devkmsg=on ima_template=ima-ng ima_appraise=fix ima_hash=sha512
initrd https://pxe.factory.talos.dev/image/be0a75fe049121ef20f5731862e2bb4a1fb345378fb3cc0a199c0d461bb23bbc/v1.9.1/initramfs-amd64.xz
boot
```
(I'm guessing there's probably a better way to do the above and would be interested in hearing more there, but that's not the primary focus of my question.)

With that setup, I've managed to successfully bootstrap and apply machine configurations to 3 separate nodes, but although I've specified an install block in the configuration, I'm unable to get any of these nodes to boot without PXE. If I cancel the PXE setup, remove the MAC-specific configs, or even change the boot order to be disk first, I always receive a "BootDevice not found" error.

Here is the install portion of machine configuration:
```
    install:
        disk: /dev/nvme0n1
        image: ghcr.io/siderolabs/installer:v1.9.1
        bootloader: true
        wipe: true
        extraKernelArgs:
            - talos.platform=metal
            - console=tty0
            - init_on_alloc=1 
            - slab_nomerge
            - pti=on
            - consoleblank=0
            - nvme_core.io_timeout=4294967295
            - printk.devkmsg=on
            - ima_template=ima-ng
            - ima_appraise=fix
            - ima_hash=sha512
```

I have also tried omitting all of the kernel args. The configuration validates with the CLI, and it says it applies successfully. I've also tried specifying to use mode reboot after applying. 

1. What is the best way to verify that an installation to disk has take place?
2. How can I appropriately debug the installation process to determine where I'm going wrong?
3. Is there anything glaringly wrong with my setup that would cause my issues?
