### DISCUSSION TITLE
Modifying network configuration, adding ipv6 address

### DISCUSSION THREAD

**Discussion by idc77** [siderolabs/talos#10247] [Q&A] [answered]
I have rented 4 VMs and am trying Talos in a live environment.
There is 1c 3w.
The instances have ipv4 and ipv6 addresses.
When I set them up, DHCP wasn't working and I had to VNC to manually set ipv4 addresses and gateways and dns.

I have applied the new machine config by editing the controlplane.yaml and worker.yaml files and applying them.
The documentation could be better in that regard.

Now I wanted to add the IPv6 addresses to the instances.
However my controlplane.yaml and worker.yaml both have 
```
network: {}
```

when I
```
talosctl get meta -n cp0.remote --talosconfig talosconfig
```
it returns a yaml type response.

```
NODE            NAMESPACE   TYPE      ID     VERSION   VALUE
cp0.remote   runtime     MetaKey   0x0a   1         addresses:
    - address: 2.3.4.5/22
      linkName: enp7s0
      family: inet4
      scope: global
      flags: permanent
      layer: platform
links:
    - name: enp7s0
      logical: false
      up: true
      mtu: 0
      kind: ""
      type: ether
      layer: platform
routes:
    - family: inet4
      dst: ""
      src: ""
      gateway: 1.2.3.4
      outLinkName: enp7s0
      table: main
      scope: global
      type: unicast
      flags: ""
      protocol: static
      layer: platform
hostnames:
    - hostname: cp0.remote
      domainname: ""
      layer: platform
resolvers:
    - dnsServers:
        - 8.8.8.8
      layer: platform
timeServers:
    - timeServers:
        - time.cloudflare.com
      layer: platform
operators: []
externalIPs: []
```

`talosctl edit machineconfig` is the same file as controlplane.yaml or worker.yaml

So...
How do I
- get the current config
- modify the current config
- apply the modified config
?

**Comment by smira** [comment, marked as answer]
So I guess you used the console dashboard to configure the network manually, that's what you see in `talosctl get meta`.

You can leave that as it is, or convert it to machine config (up to you).

Talos [machine configuration](https://www.talos.dev/v1.9/reference/configuration/) is a YAML document which you can modify by [editing](https://www.talos.dev/v1.9/talos-guides/configuration/editing-machine-configuration/) it (it gets downloaded to your editor, and re-applied back with your edits), you can [patch](https://www.talos.dev/v1.9/talos-guides/configuration/patching/) it.

I would pick rather patch it, as it's the easiest way (also, if you're considering production, see these [notes](https://www.talos.dev/v1.9/introduction/prodnotes/#configure-talos), or you can use Omni which automates config management for you). 

So if you look at the [config reference](https://www.talos.dev/v1.9/reference/configuration/v1alpha1/config/#Config.machine.network), you can come up with a patch like:

```yaml
machine:
  network:
   interfaces:
    - interface: enp7s0
       addresses: 
         - 2010:b7b::1/64 # your IPv6 address goes here
```

And patch the machine config with (the easiest way): `talosctl -n <machine IP> patch mc -p @ipv6.patch`

For IPv6 you would probably also need to set up routes, but you can simply adjust the patch to include routes as well.

**Reply by idc77** [reply]
Thank you Andrey :)
Great answer, really appreciate it

**Reply by idc77** [reply]
```
decode error: yaml: line 5: mapping values are not allowed in this context
```

**Reply by idc77** [reply]
Indentation was off
```yaml
machine:
  network:
    interfaces:
      - interface: enp7s0
        addresses:
          - 2010:b7b::1/64 # your IPv6 address goes here
```
