### DISCUSSION TITLE
Privileged System Extensions (/dev/vsock access)

### DISCUSSION THREAD

**Discussion by xvzf** [siderolabs/talos#10262] [Q&A]
Hi there

I'm currently working on a system extension which talks to `/dev/vsock` - I've managed to make everything sort-of working but I'm struggling with permissions on the `/dev/vsock` device.
My prototype is running as a privileged container within Kubernetes itself and I'm wondering if I can configure the system extension in a similar way.

The relevant securityContext on Kubernetes is
```yaml
# ...
securityContext:
  privileged: true
# ...
```

the service definition I've come up with so far is
```
name: talos-lxd-agent
depends:
  - path: /system/run/machined/machine.sock
  - service: cri
security:
  writeableSysfs: true
  rootfsPropagation: true
container:
  entrypoint: ./talos-lxd-agent
  mounts:
    - source: /system/run/machined/machine.sock
      destination: /system/run/machined/machine.sock
      type: bind
      options: [rshared, rbind, rw]
    - source: /dev
      destination: /dev
      type: bind
      options: [rshared, rbind, rw]
    - source: /var/lib/talos-lxd-agent-config
      destination: /var/lib/talos-lxd-agent-config
      type: bind
      options: [ rshared, rbind, rw ]
restart: always
```

Anyone has a suggestion?
