### DISCUSSION TITLE
Talos additional disks provisioning

### DISCUSSION THREAD

**Discussion by gelato** [siderolabs/talos#10294] [Q&A] [answered]
Is there a way to wipe and reformat a disk currently? If I define a disk with machineDisks object, it gets listed in volumes, but in failed state, with console message of filesystem mismatch (filesystem type mismatch: ext4 != xfs), this way kubelet stays in unhealthy state and machine is stuck in booting state.
When I use volume definition like:
```---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: disk.size > 280u * GB
```

Nothing happens, volume is not listed In talosctl get volumestatus, machine just boots like it does not know anything about that VolumeConfig document...

Talos: 1.9.3

**Comment by smira** [comment, marked as answer]
Talos never formats `EPHEMERAL` as `xfs`, so you should be doing something manually? Or attaching a non-empty disk.

Either way, `talosctl wipe disk` might help you.

**Comment by gelato** [comment]
Thanks, I had outdated talosctl it seems, didn't have wipe command in it.
So, this document:
```
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: disk.size > 280u * GB
```
Basically substitutes this definition?
```
disks:
    - device: /dev/disk/by-id/ata-Q100SMRIMY1024_POG351073205
      partitions:
        - mountpoint: /var/mnt/ssd
```

Or I'm not getting something?
