### DISCUSSION TITLE
How to patch CoreDNS config?

### DISCUSSION THREAD

**Discussion by Syntax3rror404** [siderolabs/talos#10329] [Q&A]
Based on the documentation only the following settings are supported. 

```
cluster:
    coreDNS:
        image: registry.k8s.io/coredns/coredns:v1.12.0
        disabled: false
```
Reference: https://www.talos.dev/v1.9/reference/configuration/v1alpha1/config/#Config.cluster.coreDNS

How to change node affinity and tolerations etc?
