### DISCUSSION TITLE
Does anything sent to the syslog receiver get sent to the external logging destinations?

### DISCUSSION THREAD

**Discussion by djryanj** [siderolabs/talos#10356] [Q&A] [answered]
Pretty much the title. It's unclear from the documentation whether things that log to the syslog receiver as of 1.7.0 are included and sent with services logs, e.g.,:

```
machine:
  logging:
    destinations:
      - endpoint: "udp://127.0.0.1:12345/"
        format: "json_lines"
```

This might be obvious from implementing it and examining the logs sent, but the documentation has clear separation between kernel, services, and syslog, but doesn't call out any way to send syslog messages to an external receiver nor does it clarify if it's included in either of the other two. 

Any clarity would be appreciated.
