### DISCUSSION TITLE
Configure allowed container registries

### DISCUSSION THREAD

**Discussion by VirtualEvan** [siderolabs/talos#10371] [Q&A] [answered]
Is there any *allowlist* configuration for registries, or a flag that would forbid access to registries not specified in `machine.registries.config.*`?

I have read, and am currently using, the documentation for configuring mirrors and custom registries
https://www.talos.dev/v1.9/reference/configuration/v1alpha1/config/#Config.machine.registries. However, I haven't been able to find a way to block access to other repos.

Let's say I want my users to be able to pull from our private registry that serves as a pull-through-cache for `docker.io` and contains some custom images. I also want them to be able to pull directly from `mcr.microsoft.com`. So I have the following configuration:

```yaml
machine:
  registries:
    mirrors:
      docker.io:
        endpoints:
          - https://myregistry.example.com/v2/docker.io
        overridePath: true
        skipFallback: true
    config:
      myregistry.example.com:
        auth:
          username: <user>
          password: <pass>
```

This works, but it also allows the user to pull from `registry.malicious.bad`. I am looking for something like:

```yaml
machine:
  registries:
    allowList:
      - myregistry.example.com
      - mcr.microsoft.com
```

or

```yaml
machine:
  registries:
    configuredOnly: true
```

**Comment by smira** [comment, marked as answer]
Yes, there is such way (but not obvious):

1. Configure all allowed registries explicitly.
2. Add `*` (catch-all) entry, and point it to an endpoint which doesn't work (e.g. 127.0.0.1:1), and disable fallback.

Any not explicitly configured registry pull will fall to `*`, fail, will not fallback, and fail completely.

**Reply by zombiemaker** [reply]
Can you provide a full example of this configuration?  Thanks!

**Reply by VirtualEvan** [reply]
@zombiemaker This is the config I tested back then, in case it could be useful

```yaml
machine:
  registries:
    mirrors:
      docker.io:
        endpoints:
          - https://harbor.example.com/v2/docker.io
        overridePath: true
        skipFallback: true
      ghcr.io:
        endpoints:
          - https://harbor.example.com/v2/ghcr.io
        overridePath: true
        skipFallback: true
      gcr.io:
        endpoints:
          - https://harbor.example.com/v2/gcr.io
        overridePath: true
        skipFallback: true
      registry.k8s.io:
        endpoints:
          - https://harbor.example.com/v2/registry.k8s.io
        overridePath: true
        skipFallback: true
      mcr.microsoft.com:
        endpoints:
          - https://harbor.example.com/v2/mcr.microsoft.com
        overridePath: true
        skipFallback: true
      '*':
        endpoints:
          - https://harbor.example.com/v2
        overridePath: true
        skipFallback: true
    config:
      harbor.example.com:
        tls:
          insecureSkipVerify: true
        auth:
          username: harbor
          password: Harbor12345
```
