### DISCUSSION TITLE
How to mount extra disk on a Single KVM ControlPlane instance ?

### DISCUSSION THREAD

**Discussion by FlogFr** [siderolabs/talos#10388] [Q&A] [answered]
Hello,

Thank you for this amazing project !

I am trying to setup a single standalone KVM Instance with Talos on it. I am generating the configuration for the ControlPlan to allowSchedule pods on it. The single machine is well bootstrapped.

I would like to mount /dev/vdb1 on this instance, but I don't find the way if it's possible because : 
- the machine.disks is only present on the machineconfig of a worker and this is the ControlPlane
- I don't find a manual way to mount the /dev/vdb1 to /var/mnt/data
- If I try with the extraMounts of the kubelet of the controlplane machineconfiguration kubelet run into the error that /dev/vdb1 is not a folder (obviously because it is not mounted and is a partition).

I have /dev/vda on ::
```
$ talosctl --talosconfig=./_out/talosconfig -n $VM_IP -e $VM_IP get disks
NODE              NAMESPACE   TYPE   ID      VERSION   SIZE    READ ONLY   TRANSPORT   ROTATIONAL   WWID   MODEL          SERIAL
192.168.122.135   runtime     Disk   loop0   1         74 MB   true                                                       
192.168.122.135   runtime     Disk   sr0     1         0 B     false       sata                            QEMU DVD-ROM   
192.168.122.135   runtime     Disk   vda     1         22 GB   false       virtio      true                               
192.168.122.135   runtime     Disk   vdb     1         11 GB   false       virtio      true                               
```

What is the right way to mount extra disks / volumes on a ControlPlane / single instance ?

Have a great day

**Comment by frezbo** [comment, marked as answer]
`machine.disks` is available for all node types, the `edit mc` just shows examples, refer here: https://www.talos.dev/v1.9/reference/configuration/

**Comment by FlogFr** [comment]
Thank you @frezbo . Indeed, I can edit in the machineconfig the disks as so : 
```
disks:
    - device: /dev/vdb
      partitions:
        - size: 10 GB
          mountpoint: /var/mnt/data
```

Unfortunately, after the reboot, I have the following error from the Volume Manager Controller : 
```
192.168.122.135: user: warning: [2025-02-19T16:57:19.41601912Z]: [talos] volume status {"component": "controller-runtime", "controller": "block.VolumeManagerController", "volume": "/dev/vdb-1", "phase": "failed -> failed", "error": "filesystem type mismatch: ext4 != xfs", "location": "/dev/vdb1", "parentLocation": "/dev/vdb"}
```

These is my partition : 
```
NODE              NAMESPACE   TYPE               ID      VERSION   TYPE        SIZE     DISCOVERED   LABEL       PARTITIONLABEL
192.168.122.135   runtime     DiscoveredVolume   loop0   1         disk        74 MB    squashfs                 
192.168.122.135   runtime     DiscoveredVolume   sr0     1         disk        1.1 GB                            
192.168.122.135   runtime     DiscoveredVolume   vda     1         disk        22 GB    gpt                      
192.168.122.135   runtime     DiscoveredVolume   vda1    1         partition   105 MB   vfat         EFI         EFI
192.168.122.135   runtime     DiscoveredVolume   vda2    1         partition   1.0 MB                            BIOS
192.168.122.135   runtime     DiscoveredVolume   vda3    1         partition   1.0 GB   xfs          BOOT        BOOT
192.168.122.135   runtime     DiscoveredVolume   vda4    1         partition   1.0 MB   talosmeta                META
192.168.122.135   runtime     DiscoveredVolume   vda5    1         partition   105 MB   xfs          STATE       STATE
192.168.122.135   runtime     DiscoveredVolume   vda6    1         partition   20 GB    xfs          EPHEMERAL   EPHEMERAL
192.168.122.135   runtime     DiscoveredVolume   vdb     1         disk        11 GB    gpt                      
192.168.122.135   runtime     DiscoveredVolume   vdb1    1         partition   11 GB    ext4                     primary
```

I have a simple 10Gigas disk that has GPT table on /dev/vdb , and with a 10Gigas primary ext4 partition on /dev/vdb1.

```
node: 192.168.122.135
metadata:
    namespace: runtime
    type: VolumeStatuses.block.talos.dev
    id: /dev/vdb-1
    version: 1
    owner: block.VolumeManagerController
    phase: running
    created: 2025-02-19T16:57:19Z
    updated: 2025-02-19T16:57:19Z
spec:
    phase: failed
    preFailPhase: prepared
    location: /dev/vdb1
    mountLocation: /dev/vdb1
    partitionIndex: 1
    parentLocation: /dev/vdb
    uuid: 3f757298-8256-4dd0-aacd-87e7fbe70428
    partitionUUID: bb7a50cd-1f93-4782-9999-b23427f6ed43
    size: 10735321088
    prettySize: 11 GB
    errorMessage: 'filesystem type mismatch: ext4 != xfs'
```

It seems Talos is trying to look for an xfs and not ext4 partition ?
