### DISCUSSION TITLE
Certificate signed by unknown authority

### DISCUSSION THREAD

**Discussion by xctg-yviel** [siderolabs/talos#10392] [Q&A]
Dear all,

I hope you can help me with an issue we are facing.

- Spin up a talos-v1.9.3 node behind a loadbalancer, behind another loadbalancer
    - `lb_ext` --> `lb_int` --> `talos`
Traffic on TCP 50000 and 6443 get sent from `lb_ext` to `lb_int`, and from there to the ctrlplane node(s).

- Run `talosctl gen secrets -o talos-secrets.yaml -f`
- Run `talosctl gen config --with-secrets talos-secrets.yaml -n $lb_ext_ip -e $lb_ext_ip,$lb_int_ip my-cluster-name https://$lb_ext_ip`
- Run `talosctl gen config --talosconfig talosconfig --output-types controlplane --config-patch @./talos-patch.yaml my-cluster-name https://$lb_ext_ip`
The patch file contains the following:
```
machine:
  certSANs:
    - $lb_ext_ip
    - $lb_int_ip
    - 127.0.0.1
  kubelet:
    extraArgs:
      node-ip: $lb_int_ip

cluster:
  apiServer:
    certSANs:
      - $lb_ext_ip
      - $lb_int_ip
      - 127.0.0.1
  controlPlane:
    endpoint: https://lb_int_ip:6443
```

The result of this is a talos-ctrlplane config which looks just fine, the right IPs are in the `certSANs` fields.
However after bootstrapping it is impossible to communicate with the cluster, the error constantly thrown in the node logs is "Certificate signed by unknown authority". The node status is also NotReady.
I have compared the certificates in `talos-secrets.yaml` to the one in the `talosconfig` and the `talos-ctrlplane` output file, and they are identical.

I am lost as to what I am doing wrong, and would very greatly appreciate a push in the right direction.
Thank you very much in advance.

PS: The Slack invite expired again, I couldn't find a valid one anywhere.
