### DISCUSSION TITLE
How to use an HDD disk to mount /var and /var/lib/longhorn?

### DISCUSSION THREAD

**Discussion by kees-closed** [siderolabs/talos#10407] [General]
From what I can gather, [Disk Management](https://www.talos.dev/v1.9/talos-guides/configuration/disk-management/) is ready? But perhaps not for my use case yet?

I'm using Talos Linux 1.9.2 on Raspberry Pi's and I want to use my external HDD to just mount the /var and also one partition for Ceph. But this is not totally ready? As I can read in [this reply](https://github.com/siderolabs/talos/discussions/10275#discussioncomment-12039325)? I didn't want to post this question in [this](https://github.com/siderolabs/talos/issues/8367) thread. It might pollute the thread there.

This is the disk I have and want to use.

```yaml
[130 17:19:32 kjong@toolbx ~]$ talosctl get disk sda -o yaml -e 172.27.11.14 -n 172.27.11.14
WARNING: : server version 1.9.2 is older than client version 1.9.4
node: 172.27.11.14
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: sda
    version: 1
    owner: block.DisksController
    phase: running
    created: 2025-02-21T16:50:03Z
    updated: 2025-02-21T16:50:03Z
spec:
    dev_path: /dev/sda
    size: 4000787030016
    pretty_size: 4.0 TB
    io_size: 4096
    sector_size: 512
    readonly: false
    cdrom: false
    model: "2135"
    modalias: scsi:t-0x00
    wwid: naa.5000000000000001
    bus_path: /platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb4/4-1/4-1:1.0/host0/target0:0:0/0:0:0:0
    sub_system: /sys/class/block
    transport: usb
    rotational: true
```

I've been trying to decode what yaml config is required. The documentation seems a bit vague. But the pseudo yaml config below is the gist of it. Yes, it won't work. But it's to indicate what I'm trying to accomplish.

```yaml
machine:
  storage:
    disks:
      - diskSelector:
          transport: usb
          rotational: true
        provisioning:
          wipe: true 
          ephemeral: false # But preserve after that
        partitions:
          - size: 160GB
            label: EPHEMERAL
            filesystem: xfs
            mount:
              point: /var
          - size: 0
            label: CEPH
            filesystem: xfs
            mount:
              point: /var/lib/longhorn
    directories:
      - path: /var/lib/longhorn
        mode: 0755
```

Is something like this possible soon? Or is another approach required? Maybe I missed it, but what's currently possible with disk management? And what is on the roadmap? Then I know what to wait for so I don't waste another Sunday on this :)
