### DISCUSSION TITLE
Worker not getting "worker" label?

### DISCUSSION THREAD

**Discussion by nickjanssen** [siderolabs/talos#10414] [Q&A] [answered]
Hello, I have a cluster with 3 controlplanes and just added my first worker node. It seems to work but for some reason the "worker" role is not being applied in kubectl, any idea?

Screenshot:
![CleanShot 2025-02-25 at 07 53 24](https://github.com/user-attachments/assets/3917eaff-ca58-4162-91a1-d0f007ffe4e4)

worker.yaml
```yaml
version: v1alpha1 
debug: false 
persist: true
machine:
  type: worker 
  token: REDACTED
  ca:
    crt: REDACTED    
    key: ""
  certSANs: []
  kubelet:
    image: ghcr.io/siderolabs/kubelet:v1.32.1 
    defaultRuntimeSeccompProfileEnabled: true 
    disableManifestsDirectory: true 
    extraArgs:
      rotate-server-certificates: true
  network:
    interfaces:
      - interface: eth0 
        dhcp: true
      - interface: eno1 
        ignore: true
  install:
    disk: /dev/nvme0n1 
    image: ghcr.io/siderolabs/installer:v1.9.3 
    wipe: false 
  registries: {}  
  features:
    rbac: true 
    stableHostname: true 
    apidCheckExtKeyUsage: true 
    diskQuotaSupport: true     
    kubePrism:
      enabled: true 
      port: 7445     
    hostDNS:
      enabled: true 
      forwardKubeDNSToHost: true 
cluster:
  id: REDACTED 
  secret: REDACTED   
  controlPlane:    
    endpoint: https://talos.homelab:6443 
  clusterName: taloscluster   
  network:
    dnsDomain: cluster.local     
    podSubnets:
      - 10.244.0.0/16    
    serviceSubnets:
      - 10.96.0.0/12
  token: REDACTED 
  ca:
    crt: REDACTED    
    key: ""
  discovery:
    enabled: true     
    registries:      
      kubernetes:
        disabled: true       
      service: {}
      
```

talosctl --nodes 192.168.110.12 get PlatformMetadatas.talos.dev -oyaml
```yaml
node: 192.168.110.12
metadata:
    namespace: runtime
    type: PlatformMetadatas.talos.dev
    id: platformmetadata
    version: 2
    owner: network.PlatformConfigController
    phase: running
    created: 2025-02-24T22:43:42Z
    updated: 2025-02-24T22:43:52Z
spec:
    platform: metal
    instanceId: 00000000-0000-0000-0000-0cc47a9f1e68
```

talosctl --nodes 192.168.110.13 get members
```
WARNING: 192.168.110.13: server version 1.9.2 is older than client version 1.9.3
NODE             NAMESPACE   TYPE     ID              VERSION   HOSTNAME        MACHINE TYPE   OS               ADDRESSES
192.168.110.13   cluster     Member   talos-1fs-hvb   1         talos-1fs-hvb   controlplane   Talos (v1.9.2)   ["192.168.110.14"]
192.168.110.13   cluster     Member   talos-75w-udl   2         talos-75w-udl   worker         Talos (v1.9.3)   ["192.168.110.12"]
192.168.110.13   cluster     Member   talos-tt6-ry7   1         talos-tt6-ry7   controlplane   Talos (v1.9.2)   ["192.168.110.11"]
192.168.110.13   cluster     Member   talos-vue-fnb   2         talos-vue-fnb   controlplane   Talos (v1.9.2)   ["192.168.110.13"]
```
