### DISCUSSION TITLE
purpose of `slaveIndex` metal network configuration option

### DISCUSSION THREAD

**Discussion by vitush93** [siderolabs/talos#10419] [Q&A] [answered]
Hi, looking at [docs](https://www.talos.dev/v1.9/advanced/metal-network-configuration/#network-configuration-format), I'm wondering whats the purpose of `slaveIndex` option and how different configurations behave in practice:

- default for all links is `0` and seems to be working just fine
- difference between defaults (`0`) and incremental indexes as per documentation?
- given 4 links, what would using `0`, `0` and `1`, `1` mean?

example:
```yaml
links:
    - name: eth0
      up: true
      masterName: bond0
      slaveIndex: 0
      layer: platform
    - name: eth1
      up: true
      masterName: bond0
      slaveIndex: 0
      layer: platform
    - name: eth2
      up: true
      masterName: bond0
      slaveIndex: 1
      layer: platform
    - name: eth3
      up: true
      masterName: bond0
      slaveIndex: 1
      layer: platform
```

thank for helping me understand.
