### DISCUSSION TITLE
In the default machineconfig, under install, why is wipe set to false?

### DISCUSSION THREAD

**Discussion by nickjanssen** [siderolabs/talos#10423] [Q&A]
if I were to install talos, why would I not want to wipe the disk? What am missing?

```
  install:
    disk: /dev/nvme0n1 # The disk used for installations.
    image: ghcr.io/siderolabs/installer:v1.9.4 # Allows for supplying the image used to perform the installation.
    wipe: false # Indicates if the installation disk should be wiped at installation time.
```
