### DISCUSSION TITLE
How to create a talos imager with an embeded image cache

### DISCUSSION THREAD

**Discussion by maelle-le-bon** [siderolabs/talos#10446] [Q&A]
Hello,
I am trying to build a custom image disk from a schematic.
The raw image is then converted to qcow2, then upload to proxmox. 

I am using the following schematic:
```yaml
arch: amd64
platform: nocloud
secureboot: false
version: 1.9.4
customization:
  extraKernelArgs:
    - net.ifnames=0
  systemExtensions:
    officialExtensions:
      - siderolabs/iscsi-tools
      - siderolabs/qemu-guest-agent
input:
  kernel:
    path: /usr/install/amd64/vmlinuz
  initramfs:
    path: /usr/install/amd64/initramfs.xz
  baseInstaller:
    imageRef: ghcr.io/siderolabs/installer:v1.9.4
  systemExtensions:
    - imageRef: ghcr.io/siderolabs/qemu-guest-agent:9.2.0
output:
  kind: image
  imageOptions:
    diskSize: 10737418240
    diskFormat: raw
  outFormat: raw

```

When I run the imager and pass my schematic to the imager, the resulting works but the image cache is not created.
```yaml
docker run --rm -i \
    -v $PWD/out:/out \
    -v $PWD/image-cache.oci:/image-cache.oci \
    -v /dev:/dev \
    --privileged \
    "ghcr.io/siderolabs/imager:v1.9.4" - --image-cache /image-cache.oci --image-disk-size 6GiB < ./schematic.yml

[...]
creating disk image...
    creating raw disk of size 11 GB
creating disk image...
    attaching loopback device
creating disk image...
    attached loopback device: /dev/loop0
creating disk image...
    created EFI (C12A7328-F81F-11D2-BA4B-00A0C93EC93B) size 104857600 bytes
creating disk image...
    created BIOS (21686148-6449-6E6F-744E-656564454649) size 1048576 bytes
creating disk image...
    created BOOT (0FC63DAF-8483-4772-8E79-3D69D8477DE4) size 1048576000 bytes
creating disk image...
    created META (0FC63DAF-8483-4772-8E79-3D69D8477DE4) size 1048576 bytes
creating disk image...
    formatting the partition "/dev/loop0p1" as "vfat" with label "EFI"
creating disk image...
    formatting the partition "/dev/loop0p2" as "zeroes" with label "BIOS"
creating disk image...
    formatting the partition "/dev/loop0p3" as "xfs" with label "BOOT"
creating disk image...
    formatting the partition "/dev/loop0p4" as "zeroes" with label "META"
creating disk image...
    copying /usr/install/amd64/vmlinuz to /tmp/imager3890916729/image/boot/A/vmlinuz
creating disk image...
    copying /tmp/imager3890916729/initramfs.xz to /tmp/imager3890916729/image/boot/A/initramfs.xz
creating disk image...
    writing /tmp/imager3890916729/image/boot/grub/grub.cfg to disk
creating disk image...
    executing: grub-install --boot-directory=/tmp/imager3890916729/image/boot --efi-directory=/tmp/imager3890916729/image/boot/EFI --removable --no-nvram --target=x86_64-efi /dev/loop0
creating disk image...
    executing: grub-install --boot-directory=/tmp/imager3890916729/image/boot --efi-directory=/tmp/imager3890916729/image/boot/EFI --removable --no-nvram --target=i386-pc /dev/loop0
[...]
```

However, when I use a predefined profile, `metal` for example, it creates a `IMAGECACHE` partition which doesn't hapened when I used my own schematic :
```
docker run --rm -i \
    -v $PWD/out:/out \
    -v $PWD/image-cache.oci:/image-cache.oci \
    -v /dev:/dev \
    --privileged \
    "ghcr.io/siderolabs/imager:v$VERSION" metal --image-cache /image-cache.oci --image-disk-size 6GiB


creating disk image...
    creating raw disk of size 6.4 GB
creating disk image...
    attaching loopback device
creating disk image...
    attached loopback device: /dev/loop0
creating disk image...
    using OCI image from /image-cache.oci...
creating disk image...
    created EFI (C12A7328-F81F-11D2-BA4B-00A0C93EC93B) size 104857600 bytes
creating disk image...
    created BIOS (21686148-6449-6E6F-744E-656564454649) size 1048576 bytes
creating disk image...
    created BOOT (0FC63DAF-8483-4772-8E79-3D69D8477DE4) size 1048576000 bytes
creating disk image...
    created META (0FC63DAF-8483-4772-8E79-3D69D8477DE4) size 1048576 bytes
creating disk image...
    created IMAGECACHE (0FC63DAF-8483-4772-8E79-3D69D8477DE4) size 5284823040 bytes
creating disk image...
    formatting the partition "/dev/loop0p1" as "vfat" with label "EFI"
creating disk image...
    formatting the partition "/dev/loop0p2" as "zeroes" with label "BIOS"
creating disk image...
    formatting the partition "/dev/loop0p3" as "xfs" with label "BOOT"
creating disk image...
    formatting the partition "/dev/loop0p4" as "zeroes" with label "META"
creating disk image...
    formatting the partition "/dev/loop0p5" as "ext4" with label "IMAGECACHE" <<<< HERE 
creating disk image...
    copying /usr/install/amd64/vmlinuz to /tmp/imager3167300471/image/boot/A/vmlinuz
creating disk image...
    copying /usr/install/amd64/initramfs.xz to /tmp/imager3167300471/image/boot/A/initramfs.xz
creating disk image...
    writing /tmp/imager3167300471/image/boot/grub/grub.cfg to disk
```

What can I add in my schematic in order to create the `IMAGECACHE` partition ?
I'v seen mimilar discutions related to image cache, but nothing about schematics

**Comment by smira** [comment]
This is not a schematic, but an `imager` profile, but it doesn't really mattre.

When you run an `imager`, it with the default args, it prints a profile being used, which you can borrow from to understand how to enable an image cache.

In genera, it's part of `input:`, with something like:

```yaml
input:
  imageCache:
   ociPath: ./my-image-cache.oci
```

https://github.com/siderolabs/talos/blob/7b2f1e23d96d86b0c23254c56b2cdc4159371858/pkg/imager/profile/input.go#L58-L60
