### DISCUSSION TITLE
Unable to Boot Talos OS After Installation on Bare Metal

### DISCUSSION THREAD

**Discussion by Sarapuce** [siderolabs/talos#10449] [Q&A]
Hi,

I'm running into an issue while installing Talos OS on a bare-metal Lenovo ThinkCentre M92p Tiny.

I created a bootable USB stick with the Talos OS installer image (talos without extensions) and booted the machine. Here's what my boot menu looks like:

```
SATA 1: ST320LM010-1KJ15C (HDD/SSD connected to SATA 1) <- My hard drive  
USB Key:  
    Legacy: Lexar USB Flash Drive 1100 <- Doesn't work (black screen)  
    UEFI: Lexar USB Flash Drive 1100 <- This works, so I boot with this option  
```

I went through a fresh installation using UEFI mode, and everything seemed to install correctly. The disk was fully formatted, Talos OS was written to /dev/sdb, and Secure Boot is disabled. I also verified that the correct image was downloaded.

However, after rebooting, the machine fails to boot from the SATA drive, I get a message telling me that no OS was found on the disk. The system is completely unreachable over the network (no ping, no open ports), so it doesn't seem to be just a display issue. When I try to boot again on the USB stick, Talos tells me that Talos is already installed on the other disk, so i have to boot on this other disk

- I checked the installed disk on another machine, and Talos OS is present.
- I successfully booted Ubuntu from the same HDD, so the machine is capable of booting from SATA.
- I tried two different disks, but the issue remains.

### Here are some questions I have:
- Could Talos OS have installed in Legacy mode instead of UEFI?
- Is there a way to force UEFI mode during installation?
- Where can I find logs to debug this?
- Could my configuration file be missing a key setting?

### Talos OS Configuration Used:

```yaml
version: v1alpha1
debug: false
persist: true
machine:
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.31.1
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    install:
        disk: /dev/sdb
        image: ghcr.io/siderolabs/installer:v1.9.4
        wipe: true
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
cluster:
    controlPlane:
        endpoint: https://192.168.1.186:6443
    clusterName: terra
    network:
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
```

And I installed Talos OS with the following command:

```bash
talosctl apply-config --insecure --nodes 192.168.1.185 --file worker.yaml
```

Everything seems to work fine before a reboot : 
- Stage: running
- Ready: true
- Kubelet: Healthy
- Connectivity: ok

One of my guesses is that Talos OS might have installed in Legacy mode, even though I booted the USB stick in UEFI mode. Is there a way to verify this? Any ideas on what could be wrong?

Thanks in advance!
