### DISCUSSION TITLE
Issue with Talos VM (Proxmox) locking up when disconnecting HDMI

### DISCUSSION THREAD

**Discussion by fma965** [siderolabs/talos#10479] [Q&A]
Hey i'm having an issue with Talos VM (Proxmox) locking up when disconnecting HDMI or using a HDMI switch and changing the input.

I passthrough the intergrated Intel GPU (i915) to the VM but when i switch my KVM to another computer the VM locks up, what troubleshooting can i do? 

it just locks up here
![image](https://github.com/user-attachments/assets/0d3f3b0e-0666-44af-97e9-650b99c5f920)
![image](https://github.com/user-attachments/assets/de90097d-1313-4da0-a00a-2ea21ae57405)
![image](https://github.com/user-attachments/assets/3dfb6ed1-9804-404a-be47-f393440f4db4)

```yaml
customization:
  systemExtensions:
    officialExtensions:
      - siderolabs/i915-ucode
      - siderolabs/intel-ucode
      - siderolabs/qemu-guest-agent
      - siderolabs/iscsi-tools
      - siderolabs/util-linux-tools
```
anyone have any ideas?
