### DISCUSSION TITLE
Eviction time change if node down

### DISCUSSION THREAD

**Discussion by suse-coder** [siderolabs/talos#10540] [Q&A] [answered]
How in talos can i set the eviction time down when a node is off. Currently when a node is down it takes some time until it is marked as NotReady and then it waits minutes after the current pods are rescheduled on a different node.

What is the best way to set these in talos?
--node-monitor-grace-period=1s
--node-monitor-period=1s
--pod-eviction-timeout=1s

**Comment by smira** [comment, marked as answer]
See https://www.talos.dev/v1.9/reference/configuration/v1alpha1/config/#Config.machine.kubelet

Kubernetes recommends using config vs. the command-line flags.

**Reply by suse-coder** [reply]
So like this?:
```
machine:
  kubelet:
    extraArgs:
      node-monitor-grace-period: "1s"
      node-monitor-period: "1s"
      pod-eviction-timeout: "1s"
```

**Reply by smira** [reply]
You need to consult Kubernetes documentation on specific values.

**Reply by suse-coder** [reply]
```
machine:
  kubelet:
    extraArgs:
      node-status-update-frequency: 2s  # Default is 10s
cluster:
  controlPlane:
    controllerManager:
      extraArgs:
        node-monitor-period: 2s 
        node-monitor-grace-period: 10s  
        pod-eviction-timeout: 30s  
        node-eviction-rate: 0.5  
 ```
 if i want to turn down the  pod-eviction-timeout is that above correct?
