### DISCUSSION TITLE
Set flannel backend to host-gw

### DISCUSSION THREAD

**Discussion by mayasBK** [siderolabs/talos#10553] [Q&A]
Hi,

the documentation states that in order to set the flannel backend-type to host-gw you should apply this patch:
https://www.talos.dev/v1.9/talos-guides/install/virtualized-platforms/vmware/#validate-the-configuration-files
```yaml
cluster:
  network:
    cni:
      extraArgs:
        - --flannel-backend=host-gw
```

Unfortunately this seems to be not correct. Talos keeps adding this node annotation:
```
flannel.alpha.coreos.com/backend-type: vxlan
```

Is there any documentation about this machineconfig somewhere else? Thank you :)
