### DISCUSSION TITLE
Ingress Firewall blocks ipv4 traffic from NAT network with Kubespan.

### DISCUSSION THREAD

**Discussion by jonsch318** [siderolabs/talos#10635] [Q&A]
Hello everyone,
I have setup a cluster with two public control nodes and one at home with ipv4 NAT (and ipv6). 

It think it worked at first, but now i can't access any node over ipv4 from my home network. From other networks or when explicitly setting the endpoint to an ipv6 I can access talos.
 
I have set it up with kubespan and wanted to only allow everything over kubespan except `50000` and `6443` which should be public. However I am a bit confused which ingresses firewall rules are needed when using kubespan and what i should set KubeSpanEndpointConfig to in my case. As I understand it node-to-node traffic over Kubespan is always allowed with ingress firewall so that my config looks like:

```yaml
machine:
  network:
    kubespan:
      enabled: true
      advertiseKubernetesNetworks: false
      allowDownPeerBypass: false
[...]
---
apiVersion: v1alpha1
kind: NetworkDefaultActionConfig
ingress: block
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: apid-ingress
portSelector:
  ports:
    - 50000
  protocol: tcp
ingress:
  - subnet: 0.0.0.0/0
  - subnet: ::/0
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: kubernetes-api-ingress
portSelector:
  ports:
    - 6443
  protocol: tcp
ingress:
  - subnet: 0.0.0.0/0
  - subnet: ::/0
---
```
Obviously I am missing something to allow ipv4 from my network that is not using kubespan since the kubespanpeerstatus says up.  This is true aswell when I set default action config accept without any rules
Thanks
