### DISCUSSION TITLE
Question about 1.10 and storage

### DISCUSSION THREAD

**Discussion by Syntax3rror404** [siderolabs/talos#10634] [General]
Because of 1.10 gets a new disk layout system, I have a question about a running system and the upgrade to 1.10.

I use Rook as storage solution. Each node has two dedicated nvme disks. One small for the os, and another big one for rook exclusively.

This is in short, what the machineconfig looks like. 
```yaml
machine:
    extraMounts:
      - destination: /var/lib/rook
        type: bind
        source: /var/lib/rook
        options:
          - bind
          - rshared
          - rw
  disks:
    - device: "/dev/disk/by-id/nvme-WD_BLACK_SN770_2TB_241834802467"
      partitions:
        - mountpoint: /var/lib/rook
          size: 1800 GB # overprovisioning for a healthy drive
```

The question is now, how to upgrade to the new disk system, when its released. 

Thanks!
