### DISCUSSION TITLE
Unable to apply firewall configuration

### DISCUSSION THREAD

**Discussion by spuxx-dev** [siderolabs/talos#10652] [Q&A] [answered]
I am unable to update my talos node's firewall configuration. Say I have a file `firewall.yaml` with this content:

```yaml
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: http
portSelector:
  ports:
    - 80
    - 443
  protocol: tcp
ingress:
  - subnet: 0.0.0.0/0
  - subnet: ::/0
```

And I run `talosctl apply -f firewall.yaml -n <node_ip> --mode=try`, I get:
```
rpc error: code = InvalidArgument desc = new config is not v1alpha1
```
What am I doing wrong?
