### DISCUSSION TITLE
Talos on Ubuntu – Resetting Node to Initial State for Reapplying Config

### DISCUSSION THREAD

**Discussion by kubebn** [siderolabs/talos#10737] [General]
Hi,

I’m currently experimenting with deploying Talos on top of Ubuntu. Here's what I'm doing:

```bash
apt install kexec-tools -y
wget -O /tmp/vmlinuz https://github.com/siderolabs/talos/releases/latest/download/vmlinuz-amd64
wget -O /tmp/initramfs.xz https://github.com/siderolabs/talos/releases/latest/download/initramfs-amd64.xz
IP=$(ip -o -4 route get 8.8.8.8 | awk -F"src " '{sub(" .*", "", $2); print $2}')
GATEWAY=$(ip -o -4 route get 8.8.8.8 | awk -F"via " '{sub(" .*", "", $2); print $2}')
ETH=$(ip -o -4 route get 8.8.8.8 | awk -F"dev " '{sub(" .*", "", $2); print $2}')
CIDR=$(ip -o -4 addr show "$ETH" | awk -F"inet $IP/" '{sub(" .*", "", $2); print $2; exit}')
NETMASK=$(echo "$CIDR" | awk '{p=$1;for(i=1;i<=4;i++){if(p>=8){o=255;p-=8}else{o=256-2^(8-p);p=0}printf(i<4?o".":o"\n")}}')
DEV=$(udevadm info -q property "/sys/class/net/$ETH" | awk -F= '$1~/ID_NET_NAME_ONBOARD/{print $2; exit} $1~/ID_NET_NAME_PATH/{v=$2} END{if(v) print v}')

CMDLINE="init_on_alloc=1 slab_nomerge pti=on console=tty0 console=ttyS0 printk.devkmsg=on talos.platform=metal ip=${IP}::${GATEWAY}:${NETMASK}::${DEV}:::::"
echo $CMDLINE
init_on_alloc=1 slab_nomerge pti=on console=tty0 console=ttyS0 printk.devkmsg=on talos.platform=metal ip=10.1.1.88::10.1.1.1:255.255.255.0::enp0s18:::::

kexec -l /tmp/vmlinuz --initrd=/tmp/initramfs.xz --command-line="$CMDLINE"
kexec -e
```

After that, I apply the Talos config as usual.

talosctl apply -f worker.yaml

```yaml
    network:
        interfaces:
          - interface: enp0s18
            addresses:
            - 10.1.1.88/24
            routes:
            - network: 0.0.0.0/0
              gateway: 10.1.1.1
        nameservers:
            - 1.1.1.1
            - 1.0.0.1
```

Now, I’m trying to reset the node using talosctl reset (`talosctl reset -n 10.1.1.88 --reboot --graceful=false --system-labels-to-wipe STATE --system-labels-to-wipe EPHEMERAL`), and my goal is to return it to the initial state, essentially the same state as right after the initial boot—so that I can reapply the Talos config to the same IP (the one defined earlier via the ip= kernel parameter). Currently, it fails as like there is no network configured, and I don't have dhcp deployed.

Is there a supported way to do this? Or a recommended approach to achieve this reset-to-initial-state behavior?

Thanks!
