### DISCUSSION TITLE
Dhcp causes no route to host errors

### DISCUSSION THREAD

**Discussion by Rick-van-Dam** [siderolabs/talos#10759] [Q&A]
I have a virtual machine in proxmox with 2 network devices, one for VLAN 3100 and one for VLAN 4000. My idea is to use one for public (still local network but less restricted) and one for private.

I have this interface config for my machine:
```
    interfaces:
      - interface: eth0
        addresses:
          - 192.168.2.34/27
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.2.32
      - interface: eth1
        addresses:
          - 192.168.2.10/27
```

I also followed https://www.talos.dev/v1.9/introduction/prodnotes/#multihoming so I got this config as well:

```
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.32.0
        defaultRuntimeSeccompProfileEnabled: true
        nodeIP:
            validSubnets:
                - 192.168.2.32/27
```
```
    etcd:
        ca:
            crt: secret
            key: secret
        advertisedSubnets:
            - 192.168.2.32/27
```      

This works and I see no errors or warnings. The machine is pingable and its possible to run workloads and reach them from the browser.

When I change it to use dhcp for eth1:
```
    interfaces:
      - interface: eth0
        addresses:
          - 192.168.2.34/27
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.2.32
      - interface: eth1
        dhcp: true
```
I see the machine correctly gets an ip and is pingable on `192.168.2.34` and the ip that dhcp got for eth1. I do see alot of no route to host warnings (mostly from the time.SyncController). After a reboot the kubelet is stuck in unhealthy, as soon as I change the config back and apply it again everything starts up correctly and the warnings go away.      

What can cause this? Do I need more config for talos to make dhcp work correctly? How come putting a static ip works with no issues?
