### DISCUSSION TITLE
Enable ipv6 router advertisments

### DISCUSSION THREAD

**Discussion by nlindblo** [siderolabs/talos#10786] [Q&A]
Firstly, I never had a reason to fully understand ipv6, so apologies if something in my question doesnt make sense. I have an application that requires the pod to run on the host network and see ipv6 routes advertised (python matter server for home assistant if relevant). I have tried all sort of combinations with sysctls values, but cannot seem to get this working. I can see the route on my mac on the same network, so I am confident that its advertised correctly and that its Talos not processing it.

I currently have this in my machine config

````
machine:
    sysctls:
      net.ipv6.conf.ens3.disable_ipv6: "0"
      net.ipv6.conf.ens3.accept_ra: "2"
````      
Has anyone got this working and can give some hints on what to configure for ipv6 RA to be processed ?
