### DISCUSSION TITLE
How to update node IP addresses?

### DISCUSSION THREAD

**Discussion by v1nsai** [siderolabs/talos#10798] [Q&A] [answered]
I've got a 2 node cluster and recently had to re-flash the router, so my node IP addresses have changed.  I tried adding the following to node1's machineconfig:

```yaml
cluster:
    extraArgs:
        initial-cluster: node1=http://192.168.1.151:2380,node2=http://192.168.1.235:2380
        initial-advertise-peer-urls: http://192.168.1.151:2380
        listen-peer-urls: http://192.168.1.151:2380
```

However I still see it trying to connect to node2 at the old IP address in the etcd logs:

```json
192.168.1.151: {"level":"warn","ts":"2025-04-25T00:57:06.692867Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_SNAPSHOT","remote-peer-id":"ccc983fd1aef78e5","rtt":"0s","error":"dial tcp 192.168.1.161:2380: connect: no route to host"}
```

As far as I can tell this is how you get two etcd nodes to talk to each other after IP addresses change, am I missing something?
