### DISCUSSION TITLE
ClusterAPI provisioning failure due to machine configuration never recognized

### DISCUSSION THREAD

**Discussion by eriknelson** [siderolabs/talos#10885] [Q&A]
## Background

I'm trying to bring up a Talos Linux cluster inside of my Proxmox machine using
ClusterAPI and the following stack:

* kind v0.27.0 go1.23.6 linux/amd64 - management cluster
* ClusterAPI: v1.10.1
* Target Kubernetes version: v1.33.0
* cluster-api-bootstrap-provider-talos: v0.6.9
* cluster-api-control-plane-provider-talos: v0.5.10
* ionos-cloud/cluster-api-provider-proxmox: v0.7.0

* cluster-api-ipam-provider-in-cluster: v1.0.1

Starting from scratch, I follow this sequence:
- Provisioned the Proxmox user and created a VM template with the talos
`metal-amd64.iso`.
- Bring up the kind cluster and create `capi-system` namespace
- Create a secret with my proxmox coordinates + creds (token-name,secret,url)
- Install CAPI:
  - ```bash
    clusterctl init \
      --infrastructure proxmox \
      --bootstrap talos \
      --control-plane talos \
      --ipam ipam-in-cluster \
      --target-namespace capi-system \
      --core cluster-api:${CAPI_CORE_VERSION}
    ```
- Apply my manifests [1]

Right now, I'm just trying to get a single control plane node launched and
healthy, recognized by capi so that I can prove out the plumbing works. There
lies the problem...

## Issue

I want to bring up my nodes on the Proxmox bridge such that each of the machines
are as if they're just other machines on my LAN (but outside of the DHCP range).
While I don't really need the ability to dynamically assing IPs in this scenario
since the cluster is quite small (single cp node, 2 workers), and I could
hardcode the IP, I'd like to understand the idiomatic way to be allocating ips
to the machines from pools. Right now, the problem is that the machine comes up,
ignores my network configuration, defaults to DHCP, and nothing can find it
despite the node actually being quite happy. I have no access to it via talosctl.
Putting that aside however, even when I attempt to statically configure the
control plane's ip address via a config patch, it is totally ignored, and its
not just this setting; it's everything. My custom machine configs are plainly
not getting recognized by Talos upon startup of the very first node. I've read
that there's some kind of a distinction in the `TalosControlPlane` object
between `init` and `controlplane` sections, and I've attempted both configuring
`init` (with the suggestion that the very first node utilizes `init` instead of
`controlplane`), and the `controlplane` section to no avail.

Notably, I can _see_ in the bootstrap secret that my configured machineconfig
is correct. That tells me the issue has nothing to do with patches. There is
some kind of breakdown between the providers in a way that causes the config
to fail to be delivered to startup for some reason.

I don't quite understand the details about how this is expected to work. I see
a lot of vague or conflicting information about using a cloud-init drive, maybe
user-data that's _not_ a cloud-init drive. It's supposedly the responsibility
of the proxmox provider to attach a disk with the secret's contents to the
machine when it starts, and talos _should_ be able to recognize the disk, mount
it, and read from it. Again, notably **I can see a user-data disk attached to
the node when it starts**. So I _think_ the proxmox provider is trying to do
what it's supposed to be doing, but it's possible I need to establish the linkage
somehow, maybe with some configuration on a talos resource to point it to where
it needs to look to find this, or proxmox isn't doing it in the way that talos
expects. Unsure about this.

I'd love to understand the expected sequence here, the different options I have
available to me to be able to configure the machine (because I know I'm going
to have to configure a bunch about this and I need to get this mechanism
rock-solid). Also just need someone to point me in the right direction, either
with a solution, or an approach to diagnosing this. I don't have enough information
at this point to even tell if this is a breakdown on the proxmox, or talos side. I'm
also pretty certain this really has nothing to do with base Talos, and is a pretty
specific CAPI question, but any help appreciated.

Thank you!

## References

[1] Cluster definition

```yaml
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: terra
  namespace: capi-system
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: terra-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxCluster
    name: terra
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: terra
  namespace: capi-system
spec:
  credentialsRef:
    name: prox-credentials
    namespace: capi-system
  allowedNodes:
  - rift
  controlPlaneEndpoint:
    host: 172.16.127.1
    port: 6443
  dnsServers:
  - 172.16.254.1
  - 172.16.0.1
  ipv4Config:
    # This has been a bit confusing, but the decision is to keep the
    # range here for the workers. It's really only necessary to move
    # to a load balancer for a multi-master setup, and there's several
    # options for that:
    # - static leases MAC -> known ip addresses
    # - still seems viable to keep the IPAM assingments, which require
    # the annotation inside of the machine template metadata.annotations.
    # Supposedly the capmox provider should configure the ip based on that.
    # It'll also end up in the status.
    addresses: ["172.16.127.2-172.16.127.3"]
    gateway: 172.16.0.1
    prefix: 16
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: terra-control-plane
  namespace: capi-system
spec:
  version: v1.33.0
  replicas: 1
  infrastructureTemplate:
    kind: ProxmoxMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    name: terra-control-plane
    namespace: capi-system
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      configPatches:
        - op: add
          path: /machine/install/extraKernelArgs
          value:
            - net.ifnames=0
        - op: add
          path: /machine/network/interfaces
          value:
            # Have tried many different combinations here with a thought that
            # I just had the interface name wrong since it renames to use
            # "predictable" naming. Attempted to disable that above as well,
            # but again, none of this actually matters. Talos never sees anything
            - interface: eth0
              dhcp: false
              addresses:
                - "172.16.127.1/16"
              gateway: 172.16.0.1
              nameservers:
                - 172.16.254.1
                - 172.16.0.1
        - op: add
          path: /machine/features/qemuGuestAgent
          value: true
    # Attempted this, not clear when it's required to use init vs. controlplane
    # Doesn't even matter, nothing is ever picked up by talos.
    # init:
    #   generateType: install
    #   configPatches:
    #     - op: add
    #       path: /machine/install/extraKernelArgs
    #       value:
    #         - net.ifnames=0
    #     - op: add
    #       path: /machine/network/interfaces
    #       value:
    #         - interface: eth0
    #           dhcp: false
    #           addresses:
    #             - "172.16.127.1/16"
    #           gateway: 172.16.0.1
    #           nameservers:
    #             - 172.16.254.1
    #             - 172.16.0.1
    #     - op: add
    #       path: /machine/features/qemuGuestAgent
    #       value: true
---
# Not sure how to use this 100%, ideally I'd be able to establish two pools:
# - One for the control plane node range
# - One for the worker range
# - Add the annotation to the machine templates
# - Dynamically configure the machine template using go templates that read
# from the IPAM assigned ip address(?)
# Pretty much irrelevant for the purposes of this example however; the config
# is not recognized.
apiVersion: ipam.cluster.x-k8s.io/v1alpha2
kind: InClusterIPPool
metadata:
  name: terra-worker-ip-pool
  namespace: capi-system
spec:
  addresses: ["172.16.127.2-172.16.127.3"]
  gateway: 172.16.0.1
  prefix: 16
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: terra-control-plane
  namespace: capi-system
spec:
  template:
    spec:
      disks:
        # This is questionable. In my template, I have the boot order:
        # ide1,scsi0
        # where ide1 is the talos iso
        # I know that the `user-data` disk is mounted as ide0
        # I don't even particularly care about a persistent os volume, all of
        # it should be ephemeral "cattle". But the key relevance I believe is
        # how talos attempts to load the config for the controlplane node.
        bootVolume:
          disk: scsi0
          sizeGb: 30
      format: qcow2
      full: true
      memoryMiB: 30720
      network:
        default:
          bridge: vmbr2
          model: virtio
      numCores: 4
      numSockets: 1
      sourceNode: rift
      templateID: 9000
```
