### DISCUSSION TITLE
UserVolumeConfig Unit size???

### DISCUSSION THREAD

**Discussion by DrummyFloyd** [siderolabs/talos#10947] [Q&A] [answered]
i don't find anything related to the Unit used for the `UserVolumeConfig`

it's only limited to `GiB` or we can use some Human readable size like `GB`

which one is recommended ? 

```yaml
apiVersion: v1alpha1
kind: UserVolumeConfig
name: ceph-data # Name of the volume.
# The provisioning describes how the volume is provisioned.
provisioning:
    # The disk selector expression.
    diskSelector:
        match: disk.transport == "nvme" 
    maxSize: 50GiB #
    ...
   ```
