### DISCUSSION TITLE
How to change Apiserver feature flags after bootstrap

### DISCUSSION THREAD

**Discussion by Xnyle** [siderolabs/talos#10968] [Q&A] [answered]
I need to get the following change propagated to the apiserver

```
cluster:
  apiServer:
    extraArgs:
      # needed for k8s talos registry to work (changed with k8s 1.32 to default true)
      feature-gates: AuthorizeNodeWithSelectors=false 
```
Referenced here https://github.com/siderolabs/talos/issues/9980

Changing the machine config after bootstrap does not add the flag to the apiserver cmdline options.

Updating k8s does not work either (mentioned here but for another use case)

https://github.com/siderolabs/talos/issues/10923#issuecomment-2858305802

https://www.talos.dev/v1.10/kubernetes-guides/upgrading-kubernetes/ explains how to change machine config manually and checking apiserver config.

```
talosctl -n <CONTROL_PLANE_IP_1> get apiserverconfig -o yaml
```

But not if and how it is possible to directly change and back apply that pod config.

Trying to change the running pod config via kubectl is also not possible as k8s forbids changing the required field while the pod is running.

So how can i add a feature flag to an already deployed and running apiserver?
