### DISCUSSION TITLE
Image pull from factory.talos.dev does not work on Talos node

### DISCUSSION THREAD

**Discussion by aeleks** [siderolabs/talos#10984] [General]
Hi,

my Talos OS can pull docker images normally from any registry, but factory.talos.dev and I don't know how to debug the issue further. My laptop can docker pull the exact image.

Talos:
`
➜ talosctl images pull nginx -n node01.prod.gallifrey.local

➜ talosctl images pull factory.talos.dev/metal-installer/def336ea9dcf27176acacc021de46490035de9d7750fd260806e0a6d8d7a6f68:v1.10.1 -n node01.prod.gallifrey.local
`
Laptop:
`
➜ docker pull factory.talos.dev/metal-installer/def336ea9dcf27176acacc021de46490035de9d7750fd260806e0a6d8d7a6f68:v1.10.1
v1.10.1: Pulling from metal-installer/def336ea9dcf27176acacc021de46490035de9d7750fd260806e0a6d8d7a6f68
Digest: sha256:c2f263a4773ad32ec4a6743b7ecf898dad50625ac1c86111f78fc0d0b374dd97
Status: Image is up to date for factory.talos.dev/metal-installer/def336ea9dcf27176acacc021de46490035de9d7750fd260806e0a6d8d7a6f68:v1.10.1
factory.talos.dev/metal-installer/def336ea9dcf27176acacc021de46490035de9d7750fd260806e0a6d8d7a6f68:v1.10.1
`

When using this image with 

`
➜ talosctl upgrade -n node01.prod.gallifrey.local --image factory.talos.dev/metal-installer/def336ea9dcf27176acacc021de46490035de9d7750fd260806e0a6d8d7a6f68:v1.10.1 --force
`

the dashboard shows

`
 user: warning: [2025-05-09T21:36:07.039181137Z]: level=info msg=fetch failed error=failed to do request: Head "https://images.factory.talos.dev/v2/image-factory/metal-installer/
 def336ea9dcf27176acacc021de46490035de9d7750fd260806e0a6d8d7a6f68/manifests/sha256:c2f263a4773ad32ec4a6743b7ecf898dad50625ac1c86111f78fc0d0b374dd97": net/http: TLS handshake
 timeout host=factory.talos.dev image=factory.talos.dev/metal-installer/def336ea9dcf27176acacc021de46490035de9d7750fd260806e0a6d8d7a6f68:v1.10.1
 user: warning: [2025-05-09T21:36:07.042248137Z]: [talos] retrying error: failed to pull image "factory.talos.dev/metal-installer/
 def336ea9dcf27176acacc021de46490035de9d7750fd260806e0a6d8d7a6f68:v1.10.1": failed to resolve reference "factory.talos.dev/metal-installer/
 def336ea9dcf27176acacc021de46490035de9d7750fd260806e0a6d8d7a6f68:v1.10.1": failed to do request: Head "https://images.factory.talos.dev/v2/image-factory/metal-installer/
 def336ea9dcf27176acacc021de46490035de9d7750fd260806e0a6d8d7a6f68/manifests/sha256:c2f263a4773ad32ec4a6743b7ecf898dad50625ac1c86111f78fc0d0b374dd97": net/http: TLS handshake
 timeout
`

Which does't make any sense, because my Kubernetes pods can resolve the domain, and Talos and my Laptop use the same dns servers (1 local hosted - which can actually resolve this domain, but also 8.8.8.8)

Do you have any further clues or an idea what else I can provide to you? 

Thank you in advance!

**Comment by aeleks** [comment]
Background why I want that: I have an intel cpu with intel arc and i want to use hardware transcoding with the intel i915 extension

**Comment by rothgar** [comment]
Was this the first time you tried to pull that image? Images are built by the image factory and then cached in a CDN but sometimes the first pull times out.

I was able to pull the image from my computer, but if you are getting repeat errors it would be something to look into.

**Comment by aeleks** [comment]
Thank you for your quick response!

I have tried it multiple times (5-6 times) distributed over about 1 hour, since I really wanted it to work.

I also tried it right now 3 times, for about 10 minutes. Same error I am afraid.

**Reply by rothgar** [reply]
I'm able to pull that image from my machines. The log looks like it has a space in the image name. Are you able to `docker pull` the image? You can also try `talosctl image pull`

**Reply by aeleks** [reply]
I can docker pull this yes.

I have also tried talosctl image pull (see the log in the issue description at the beginning, it is the second command). It does not work, for over 10 minutes, but nginx can be pulled without issues. talosctl image pull does not provide any logs sadly.

I also thought about the space, but sadly no :( It works with the regular image.

I also ruled out version (I tried it with 1.9.6 as well)

**Reply by rothgar** [reply]
What about running `talosctl tcpdump` while you try to pull the image?

**Reply by aeleks** [reply]
<img width="1588" alt="Screenshot 2025-05-12 at 20 48 53" src="https://github.com/user-attachments/assets/4a2e6549-de1a-4f39-8e15-5b2a31e20b97" />

when i filter for that IP - dig factory.talos.dev - then I see a lot of packet retransmissions. those are all packets between those two hosts during a span of ~ 1 minute.

**Reply by aeleks** [reply]
I want to add: From INSIDE a Pod - i can resolve and query factory.talos.dev:

```
 tmp-shell  ~  curl factory.talos.dev
<html>
<head><title>308 Permanent Redirect</title></head>
<body>
<center><h1>308 Permanent Redirect</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Reply by rothgar** [reply]
TCP Retransmissions happen when the sender (your node) doesn't receive an ACK for a packet. In this case the problem is the SNI packet isn't being received by the server which is likely due to a firewall or MTU fragmentation issue. Because it works from within the cluster I assume it's not a firewall issue and probably an issue with a hypervisor or MTU.

Where are you running the node? You mention you're pulling the metal image, but I'm not sure if you're running on bare metal or on a hypervisor.
Can you also let me know what CNI you're using?

**Reply by aeleks** [reply]
I really appreciate your help, btw!

I am running bare-metal (it is an Intel NUC) without any Hypervisor involved.

Currently running on cilium-1.17.3 with the following values:

```
➜ helm get values cilium -n kube-system
USER-SUPPLIED VALUES:
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
ingressController:
  default: true
  enabled: true
  enforceHttps: false
  loadbalancerMode: shared
  service:
    annotations:
      lbipam.cilium.io/sharing-cross-namespace: '*'
      lbipam.cilium.io/sharing-key: gallifrey-prod
ipam:
  mode: kubernetes
k8sServiceHost: kube-apiserver.prod.gallifrey.local
k8sServicePort: 6443
kubeProxyReplacement: true
operator:
  replicas: 1
securityContext:
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
```

Although I don't think that is an issue - but not best practice ^^ - it is a single node cluster.

It seems weird that i can pull a generic `nginx` image, but not any image from factory.talos.dev
