### DISCUSSION TITLE
iptables -> nftables unintended consequence

### DISCUSSION THREAD

**Discussion by westnet-paul** [siderolabs/talos#11042] [General]
I thought I'd give some feedback on the switch from iptables to nftables with Talos 1.8 / Kubernetes 1.31.

Several of my workloads use container images that I build and push to a private registry. This registry runs on the Talos cluster and is accessible through a MetalLB / ingress-nginx loadbalancer. This has worked to date, and continued to work after I upgraded to Talos 1.8... but it stopped working after I upgraded Kubernetes to 1.31.

It took several hours to diagnose yesterday, but I was able to fix it by explicitly configuring kube-proxy to use iptables mode:

```yaml
cluster:
    proxy:
        image: registry.k8s.io/kube-proxy:v1.31.9
        mode: iptables
```

This has solved my problem but at the (minor) expense of drifting from default config. Maybe it's something that needs to be looked at in the kube-proxy nftables implementation?
