### DISCUSSION TITLE
Upgrade talos/k8s via config file

### DISCUSSION THREAD

**Discussion by kaerbr** [siderolabs/talos#11072] [Q&A] [answered]
So coming from kubernets, let's say I have this manifest:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
spec:
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: alpine:3.11
```

To update my deployment I would update `alpine:3.11` to `alpine3.12` and using `kubectl apply -f ./my-manifest.yaml` apply it.

---

For talos on the other hand: Let's say I have this (stripped down) controlplane.yaml:
```yaml
machine:
  install:
    disk: /dev/sda
    image: ghcr.io/siderolabs/installer:v1.10.1
```

My naive approach would be to update the config file: `ghcr.io/siderolabs/installer:v1.10.1` to `ghcr.io/siderolabs/installer:v1.10.2` apply the config using `talosctl apply-config -n <my-node> -e <my-endpoint>` and therefore the node would update itself to the given version.

Unfortunately(?) this does not work and I have to use `talosctl upgrade --nodes <my-node> -e <my-endpoint> --image ghcr.io/siderolabs/installer:v1.10.2`. The same applies to k8s version upgrades.

The amount of workload is that same but I dont understand why I cannot use my naive approach.  
What are the backgrounds to this decission?

In discussion https://github.com/siderolabs/talos/discussions/10796 there was the question how to metigate this behaviour but my question is more on the "why" this decision was made this way.

I hope someone can help me clear my mind on this topic. (:
