### DISCUSSION TITLE
Nvidia 50xx with Talos 1.10.3 - Nvidia modules are not found

### DISCUSSION THREAD

**Discussion by flashpixx** [siderolabs/talos#11123] [Q&A]
Hello,

I try to make it work that my new computer (one node) can run within the pods my Nvidia 5090.
I follow the [NVIDIA GPU (Proprietary drivers)](https://www.talos.dev/v1.10/talos-guides/configuration/nvidia-gpu-proprietary/) and prepare with the [image factory](https://factory.talos.dev/) (online / running locally with docker compose) my own ISO bare-metal image. My customizing to generate the ISO is

```yaml
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/nonfree-kmod-nvidia-production
            - siderolabs/nvidia-container-toolkit-production
```

and on the `controlplane.yaml`I set for installing the system

```yaml

machine:
    sysctls:
        net.core.bpf_jit_harden: 1

    kernel:
        modules:
            - name: nvidia
            - name: nvidia_uvm
            - name: nvidia_drm
            - name: nvidia_modeset
``` 

But I get the error on dmesg the no nvidia model is found.  I Have tested it with 1.10.1. 1.10.2, 1.10.3. Did I something wrong?
