### DISCUSSION TITLE
Installation Error "Controller runtime block volume manager controller"

### DISCUSSION THREAD

**Discussion by sub2010** [siderolabs/talos#11142] [General]
Based on the information provided, here's a template for a GitHub issue:

---

**Title:** Installation task "upgrade" failed with exit code 1

**Description:**

I'm trying to perform an installation on my mini PC with the following hardware specifications:

- Mini Forum PC: [MS-01](https://minisforumpc.eu/products/ms-01?variant=42097212489911)
- 1TB NVMe SSD: Samsung SSD 990 PRO 1TB (`nvme0n1`)
- 4TB NVMe SSD: Samsung SSD 990 EVO Plus 4TB (`nvme1n1`)
- BIOS settings: Secure Boot and Secure Disks are disabled

Disk Overview
```Disks:
ODE   NAMESPACE   TYPE   ID        VERSION   SIZE     READ ONLY   TRANSPORT   ROTATIONAL   WWID                   MODEL                          SERIAL
       runtime     Disk   loop0     2         77 MB    true
       runtime     Disk   nvme0n1   2         1.0 TB   false       nvme                     eui.0025384c41a085cf   Samsung SSD 990 PRO 1TB
       runtime     Disk   nvme1n1   2         4.0 TB   false       nvme                     eui.0025385b41435ccb   Samsung SSD 990 EVO Plus 4TB
       runtime     Disk   sda       3         128 GB   false       usb         true                                Type-C
```

The installation is being performed using the following controlplane yaml configuration:

```yaml
install:
    disk: /dev/nvme0n1 # The disk used for installations.
    image: [ghcr.io/siderolabs/installer:v1.9.5](http://ghcr.io/siderolabs/installer:v1.9.5) # Allows for supplying the image used to perform the installation.
    wipe: true # Indicates if the installation disk should be wiped at installation time.
```

The installation is failing with the following error message:

```
task install (1/1): failed: task "upgrade" failed: exit code 1
```

I've attached a screenshot of the error message for reference.

![Screenshot 2025-06-03 111424](https://github.com/user-attachments/assets/5a42ad76-5467-4a20-86f8-5a95eb0cfb0a)
