### DISCUSSION TITLE
Kubeletservicecontroller - error - error writing kubelet PKI: open /etc/kubernetes/bootstrap-kubeconfig: read-only file-system

### DISCUSSION THREAD

**Discussion by GurdipS5** [siderolabs/talos#11217] [Q&A]
Hi All,
Just setup Talos v1.33.1 on VMWare. I am noticing this error on the first control plane I have deployed:

Kubeletservicecontroller - error - error writing kubelet PKI: open /etc/kubernetes/bootstrap-kubeconfig: read-only file-system

I am attaching additional disks to my nodes, which may be the cause here. My controlplane config has the following:

```
 disks:
        - device: /dev/sdb
          partitions:
            - mountpoint: /var/mnt/rook
        - device: /dev/sdc
          partitions:
            - mountpoint: /var/mnt/kubelet

```

And

  ```
kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.33.1 # The `image` field is an optional reference to an alternative kubelet image.
        # The `extraArgs` field is used to provide additional flags to the kubelet.
        extraArgs:
            rotate-server-certificates: "true"
        # The `extraMounts` field is used to add additional mounts to the kubelet container.
        extraMounts:
            - destination: /var/mnt/kubelet # Destination is the absolute path where the mount will be placed in the container.
              type: bind # Type specifies the mount kind.
              source: /var/mnt/kubelet # Source specifies the source path of the mount.
              # Options are fstab style mount options.
              options:
                - bind
                - rshared
                - rw
            - destination: /var/mnt/rook # Destination is the absolute path where the mount will be placed in the container.
              type: bind # Type specifies the mount kind.
              source: /var/mnt/rook # Source specifies the source path of the mount.
              # Options are fstab style mount options.
              options:
                - bind
                - rshared
                - rw

```
I am assuming the problem is somewhere here and this may not be the correct config. The plan is to use a disk for the kubelet and another disk for rook. If this is incorrect, please let me know. :) 

I know the rules are to put errors in text, but for completion, I have added a screenshot of what I see on the logs of node: 

![image](https://github.com/user-attachments/assets/618e0486-6019-4b5c-9585-aecff1642a08)
