### DISCUSSION TITLE
Setup static IPv6 Address

### DISCUSSION THREAD

**Discussion by LukasKnuth** [siderolabs/talos#11227] [Q&A] [answered]
I run a single-node cluster on a Rapsberry Pi 4 with Talos. I have the following in my config patch:

```yaml
# Static IP interface
- op: add
  path: /machine/network/interfaces
  value:
    - interface "enxe45f012b8369"
      dhcp: false
      addresses:
        - "192.168.107.3/24"
        - "fd00:affe:cafe:107::3/48"
      routes:
        - network: 0.0.0.0/0
          gateway: 192.168.107.1
        - network: ::/0
          gateway: fd00:affe:cafe:107:d624:ddff:fed9:7b78

# Pick the nodeIP from the static IP network.
# NOTE: Not sure if this is required, added it following the troubleshooting guide when my node
# still had the initial DHCP IP set on the Kubernetes Node ("couldn't find node" issue)
- op: add
  path: /machine/kubelet/nodeIP
  value:
    validSubnets: ["192.168.107.0/24"]
```

(The [full config](https://github.com/LukasKnuth/homeserver/blob/main/talos/patches/rpi4-controlplane.yaml) - if needed)

The point of this is to set the static IPv4 address of the node to `192.168.107.3` and the static IPv6 address to `fd00:affe:cafe:107::3`. The `fd00:affe:cafe:107/48` ULA prefix is setup in my Router. (I static addresses because they are advertised as DNS server in my network.)

The IPv4 address works as expected, I can send traffic to the cluster and it responds. The IPv6 address can't reach the server however:

```
$ dig +short @192.168.107.3 home.rpi
192.168.107.3
$ dig -6 +short @fd00:affe:cafe::3 home.rpi
;; connection timed out; no servers could be reached
```

If I run `talosctl get links` I can see that the HW address is correct and the link is UP:

```
192.168.107.3 | network | LinkStatus | end0 | 3 | ether | e4:5f:01:2b:83:69 | up | true
```

When I run `talosctl get addresses` I see that both addresses are set for the link:

```
192.168.107.3   network     AddressStatus   end0/192.168.107.3/24                           1         192.168.107.3/24                           end0
192.168.107.3   network     AddressStatus   end0/2001:4dd2:46ce:0:e65f:1ff:fe2b:8369/64     2         2001:4dd2:46ce:0:e65f:1ff:fe2b:8369/64     end0
192.168.107.3   network     AddressStatus   end0/fd00:affe:cafe:107::3/48                   2         fd00:affe:cafe:107::3/48                   end0
192.168.107.3   network     AddressStatus   end0/fd00:affe:cafe:107:e65f:1ff:fe2b:8369/64   1         fd00:affe:cafe:107:e65f:1ff:fe2b:8369/64   end0
192.168.107.3   network     AddressStatus   end0/fe80::e65f:1ff:fe2b:8369/64                2         fe80::e65f:1ff:fe2b:8369/64                end0
```

I'm sure I'm overlooking something, I had this working on Talos 1.7.5 but since I upgrade my way up to 1.10.4 this morning, it must have broken along the way...
