### DISCUSSION TITLE
How to setup zfs kernel parameters?

### DISCUSSION THREAD

**Discussion by olivier-norture** [siderolabs/talos#11242] [General]
Hey there!

How to setup kernel parameters for ZFS?

I'm trying to adjust zfs arc size using `zfs_arc_max` (https://openzfs.github.io/openzfs-docs/Performance%20and%20Tuning/Module%20Parameters.html#zfs-arc-max).

So I updated my Talos Image to include the parameter:
```yaml
customization:
  extraKernelArgs:
    - talos.platform=metal
    - cpufreq.default_governor=powersave
    - amd_pstate=active
    - zfs_arc_max=32212254720 # 30GB
  systemExtensions:
    officialExtensions:
      - siderolabs/nvidia-container-toolkit-production
      - siderolabs/nvidia-open-gpu-kernel-modules-production
      - siderolabs/zfs
```

And I can see that parameter is active:
```bash
talosctl -e 192.168.1.49 -n 192.168.1.49 read /proc/cmdline
```
```
talos.platform=metal talos.config=none console=tty0 init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 printk.devkmsg=on ima_template=ima-ng ima_appraise=fix ima_hash=sha512 selinux=1 cpufreq.default_governor=powersave amd_pstate=active zfs_arc_max=32212254720
```

But the value doesn't respect the setting; it's 60GB at the moment (and keep growing).
Unfortunatly this server run a tons of container as well and when workload increase there is some freeze until ARC release some memory.

Thank you!

Edit:
For now I was able to set it using a pod and mounting `/sys/module/zfs` and running:
```bash
echo 32212254720 |  tee /sys/module/zfs/parameters/zfs_arc_max
```
It will not persist until reboot but I only reboot it for system upgrade so it's fine enough until I got a proper answer :)

**Comment by smira** [comment]
There are at least two ways (I'm not that familiar with ZFS, so not sure which one works/is supported):

* https://www.talos.dev/v1.10/reference/configuration/v1alpha1/config/#Config.machine.kernel - when loading the `zfs` module, you can specify module parameters
* https://www.talos.dev/v1.10/reference/configuration/v1alpha1/config/#Config.machine - you can use `machine.sysfs` section to specify and parameters under `/sys`, e.g. in your case it might be something like:


```yaml
machine:
  sysfs:
    module.zfs.parameters.zfs_arc_max: "32212254720"
```
