### DISCUSSION TITLE
Cannot mount an external volume

### DISCUSSION THREAD

**Discussion by m-vitale** [siderolabs/talos#11258] [Q&A]
I'm trying to mount a lvm volume composed of two nvme drives that have been passed through to the VM running talos.
The disk I'd like to mount is:

```
talosctl -n 10.0.1.207 get disks -o yaml                                    
Found existing alias for "talosctl". You should use: "t"
node: 10.0.1.207
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: dm-0
    version: 5
    owner: block.DisksController
    phase: running
    created: 2025-06-24T14:51:44Z
    updated: 2025-06-24T14:51:45Z
spec:
    dev_path: /dev/dm-0
    size: 2000406183936
    pretty_size: 2.0 TB
    io_size: 512
    sector_size: 512
    readonly: false
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
    secondary_disks:
        - nvme0n1
        - nvme1n1
    symlinks:
        - /dev/disk/by-diskseq/17
        - /dev/disk/by-id/dm-name-longhorn_vg-longhorn_lv
        - /dev/disk/by-id/dm-uuid-LVM-HQ4iQD5BUOfvVpRHV1RaWkoN8ZEg3CHjJJIwKV2MAjpYHx2Ihx36T0zy8zJx9X6X
        - /dev/disk/by-uuid/e95a70cb-4c84-4355-bd0b-3de5af0f3e34
```
One of my attempts is:
```
machine:
  disks:
    - device: /dev/dm-0
      partitions:
        - mountpoint: /var/mnt/storage
```
but although this is accepted without errors when the node reboots I'm met with 'no disks matched for volume' and the error message talks about a volume '/dev/dm-0-1' and I'm not sure where the suffix '-1' comes from.

I've read the documentation at https://www.talos.dev/v1.10/talos-guides/configuration/disk-management/ and I cannot make much sense of it. My question on slack resulted in a request for `support.zip` and I'm attaching it here, although what I'm looking for is an example of a config patch that mounts a physical drive (or a lvm volume but I'd think that would be the same)
[support.zip](https://github.com/user-attachments/files/20937054/support.zip)
