### DISCUSSION TITLE
After shutting down first controlplane all workers are become `NotReady`

### DISCUSSION THREAD

**Discussion by michaelkebe** [siderolabs/talos#11261] [Q&A] [answered]
I deployed the cluster using the attached `controlplane.yaml` and `worker.yaml`.

When the node `k8s-kebe-c1-test` is powered off, the worker nodes transition to the `NotReady` state after a few seconds.

(Don't wonder about the extra `inlineManifests` for the custom flannel installation. This is due a problem with the vmware network interface.)

What could be causing this issue?

Is it related to the `cluster.controlPlane.endpoint` value being set to `https://k8s-kebe-c1-test.domain.com:6443` in either `controlplane.yaml` or `worker.yaml`?

Should I be using a Virtual IP (VIP) (https://www.talos.dev/v1.10/talos-guides/network/vip/)?

Shutting down any other controlplane node (`k8s-kebe-c2-test` or `k8s-kebe-c3-test`) does *not* cause the worker nodes become `NotReady`.

# controlplane.yaml
```yaml
version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token: XXX
    ca:
        crt: XXX
        key: XXX
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.32.1
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network: {}
    install:
        disk: /dev/sda
        image: ghcr.io/siderolabs/installer:v1.9.3
        wipe: false
    time:
        disabled: false
        servers:
            - ntp.domain.com
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
    nodeLabels:
        node.kubernetes.io/exclude-from-external-load-balancers: ""
cluster:
    id: XXX
    secret: XXX
    controlPlane:
        endpoint: https://k8s-kebe-c1-test.domain.com:6443
    clusterName: kebe_test
    network:
        cni:
            name: none
        dnsDomain: cluster.local
        podSubnets:
            - 10.36.0.0/16
        serviceSubnets:
            - 10.35.0.0/16
    token: z676si.1djvh72iwtt5ax8r
    secretboxEncryptionSecret: XXX
    ca:
        crt: XXX
        key: XXX
    aggregatorCA:
        crt: XXX
        key: XXX
    serviceAccount:
        key: XXX
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.32.1
        certSANs:
            - k8s-kebe-c1-test.domain.com
        disablePodSecurityPolicy: true
        admissionControl:
            - name: PodSecurity
              configuration:
                apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                defaults:
                    audit: restricted
                    audit-version: latest
                    enforce: baseline
                    enforce-version: latest
                    warn: restricted
                    warn-version: latest
                exemptions:
                    namespaces:
                        - kube-system
                    runtimeClasses: []
                    usernames: []
                kind: PodSecurityConfiguration
        auditPolicy:
            apiVersion: audit.k8s.io/v1
            kind: Policy
            rules:
                - level: Metadata
    controllerManager:
        image: registry.k8s.io/kube-controller-manager:v1.32.1
    proxy:
        image: registry.k8s.io/kube-proxy:v1.32.1
    scheduler:
        image: registry.k8s.io/kube-scheduler:v1.32.1
    discovery:
        enabled: false
        registries:
            kubernetes:
                disabled: true
            service: {}
    etcd:
        ca:
            crt: XXX
            key: XXX
    inlineManifests:
        - name: flannel-custom-installation
          contents: |-
            apiVersion: v1
            kind: Namespace
            metadata:
              labels:
                k8s-app: flannel
                pod-security.kubernetes.io/enforce: privileged
              name: kube-flannel
            ---
            apiVersion: v1
            kind: ServiceAccount
            metadata:
              labels:
                k8s-app: flannel
              name: flannel
              namespace: kube-flannel
            ---
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            metadata:
              labels:
                k8s-app: flannel
              name: flannel
            rules:
            - apiGroups:
              - ""
              resources:
              - pods
              verbs:
              - get
            - apiGroups:
              - ""
              resources:
              - nodes
              verbs:
              - get
              - list
              - watch
            - apiGroups:
              - ""
              resources:
              - nodes/status
              verbs:
              - patch
            ---
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            metadata:
              labels:
                k8s-app: flannel
              name: flannel
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: flannel
            subjects:
            - kind: ServiceAccount
              name: flannel
              namespace: kube-flannel
            ---
            apiVersion: v1
            data:
              cni-conf.json: |
                {
                  "name": "cbr0",
                  "cniVersion": "0.3.1",
                  "plugins": [
                    {
                      "type": "flannel",
                      "delegate": {
                        "hairpinMode": true,
                        "isDefaultGateway": true
                      }
                    },
                    {
                      "type": "portmap",
                      "capabilities": {
                        "portMappings": true
                      }
                    }
                  ]
                }
              net-conf.json: |
                {
                  "Network": "10.36.0.0/16",
                  "EnableNFTables": false,
                  "Backend": {
                    "Type": "host-gw"
                  }
                }
            kind: ConfigMap
            metadata:
              labels:
                app: flannel
                k8s-app: flannel
                tier: node
              name: kube-flannel-cfg
              namespace: kube-flannel
            ---
            apiVersion: apps/v1
            kind: DaemonSet
            metadata:
              labels:
                app: flannel
                k8s-app: flannel
                tier: node
              name: kube-flannel-ds
              namespace: kube-flannel
            spec:
              selector:
                matchLabels:
                  app: flannel
                  k8s-app: flannel
              template:
                metadata:
                  labels:
                    app: flannel
                    k8s-app: flannel
                    tier: node
                spec:
                  affinity:
                    nodeAffinity:
                      requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                        - matchExpressions:
                          - key: kubernetes.io/os
                            operator: In
                            values:
                            - linux
                  containers:
                  - args:
                    - --ip-masq
                    - --kube-subnet-mgr
                    command:
                    - /opt/bin/flanneld
                    env:
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: POD_NAMESPACE
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.namespace
                    - name: EVENT_QUEUE_DEPTH
                      value: "5000"
                    image: ghcr.io/flannel-io/flannel:v0.26.4
                    name: kube-flannel
                    resources:
                      requests:
                        cpu: 100m
                        memory: 50Mi
                    securityContext:
                      capabilities:
                        add:
                        - NET_ADMIN
                        - NET_RAW
                      privileged: false
                    volumeMounts:
                    - mountPath: /run/flannel
                      name: run
                    - mountPath: /etc/kube-flannel/
                      name: flannel-cfg
                    - mountPath: /run/xtables.lock
                      name: xtables-lock
                  hostNetwork: true
                  initContainers:
                  - args:
                    - -f
                    - /flannel
                    - /opt/cni/bin/flannel
                    command:
                    - cp
                    image: ghcr.io/flannel-io/flannel-cni-plugin:v1.6.2-flannel1
                    name: install-cni-plugin
                    volumeMounts:
                    - mountPath: /opt/cni/bin
                      name: cni-plugin
                  - args:
                    - -f
                    - /etc/kube-flannel/cni-conf.json
                    - /etc/cni/net.d/10-flannel.conflist
                    command:
                    - cp
                    image: ghcr.io/flannel-io/flannel:v0.26.4
                    name: install-cni
                    volumeMounts:
                    - mountPath: /etc/cni/net.d
                      name: cni
                    - mountPath: /etc/kube-flannel/
                      name: flannel-cfg
                  priorityClassName: system-node-critical
                  serviceAccountName: flannel
                  tolerations:
                  - effect: NoSchedule
                    operator: Exists
                  volumes:
                  - hostPath:
                      path: /run/flannel
                    name: run
                  - hostPath:
                      path: /opt/cni/bin
                    name: cni-plugin
                  - hostPath:
                      path: /etc/cni/net.d
                    name: cni
                  - configMap:
                      name: kube-flannel-cfg
                    name: flannel-cfg
                  - hostPath:
                      path: /run/xtables.lock
                      type: FileOrCreate
                    name: xtables-lock

```

# worker.yaml
```yaml
version: v1alpha1
debug: false
persist: true
machine:
    type: worker
    token: XXX
    ca:
        crt: XXX
        key: ""
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.32.1
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network: {}
    install:
        disk: /dev/sda
        image: ghcr.io/siderolabs/installer:v1.9.3
        wipe: false
    time:
        disabled: false
        servers:
            - ntp.domain.com
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
cluster:
    id: XXX
    secret: XXX
    controlPlane:
        endpoint: https://k8s-kebe-c1-test.domain.com:6443
    clusterName: kebe_test
    network:
        cni:
            name: none
        dnsDomain: cluster.local
        podSubnets:
            - 10.36.0.0/16
        serviceSubnets:
            - 10.35.0.0/16
    token: XXX
    ca:
        crt: XXX
        key: ""
    discovery:
        enabled: false
        registries:
            kubernetes:
                disabled: true
            service: {}
    inlineManifests:
        - name: flannel-custom-installation
          contents: |-
            apiVersion: v1
            kind: Namespace
            metadata:
              labels:
                k8s-app: flannel
                pod-security.kubernetes.io/enforce: privileged
              name: kube-flannel
            ---
            apiVersion: v1
            kind: ServiceAccount
            metadata:
              labels:
                k8s-app: flannel
              name: flannel
              namespace: kube-flannel
            ---
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            metadata:
              labels:
                k8s-app: flannel
              name: flannel
            rules:
            - apiGroups:
              - ""
              resources:
              - pods
              verbs:
              - get
            - apiGroups:
              - ""
              resources:
              - nodes
              verbs:
              - get
              - list
              - watch
            - apiGroups:
              - ""
              resources:
              - nodes/status
              verbs:
              - patch
            ---
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            metadata:
              labels:
                k8s-app: flannel
              name: flannel
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: flannel
            subjects:
            - kind: ServiceAccount
              name: flannel
              namespace: kube-flannel
            ---
            apiVersion: v1
            data:
              cni-conf.json: |
                {
                  "name": "cbr0",
                  "cniVersion": "0.3.1",
                  "plugins": [
                    {
                      "type": "flannel",
                      "delegate": {
                        "hairpinMode": true,
                        "isDefaultGateway": true
                      }
                    },
                    {
                      "type": "portmap",
                      "capabilities": {
                        "portMappings": true
                      }
                    }
                  ]
                }
              net-conf.json: |
                {
                  "Network": "10.36.0.0/16",
                  "EnableNFTables": false,
                  "Backend": {
                    "Type": "host-gw"
                  }
                }
            kind: ConfigMap
            metadata:
              labels:
                app: flannel
                k8s-app: flannel
                tier: node
              name: kube-flannel-cfg
              namespace: kube-flannel
            ---
            apiVersion: apps/v1
            kind: DaemonSet
            metadata:
              labels:
                app: flannel
                k8s-app: flannel
                tier: node
              name: kube-flannel-ds
              namespace: kube-flannel
            spec:
              selector:
                matchLabels:
                  app: flannel
                  k8s-app: flannel
              template:
                metadata:
                  labels:
                    app: flannel
                    k8s-app: flannel
                    tier: node
                spec:
                  affinity:
                    nodeAffinity:
                      requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                        - matchExpressions:
                          - key: kubernetes.io/os
                            operator: In
                            values:
                            - linux
                  containers:
                  - args:
                    - --ip-masq
                    - --kube-subnet-mgr
                    command:
                    - /opt/bin/flanneld
                    env:
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: POD_NAMESPACE
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.namespace
                    - name: EVENT_QUEUE_DEPTH
                      value: "5000"
                    image: ghcr.io/flannel-io/flannel:v0.26.4
                    name: kube-flannel
                    resources:
                      requests:
                        cpu: 100m
                        memory: 50Mi
                    securityContext:
                      capabilities:
                        add:
                        - NET_ADMIN
                        - NET_RAW
                      privileged: false
                    volumeMounts:
                    - mountPath: /run/flannel
                      name: run
                    - mountPath: /etc/kube-flannel/
                      name: flannel-cfg
                    - mountPath: /run/xtables.lock
                      name: xtables-lock
                  hostNetwork: true
                  initContainers:
                  - args:
                    - -f
                    - /flannel
                    - /opt/cni/bin/flannel
                    command:
                    - cp
                    image: ghcr.io/flannel-io/flannel-cni-plugin:v1.6.2-flannel1
                    name: install-cni-plugin
                    volumeMounts:
                    - mountPath: /opt/cni/bin
                      name: cni-plugin
                  - args:
                    - -f
                    - /etc/kube-flannel/cni-conf.json
                    - /etc/cni/net.d/10-flannel.conflist
                    command:
                    - cp
                    image: ghcr.io/flannel-io/flannel:v0.26.4
                    name: install-cni
                    volumeMounts:
                    - mountPath: /etc/cni/net.d
                      name: cni
                    - mountPath: /etc/kube-flannel/
                      name: flannel-cfg
                  priorityClassName: system-node-critical
                  serviceAccountName: flannel
                  tolerations:
                  - effect: NoSchedule
                    operator: Exists
                  volumes:
                  - hostPath:
                      path: /run/flannel
                    name: run
                  - hostPath:
                      path: /opt/cni/bin
                    name: cni-plugin
                  - hostPath:
                      path: /etc/cni/net.d
                    name: cni
                  - configMap:
                      name: kube-flannel-cfg
                    name: flannel-cfg
                  - hostPath:
                      path: /run/xtables.lock
                      type: FileOrCreate
                    name: xtables-lock
```
