### DISCUSSION TITLE
CA Trust Error connecting to node without specifying endpoint

### DISCUSSION THREAD

**Discussion by roganlynch** [siderolabs/talos#11274] [Q&A]
## Error 
```
talosctl -n 172.16.12.235 get manifests 01-csr-approver-role-binding --namespace=controlplane -o yaml

rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority"
```
## Workaround
```
talosctl -n 172.16.12.235 -e 172.16.12.235 get manifests 01-csr-approver-role-binding --namespace=controlplane -o yaml

node: 172.16.12.235
metadata:
    namespace: controlplane
    type: Manifests.kubernetes.talos.dev
    id: 01-csr-approver-role-binding
    version: 1
    owner: k8s.ManifestController
    phase: running
    created: 2025-06-28T17:45:40Z
    updated: 2025-06-28T17:45:40Z
spec:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: system-bootstrap-approve-node-client-csr
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: system:certificates.k8s.io:certificatesigningrequests:nodeclient
      subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: Group
          name: system:bootstrappers:nodes

```
## Config Patches:
```
❯ bat *.yaml
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: allowScheduling.patch.yaml
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ cluster:
   2   │   allowSchedulingOnControlPlanes: true
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: cert-san.patch.yaml
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ machine:
   2   │   certSANs:
   3   │     - 127.0.0.1
   4   │     - 172.16.12.25
   5   │     - talos-cp.internal.lan
   6   │     - talos-pve1.internal.lan
   7   │     - talos-pve2.internal.lan
   8   │     - talos-pve3.internal.lan
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: network-config.yaml
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ machine:
   2   │     network:
   3   │         interfaces:
   4   │             - deviceSelector:
   5   │                 physical: true
   6   │               dhcp: true
   7   │               vip:
   8   │                 ip: 172.16.12.25
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

## DNS Config

```
❯ for h in  talos-pve{1..3}.internal.lan talos-cp; do host $h;done
talos-pve1.internal.lan has address 172.16.12.235
talos-pve2.internal.lan has address 172.16.12.145
talos-pve3.internal.lan has address 172.16.12.197
talos-cp.internal.lan has address 172.16.12.145
talos-cp.internal.lan has address 172.16.12.235
talos-cp.internal.lan has address 172.16.12.197
```
