### DISCUSSION TITLE
Kubernetes Bootstrap - error executing bootstrap: rpc error: code = Unavailable desc = name resolver error: produced zero addresses

### DISCUSSION THREAD

**Discussion by Sparkxxx** [siderolabs/talos#4946] [Q&A] [answered]
```
talosctl gen config "k8s-talos-1" "https://k8s-ctrlplane.kub.local:6443"
```  

I am trying to use vip ( 10.170.0.20 - k8s-ctrlplane.kub.local ) and alocate IPs trough dhcp for each node based on mac addresses (**no dns name for controlplane nodes as per docs**). https://k8s-ctrlplane.kub.local:6443 is also the cluster endpoint, 10.170.0.11,12,13 are the controlplane nodes.
When trying to bootstrap I get:
```
talosctl --talosconfig=./talosconfig bootstrap --nodes 10.170.0.11
error executing bootstrap: rpc error: code = Unavailable desc = name resolver error: produced zero addresses  
```
talosconfig:  
```
context: k8s-talos-1
contexts:
    k8s-talos-1:
        endpoints:
            - 10.170.0.11,10.170.0.12,10.170.0.13
        nodes:
            - 10.170.0.11
        ca: ...
        crt: ... 
        key: ...
```  
controlplane.yml for all 3 nodes:
```
    network:
      interfaces:
        - interface: eth0
          dhcp: true
          vip:
            ip: 10.170.0.20
```  
```  
talosctl edit mc --nodes 10.170.0.11
rpc error: code = Unavailable desc = name resolver error: produced zero addresses
```  
I think it's expecting to resolve the ip to dns but at this point there is no vip available (it should be up after kubernetes etcd bootstrap) so, on purpose, there should be no dns names asociated with the cluster yet.  
Would you be so kind to direct me in this matter?
thx

**Comment by sergelogvinov** [comment, marked as answer]
I think, this is yaml format issue. 
Try this

```yaml
context: k8s-talos-1
contexts:
    k8s-talos-1:
        endpoints:
            - 10.170.0.11
            - 10.170.0.12
            - 10.170.0.13
...
```
