### DISCUSSION TITLE
"cluster create" fails behind corporate proxy

### DISCUSSION THREAD

**Discussion by miphip** [siderolabs/talos#5393] [Q&A]
Hi, using talosctl v 1.0.3.

```
> talosctl cluster create
validating CIDR and reserving IPs
generating PKI and tokens
downloading ghcr.io/siderolabs/talos:v1.0.3
creating network talos-default
creating master nodes
creating worker nodes
waiting for API
bootstrapping cluster
◳ waiting for etcd to be healthy: 1 error occurred:
    * 10.5.0.2: service "etcd" not in expected state "Running": current state [Preparing] Running pre state
```

From " docker logs talos-default-master-1":
```
[talos] 2022/04/20 08:37:29 service[etcd](Failed): Failed to run pre stage: failed to pull image "gcr.io/etcd-development/etcd:v3.5.3": 1 error(s) occurred:
	failed to pull image "gcr.io/etcd-development/etcd:v3.5.3": failed to resolve reference "gcr.io/etcd-development/etcd:v3.5.3": failed to do request: context canceled
```
[talos-default-master-1.log](https://github.com/siderolabs/talos/files/8520428/talos-default-master-1.log)

I'm behind a corporate proxy with a self-signed ca-cert. The proxy env vars are injected into docker containers through "~/.docker/config.json" but I suspect it fails because of the proxy ca-cert. How can I provide it to the containers?

**Comment by smira** [comment]
Probably the error you're seeing is before the bootstrap, and it's not the real error. You might need to wait more to see the pull error (if it fails).

I suspect you might need to have HTTP_PROXY env vars injected as well as the self-signed CA cert.

So you probably need to do:

* https://www.talos.dev/v1.0/talos-guides/configuration/certificate-authorities/
* https://www.talos.dev/v1.0/reference/configuration/ and `machine.env`

You can create a config patch which looks like that:

```yaml
- op: add
  path: /machine/env
  value:
      http_proxy: ...
      https_proxy: ...
- op: add
  path: /machine/files
  value: 
    - content: |
         -----BEGIN CERTIFICATE-----
         ...
         -----END CERTIFICATE-----        
      permissions: 0644
      path: /etc/ssl/certs/ca-certificates
      op: append 
```

And pass it to `talosctl cluster create` as `--config-patch @your-patch.yaml`
