### DISCUSSION TITLE
(Virtual) IP address strategy to (TalOS based) Edge server in data center

### DISCUSSION THREAD

**Discussion by pojusoi** [siderolabs/talos#6367] [Show and tell]
Want to show our use case and ask future plans for a machines and interface virtual IP address solution in TalOS.

We run multiple data centers and we have recently moved (Migration ongoing) to Sidero/TalOS deployments for all our servers. Let's say that in our data center we run:
- One k8s cluster with 3 servers (Controls: 3) as Edge
- Two k8s cluster with 6 to 9 server (Controls: 3-4, Workers: 3-5) as a Backend

In our solution we are using VIP to have high-availability for our services in the Edge. And we would like add more virtual IP addresses to distribute the incoming IP traffic evenly (and keep the high-availability) to all servers in Edge.

Today, we see - we can add only one VIP per Machine
-- clip --
````
machine:
  network:
    interfaces:
    - interface: bond0
      dhcp: false
      vlans:
        - vlanId: 100
          dhcp: false
          cidr: 10.255.0.10/24
          routes:
          - network: 10.255.0.0/14
            gateway: 10.255.0.1
    - interface: bond1
      dhcp: false
      vlans:
        - vlanId: 800
          dhcp: false
          cidr: 10.1.1.10/27
          routes:
          - network: 0.0.0.0/0
            gateway: 10.1.1.1
          vip:
            ip: 10.1.1.30
````

Doc ref: https://www.talos.dev/v1.2/talos-guides/network/vip/#configure-your-talos-machines

I hope I can use this forum to also ask following questions:
- Is there any options how could we add more virtual IP addresses to the server interface (e.g. bond1.800)?
- Is there future plans to allow use of many virtual IP addresses (ref: vip) in the machine interface?
    -- ref --
    ```
    vip:
      - ip: <ip_address>
      - ip: <ip_address>
    ```
