### DISCUSSION TITLE
Trouble Configuring Local Storage

### DISCUSSION THREAD

**Discussion by larrywalters** [siderolabs/talos#6372] [Q&A]
Hello, I'm having some trouble understanding and configuring my `extraMounts` and PVs. I have a directory on my local machine that I want to mount to a directory in the Talos control-plane node, and then have that be the location of a `local-storage` PersistentVolume. This worked fine in a minikube setup, where the directory was mounted into the minikube VM. I am running Talos using the local docker setup, so it's running in my Docker Desktop on macOS.

When I do this in Talos, I cannot see the mount point as a directory on the node. But strangely the volume seems to work, in that I can direct my Pods to read and write to it. However, they cannot read any of the files/directories present there already, only ones that they specify to create.

Here is my applicable machine patch section (local machine path is redacted below, but I am using the absolute path in reality):
```
"op": "add",
"path": "/machine/kubelet/extraMounts",
"value": [
    {
        "destination": "/demo_data",
        "type": "bind",
        "source": "/Users/.../k8s/data",
        "options": [
            "bind",
            "rshared",
            "rw"
        ]
    }
]
```
Here are my PV/PVC manifests
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: default
  labels:
    app: mylabel
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  local:
    path: /demo_data
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  volumeMode: Filesystem
  claimRef:
    name: local-pvc
    namespace: default
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - talos-default-controlplane-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: default
  labels:
    app: mylabel
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
  storageClassName: local-storage
  volumeName: local-pv
```
And then I use this PVC in a couple Pods.

When I try to find this `/demo_data` directory on my node, I cannot, but interestingly I can see an added directory that corresponds to my host machine file path
```
> talosctl list -n 10.5.0.2 /
NODE       NAME
10.5.0.2   .
10.5.0.2   .dockerenv
10.5.0.2   Users
10.5.0.2   bin
10.5.0.2   boot
10.5.0.2   dev
10.5.0.2   etc
10.5.0.2   lib
10.5.0.2   mnt
10.5.0.2   opt
10.5.0.2   proc
10.5.0.2   root
10.5.0.2   run
10.5.0.2   sbin
10.5.0.2   sys
10.5.0.2   system
10.5.0.2   tmp
10.5.0.2   usr
10.5.0.2   var
> talosctl list -n 10.5.0.2 /Users/.../k8s/
NODE       NAME
10.5.0.2   .
10.5.0.2   data
```
But again, I cannot see the actual data residing on the host machine. If one of the Pods writes a file here, I can see it, but otherwise, it appears empty.
```
> talosctl list -n 10.5.0.2 /Users/.../k8s/data
NODE       NAME
10.5.0.2   .
```
This means that when I try to have my Pod look for a file in the volume, it cannot.

Some help here would be much appreciated!

I'm also wondering how the `options` section of the machine patch should be configured. My understanding is that this specification is essentially wrapping the way docker containers are mounted (as described [here](https://docs.docker.com/storage/bind-mounts/#choose-the--v-or---mount-flag)), but I've noticed if I exclude the `bind` option from the list, even if the `type` is `volume`, that the cluster cannot start successfully. I'm not sure why that is, and what values should be here.

Thank you!
