### DISCUSSION TITLE
Outgoing IP / OnLink Default Route

### DISCUSSION THREAD

**Discussion by dedene** [siderolabs/talos#6903] [Q&A] [answered]
I'm currently running a Talos cluster on Hezner cloud. They have the concept of floating ips, which I'd like to use for having a fixed outgoing ip address (for whitelisting in other applications).

A custom route with the source set to the floating ip should enable this if I'm not mistaken:

```
interfaces:
      - interface: eth0 
        addresses:
          - a.b.c.d/32
        routes:
          - network: 0.0.0.0/0
            gateway: 172.31.1.1
            source: a.b.c.d
``` 

However this is not working. Hetzner uses the special 172.31.1.1 as default gateway in it's cloud network. With DHCP it's working and I can see from https://github.com/siderolabs/talos/issues/4320 this is probably because in dhcp the `onlink` or `NextHop` is added. Is there any way to get this to work for static configured ip addresses?

Many thanks for your help!

**Comment by smira** [comment, marked as answer]
You can add link-scope route by adding a route without a gateway, in your case you need something like I guess:

```yaml
interfaces:
      - interface: eth0 
        addresses:
          - a.b.c.d/32
        routes:
          - gateway: 172.31.1.1
          - network: 172.31.1.1/32
```
