### DISCUSSION TITLE
Gateway routing with multiple (public / private) network interfaces

### DISCUSSION THREAD

**Discussion by dedene** [siderolabs/talos#7177] [Q&A]
I have the following setup: a cluster of mulitple servers at OVH where I want to run Talos. Each have access to a private network (VLAN based), with DHCP and a gateway for internet access. This works perfectly fine. There is a second network interface that can route public ips to the servers. You get a range and a associated gateway. 

For the example, let's use following ips:
- `1.2.3.4` → my ip address
- `10.0.0.10/24` → the ip in the private network, configured through dhcp, on eth0.101 (so using vlan tag 101)
- `5.6.7.8` → a public ip in the /28 subnet leased from OVH, on eth0 (so same parent interface, untagged). The instructions from OVH are to use the second to last ip as Network Gateway: https://help.ovhcloud.com/csm/en-ca-dedicated-servers-ip-block-vrack?id=kb_article_view&sysparm_article=KB0043335 → Let's use 5.6.7.14/32 as the example.

This setup works great on a non-Talos Linus (Ubuntu or Debian), so it should be able to work on Talos as well.

When configuring a node as follows:

```
[...]
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: false
        addresses:
          - 5.6.7.8/32
        routes:
          - network: 5.6.7.14/32
          - network: 5.6.7.8/32
            gateway: 5.6.7.14
        vlans:
          - vlanId: 101
            dhcp: true
            routes:
              - network: 0.0.0.0/0
                gateway: 10.0.0.1
[...]
```

`eth0` has `00:93:65:69:3d:bb` as MAC address in this example.

When looking with tcpdump I can see package are reaching the Talos server fine, but the response seems to have the VLAN tag applied, so the reply is not routed correctly back.

```
12:03:04.887509 28:99:3a:99:9f:9e > 00:93:65:69:3d:bb, ethertype IPv4 (0x0800), length 98: 1.2.3.4 > 5.6.7.8: ICMP echo request, id 61214, seq 8, length 64
12:03:04.887580 00:93:65:69:3d:bb > 00:00:5e:00:01:02, ethertype 802.1Q (0x8100), length 102: vlan 101, p 0, ethertype IPv4 (0x0800), 5.6.7.8 > 1.2.3.4: ICMP echo reply, id 61214, seq 8, length 64
```

Even when using `metric: 0` for the public ip gateway route, it still has the VLAN tag applied. 

Does someone has an idea if there is something missing from the config? Or what I can do to get the 5.6.7.8 ip address to respond?

**Comment by smira** [comment]
Your setup works exactly as you configured default gateway is 10.0.0.1 only. Why would packet to 1.2.3.4 be routed to 5.6.7.14 via eth0 untagged?

You need to figure out what should be the path for public outbound, if it's eth0, it should be a default route on eth0, and eth0.101 should only route to 10/8 ?

**Reply by dedene** [reply]
Thanks for your reply! 

10.0.0.1 ís the path for public outbound. It's a pair of high available routers, all nodes from the private network can use it for internet access. We're using VLANs to separate various projects. 

However 1.2.3.4 is an extra subnet that is routed on the same physical link on the server. As explained in the docs from OVH you need to use a different gateway for replies to traffic to 1.2.3.4.

**Reply by smira** [reply]
I'm still confused about the desired effect, but you need something like:

```
      - interface: eth0
        mtu: 1500
        dhcp: false
        addresses:
          - 5.6.7.8/32
        routes:
          - network: 5.6.7.14/32
          - network: 1.2.3.4/32
            gateway: 5.6.7.14
```

This way if 1.2.3.4 -> 5.6.7.8 gets routed over eth0 untagged, response packets will go same way

**Reply by dedene** [reply]
Indeed, that's also what I thought and exactly what I have configured. But it's not what I'm seeing. Also when setting a route metric of i.e. 100 (lower is higher priority, right?) I still see the ping reply going out with the vlan tag applied.

The desired effect in the end would be to use the public ip (or multiple) as failover ips for ingress traffic, using MetalLB. It's working great on Ubuntu or Debian, so I was hoping it should be possible using Talos too.

**Reply by smira** [reply]
What I posted above is not what you have configured (in the original message).

If it's working great on Ubuntu/Debian, it makes sense to post that config, and we can see what we can do.

**Reply by dedene** [reply]
Yeah, my mistake, I checked against the real ips but the example is indeed mixed up. I'll use the ips from the example on https://help.ovhcloud.com/csm/en-ca-dedicated-servers-ip-block-vrack?id=kb_article_view&sysparm_article=KB0043335 (which is 46.105.135.96/28)

So this config is working on Debian 11:

```
auto eth0
iface eth0 inet static
    address 46.105.135.97
    netmask 255.255.255.240
    gateway 46.105.135.110
    post-up ip route add default via 46.105.135.110 dev eth0 table 100
    post-up ip rule add from 46.105.135.96/28 table 100
    post-down ip route del default via 46.105.135.110 dev eth0 table 100
    post-down ip rule del from 46.105.135.96/28 table 100

auto eth0.101
iface eth0.101 inet dhcp
    post-up route del default
    post-up route add default gw 10.0.0.1
```

I may have missed at first, without the routing table rules, I could ping but not connect i.e. through ssh over the public ip. After adding those rules both work. When getting the external ip from the machine, I'm getting the ips of the gateway, so outgoing traffic is routed through 10.0.0.1. But I can run a service on 46.105.135.97 and connect.

I was hoping to get this to work on kubernetes through Talos as well, using MetalLB. The OVH Vrack is a L2 network, so using ARP you can very fast switch IPs between nodes.

**Reply by smira** [reply]
They're pushing the routing rules to a custom routing table, which is not supported by Talos currently, but this configuration won't work on its own, as nothing references that table. There is some other integration with something else here.

**Reply by dedene** [reply]
Yet somehow it does work.. :) I just installed this in a vanilla cloud-init VM (I wanted to make sure the example I gave worked), added it to the VRack, changed `/etc/network/interfaces.d/50-cloud-init` to the config above (with an unused ip of our blocks) and rebooted: outgoing traffic is going through the private network and I can access the VM using the public ip.

But I understand you correctly, this is not possible using Talos at the moment? Would a custom [extension service](https://www.talos.dev/v1.4/advanced/extension-services/) be able to help?

**Reply by smira** [reply]
To test things out, you can even boot it up, schedule a privileged pod with host networking and configure all the above with `ip` tool. But without something else in the mix it won't work.

**Reply by dedene** [reply]
Ok, I just tested this on a new Talos 1.4.1 cluster (using Cilium, but I don't this it matters much).

So something like this in the machine config for the node `node-1`

```
networkInterfaces:
- interface: eth0
  mtu: 1500
  dhcp: false
  addresses:
    - 46.105.135.97/32
  routes:
    - network: 46.105.135.110/32
    - network: 46.105.135.97/28
      gateway: 46.105.135.110
      metric: 0
  vlans:
    - vlanId: 102
      dhcp: true
      dhcpOptions:
        ipv4: true
        ipv6: true
      routes:
        - network: 0.0.0.0/0
          gateway: 10.0.0.1
```

Schedule a pod with hostnetwork:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: netshoot
  name: netshoot
  namespace: kube-system
spec:
  nodeName: `node-1`
  hostNetwork: true
  containers:
    - image: nicolaka/netshoot
      name: netshoot
      command: ["/bin/sh"]
      securityContext:
        privileged: true
      args:
        - "-c"
        - "sleep infinity"
```

After that I ran only these two commands:

```
ip route add default via 46.105.135.110 dev eth0 table 100
ip rule add from 46.105.135.96/28 table 100
```

and ✨ I can ping. Or start a webserver and connect through the public ip. Outgoing traffic is from the gateway on the private network (the public ip of 10.0.0.1).

Maybe it's something specific to OVH that allows this to work? 🤷‍♂️ 

I'll experiment further to check if I can get it from here to work with MetalLB.
