### DISCUSSION TITLE
How to get etcd metrics?

### DISCUSSION THREAD

**Discussion by CRASH-Tech** [siderolabs/talos#7214] [Q&A] [answered]
It's not a pod, and I can't scape metrics from the cluster.
Where is metrics endpoint?

**Comment by frezbo** [comment]
You'd set the `extraArgs` for etcd here: https://www.talos.dev/v1.4/reference/configuration/#etcdconfig

and add a `listen-metric-urls`

**Reply by CRASH-Tech** [reply]
Set to 0.0.0.0 and scrape from cp node ip's?

**Reply by frezbo** [reply, marked as answer]
yes, you can also set it to the node ip

**Reply by CRASH-Tech** [reply]
Thanks!

**Comment by gerhard** [comment]
So what is the recommended way of configuring etcd metrics scraping again?

I was not able to get the above recommendation to work. I am running:
* [Talos `v1.5.3` managed by `Omni v0.18.1`](https://changelog.omni.siderolabs.io/cluster/experimental-2023-08-12/overview)
* K8s `v1.28.2`
* kube-prometheus-stack `v48.3.6`

After applying the following cluster patch:

```yaml
cluster:
  etcd:
    extraArgs:
      listen-metrics-url: 0.0.0.0
```

`etcd` continues to listen on IPv6 only:

```cfg
# netstat -ltnp | grep etcd
tcp6       0      0 :::2380                 :::*                    LISTEN      2061/etcd
tcp6       0      0 :::2379                 :::*                    LISTEN      2061/etcd
```

---
FWIW:

```cfg
# curl -6 "http://[::1]:2380/metrics" -v
*   Trying [::1]:2380...
* Connected to ::1 (::1) port 2380 (#0)
> GET /metrics HTTP/1.1
> Host: [::1]:2380
> User-Agent: curl/7.88.1
> Accept: */*
>
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
```

```cfg
# curl -6 "http://[::1]:2379/metrics" -v
*   Trying [::1]:2379...
* Connected to ::1 (::1) port 2379 (#0)
> GET /metrics HTTP/1.1
> Host: [::1]:2379
> User-Agent: curl/7.88.1
> Accept: */*
>
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
```

**Reply by gerhard** [reply]
I have a similar question but for `kube-proxy`:
- https://github.com/siderolabs/talos/discussions/7799

**Reply by Preisschild** [reply]
I've set mine to this:

```
        - op: add
          path: /cluster/etcd/extraArgs
          value:
            listen-metrics-urls: http://127.0.0.1:9623
```

You need the `listen-metrics-urls` (not `url`) argument and include scheme and port.

**Reply by gerhard** [reply]
Thank you!

After setting this config, `etcd` does not seem to expose this:

![image](https://github.com/siderolabs/talos/assets/3342/0191b825-3283-41d8-9183-5f057087a356)

I do however see `[talos] apply config request: mode auto(no_reboot)` entries in the machine console log.

Also hit this other bug with `talosctl`:
- https://github.com/siderolabs/omni-feedback/issues/64

Not sure how else to check the etcd config.

**Reply by smira** [reply]
`etcd` config changes at the moment required a node reboot which doesn't get triggered automatically

**Reply by gerhard** [reply]
Got it! Will try & report back.

**Reply by gerhard** [reply]
I was not able to reboot the node via Omni, getting `Failed to Issue Reboot` error:

![image](https://github.com/siderolabs/talos/assets/3342/fdb51086-f17d-45e1-b909-bafbef9033d6)

Rebooting Talos node from my [`sysadmin` container](https://ghcr.io/gerhard/sysadmin):

```sh
echo 1 > /host/proc/sys/kernel/sysrq
echo b > /host/proc/sysrq-trigger
```

**Reply by gerhard** [reply]
I was able to reboot it from Omni after the manual reboot.

**Reply by gerhard** [reply]
All working, thanks everyone!

![image](https://github.com/siderolabs/talos/assets/3342/ad98bbbc-6ce5-41a6-983b-939851193215)

`kube-prometheus-stack.yaml`

```yaml
# ↑ 1557 rows of config before

kubeEtcd:
  enabled: true

  ## If your etcd is not deployed as a pod, specify IPs it can be found on
  ##
  endpoints:
  - 192.168.88.12

  ## Etcd service. If using kubeEtcd.endpoints only the port and targetPort are used
  ##
  service:
    enabled: true
    port: 2381
    targetPort: 2381

# ↓ 2482 lines of config after
```

`patches/etcd-metrics.yaml` (for Omni)

```yaml
# ⚠️ Requires reboot after changing!
cluster:
  etcd:
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
```

**Reply by R-Studio** [reply]
Is there no way to automate this (prevent hardcoded IP's in `kube-prometheus-stack.yaml`)?

**Reply by abueschel** [reply]
@R-Studio I found a (admittedly bit ugly) workaround to this. Under the assumption that every controlplane node runs the same controlplane services (etcd, kube-controller-manager etc.) you can modify the selector of the headless service`kube-prometheus-stack-kube-etcd` that `kube-prometheus-stack` uses for the `serviceMonitor` resource:

`kube-prometheus-stack.yaml`:
```yaml
kubeEtcd:
  service:
    selector:
      k8s-app: kube-controller-manager # or any other service like kube-proxy or kube-scheduler
```

This populates the endpoints of the service with the controlplane server IPs, because `kube-controller-manager` pods are running in host network mode. You might want to do some additional relabeling, as the `serviceMonitor` will add some wrong labels for e.g. `pod` (etcd isn't running in a pod...)

Alternatively you could also add a simple deployment manifest to your Talos machine configuration for the controlplane. Just run a "pause" container in host network mode and you could pick a more fitting name.

**Reply by R-Studio** [reply]
@abueschel nice this workaround works perfectly (all of our controlplane nodes runs the same controlplane services).
My kube-prometheus-stack Helm values for etcd looks like this:
```yaml
kubeEtcd:
  enabled: true
  service:
    selector:
      k8s-app: kube-controller-manager # Fix selector for kube-etcd for Talos (set itentionally to kube-controller-manager because all master nodes has the same roles)
  serviceMonitor:
    relabelings:   # Add nodename label
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        separator: ;
        regex: ^(.*)$
        targetLabel: nodename
        replacement: $1
        action: replace
    metricRelabelings:   # Remove pod label
      - action: labeldrop
        regex: pod
```

**Reply by Tireur2cables** [reply]
Thanks @R-Studio for sharing your values.  
I am using the same values and wondering if the `remove label` part is working, I am not very experimented with prometheus labelling but I can see in my prometheus targets page a pod label for the etcd target with `kube-controller-manager-...` as value.  
I am wondering if you had the same issue or perhaps if you managed to remove it efectively (as this thread is quite old).

**Comment by Charlotte-br560** [comment]
You can retrieve etcd metrics directly from the etcd server using its HTTP API. The metrics endpoint typically resides at `http://<etcd-server>:<port>/metrics`. Ensure you have access to the etcd server and its port to fetch metrics.

**Reply by maxpain** [reply]
But this does require a client certificate.

**Comment by Hr46ph** [comment]
For those coming here using kube-prometheus-stack and looking for a way to make scraping etcd, controller manager and scheduler work, here is how I did it.

Add mc patch on all control planes:

```yaml
- op: add
  path: /cluster/etcd/extraArgs
  value:
    listen-metrics-urls: https://0.0.0.0:2379
- op: add
  path: /cluster/controllerManager/extraArgs
  value:
    bind-address: 0.0.0.0
- op: add
  path: /cluster/scheduler/extraArgs
  value:
    bind-address: 0.0.0.0
```
Patch:
`talosctl patch mc -n 10.0.0.1 --patch @etcd_metrics_patch.yaml`

And repeat for all control planes.

Get the certificates from etcd by running:

```sh
talosctl get etcdrootsecret -o yaml
talosctl get etcdsecret  -o yaml
```
The output should look like:
```yaml
spec:
    etcdCA:
        crt
```

```yaml
spec:
    etcd:
        crt:
        key:
```

The strings are already base64 encoded so straight copy/paste into a new secret.

Create a new secret:
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-client-cert
  namespace: monitoring
type: Opaque
data:
  etcd-ca.crt:
    LS0t....LS0K
  etcd-client.crt:
    LS0t....LS0K
  etcd-client-key.key:
    LS0t....=
```
`kubectl apply -f etcd-secret.yaml`.

In your custom-values.yaml for the helm deployment, add / change the following and replace the IP's with your control planes:

```yaml
kubeControllerManager:
  endpoints:
    - 10.0.0.1
    - 10.0.0.2
    - 10.0.0.3

kubeEtcd:
  endpoints:
    - 10.0.0.1
    - 10.0.0.2
    - 10.0.0.3
  service:
    selector:
      component: etcd
  serviceMonitor:
    scheme: https
    insecureSkipVerify: false
    serverName: "localhost"
    caFile: "/etc/prometheus/secrets/etcd-client-cert/etcd-ca.crt"
    certFile: "/etc/prometheus/secrets/etcd-client-cert/etcd-client.crt"
    keyFile: "/etc/prometheus/secrets/etcd-client-cert/etcd-client-key.key"

kubeScheduler:
  endpoints:
    - 10.0.0.1
    - 10.0.0.2
    - 10.0.0.3

prometheus:
  prometheusSpec:
    secrets:
      - etcd-client-cert
```
Note stating the obvious: the values above are not enough for a complete and succesful deployment of kube-prometheus-stack. These are only the additional changes that you need to make this particular scraping work.
