### DISCUSSION TITLE
Point to point  network configuration

### DISCUSSION THREAD

**Discussion by eshikhov** [siderolabs/talos#7519] [Q&A]
Does talos support network setup in pointopoint mode?

Configuration example
**etc/network/interfaces**
```
auto eth0
iface eth0 inet static
   address (ADDITIONAL IP)/32
   pointopoint (MIAN IP)
   gateway (MIAN IP)
```

**netplan**
```
network:
  ethernets:
    ens3:
      addresses:
      - (ADDITIONAL IP)/32
      routes:
      - to: 0.0.0.0/0
        via: (MIAN IP)
        on-link: true
      nameservers:
        addresses:
        - 8.8.8.8
        search: []
  version: 2
```
