### DISCUSSION TITLE
What is the proper, talos way to install basic (bridge, macvlan etc.) CNI plugins?

### DISCUSSION THREAD

**Discussion by ajgon** [siderolabs/talos#7583] [Q&A] [answered]
Default talos installation doesn't have most of the CNI plugins like `bridge` or `macvlan`. However I noticed, they are provided here: https://github.com/siderolabs/pkgs/pkgs/container/cni . 

The problem is, I can't create extension out of them, as talos complains, that extensions can't write to `/opt/cni/bin` directory. So what is the proper way to install it? I noticed in the docs, that `talosctl` [should do this automatically](https://www.talos.dev/v1.5/talos-guides/install/local-platforms/qemu/#requirements) - however I assume this is only in QEMU context, or I did something wrong...

**Comment by smira** [comment, marked as answer]
Most usually the CNI plugins are shipped as part of the CNI installation (e.g. Cilium, Calico). 

If they are not shipped with CNI, you have an option to use a Talos-provided init container which contains the plugins.

You can check it out in the default installation mode of Talos with Flannel CNI:

```yaml
  - command:
    - /install-cni.sh
    image: ghcr.io/siderolabs/install-cni:v1.5.0
    imagePullPolicy: IfNotPresent
    name: install-cni
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /host/opt/cni/bin/
      name: cni-plugin
```

You can use this [container image](https://github.com/siderolabs/extras/tree/main/install-cni) or any other similar image.

> We would love to make CNI plugins part of the base Talos installation (or via system extensions), and make `/opt/cni/bin` read-only, but that would make Talos incompatible with popular CNIs like Cilium.

**Reply by ajgon** [reply]
Ended up with something similar, but with my own image. Wasn't aware, there is a talos-provided one - which is great (one less thing to maintain for me :) ).

Works like a charm, thank you!

**Comment by okamidash** [comment]
I utilized this as a patch for the kube-router Daemonset; and resulted with the following:
```
cat << EOF > kube-router-patch.yaml
spec:
  template:
    spec:
      volumes:
      - hostPath:
          path: /opt/cni/bin
          type: ""
        name: cni-plugin
      initContainers:
        - command:
          - /install-cni.sh
          image: ghcr.io/siderolabs/install-cni:v1.5.0
          imagePullPolicy: IfNotPresent
          name: install-cni-sidero
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /host/opt/cni/bin/
            name: cni-plugin
EOF

cat kube-router-patch.yaml
kubectl patch ds -n kube-system kube-router --type strategic --patch-file patch.yaml
rm kube-router-patch.yaml
```

Looks like it's working. Would you benefit from instruction being provided to install kube-router?
