### DISCUSSION TITLE
how can enable KVM and OVS support?

### DISCUSSION THREAD

**Discussion by cybercoder** [siderolabs/talos#7793] [General]
I need to enable KVM support and OpenVswitch kernel module. How i can do that?
The goal is using OVS cni with KubeVirt VMs and Multus.

**Comment by frezbo** [comment]
KVm and ovenvswitcg are already compiled in the talos kernel, should work just fine

**Reply by cybercoder** [reply]
@frezbo 
Do you know how i can load openvswitch kernel module?
When i create a bridge ( e.g. "ext" ) using ovs-ctl inside a prvileged net host ready ovs container and add the ethernet port to it, talos shows both bridge and interface are down.

talosctl -n 172.16.15.110 get link
```
172.16.15.110   network     LinkStatus   eno50332176       5         ether                    00:0c:29:13:d2:4e                                 down         false
172.16.15.110   network     LinkStatus   ext               4         ether      openvswitch   00:0c:29:13:d2:4e                                 down         false
```

and dmesg shows:
```
172.16.15.111: kern:    info: [2023-10-07T22:10:34.099289494Z]: e1000: eno50332176 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: None
172.16.15.111: kern:    info: [2023-10-07T22:10:34.102092494Z]: IPv6: ADDRCONF(NETDEV_CHANGE): eno50332176: link becomes ready
172.16.15.111: user: warning: [2023-10-07T22:10:56.010322494Z]: [talos] controller failed {"component": "controller-runtime", "controller": "network.LinkSpecController", "error": "1 error occurred:\x5cn\x5ct* error enslaving/unslaving link \x5c"eno50332176\x5c" under \x5c"\x5c": netlink receive: operation not supported\x5cn\x5cn"}
```

ip link output inside ovs container:
```
22: ovs-system: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN qlen 1000
    link/ether 1e:a3:9d:47:8b:fb brd ff:ff:ff:ff:ff:ff
23: ext: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN qlen 1000
    link/ether 00:0c:29:30:fe:d5 brd ff:ff:ff:ff:ff:ff
```

**Reply by smira** [reply]
have you tried to mark it as 'up`?

**Reply by cybercoder** [reply]
It's getting up for a few seconds and all thing works but getting down after:

```
[48590.840864] vmxnet3 0000:13:00.0 eno33559296: NIC Link is Up 10000 Mbps
[48590.841824] 8021q: adding VLAN 0 to HW filter on device eno33559296
[48590.842301] IPv6: ADDRCONF(NETDEV_CHANGE): eno33559296: link becomes ready
[48590.865392] [talos] controller failed {"component": "controller-runtime", "controller": "network.LinkSpecController", "error": "1 error occurred:\n\t* error enslaving/unslaving link \"eno33559296\" under \"\": netlink receive: operation not supported\n\n"}
[48594.068883] [talos] controller failed {"component": "controller-runtime", "controller": "network.RouteSpecController", "error": "1 error occurred:\n\t* error adding route: netlink receive: file exists, message {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:0 Protocol:3 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:172.16.16.7 Gateway:172.16.16.254 OutIface:10 Priority:1024 Table:254 Mark:0 Pref:<nil> Expires:<nil> Metrics:<nil> Multipath:[]}}\n\n"}
```
output of talosctl dmesg:

```
172.16.15.110: user: warning: [2023-10-11T10:04:34.94190662Z]: [talos] controller failed {"component": "controller-runtime", "controller": "network.LinkSpecController", "error": "1 error occurred:\x5cn\x5ct* error enslaving/unslaving link \x5c"eno33559296\x5c" under \x5c"\x5c": netlink receive: operation not supported\x5cn\x5cn"}
```
I've an alpine linux in that VM networks works well with my ovs docker container.
The output of lsmod command on the Talos container shows only the vmxnet3:
```
# lsmod
Module                  Size  Used by    Not tainted
vmxnet3                65536  -
```
but the alpine linux:
```
docker compose exec vswitch /bin/sh
/ # lsmod
Module                  Size  Used by    Not tainted
nfnetlink_cttimeout    20480  0
veth                   36864  0
xt_conntrack           16384  2
xt_MASQUERADE          20480  2
nf_conntrack_netlink    57344  0
nfnetlink              20480  4 nfnetlink_cttimeout,nf_conntrack_netlink
xfrm_user              53248  1
xfrm_algo              16384  1 xfrm_user
iptable_nat            16384  1
xt_addrtype            16384  2
iptable_filter         16384  1
ip_tables              36864  2 iptable_nat,iptable_filter
x_tables               61440  6 xt_conntrack,xt_MASQUERADE,iptable_nat,xt_addrtype,iptable_filter,ip_tables
br_netfilter           32768  0
bridge                323584  1 br_netfilter
stp                    16384  1 bridge
llc                    16384  2 bridge,stp
overlay               163840  2
openvswitch           196608  3
nsh                    16384  1 openvswitch
nf_conncount           24576  1 openvswitch
nf_nat                 57344  3 xt_MASQUERADE,iptable_nat,openvswitch
nf_conntrack          184320  7 nfnetlink_cttimeout,xt_conntrack,xt_MASQUERADE,nf_conntrack_netlink,openvswitch,nf_conncount,nf_nat
nf_defrag_ipv6         24576  2 openvswitch,nf_conntrack
nf_defrag_ipv4         16384  1 nf_conntrack
libcrc32c              16384  3 openvswitch,nf_nat,nf_conntrack
ipv6                  679936 16 br_netfilter,bridge,[permanent]
af_packet              61440  0
joydev                 28672  0
mousedev               24576  0
psmouse               167936  0
serio_raw              20480  0
pcspkr                 16384  0
intel_agp              24576  1
intel_gtt              28672  1 intel_agp
i2c_piix4              28672  0
vmxnet3                73728  0
vmwgfx                389120  1
drm_ttm_helper         16384  1 vmwgfx
ttm                    98304  2 vmwgfx,drm_ttm_helper
input_leds             16384  0
vmw_balloon            24576  0
vmw_vmci               98304  1 vmw_balloon
intel_rapl_msr         20480  0
intel_rapl_common      32768  1 intel_rapl_msr
crct10dif_pclmul       16384  1
ghash_clmulni_intel    16384  0
sha512_ssse3           49152  0
aesni_intel           393216  0
crypto_simd            16384  1 aesni_intel
cryptd                 28672  2 ghash_clmulni_intel,crypto_simd
rapl                   16384  0
evdev                  28672  5
button                 24576  0
ac                     20480  0
dm_mod                167936  7
crc32_pclmul           16384  0
ata_generic            16384  0
pata_acpi              16384  0
sr_mod                 28672  0
cdrom                  81920  1 sr_mod
mptspi                 28672  2
mptscsih               40960  1 mptspi
mptbase                81920  2 mptspi,mptscsih
scsi_transport_spi     40960  1 mptspi
ata_piix               45056  0
libata                405504  3 ata_generic,pata_acpi,ata_piix
simpledrm              20480  0
drm_shmem_helper       20480  1 simpledrm
drm_kms_helper        208896  2 vmwgfx,simpledrm
cfbfillrect            16384  2 vmwgfx,drm_kms_helper
syscopyarea            16384  1 drm_kms_helper
cfbimgblt              16384  2 vmwgfx,drm_kms_helper
sysfillrect            16384  1 drm_kms_helper
sysimgblt              16384  1 drm_kms_helper
fb_sys_fops            16384  1 drm_kms_helper
cfbcopyarea            16384  2 vmwgfx,drm_kms_helper
drm                   679936  7 vmwgfx,drm_ttm_helper,ttm,simpledrm,drm_shmem_helper,drm_kms_helper
drm_panel_orientation_quirks    28672  1 drm
agpgart                57344  4 intel_agp,intel_gtt,ttm,drm
loop                   32768  0
ext4                  995328  2
crc32c_generic         16384  0
crc32c_intel           24576  5
crc16                  16384  1 ext4
mbcache                16384  1 ext4
jbd2                  172032  1 ext4
usb_storage            81920  0
usbcore               352256  1 usb_storage
usb_common             16384  1 usbcore
sd_mod                 53248  3
t10_pi                 16384  1 sd_mod
crc64_rocksoft         20480  1 t10_pi
crc64                  20480  1 crc64_rocksoft
scsi_mod              233472  7 sr_mod,mptspi,mptscsih,scsi_transport_spi,libata,usb_storage,sd_mod
scsi_common            16384  5 sr_mod,mptscsih,libata,usb_storage,scsi_mod
```

**Reply by cybercoder** [reply]
I've changed my docker base image from alpine to ubuntu but no difference:
Dockerfile
```
FROM alpine
RUN apk --update add openvswitch && mkdir -p /host/var/run/openvswitch && mkdir -p /host/var/lib/openvswitch
COPY cmd.sh /cmd.sh
RUN chmod +x /cmd.sh
CMD ["./cmd.sh"]
```
and cmd.sh
```
#!/bin/sh

ovsdb-tool create /host/var/lib/openvswitch/conf.db 2> /dev/null
ovsdb-server \
   --unixctl=/host/var/run/openvswitch/ovsdb-server.0.ctl \
   --pidfile=/host/var/run/openvswitch/ovsdb-server.pid \
   --remote=punix:/host/var/run/openvswitch/db.sock \
   --overwrite-pidfile \
   --detach \
   /host/var/lib/openvswitch/conf.db

ovs-vswitchd \
   --unixctl=/host/var/run/openvswitch/ovs-vswitchd.0.ctl \
   --pidfile=/host/var/run/openvswitch/ovs-vswitchd.pid \
   --overwrite-pidfile \
    unix:/host/var/run/openvswitch/db.sock
```
Its working on an alpine linux using docker compose:
```
services:
  vswitch:
    image: registry.ik8s.ir/ovs
    volumes:
    - /var/run/openvswitch:/host/var/run/openvswitch
    - /var/lib/openvswitch:/host/var/lib/openvswitch
    network_mode: "host"
    privileged: true
    cap_add:
    - SYS_MODULE
    - NET_ADMIN
    - SYS_NICE
```
But the DaemonSet:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ovs
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: ik8s-ovs
  template:
    metadata:
      labels:
        name: ik8s-ovs
    spec:
      
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/storage
        effect: NoSchedule
      - key: node-role.kubernetes.io/storage-node
        effect: NoSchedule
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: vswitch
        imagePullPolicy: Always
        image: registry.example.org/ovs
        securityContext:
          privileged: true
          capabilities:
            add:  
            - NET_ADMIN
            - SYS_MODULE
            - SYS_NICE
        volumeMounts:
        - mountPath: /host/var/run/openvswitch
          name: nodeovsrun
        - mountPath: /host/var/lib/openvswitch
          name: nodeovslib
        - mountPath: /lib/modules
          name: kernel-modules
        # command: [ "/cmd.sh" ]
      volumes:
      - name: nodeovsrun
        hostPath:
          path: /var/run/openvswitch
      - name: nodeovslib
        hostPath:
          path: /var/lib/openvswitch
      - name: kernel-modules
        hostPath:
          path: /lib/modules
```

**Comment by davmin** [comment]
@cybercoder have you had any success with this? I'm looking to configure multus/ovs/kubevirt on my talos cluster as well.

**Reply by cybercoder** [reply]
Yes, I've configured it and works as a charm. My problem was with networking and with ignoring the ovs interface in machine config, (the trick which @smira told me) my problem has been solved:
```yaml
      interfaces:
      - interface: eno33559296 # The ovs interface name (binding MULTUS CNI and OVS).
        ignore: true
```
