### DISCUSSION TITLE
vip config with predictable interface names

### DISCUSSION THREAD

**Discussion by stelb** [siderolabs/talos#7798] [Q&A] [answered]
Hi,

I would like to use a VIP for the controlplane nodes, but config examples show:

https://www.talos.dev/v1.5/talos-guides/network/vip/

```
machine:
  network:
    interfaces:
    - interface: eth0
      dhcp: true
      vip:
        ip: 192.168.0.15
```

As this did not work, I thought the interfacename might be not correct. And indeed its enx`mac`
How can I define a vip without manually crafting config files / patches?

Regards
