### DISCUSSION TITLE
How to update proxy settings for running cluster?

### DISCUSSION THREAD

**Discussion by zulhfreelancer** [siderolabs/talos#7835] [Q&A] [answered]
I have a Talos v1.5.3 cluster consists of 1 control plane and 1 worker. I'm trying to set `--metrics-bind-address=0.0.0.0:10249` flag to the kube-proxy pods ([docs](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/)).

According to [ProxyConfig](https://www.talos.dev/v1.5/reference/configuration/#proxyconfig) section, this can be done using `extraArgs` field.

So, here is my _controlplane.yaml_ file:

```yaml
# lines removed for brevity
cluster:
  proxy:
    image: registry.k8s.io/kube-proxy:v1.28.2 
    extraArgs:
      metrics-bind-address: "0.0.0.0:10249"
```

When I do `talosctl apply-config --file controlplane.yaml` on existing cluster, the kube-proxy container args didn't get updated. 

However, when I do `talosctl apply-config --file controlplane.yaml` on new cluster, it worked fine.

![image](https://github.com/siderolabs/talos/assets/3416976/91fb3030-b48d-4686-a403-de2fa9500114)

What else that I've tried but didn't work (in random order):
- use `talosctl apply-config` with `--mode=reboot`
- `talosctl reboot` to reboot the node
- `talosctl service kubelet restart`
- restart the `kube-proxy-*` pods in `kube-system` namespace
- create a _patch.yaml_ file and ran `talosctl patch mc -n IP -e IP --talosconfig talosconfig --patch @patch.yaml`

Contents of _patch.yaml_ file:

```yaml
cluster:
  proxy:
    image: registry.k8s.io/kube-proxy:v1.28.2 
    extraArgs:
      metrics-bind-address: "0.0.0.0:10249"
```

Did I miss something?
