### DISCUSSION TITLE
Setting network interface name via udev rules

### DISCUSSION THREAD

**Discussion by btkostner** [siderolabs/talos#8018] [Q&A]
Hello everyone 👋 

I'm currently running Talos on a cluster of various Intel NUCs running Cilium. Due to some configurations options, I need all of the interface names to be the same. I have tried to achieve this with udev rules set in the configuration like so:

```yaml
machine:
  udev:
    # Rename all Intel NUC network devices to net0 for consistency
    # required for Cilium configuration. Hardware addresses are taken
    # from the output of `talosctl get links`.
    #
    # Note: currently this does not work
    rules:
      - SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="88:ae:dd:0e:a9:39" ATTR{type}=="1", NAME="net0"
      - SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="48:21:0b:2e:2b:6c" ATTR{type}=="1", NAME="net0"
      - SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="1c:69:7a:aa:4a:db" ATTR{type}=="1", NAME="net0"
      - SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="1c:69:7a:60:69:20" ATTR{type}=="1", NAME="net0"
```

Sadly running this causes this to show up in dmesg:

```
192.168.3.12: user: warning: [2023-12-01T17:16:27.419532224Z]: [talos] task writeUdevRules (1/1): starting
192.168.3.12: daemon:     err: [2023-12-01T17:16:27.451923224Z]: udevd[2662]: Error changing net interface name enp89s0 to net0: Resource busy
192.168.3.12: daemon: warning: [2023-12-01T17:16:27.454487224Z]: udevd[2662]: could not rename interface '8' from 'enp89s0' to 'net0': Resource busy
192.168.3.12: user: warning: [2023-12-01T17:16:27.563055224Z]: [talos] task writeUdevRules (1/1): done, 143.517169ms
```

I've also tried to rewrite some of the built in udev rule files with no success.

Has anyone been able to rename network devices consistently?
