### DISCUSSION TITLE
How do I add more exempted namespaces for pod security

### DISCUSSION THREAD

**Discussion by stevefan1999-personal** [siderolabs/talos#8042] [Q&A]
I have this patch.yaml:
```yaml
cluster:
  apiServer:
    admissionControl:
    - name: PodSecurity
      configuration:
        exemptions:
          namespaces:
          - openelb-system
```
Then I ran `talosctl patch machineconfig --patch "@patch.yaml" --talosconfig=talosconfig`, then the cluster stopped working. Why? Am I doing this wrong?

**Comment by smira** [comment]
You need to add some details on what went wrong exactly.

**Reply by stevefan1999-personal** [reply]
Uh the apiserver, controller-manager and scheduler just stopped working, and I couldn't find more diagnostic log that are useful from the console

**Reply by stevefan1999-personal** [reply]
just FYI the admission-control YAML looks like this after patching:
```yaml
metadata:
    namespace: controlplane
    type: AdmissionControlConfigs.kubernetes.talos.dev
    id: admission-control
    version: 3
    owner: k8s.ControlPlaneAdmissionControlController
    phase: running
    created: 2023-12-08T11:00:54Z
    updated: 2023-12-08T11:12:45Z
spec:
    config:
        - name: PodSecurity
          configuration:
            apiVersion: pod-security.admission.config.k8s.io/v1alpha1
            defaults:
                audit: restricted
                audit-version: latest
                enforce: baseline
                enforce-version: latest
                warn: restricted
                warn-version: latest
            exemptions:
                namespaces:
                    - kube-system
                    - openelb-system
                    - openelb-system
                runtimeClasses: []
                usernames: []
            kind: PodSecurityConfiguration
```
