### DISCUSSION TITLE
Can't get network running (perhaps network issue in Talos)?

### DISCUSSION THREAD

**Discussion by blitss** [siderolabs/talos#8077] [Q&A] [answered]
I'm trying to run talos on the Hetzner bare metal server, but unfortunately I'm not able to setup a network properly (it runs ok on the installer but after bootstrap and reboot I just lose the connection.). If I try to configure Talos without network option it runs just fine but I'm not able to use specific network configuration.

Here's the config I'm attempting (values are altered). It's heavily influenced by netplan config which was I trying to reproduce in Talos, which I'll also provide below

Maybe someone can take a look and tell if there's something wrong with the config or anything I'm missing.

```yaml
machine:
  install:
    disk: /dev/nvme1
    image: ghcr.io/siderolabs/installer:v1.5.5
  network:
    hostname: node1
    nameservers:
      - 185.12.64.1
      - 2a01:4ff:ff00::add:2
      - 185.12.64.2
      - 2a01:4ff:ff00::add:1

    interfaces:
      # External network configuration
      - interface: enp35s0
        # This vlan corresponds to a vswitch in Hetzner which provides virtual network for servers
        vlans:
          - addresses:
              - 10.0.1.3/24
            vlanId: 4000
            mtu: 1400
            routes:
              - network: 10.0.0.0/16
                gateway: 10.0.1.1
        addresses:
          # These are external IPs that are available to server using the gateway
          - 135.181.180.222/32
          - 135.181.180.234/32
          - 2a01:4f9:3a:22c8::2/64
        routes:
          - network: 135.181.180.193/32
          - network: 0.0.0.0/0
            gateway: 135.181.180.193
          - network: 2a01:4f9:3a:22c8::/64
            gateway: fe80::1
```

Here's an example netplan config which would work on Ubuntu, for example:

```
### Hetzner Online GmbH installimage
network:
  version: 2
  renderer: networkd
  ethernets:
    enp35s0:
      addresses:
         - 135.181.180.222/32
         - 135.181.180.234/32
      routes:
        - on-link: true
          to: 0.0.0.0/0
          via: 135.181.180.19
        - to: default
          via: fe80::1
      nameservers:
        addresses:
          - 185.12.64.1
          - 2a01:4ff:ff00::add:2
          - 185.12.64.2
          - 2a01:4ff:ff00::add:1

  vlans:
    enp35s0.4000:
      id: 4000
      link: enp35s0
      mtu: 1400
      routes:
        - to: "10.0.0.0/16"
          via: "10.0.1.1"

      addresses: [10.0.1.3/24]
```

**Comment by smira** [comment]
the configuration looks fine to me, it'd be weird if it works during the install, but fails afterwards

Do you have console logs of the machine when it fails?

**Reply by blitss** [reply, marked as answer]
@smira thank you for clarification, you're right. The problem was that I actually had a different network interface name locally and that's why it didn't work (spent a day trying to figure that out). 

Here's a working config for anyone that might try to setup Talos with Hetzner as well (most of the configs out there have configs that are working only for legacy Hetzner servers):

```yaml
cluster:
  # This makes sure all communication goes over internal network, see: https://www.talos.dev/v1.6/introduction/prodnotes/#example
  etcd:
    advertisedSubnets: # listenSubnets defaults to advertisedSubnets if not set explicitly
      - 10.0.0.0/16

machine:
  kubelet:
    nodeIP:
      validSubnets:
        - 10.0.0.0/16

  # This enables huge pages and relevant settings for Elastic, you can disable it if you don't need it
  sysctls:
    vm.nr_hugepages: "1024"
    vm.max_map_count: 262144 # Increase max_map_count required by eg. elasticsearch
  install:
    disk: /dev/nvme1
    image: ghcr.io/siderolabs/installer:v1.5.5
    wipe: true
    bootloader: true
  network:
    hostname: node1

    interfaces:
      # External network configuration
      - interface: enp35s0
        # This vlan corresponds to a vswitch in Hetzner which provides virtual network for servers. You can replace 10.0.1.3 with your node IP address
        vlans:
          - addresses:
              - 10.0.1.3/24
            vlanId: 4000
            dhcp: false
            mtu: 1400
            routes:
              - network: 10.0.0.0/16
                gateway: 10.0.1.1
        dhcp: false
        addresses:
          # These are external IPs that are available to server using the gateway
          - 135.181.180.222/32
          - 135.181.180.234/32
          - 2a01:4f9:3a:22c8::2/64
        routes:
          # 135.181.180.193 is a gateway IP
          - network: 135.181.180.193/32
          - network: 0.0.0.0/0
            gateway: 135.181.180.193
          - network: 2a01:4f9:3a:22c8::/64
            gateway: fe80::1
```

To create a disk with Talos installer you can do so from Hetzner rescue system (then reboot)., You have to disable Raid beforehand (because otherwise I was unable to boot it at all):

```bash
# Define the Talos version and the target disk
TALOS_VERSION="v1.6.0-beta.1"
# Update this to the correct disk, e.g., /dev/nvme0n1 or /dev/nvme1n1
TARGET_DISK="/dev/nvme0n1"

# Download the release asset for metal deployments
wget -O /tmp/talos.raw.xz "https://github.com/siderolabs/talos/releases/download/${TALOS_VERSION}/metal-amd64.raw.xz"

# Unpack the .xz file and extract the .raw file
xz -dk /tmp/talos.raw.xz

# Write the raw disk image directly to the hard drive
dd if=/tmp/talos.raw of="${TARGET_DISK}" bs=4M && sync
```
