### DISCUSSION TITLE
Mirror registry is not working during bootstrap

### DISCUSSION THREAD

**Discussion by soulwhisper** [siderolabs/talos#8094] [General]
When I start a new talos cluster with private registry, it shows 
   "failed to pull image "gcr.io/etcd-development/etcd:v3.5.11": failed to resolve reference "gcr.io/etcd-development/etcd:v3.5.11": gcr.io/etcd-development/etcd:v3.5.11: not found",
   however if I change the etcd image to "hub.homelab.internal/gcr.io/etcd-development/etcd:v3.5.11", it is working.

To reproduce my scenario, I will provide necessary snipplets below:
```yaml
# talos-vmw-master-01.yaml
# 172.19.82.10 is my private dns, it contains record for hub.homelab.internal
...
  kubelet:
    image: ghcr.io/siderolabs/kubelet:v1.29.0
    extraArgs:
      rotate-server-certificates: "true"
    defaultRuntimeSeccompProfileEnabled: true
    disableManifestsDirectory: true
  network:
    hostname: talos-vmw-master-01
    interfaces:
      - deviceSelector:
          busPath: 0*
        addresses:
          - 172.19.82.31/24
        routes:
          - network: 0.0.0.0/0
            gateway: 172.19.82.1
        mtu: 1500
        dhcp: false
    nameservers:
      - 172.19.82.10
    disableSearchDomain: true
...
  registries:
    mirrors:
      docker.io:
        endpoints:
          - https://hub.homelab.internal/docker.io/
        overridePath: true
      gcr.io:
        endpoints:
          - https://hub.homelab.internal/gcr.io/
        overridePath: true
      ghcr.io:
        endpoints:
          - https://hub.homelab.internal/ghcr.io/
        overridePath: true
      registry.k8s.io:
        endpoints:
          - https://hub.homelab.internal/k8s.io/
        overridePath: true
    config:
      hub.homelab.internal:
        tls:
          insecureSkipVerify: true
        auth:
          username: <secret>
          password: <secret>

# my private registry is using Jfrog container registry, repo configs below
# all the registries are remote registry, work as a pull-through cache
# I have to use http-proxy to access some repo, so if you dont need it, just skip it

docker.io = https://registry-1.docker.io/, default
gcr.io = https://gcr.io/, disable 'blocking manifest v2 schema 1', w/ http-proxy, Bypass-HEAD-request
ghcr.io = https://ghcr.io/, default, w/ http-proxy
k8s.io = https://registry.k8s.io/, default, w/ http-proxy

# I have test direct pull w/ docker, daemon.json below
# both "docker pull hub.homelab.internal/ghcr.io/siderolabs/kubelet:v1.29.0" 
# and "docker pull hub.homelab.internal/gcr.io/etcd-development/etcd:v3.5.11" worked

{
  "live-restore": true,
  "dns": ["<my-internal-dns-ip>", "8.8.8.8"],
  "registry-mirrors": ["https://hub.homelab.internal"]
}

# note, hub.homelab.internal is enabled https w/ step-ca, its ca.crt is trusted by host with commands below
# this part is necessary for docker, yet talos using "insecureSkipVerify"
cp ca.crt /etc/pki/ca-trust/source/anchors/
update-ca-trust

```
