### DISCUSSION TITLE
How can I get Virtual/Shared IP running (on TuringPI2/RK1)?

### DISCUSSION THREAD

**Discussion by bguijt** [siderolabs/talos#8222] [Q&A] [answered]
Context: I have a turingpi2 with 4 RK1 (rockchip) units installed. Now I want to have Talos flashed on them, with Virtual / Shared IP enabled according to https://www.talos.dev/v1.6/talos-guides/network/vip/. However, after applying controlplane config to two RK1 units, both cannot use the configured vip IP (192.168.1.210) and log the line:

`[ 1476.380178] [talos] kubernetes endpoint watch error {"component": "controller-runtime", "controller": "k8s.EndpointController", "error": "failed to list *v1.Endpoints: Get \"https://192.168.1.210:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&limit=500&resourceVersion=0\": dial tcp 192.168.1.210:6443: connect: no route to host"}`

every other minute or so.

The RK1 units have IP addresses 192.168.1.111 and 192.168.1.112, so within the same 192.168.1.0/24 subnet.

The network section in `controlplane.yaml` is this:

```yaml
    network:
        # `interfaces` is used to define the network interface configuration.
        interfaces:
            - interface: eth0 # The interface name.
              dhcp: true # Indicates if DHCP should be used to configure the interface.
              # Virtual (shared) IP address configuration.
              vip:
                ip: 192.168.1.210 # Specifies the IP address to be used.
```

Can anyone help me? What did I do wrong?

Thanks in advance!

/Bart

**Comment by smira** [comment]
First of all, most probably you missed the step to [bootstrap the cluster](https://www.talos.dev/v1.6/introduction/getting-started/#kubernetes-bootstrap).

Second, running two  controlplane nodes is not a good idea, as `etcd` would lose quorum in case of any node failure.

**Comment by bguijt** [comment]
Thanks for your reply @smira !

A little more context: I just added a second controlplane node to verify whether the VIP feature needed more than 1 controlplane node for it to work. Turns out, it did not make a difference. I am planning to run three of these nodes.

I followed the instructions of @nberlee as demonstrated in [this video](https://asciinema.org/a/633378), from his [RK1 specific fork of Talos](https://github.com/nberlee/talos). I am using version 1.6.3.

And I already bootstrapped the cluster. These services are running:

```zsh
$ talosctl -n 192.168.1.111 services
NODE            SERVICE      STATE     HEALTH   LAST CHANGE     LAST EVENT
192.168.1.111   apid         Running   OK       16h17m36s ago   Health check successful
192.168.1.111   containerd   Running   OK       16h17m39s ago   Health check successful
192.168.1.111   cri          Running   OK       16h17m36s ago   Health check successful
192.168.1.111   etcd         Running   OK       16h12m2s ago    Health check successful
192.168.1.111   kubelet      Running   OK       16h12m0s ago    Health check successful
192.168.1.111   machined     Running   OK       16h17m46s ago   Health check successful
192.168.1.111   trustd       Running   OK       16h12m6s ago    Health check successful
192.168.1.111   udevd        Running   OK       16h17m41s ago   Health check successful
```

Watching the video at the [Virtual/Shared IP guide](https://www.talos.dev/v1.6/talos-guides/network/vip/) it seems a service named `networkd` also needs to be running. Might this be something to look into?

Do I need to have specific router settings?

**Reply by nberlee** [reply, marked as answer]
Hi @bguijt ,

Thanks for using the image the eth0 is wrong, unless you have set :
```
        extraKernelArgs:
            - net.ifnames=0
```
Please use:
```
    network:
        # `interfaces` is used to define the network interface configuration.
        interfaces:
            - deviceSelector:
                driver: rk_gmac-dwmac 
              dhcp: true # Indicates if DHCP should be used to configure the interface.
              # Virtual (shared) IP address configuration.
              vip:
```
