### DISCUSSION TITLE
How to add Gasket extension to a custom image?

### DISCUSSION THREAD

**Discussion by hagak** [siderolabs/talos#8454] [Q&A] [answered]
I am attempting to use the RK1 fork of talos https://github.com/nberlee/talos and wondering how it would be possible to use a System extension with it, such as the Gasket extension.

**Comment by frezbo** [comment, marked as answer]
You'd need to pull down the corresponding `imager` container image and use it to build an installer/metal image containing with gasket extension. The follow this https://www.talos.dev/v1.6/talos-guides/install/boot-assets/#imager with the custom imager

**Reply by hagak** [reply]
So I have done this with several extensions and they all create the disk image EXCEPT the gasket-driver.  Below is the error I get with the gasket-driver
```
docker run --rm -t -v $PWD/_out:/out -v /dev:/dev --privileged ghcr.io/nberlee/imager:v1.6.7 metal --system-extension-image ghcr.io/siderolabs/gasket-driver:09385d4-v1.6.7@sha256:1add5eaa6da69397ed19d9af744e0564d36443fa75859f562dd9418376ce522a
profile ready:
arch: arm64
platform: metal
secureboot: false
version: v1.6.7
input:
  kernel:
    path: /usr/install/arm64/vmlinuz
  initramfs:
    path: /usr/install/arm64/initramfs.xz
  dtb:
    path: /usr/install/arm64/dtb
  uBoot:
    path: /usr/install/arm64/u-boot
  rpiFirmware:
    path: /usr/install/arm64/raspberrypi-firmware
  baseInstaller:
    imageRef: ghcr.io/nberlee/installer:v1.6.7
  systemExtensions:
    - imageRef: ghcr.io/siderolabs/gasket-driver:09385d4-v1.6.7@sha256:1add5eaa6da69397ed19d9af744e0564d36443fa75859f562dd9418376ce522a
output:
  kind: image
  imageOptions:
    diskSize: 1306525696
    diskFormat: raw
  outFormat: .xz
◰ copying kernel modules from /tmp/imager2988444800/extensions/0/rootfs/lib/modules failed: stat /tmp/imager2988444800/extensions/0/rootfs/lib/modules/6.6.22-talos: no such file or directory
```
