### DISCUSSION TITLE
talosctl gen config with extraMounts info

### DISCUSSION THREAD

**Discussion by marcoferraraUK** [siderolabs/talos#8497] [Q&A] [answered]
Hi, 
I'm try to configure talos cluster.
I generate my config files using the command:
```
talosctl gen config k8s-cluster https://talos.mydomain.local:6443 --with-examples=false --with-docs=false --with-kubespan \
	--kubernetes-version v1.28.0 \
	--talos-version v1.6.6 \
	--with-secrets secrets.yaml \
	--additional-sans talos.mydomain.local,1192.168.0.1,192.168.0.2,192.168.0.3 \
	--dns-domain mydomain.local
```

Now I need configure the extraMounts as below:
```
 extraMounts:
    - destination: /var/openebs
       type: bind
       source: /var/openebs
       options:
          - bind
          - rshared
          - rw
```

Is there a way to pass it to the `talosctl gen config` command?
I tried to use `--config-patch` but I receive the error:
`error parsing config JSON patch: missing kind`

**Comment by marcoferraraUK** [comment, marked as answer]
ok I found the solution:
```
cat openebs.yaml
machine:
  kubelet:
    extraMounts:
      - destination: /var/openebs
        type: bind
        source: /var/lib/openebs
        options:
          - bind
          - rshared
          - rw
```

and apply using the command:
```
talosctl gen config k8s-cluster https://talos.mydomain.local:6443 --with-examples=false --with-docs=false --with-kubespan \
	--kubernetes-version v1.28.0 \
	--talos-version v1.6.6 \
	--with-secrets secrets.yaml \
	--additional-sans talos.mydomain.local,1192.168.0.1,192.168.0.2,192.168.0.3 \
	--dns-domain mydomain.local
	--config-patch @openebs.yaml
```
