### DISCUSSION TITLE
Unable to get VLAN working

### DISCUSSION THREAD

**Discussion by vijayanms** [siderolabs/talos#8676] [General]
I am trying to setup a cluster and am running into some connectivity issues that have me stumped. I went through similar threads @ https://github.com/siderolabs/talos/issues/7331, https://github.com/siderolabs/talos/issues/8079 and https://github.com/siderolabs/talos/discussions/7844 but am not able to resolve the error I am facing.

I am verifying the setup on a VM before going ahead with the bare metal install. The host running the VM uses a bridge interface and vlans w/o any errors. 

The cluster networking config is as follows

```
  network:
    hostname: rodin
    interfaces:
      - interface: bond0
        bond:
          interfaces: []
          deviceSelectors:
            - hardwareAddr: 52:54:00:eb:c5:6f
              driver: virtio_net
          mode: active-backup
          miimon: 100
        vlans:
          - addresses:
              - 10.10.1.62/24
            routes:
              - network: 0.0.0.0/0
                gateway: 10.10.1.1
                metric: 1008
            dhcp: false
            vlanId: 101
            mtu: 9000
          - addresses:
              - 10.10.7.62/24
            routes:
              - network: 0.0.0.0/0
                gateway: 10.10.7.1
                metric: 1009
            dhcp: false
            vlanId: 107
            mtu: 9000
        mtu: 9000
        dhcp: false
    nameservers:
      - 10.10.1.124
      - 10.10.1.1
```

```
  kubelet:
    extraArgs:
      feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
      rotate-server-certificates: "true"
    nodeIP:
      validSubnets:
        - 10.10.1.0/24
```

```
  etcd:
    advertisedSubnets:
      - "10.10.1.0/24"
```

![Screenshot_20240429_190628](https://github.com/siderolabs/talos/assets/2917621/c6ca97f8-2b1d-4c88-903b-45165c0c2022)

The dashboard shows that connectivity as ok. I do not see any traffic reaching my gateway device from either of the IP's and the dashboard keeps scrolling with a repeating i/o timeout error. I'm not sure what I am missing here and am completely stumped on what I can do to resolve this error and get the install process to complete.
