### DISCUSSION TITLE
How does mirror registry endpoints work?

### DISCUSSION THREAD

**Discussion by devantler** [siderolabs/talos#8787] [Q&A] [answered]
Q1 I noticed that it is possible to add multiple endpoints to one mirror-registry. What is the logic in place when doing that? For example:

```yaml
machine:
  registries:
    mirrors:
      docker.io:
        endpoints:
          - https://harbor/v2/proxy-docker.io
          - https://docker.io
```

Q2 I would like to reroute all images to my harbor by default, but if it isnt up yet, I would like the requests to target their original source. Is that possible with Talos mirror-registries?
