### DISCUSSION TITLE
Talos not bootable after install

### DISCUSSION THREAD

**Discussion by BloodWorkXGaming** [siderolabs/talos#8806] [Q&A] [answered]
Hello together,
First all I wanted to thank you for creating talos, it is exactly the solution we need.

We have multiple issues with setting up a cluster:

After booting from the ISO and applying the config (installing it) everything works fine. I even joined another the Node into the Cluster. However, after rebooting (after changing a config option) there is no bootable device found. This is across all three nodes where we installed the OS. We tried it with and without fulldiskencryption being enabled and on multiple different types of drives. 
This is the install config file:
```yaml
   # Used to provide instructions for installations.
    install:
        # disk: /dev/nvme0n1 # The disk used for installations.
        disk: /dev/sdc # The disk used for installations.
        image: ghcr.io/siderolabs/installer:v1.7.2 # Allows for supplying the image used to perform the installation.
        wipe: true # Indicates if the installation disk should be wiped at installation time.
```
Are we missing anything here?

The second issue is that we can't create a bond with the name `bond0`, `bond1` however works. This took us quite a while to figure out why our config always fails. Maybe it's worth adding this to the docs.

The third issue is regarding the DNS-Name to multiple control plane nodes as described here: https://www.talos.dev/v1.7/introduction/prodnotes/#dns-records  
Using nslookup I can see all entries, but the talosctl and kubernetes as well always only use one of the entries and therefore fail to connect to the Control Plane if that node is down (hence not being HA). Is there any additional settings needed?

We are installing talos 1.7.2 on bare Metal on three "Gigabyte mc le0" Boards.

Thanks you in advance for any help!

**Comment by smira** [comment]
> Are we missing anything here?

It's hard to say, check your BIOS/UEFI settings to make sure your disk is in the list of bootable devices.

`wipe: true` is not needed usually.

 > The second issue is that we can't create a bond with the name bond0, bond1 however works. This took us quite a while to figure out why our config always fails. Maybe it's worth adding this to the docs.

There's no difference between `bond0` and `bond1` - they work exactly same way.

> The third issue is regarding the DNS-Name to multiple control plane nodes as described here:

Might be an issue with round-robin behavior of DNS resolvers you're using, or something similar, but once again not something that Talos can fix. (it should return a randomized list of addresses).

**Comment by BloodWorkXGaming** [comment]
Hello smira,

Thank you very much for the answer!
Thanks for the tip with the round-robin-dns, I will check for this setting :)

`wipe: true` seems to be needed in our case otherwise it will just shut down (but this might be due to a previous installation).

The disk is not in the list of the bootable devices in the uefi, however a previous installation of ubuntu was working just fine with this exact setup. Is there any setting I need to set for it to force install a bootloader? Something like setting the platform as "metal", as it wouldn't install a bootloader on a cloud instance?

Thanks in advance!

**Reply by smira** [reply]
> The disk is not in the list of the bootable devices in the uefi, however a previous installation of ubuntu was working just fine with this exact setup. Is there any setting I need to set for it to force install a bootloader? Something like setting the platform as "metal", as it wouldn't install a bootloader on a cloud instance?

Using wrong disk? Not using UEFI boot? hard to say, as this is hardware-dependent a lot.

Bootloader is always installed, and if booted with UEFI, Talos will install UEFI bootloader, otherwise it will install BIOS bootloader.

**Reply by attilaolah** [reply]
I had a similar issue, unbootable AMD SOC boards, and this helped me a lot:

> if booted with UEFI, Talos will install UEFI bootloader, otherwise it will install BIOS bootloader

I just stumbled upon this information now, and it allowed me to install Talos on a couple buggy AMD SOC boards I had lying around, that somehow had a buggy UEFI implementation or somesuch.

By default, the Talos ISO from the USB loads the installer using UEFI, so Talos ended up installing a UEFI bootloader which the board was unable to load.

Once I selected the non-UEFI USB boot option in the boot menu, I managed to install Talos using the BIOS bootloader and now it loads fine.

**Comment by BloodWorkXGaming** [comment, marked as answer]
Hey, I just wanted to give a quick update how we were able to solve the issue.

As we were running with secure boot enabled, we had to use a secure boot installer image in the install script
```yaml
    install:
        disk: /dev/nvme0n1
        image: factory.talos.dev/installer-secureboot/91c86b0fe2cc527fa3a18208aa55377e8e906a83e3113c11aa35aee572068893:v1.7.2
        wipe: true
        extraKernelArgs:
            - talos.platform=metal
```

We had the normal install script in there and everything worked fine, it just didn't install a compatible bootloader.
After changing everything works fine.

To avoid future problems like this, I would recommend adding an additional check if the correct installer image is used when starting with the wrong image. This could have avoided a few frustrating hours if the installer just failed with a meaning full error instead of working with silently not installing a bootloader.
