### DISCUSSION TITLE
Do registry mirrors work before having a running CNI?

### DISCUSSION THREAD

**Discussion by michel-zimmer** [siderolabs/talos#8940] [Q&A]
Hello, I'm trying to run Talos with Cilium and behind a corporate firewall with a registry mirror.
Everything works as expected unless I try to achieve both at the same time.
Without a manual CNI deployment everything appears to be working.
```yaml
machine:
  registries:
    mirrors:
      docker.io:
        endpoints:
          - https://<registry-mirror-domain>
      gcr.io:
        endpoints:
          - https://<registry-mirror-domain>
      quay.io:
        endpoints:
          - https://<registry-mirror-domain>
      public.ecr.aws:
        endpoints:
          - https://<registry-mirror-domain>
      registry.k8s.io:
        endpoints:
          - https://<registry-mirror-domain>
```
For example I've deployed ArgoCD using the upstream images from `quay.io`.
In the next iteration I wanted to deploy Clilium as CNI.
As described in the documentation I've disabled the default CNI:
```yaml
cluster:
  network:
    cni:
      name: none
  proxy:
    disabled: true
```
Then when using `helm … argocd argo-cd --repo https://argoproj.github.io/argo-helm …` and after waiting a bit I get lines like the following in the logs from cri (`talosctl … logs cri`):
```
test-k8s-1…: {"error":"failed to do request: Head \"https://quay.io/v2/cilium/operator-generic/blobs/sha256:3014d4bcb8352f0ddef90fa3b5eb1bbf179b91024813a90a0066eb4517ba93c9\": dial tcp 52.204.93.25:443: i/o timeout","host":"quay.io","level":"info","msg":"trying next host","time":"2024-06-26T11:26:33.075976754Z"}
```
This looks exactly like every other case where something is blocked by our firewall as no TCP connection can be established.
But I would have expected Talos not trying to pull the images from `quay.io` directly. The IP address from the logs is not our registry mirror but instead is one of the public IP addresses we get when looking up `quay.io`.

So does someone know what's going on here? Is it actually not possible to use a registry mirror before / while installing a custom CNI currently?

Thanks and best regards :)
