### DISCUSSION TITLE
Problem joining in new nodes

### DISCUSSION THREAD

**Discussion by t-persson** [siderolabs/talos#8969] [Q&A] [answered]
I am having a problem with joining in a new node into my cluster.

Getting this error message:
`error applying new configuration: rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: remote error: tls: certificate required"`

I have set up my secrets, controlplane patches and worker patches according to this: https://www.talos.dev/v1.7/introduction/prodnotes/#configure-talos

The secrets.yaml was generated by talosctl when I created the cluster. The controlplane and worker yaml files have since been removed.

To generate new controlplane and worker machine configurations I do:

`talosctl gen config --with-secrets secrets.yaml --config-patch-control-plane @controlplane.patch --config-patch-worker @worker.patch $(NAME) https://$(CLUSTER):$(PORT)`

And I try to apply a configuration to a new node like this:
`talosctl apply-config --insecure --nodes $(NODE) --file controlplane.yaml`
The same error happens when adding a worker as well.

I have verified that the secrets in the controlplane.yaml and secrets.yaml are the same using `talosctl gen secrets --from-controlplane-config controlplane.yaml -o test.yaml` and diffing them.

```
# cat worker.patch
machine:
    certSANs:
        - <CLUSTER HOST>
        - 172.20.10.65
```

```
# cat controlplane.patch
machine:
    certSANs:
        - <CLUSTER HOST>
        - 172.20.10.65
    network:
        interfaces:
          - deviceSelector:
                busPath: "0*"
            dhcp: true
            vip:
                ip: 172.20.10.65
cluster:
    apiServer:
        certSANs:
            - 172.20.10.65
```
