### DISCUSSION TITLE
NFS CSI (nfs.csi.k8s.io) complains of permission denied in tmp directory when writing a pvc.

### DISCUSSION THREAD

**Discussion by Spaghetto392** [siderolabs/talos#8984] [Q&A]
Hi, when trying to create a NFS based PVC, I get an error saying that permission was denied for creating a directory in /tmp. I was wondering if /tmp was potentially made read only, or otherwise has some permissions that k8s fails to clear. That or is the CSI I'm using just incompatible with Talos?

**Comment by smira** [comment]
On the host `/tmp` is a `tmpfs`, so it's writable (but it's small, so it's better not to create anything big there).

**Reply by Spaghetto392** [reply]
Hi, thank you for the reply. Do you happen to know if it's a CSI incompatibility or something then? Does Talos have a guide for creating NFS PVCs? I haven't been able to find much on the internet about the issue I've been having.

**Reply by smira** [reply]
I know that people use NFS mounts with Talos, but we don't have any guide on that topic.

It's not quite possible to help without even having a way to reproduce or just the full logs.

**Reply by Spaghetto392** [reply]
Here is the configs I've used:

K8S version: 1.28.0
Talos Version: 1.7.4

CSI installed via helm:
```
helm repo add csi-driver-nfs https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
helm install csi-driver-nfs csi-driver-nfs/csi-driver-nfs --namespace kube-system --version v4.7.0
```

storage-class.yaml
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.200
  share: /mnt/Pool1/Test
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - hard
  - nfsvers=4.1
```

pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
  namespace: test
spec:
 accessModes:
   - ReadWriteMany
 storageClassName: nfs-csi
 resources:
   requests:
     storage: 2Gi
```

Error recieved via ```kubectl describe pvc pvc-test -n test```:
```
Events:
  Type     Reason                Age                    From                                                               Message
  ----     ------                ----                   ----                                                               -------
  Normal   Provisioning          22h (x564 over 2d8h)   nfs.csi.k8s.io_talos-goz-704_7a7639b6-f595-400f-b5c9-df114cd120a6  External provisioner is provisioning volume for claim "test/pvc-test"
  Normal   ExternalProvisioning  22h (x8344 over 2d8h)  persistentvolume-controller                                        Waiting for a volume to be created either by the external provisioner 'nfs.csi.k8s.io' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
  Normal   Provisioning          3m55s (x10 over 12m)   nfs.csi.k8s.io_talos-goz-704_169e4f00-a8c8-4f5f-b04f-0e51713846e0  External provisioner is provisioning volume for claim "test/pvc-test"
  Warning  ProvisioningFailed    3m55s (x10 over 12m)   nfs.csi.k8s.io_talos-goz-704_169e4f00-a8c8-4f5f-b04f-0e51713846e0  failed to provision volume with StorageClass "nfs-csi": rpc error: code = Internal desc = failed to make subdirectory: mkdir /tmp/pvc-c5435e50-2b7b-44ca-ae77-249b778b4530/pvc-c5435e50-2b7b-44ca-ae77-249b778b4530: permission denied
  Normal   ExternalProvisioning  110s (x42 over 12m)    persistentvolume-controller                                        Waiting for a volume to be created either by the external provisioner 'nfs.csi.k8s.io' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
```

NFS Server is a TrueNAS scale sytem with permission set to root.
Talos is installed in a VM on proxmox.
