### DISCUSSION TITLE
Cannot disable predictable interface names when using an image from the image factory

### DISCUSSION THREAD

**Discussion by MagellanTX** [siderolabs/talos#9011] [Q&A] [answered]
Hello,

I am using Talos 1.7.5 with predictable interface names disabled, and this is working well until I use an image built from the image factory. Specifically, I am using an image suited for secure-boot, disk-encryption, and the qemu-guest-agent.

Here is the patch I'm using:
```
---
machine:
  install:
    extraKernelArgs:
      - net.ifnames=0
```

Here is a snippet from the controlplane.yaml:
```
# Used to provide instructions for installations.
    install:
        disk: /dev/sda # The disk used for installations.
        # Allows for supplying extra kernel args via the bootloader.
        extraKernelArgs:
            - net.ifnames=0
        image: factory.talos.dev/installer-secureboot/dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586:v1.7.5 # Allows for supplying the image used to perform the installation.
        wipe: false # Indicates if the installation disk should be wiped at installation time.
```

When I generate the configs, I pass the `--install-image` parameter along with the config patches, and I don't get any errors. 
```
talosctl gen config mycluster https://myvip:6443 \
--install-image factory.talos.dev/installer-secureboot/dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586:v1.7.5 \
--with-secrets secrets.yaml \
--config-patch @patches/interface-names.yaml \
...{the rest of the patches}
--config-patch-control-plane @patches/vip.yaml \
--output rendered/
```

The cluster seems to build fine, I can enumerate the members, the dashboard is green, and I can bootstrap Kubernetes. However, when I boot/reboot I can see the interface being renamed back to the predictable name:

>kern:    info: [2024-07-13T00:41:25.801758076Z]: virtio_net virtio2 enxbc2411a0f8a8: renamed from eth0

This is a problem for my VIP because I have it set to bind to eth0. I know I can use bus selections instead, but I'd like to get it working without predictable interface names.

This only happens with the image factory, if I use the standard Talos image, the interface name remains eth0.
