### DISCUSSION TITLE
Building secureboot assets using `imager` with own PK and KEK

### DISCUSSION THREAD

**Discussion by stereobutter** [siderolabs/talos#9035] [Q&A]
I'm currently in the process of figuring out how to build secureboot assets (installer images, secureboot.iso etc.) using `imager`. In the end I'd like to use `imager` with a suitable `profile.yaml` in my CI using my own PKI. Unfortunately [the docs](https://www.talos.dev/v1.7/talos-guides/install/bare-metal-platforms/secureboot/#secureboot-with-custom-keys) are a little sparse here and I find the key generation utilities of `talosctl gen secureboot` and their docs a bit confusing due to terms such as *SecureBoot key*  being used instead of the usual secureboot nomenclature. 

If my understanding of secureboot is correct there are basically two keys involved here:

* A *PK* (*Platform Key*) which is private key and an accompanying self-signed certificate that serves as root certificate. The certificate gets enrolled into the UEFI.
* A *KEK* (*Key Exchange Key*) which is a private key and an accompanying certificate signed by the *PK*. It is used to sign the secureboot databases (*db* of allowed signatures , *dbx* of revoked signatures and hashes) as well as the stuff in the UKI (kernel, initrd etc.). UEFI uses the enrolled *PK* certificate to verify the *KEK* during boot. 

Based on the above and [the code](https://github.com/siderolabs/talos/blob/fd6ddd11ef810f92190fe0d7490f2314ce21d595/pkg/imager/profile/input.go#L90) for configuring build options of `imager` is my interpretation of the fields in the example bellow correct?

```yaml
# profile.yaml
secureboot:
  secureBootSigner:
    # using the file-based option as an example
    keyPath: ...  # path to KEK private key?
    certPath: ... # path to KEK cert?
  # optional auto-enrollment options 
  plattformKeyPath:  ... # path to the PK cert?
  keyExchangeKeyPath: ... # path to the KEK cert?
  signatureKeyPath: ... # what does this do?
```

**Comment by smira** [comment]
PK, KEK and friends are UEFI security database things, built to facilitate SecureBoot key enrollment. They are not used by Talos in any way.

SecureBoot signer is important - it signs the UKI binary. 

Imager can auto-generate default PK, KEK and stuff for you, if you don't pass in paths to the files. If you pass in your files, it will use them and copy to the ISO

**Reply by stereobutter** [reply]
> SecureBoot signer is important - it signs the UKI binary

the question is with which key - I think the correct key for signing the UKI binary is the KEK hence my questions above :)

**Reply by smira** [reply]
There are many ways to set up things, and you might need to refer to the UEFI specification for details.

Talos default way is the following:

* we generate two-long term keys - one is what we call "SecureBoot" key and that gets enrolled into the UEFI firmware as "trusted"; it is used to sign the UKI, kernel, etc.
* the second key is used to sign the UKI PCR exepected values, and eventually to unlock the encryption key in the TPM; it can be same as the first key, but once again we keep them separate

PK, KEK, etc. are containers to enroll the first key into the UEFI firmware, they also do some intermediate signing procedures not relevant for Talos operations, but required by the UEFI firmware.

**Comment by stereobutter** [comment]
Looking at (part of) the`profile.yaml` that is emitted by `imager` ([following the docs](https://www.talos.dev/v1.7/talos-guides/install/bare-metal-platforms/secureboot/#secureboot-with-custom-keys)) clears up a lot of the questions I had. 

```yaml
secureboot:
  secureBootSigner:
    keyPath: /secureboot/uki-signing-key.pem
    certPath: /secureboot/uki-signing-cert.pem
  pcrSigner:
    keyPath: /secureboot/pcr-signing-key.pem
  platformKeyPath: /secureboot/PK.auth
  keyExchangeKeyPath: /secureboot/KEK.auth
  signatureKeyPath: /secureboot/db.auth
```

* `keyPath` and `certPath` indeed are just paths to a suitable pair of `.pem` files representing a signing key and certificate.
* `platformKeyPath` is a path to a `.auth` file (i.e. a signed UEFI signature list) for the *PK*
* `keyExchangeKeyPath` is a path to a `.auth` file containing the *KEK*
* `signatureKeyPath` is a path to a `.auth` file containing the *db*
