### DISCUSSION TITLE
Is there a way to open ports for incoming BGP requests? (port 179)

### DISCUSSION THREAD

**Discussion by YaroCabbage** [siderolabs/talos#9114] [Q&A] [answered]
Hi everyone,

I'm configuring cluster to allow incoming connections on port 179 for BGP (Border Gateway Protocol) using Cilium as the CNI.
I've tried already to open ports using Talos and Cilium, but still ports seems to be closed. 

Talos configuration:
```yaml
---
apiVersion: v1alpha1
kind: NetworkDefaultActionConfig
ingress: accept
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: bgp-ingress
portSelector:
  ports:
    - 179
  protocol: tcp
ingress:
  - subnet: 0.0.0.0/0

``` 

Cilium configuration:
```yaml
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      rack: rack0
  bgpInstances:
    - name: "instance-a"
      localASN: a
      peers:
        - name: "peer-a"
          peerASN: 64515
          peerAddress: 169.254.169.254
          peerConfigRef:
            name: "cilium-peer"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  authSecretRef: vultr-bgp-auth-secret
  gracefulRestart:
    enabled: true
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPNodeConfigOverride
metadata:
  name: vultr-worker1
spec:
  bgpInstances:
    - name: "instance-a"
      routerID: "199.247.31.65"
      localPort: 179
      peers:
        - name: "peer-a"
          localAddress: 169.254.169.254

``` 

Any advice or steps to resolve this issue would be greatly appreciated!

Thanks in advance.
