### DISCUSSION TITLE
Random loading when using lvm mirror and lvm thin pool

### DISCUSSION THREAD

**Discussion by eshikhov** [siderolabs/talos#9140] [Q&A]
Hi,

When using the lvm mirror and lvm thin pool functionality, the OS is loaded randomly. 

When setting up for the first time, everything is fine, the kernel modules (dm_raid and dm_thin_pool) are loaded with the config. Then the lvm mirror and lvm thin pool volumes are created and everything works well until the server is rebooted (and the reboot can be caused by various reasons, be it talosctl upgrade with the --reboot-mode powercycle option or just talosctl reboot --mode powercycle). After a restart, talos does not start, but constantly goes into cyclic restarts and at some time of restart it can boot successfully.

Screenshots of unsuccessful launches that I managed to take:

![screenshot_1](https://github.com/user-attachments/assets/d3e049d1-f81e-40ad-9a34-54138d76f6d4)

![screenshot_2](https://github.com/user-attachments/assets/24fb60eb-63b2-429d-8882-b6a6e929f80a)

![screenshot_3](https://github.com/user-attachments/assets/4fa99fec-5ed5-4e73-aa0d-495b0c9a89f0)

![screenshot_4](https://github.com/user-attachments/assets/72adf05c-49ff-4473-8c70-ae86289d5698)

![screenshot_5](https://github.com/user-attachments/assets/64c96f52-72cd-41b7-9b16-8a46ee64678a)

Dump debug information about the cluster:

[support.zip](https://github.com/user-attachments/files/16562249/support.zip)

Talos v1.7.6

**Comment by smira** [comment]
There is nothing in the screenshots which would indicate exactly the problem you're facing.

It's way easier to use serial console logs for debugging, or capture at least the message before the reboot.

**Reply by eshikhov** [reply]
Maybe this will be better visible, starting from the line [21.363289]

![screenshot_1723193338655](https://github.com/user-attachments/assets/c155c281-a720-415d-9aa9-872f5c0bfa92)

**Reply by smira** [reply]
I don't know what is going on here, and what you're doing, but it seems to do modprobe and do it wrong way. 

I don't know why it even does that, you need to load the modules in the machine configuration.

**Reply by eshikhov** [reply]
modules are registered in the machine configuration

```
kernel:
  modules:
    - name: dm_raid
    - name: dm_thin_pool
    - name: drbd
      parameters:
        - usermode_helper=disabled
    - name: drbd_transport_tcp
```

My machine configuration

[worker-01.txt](https://github.com/user-attachments/files/16565478/worker-01.txt)

This behavior is different hardware servers and on virtual machines

**Reply by eshikhov** [reply]
![Снимок экрана 2024-08-12 в 18 23 40](https://github.com/user-attachments/assets/7b4c9486-38f9-4bd5-a7db-16e20bf616d7)

Always crashes at the same LVM phase step 14 and it doesn’t matter if I use only lvm mirror or lvm thin pool or their combination

We do not call any additional scripts or the modprobe command separately.
According to the code, the command is executed at this step
```
lvm vgchange -ay 
```

**Comment by eshikhov** [comment]
The problem can be easily reproduced even on a virtual machine.
1) Prepare a VM with two additional disks
2) Expand talos with
```
kernel:
    modules:
      - name: dm_raid
```
3) Create a VG
```
vgcreate vg0 /dev/sdb /dev/sdc
```  
4) Create a logical volume with the mirror type
```
lvcreate -L 1G -m1 -n mirrorlv vg0
```
5) Restart the VM (hardware reset or talosctl reboot --mode powercycle)

The bug is floating, so after the first reboot it can load successfully. Therefore, you need to repeat the cycle with a reboot.

**Comment by mst1711** [comment]
Same problem
Talos 1.7.4
VM on Proxmox
Machine config:
```yaml
   kernel:
        modules:
            - name: dm_raid
            - name: dm_thin_pool
            - name: drbd
              parameters:
                - usermode_helper=disabled
            - name: drbd_transport_tcp
            - name: zfs
```
Modules appended using `talosctl edit mc` and applied without reboot
But when I tried to upgrade to Talos 1.7.6, I got the trouble with boot
Cycling reboot
![image](https://github.com/user-attachments/assets/81ba36f4-0d3e-42db-8937-4fcdc4fac92c)
Talos node loaded after 20-30 reboots
