### DISCUSSION TITLE
controller runtime dhcp renew constantly failing

### DISCUSSION THREAD

**Discussion by v1nsai** [siderolabs/talos#9142] [Q&A]
I'm investigating intermittent connectivity issues between containers and the apiserver on my Talos 1.7.6 cluster.  I notice that the logs on every node of my cluster are full of warnings for an issue with renewing dhcp:
```
192.168.1.155: 2024-08-09T17:02:00.218Z [33mWARN[0m request/renew failed {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "error": "unable to receive an offer: got an error while the discovery request: no matching response packet received", "link": "enp10s0"}
```
Could this be the culprit?  What can I do about it?  No other devices on my network are having any issues, DHCP or otherwise.

**Comment by v1nsai** [comment]
I went ahead and downgraded my cluster (holy crap it was so easy 3 nodes took 15 minutes!) and this issue has gone away, but it looks like my apiserver issues are being caused by something else.

**Reply by smira** [reply]
I don't think you need to downgrade. These logs just mean failed attempts to run DHCP. 

Talos tries to run DHCP on all interfaces which are not configured explicitly if they have the cable plugged in. So it might be that this interface doesn't have DHCP on it, it's harmless.

**Reply by Simon-CR** [reply]
having a way to hide those from the console would be useful ...

**Comment by cliveza** [comment]
I had a similar error when I added a virtual IP to the nodes on my cluster, which is a static IP address, what squashed the error was setting dhcp to false.

```
machine:
  network:
    interfaces:
      - deviceSelector:
          physical: true  
        dhcp: false
        vip:
          ip: 10.0.11.15
        vlans:
          - vlanId: 11
            dhcp: false
            vip:
              ip: 10.0.11.15
```
