### DISCUSSION TITLE
Talos install not persisting after initial boot / config from ISO

### DISCUSSION THREAD

**Discussion by MonMothma1ABY** [siderolabs/talos#9256] [Q&A] [answered]
Hi - ive got a fun issue where, i can boot to the ISO, apply a config, bootstrap and see all running nodes however when I reboot and remove the USB stick the node fails with errors about etcd.

![image](https://github.com/user-attachments/assets/b22f12c4-4a57-4c65-a395-6dfd0128fb02)
![image](https://github.com/user-attachments/assets/3a679df4-8a67-4d16-b43f-12815da07726)

Error message after removing boot medium.

![image](https://github.com/user-attachments/assets/e13a6003-d8af-456b-8d25-cf9d3319bb16)

I can't reboot into the Talos OS, as it just reverts back to my initial Ubuntu OS.

Static IP / network config is applied correctly as well so the config is getting loaded nicely. Maybe just ignoring some of the install parameters? I've disabled Both Legacy Support and SecureBoot in BIOS. I just can't get it to persist.

This is the output from the disk selector, they seem to tie.
```
NODE            DEV            MODEL                SERIAL            TYPE   UUID   WWID                                                                                     MODALIAS      NAME   SIZE     BUS_PATH                                                               SUBSYSTEM          READ_ONLY   SYSTEM_DISK
192.168.68.71   /dev/nvme0n1   HP SSD EX900 500GB   HASE32421402668   NVME   -      nvme.126f-484153453332343231343032363638-485020535344204558393030203530304742-00000001   -             -      500 GB   /pci0000:00/0000:00:1d.0/0000:01:00.0/nvme/nvme0/nvme0n1               /sys/class/block               
192.168.68.71   /dev/sda       Flash Drive          -                 HDD    -      -                                                                                        scsi:t-0x00   -      128 GB   /pci0000:00/0000:00:14.0/usb2/2-3/2-3:1.0/host0/target0:0:0/0:0:0:0/   /sys/class/block               *
```

Relevant config below - have tried to include the metal platform args, being verbose about installing a bootloader and then as a hail maray put legacyBIOS support to true which did not help. 
```
    install:
        disk: /dev/nvme0n1
        image: ghcr.io/siderolabs/installer:v1.7.6
        wipe: true
        extraKernelArgs:
            - talos.platform=metal
        bootloader: true
```

I've seen https://github.com/siderolabs/talos/discussions/8806, and https://github.com/siderolabs/talos/discussions/9060 but I may not be understanding the issues here.

**Comment by rothgar** [comment]
Try booting the machine from usb and before you apply the config remove the USB drive. This will eliminate the `/dev/sda` device being available at all to make sure the install happens on the nvme disk.

**Comment by MonMothma1ABY** [comment]
The machine instantly reboots landing me on my secondary boot option. Had tried that a few times before my initial post however, putting the logs here may put me down a path. Ended up being able to grab a snap (below) of the error... typed it out for brevity.

[sda] Synchronize Cache(10) failed: Result: hostbyte=DID_NO_CONNECT driverbyte=DRIVER_OK

![image](https://github.com/user-attachments/assets/6c8909df-cf4c-4f4d-ae82-f0ba835b1b42)

It does however remove the drive from the talosctl drives list... curiously on push of the config it goes straight to the sda drive. Do I need to create partitions in the nvme? I had thought the OS was loaded into memory removing dependencies on any physical medium.

Additionally used the device selector on and off to no avail. I've been investigating PXE boot, which has given me a bit of a headache however something I need to figure out eventually but... more of a me problem.  Would really like to be able to get this cluster up and running with the .iso and play with the cluster before I jump head first into the lovely word of IaC - (Digital Rebar, Matchbox, Terraform, Ansible)

**Reply by MonMothma1ABY** [reply]
Some additional info - in case it is helpful.

Using metal-amd64 from https://factory.talos.dev/image/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba/v1.7.6/metal-amd64.iso

Install steps below as follows:

  - Download metal-amd64 and burn to USB with BalenaEtcher
  - Generate config files using expected configured static IP
`talosctl gen config astromec https://192.168.68.71:6443 --with-docs=false --with-examples=false`
  - Update contralplane .yaml for static IP usage
```
    network:
        hostname: jabba_control_plane
        nameservers:
          - 192.168.68.1
        interfaces:
          - interface: eno1
            addresses:
              - 192.168.68.71
            routes:
              - network: 0.0.0.0/0
                gateway: 192.168.68.1
```
  - Update timeserver in config
```
   time:
        servers:
          - time.cloudflare.com
```
- set install path (drive) and configure diskSelector, also update image from imagefactory
```
install:
        disk: /dev/nvme0n1
        diskSelector:
            size: '>= 250GB' # Disk size.
        image: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.7.6
        extraKernelArgs:
            - talos.platform=metal
```
- Add config for control plane scheduling
`allowSchedulingOnControlPlanes: true`
- configure talosconfig for static IP
`export TALOSCONFIG=./talosconfig && talosconfig endpoint 192.168.68.71 && talosctl node 192.168.68.71`
- apply controlplane.yaml to DHCP provisioned IP - if keeping with the USB in the machine, all is well and can bootstrap and see nodes with kubectl. Beginning of issues from initial post
`talosctl apply-config -f controlplane.yaml -n 192.168.68.62 --insecure`
