### DISCUSSION TITLE
Running DPDK APP

### DISCUSSION THREAD

**Discussion by infinitydon** [siderolabs/talos#9289] [Q&A]
Hi,

I am currently trying to test running dpdk apps on talos, I have the following worker machine config:

```
    kernel:
     modules:
     - name: vfio_pci

    install:
        # # Allows for supplying extra kernel args via the bootloader.
        extraKernelArgs:
        - "vfio-pci.enable_unsafe_noiommu_mode=1"
        - "hugepagesz=1G"
        - "hugepages=4"

    udev:
     rules:
     - SUBSYSTEM=="pci", KERNELS=="0000:00:13.0", DRIVER=="", ATTR{driver_override}="vfio-pci"
     - SUBSYSTEM=="pci", KERNELS=="0000:00:14.0", DRIVER=="", ATTR{driver_override}="vfio-pci"
```

I am able to see the hugepages when I desribe the workernode but I am still seeing the 2 ethernet NICs 0000:00:13.0 and 0000:00:14.0 when I run _**talosctl get links**_, usually when an interface is assigned to vfio-pci driver it will no longer visible at the kernel level

I need help to confirm if the above config is correct or suggestions on how to get it working.

Thanks
