### DISCUSSION TITLE
Unable to expose nginx to the internet after creating Talos cluster on Hetzner Cloud

### DISCUSSION THREAD

**Discussion by aochagavia** [siderolabs/talos#9344] [Q&A] [answered]
I'm new to Talos and just set up a cluster on Hetzner Cloud, following the website's [documentation](https://www.talos.dev/v1.7/talos-guides/install/cloud-platforms/hetzner/). I deployed the official nginx container to the cluster, to test connectivity from the internet, but it doesn't look like the HTTP endpoint is reachable.

Reading around the discussions forum, I got the impression that this is related to kubernetes not knowing that my nodes have an external ip address. For instance, here's the output of `kubectl get nodes -owide` (I redacted the values for INTERNAL-IP, because those actually correspond to the node's external ip address):

```
NAME              STATUS   ROLES           AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE         KERNEL-VERSION   CONTAINER-RUNTIME
talos-cp-reborn   Ready    control-plane   86m   v1.30.3   123.456.789.0   <none>        Talos (v1.7.6)   6.6.43-talos     containerd://1.7.18
talos-w-1         Ready    <none>          85m   v1.30.3   123.456.789.1   <none>        Talos (v1.7.6)   6.6.43-talos     containerd://1.7.18
```

Have you seen something like this before? I'm wondering how I can fix it, but don't know where to get started.

### More context for debugging

I deployed nginx using the following yaml:

```yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nginx:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
```

I'm able to access the deployed nginx through port-forwarding:

```
$ kubectl port-forward deployment/hello-world 8001:80
$ curl 127.0.0.1:8001
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
...
```

Exposing it to the internet doesn't get us an external IP (not a surprise, given the nodes themselves don't have an external ip):

```
$ kubectl expose deployment hello-world --type=NodePort --name=example-service
$ kubectl get services
NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
hello-world-service   NodePort    10.107.54.227   <none>        80:30547/TCP   13s
kubernetes            ClusterIP   10.96.0.1       <none>        443/TCP        85m
```
