### DISCUSSION TITLE
AMD GPU mount /dev/dri in workload container

### DISCUSSION THREAD

**Discussion by bernardgut** [siderolabs/talos#9366] [Q&A] [answered]
## Bug Report
This is actually a continuation of this : https://github.com/siderolabs/talos/issues/4001 but since that thread is locked I am starting a new one.

I have a bunch of workloads similar to plex on bare metal nodes with AMD GPUs. I see a lot of documentation on how to use NVIDIA but nothing on AMD. In my case I was only trying to mount `/dev/dri` into workloads containers as I assume it is enough.

How do you do that ? I mounted `/dev/dri` using a `hostPath` mount on the container but the scheduler ignored it (which is good). I am assuming the new `securityContext` rules mean it is not possible with the latest versions of k8s. How do I mount /dev/dri in a container in Talos 1.7.6/1.8.0 on kubernetes 1.31.1 without giving privileges to the container ? 

I also tried 
```
machine:
  kubelet:
    extraMounts:
    - destination: /dev/dri
      type: bind
      source: /dev/dri
      options:
        - bind
        - rshared
        - rw
  udev:
    rules:
    - SUBSYSTEM=="drm", KERNEL=="card*", GROUP="44", MODE="0660"
    - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"
```
but it didnt change anything so I am probably missing something ?

Thanks
b.
