### DISCUSSION TITLE
Successful upgrade to 1.8.0 but machineconfig is unaltered?

### DISCUSSION THREAD

**Discussion by Hr46ph** [siderolabs/talos#9439] [Q&A] [answered]
Specifically, this part:

```
        install:
            disk: /dev/nvme0n1
            extraKernelArgs:
                - talos.platform=metal
                - net.ifnames=0
                - talos.shutdown=poweroff
                - reboot=k
            image: factory.talos.dev/installer/1cb9c657e574b399f410f7a3e2d6a77cd8766d906d82df35f66e8d21617cd65a:v1.7.6
```
Shouldnt that have updated?
