### DISCUSSION TITLE
Bond interface fails during syncLink

### DISCUSSION THREAD

**Discussion by Tenebresus** [siderolabs/talos#9444] [Q&A]
I'm currently trying to setup openvswitch, where I want to connect a bond interface to a bridge. But in the kernel logs I see the following error:

```[talos] controller failed {"component": "controller-runtime", "controller": "network.LinkSpecController", "error": "1 error occurred:\n\t* error enslaving/unslaving link \"bond1\" under \"\": netlink receive: operation not supported\n\n"}```

In the code I found the following function that is responsible for throwing this error:
https://github.com/siderolabs/talos/blob/6a014374be26f0caf8faa90a34f2476e0e77a46a/internal/app/machined/pkg/controllers/network/link_spec.go#L200
Does anyone have any experience with attaching a bond interface to an openvswitch bridge? And can someone explain to me why Talos wants to enslave the bond interface under an empty master?
This is my network config for the bond interface:

```
        - interface: bond1
          dhcp: false
          bond:
            mode: 802.3ad
            lacpRate: fast
            xmitHashPolicy: layer3+4
            miimon: 100
            updelay: 200
            downdelay: 200
            interfaces:
              - enp94s0f1
              - enp94s0f0
          mtu: 9000
```

**Comment by smira** [comment]
Please run `talosctl get linkspecs -o yaml` and post it here.

**Reply by Tenebresus** [reply]
```
node: 172.19.120.4
metadata:
    namespace: network
    type: LinkSpecs.net.talos.dev
    id: bond0
    version: 2
    owner: network.LinkMergeController
    phase: running
    created: 2024-10-04T09:33:39Z
    updated: 2024-10-04T09:33:39Z
    finalizers:
        - network.LinkSpecController
spec:
    name: bond0
    logical: true
    up: true
    mtu: 0
    kind: bond
    type: ether
    bondMaster:
        mode: 802.3ad
        xmitHashPolicy: layer3+4
        lacpRate: fast
        arpValidate: none
        arpAllTargets: any
        primaryReselect: always
        failOverMac: 0
        miimon: 100
        updelay: 200
        downdelay: 200
        resendIgmp: 1
        lpInterval: 1
        packetsPerSlave: 1
        numPeerNotif: 1
        tlbLogicalLb: 1
        useCarrier: true
        adActorSysPrio: 65535
    layer: configuration
---
node: 172.19.120.4
metadata:
    namespace: network
    type: LinkSpecs.net.talos.dev
    id: bond0.350
    version: 2
    owner: network.LinkMergeController
    phase: running
    created: 2024-10-04T09:33:39Z
    updated: 2024-10-04T09:33:39Z
    finalizers:
        - network.LinkSpecController
spec:
    name: bond0.350
    logical: true
    up: true
    mtu: 0
    kind: vlan
    type: ether
    parentName: bond0
    vlan:
        vlanID: 350
        vlanProtocol: 802.1q
    layer: configuration
---
node: 172.19.120.4
metadata:
    namespace: network
    type: LinkSpecs.net.talos.dev
    id: bond0.362
    version: 2
    owner: network.LinkMergeController
    phase: running
    created: 2024-10-04T09:33:39Z
    updated: 2024-10-04T09:33:39Z
    finalizers:
        - network.LinkSpecController
spec:
    name: bond0.362
    logical: true
    up: true
    mtu: 0
    kind: vlan
    type: ether
    parentName: bond0
    vlan:
        vlanID: 362
        vlanProtocol: 802.1q
    layer: configuration
---
node: 172.19.120.4
metadata:
    namespace: network
    type: LinkSpecs.net.talos.dev
    id: bond0.370
    version: 2
    owner: network.LinkMergeController
    phase: running
    created: 2024-10-04T09:33:39Z
    updated: 2024-10-04T09:33:39Z
    finalizers:
        - network.LinkSpecController
spec:
    name: bond0.370
    logical: true
    up: true
    mtu: 0
    kind: vlan
    type: ether
    parentName: bond0
    vlan:
        vlanID: 370
        vlanProtocol: 802.1q
    layer: configuration
---
node: 172.19.120.4
metadata:
    namespace: network
    type: LinkSpecs.net.talos.dev
    id: bond1
    version: 2
    owner: network.LinkMergeController
    phase: running
    created: 2024-10-04T09:33:39Z
    updated: 2024-10-04T09:33:39Z
    finalizers:
        - network.LinkSpecController
spec:
    name: bond1
    logical: true
    up: true
    mtu: 9000
    kind: bond
    type: ether
    bondMaster:
        mode: 802.3ad
        xmitHashPolicy: layer3+4
        lacpRate: fast
        arpValidate: none
        arpAllTargets: any
        primaryReselect: always
        failOverMac: 0
        miimon: 100
        updelay: 200
        downdelay: 200
        resendIgmp: 1
        lpInterval: 1
        packetsPerSlave: 1
        numPeerNotif: 1
        tlbLogicalLb: 1
        useCarrier: true
        adActorSysPrio: 65535
    layer: configuration
---
node: 172.19.120.4
metadata:
    namespace: network
    type: LinkSpecs.net.talos.dev
    id: eno1
    version: 2
    owner: network.LinkMergeController
    phase: running
    created: 2024-10-04T09:33:33Z
    updated: 2024-10-04T09:33:33Z
    finalizers:
        - network.LinkSpecController
spec:
    name: eno1
    logical: false
    up: true
    mtu: 0
    kind: ""
    type: netrom
    layer: default
---
node: 172.19.120.4
metadata:
    namespace: network
    type: LinkSpecs.net.talos.dev
    id: eno2
    version: 2
    owner: network.LinkMergeController
    phase: running
    created: 2024-10-04T09:33:33Z
    updated: 2024-10-04T09:33:34Z
    finalizers:
        - network.LinkSpecController
spec:
    name: eno2
    logical: false
    up: true
    mtu: 0
    kind: ""
    type: netrom
    layer: default
---
node: 172.19.120.4
metadata:
    namespace: network
    type: LinkSpecs.net.talos.dev
    id: eno3
    version: 2
    owner: network.LinkMergeController
    phase: running
    created: 2024-10-04T09:33:33Z
    updated: 2024-10-04T09:33:33Z
    finalizers:
        - network.LinkSpecController
spec:
    name: eno3
    logical: false
    up: true
    mtu: 0
    kind: ""
    type: netrom
    layer: default
---
node: 172.19.120.4
metadata:
    namespace: network
    type: LinkSpecs.net.talos.dev
    id: enp59s0f0
    version: 2
    owner: network.LinkMergeController
    phase: running
    created: 2024-10-04T09:33:33Z
    updated: 2024-10-04T09:33:33Z
    finalizers:
        - network.LinkSpecController
spec:
    name: enp59s0f0
    logical: false
    up: true
    mtu: 0
    kind: ""
    type: netrom
    layer: default
---
node: 172.19.120.4
metadata:
    namespace: network
    type: LinkSpecs.net.talos.dev
    id: enp59s0f1
    version: 2
    owner: network.LinkMergeController
    phase: running
    created: 2024-10-04T09:33:33Z
    updated: 2024-10-04T09:33:33Z
    finalizers:
        - network.LinkSpecController
spec:
    name: enp59s0f1
    logical: false
    up: true
    mtu: 0
    kind: ""
    type: netrom
    layer: default
---
node: 172.19.120.4
metadata:
    namespace: network
    type: LinkSpecs.net.talos.dev
    id: enp59s0f2
    version: 2
    owner: network.LinkMergeController
    phase: running
    created: 2024-10-04T09:33:33Z
    updated: 2024-10-04T09:33:33Z
    finalizers:
        - network.LinkSpecController
spec:
    name: enp59s0f2
    logical: false
    up: true
    mtu: 0
    kind: ""
    type: netrom
    layer: default
---
node: 172.19.120.4
metadata:
    namespace: network
    type: LinkSpecs.net.talos.dev
    id: enp59s0f3
    version: 2
    owner: network.LinkMergeController
    phase: running
    created: 2024-10-04T09:33:33Z
    updated: 2024-10-04T09:33:34Z
    finalizers:
        - network.LinkSpecController
spec:
    name: enp59s0f3
    logical: false
    up: true
    mtu: 0
    kind: ""
    type: netrom
    layer: default
---
node: 172.19.120.4
metadata:
    namespace: network
    type: LinkSpecs.net.talos.dev
    id: enp94s0f0
    version: 3
    owner: network.LinkMergeController
    phase: running
    created: 2024-10-04T09:33:33Z
    updated: 2024-10-04T09:33:39Z
    finalizers:
        - network.LinkSpecController
spec:
    name: enp94s0f0
    logical: false
    up: true
    mtu: 0
    kind: ""
    type: netrom
    masterName: bond1
    slaveIndex: 1
    layer: configuration
---
node: 172.19.120.4
metadata:
    namespace: network
    type: LinkSpecs.net.talos.dev
    id: enp94s0f1
    version: 3
    owner: network.LinkMergeController
    phase: running
    created: 2024-10-04T09:33:33Z
    updated: 2024-10-04T09:33:39Z
    finalizers:
        - network.LinkSpecController
spec:
    name: enp94s0f1
    logical: false
    up: true
    mtu: 0
    kind: ""
    type: netrom
    masterName: bond1
    layer: configuration
---
node: 172.19.120.4
metadata:
    namespace: network
    type: LinkSpecs.net.talos.dev
    id: enp94s0f2
    version: 3
    owner: network.LinkMergeController
    phase: running
    created: 2024-10-04T09:33:34Z
    updated: 2024-10-04T09:33:39Z
    finalizers:
        - network.LinkSpecController
spec:
    name: enp94s0f2
    logical: false
    up: true
    mtu: 0
    kind: ""
    type: netrom
    masterName: bond0
    slaveIndex: 1
    layer: configuration
---
node: 172.19.120.4
metadata:
    namespace: network
    type: LinkSpecs.net.talos.dev
    id: enp94s0f3
    version: 3
    owner: network.LinkMergeController
    phase: running
    created: 2024-10-04T09:33:34Z
    updated: 2024-10-04T09:33:39Z
    finalizers:
        - network.LinkSpecController
spec:
    name: enp94s0f3
    logical: false
    up: true
    mtu: 0
    kind: ""
    type: netrom
    masterName: bond0
    layer: configuration
---
node: 172.19.120.4
metadata:
    namespace: network
    type: LinkSpecs.net.talos.dev
    id: lo
    version: 2
    owner: network.LinkMergeController
    phase: running
    created: 2024-10-04T09:32:49Z
    updated: 2024-10-04T09:33:33Z
    finalizers:
        - network.LinkSpecController
spec:
    name: lo
    logical: false
    up: true
    mtu: 0
    kind: ""
    type: netrom
    layer: default
    ```
