### DISCUSSION TITLE
Clarification on how to set up a static IP for the control plane

### DISCUSSION THREAD

**Discussion by kavishgr** [siderolabs/talos#9446] [General]
Hey there!

First time trying Talos. For now the cluster only contains a control plane. I'm trying to set a static IP. Here's the patch that I came up with:

```yaml
machine:
  network:
    hostname: controlplane-01
    interfaces:
          - interface: enp0s1
            addresses:
              - 192.168.100.211/24
            routes:
              - network: 0.0.0.0/0
                gateway: 192.168.100.1
                metric: 1024
            mtu: 1500
    nameservers:
        - 192.168.100.1
cluster:
  controlPlane:
      endpoint: https://192.168.100.211:6443
  apiServer:
      certSANs:
          - 192.168.100.211
  allowSchedulingOnControlPlanes: true
```

The patch was generated with the following command:

```console
❯ talosctl gen config test-conplane https://192.168.100.211:6443 --config-patch-control-plane @controlplane-patch.yaml --with-examples=false
generating PKI and tokens
Created /Users/kavish/Desktop/talos-test/controlplane.yaml
Created /Users/kavish/Desktop/talos-test/worker.yaml
Created /Users/kavish/Desktop/talos-test/talosconfig 
```

Applied like so:

```console
talosctl apply-config -n 192.168.100.170 --file controlplane.yaml --insecure
```

I noticed that the hostname was set up correctly but not the IP. Here's a screenshot of the console being stuck in the booting stage:

<img width="902" alt="Screenshot 2024-10-08 at 08 22 58" src="https://github.com/user-attachments/assets/ec6983ab-51e7-4fe0-bf4f-eeb70f6fda8e">

I was like maybe the patch only needs the machine network. I did try with the following and same issue as above:

```yaml
machine:
  network:
    hostname: controlplane-01
    interfaces:
          - interface: enp0s1
            addresses:
              - 192.168.100.211/24
            routes:
              - network: 0.0.0.0/0
                gateway: 192.168.100.1
                metric: 1024
            mtu: 1500
    nameservers:
        - 192.168.100.1
cluster:
  controlPlane:
  allowSchedulingOnControlPlanes: true
```

But if I set the static IP on the console by pressing F3, everything is set up correctly. I'm not sure what I'm doing wrong here. I wanted to achieve the same thing without touching the console. The docs has nothing on how to set up a static IP(only examples about patches I guess).  

I'm 100% sure I'm doing something wrong. So any tips are highly appreciated. Thanks.

**Comment by smira** [comment]
I'm not quite sure what's wrong, we need full kernel logs and/or `talosctl support` bundle which requires network access.

But the first thing is that you don't have `dhcp: false` for the link, so you do both DHCP and static network config at the same time, and this certainly wouldn't work for /24.

**Reply by kavishgr** [reply]
I tried with `dhcp: false`:

```yaml
machine:
  network:
    hostname: controlplane-01
    interfaces:
          - interface: enp0s1
            dhcp: false
            addresses:
              - 192.168.100.211/24
            routes:
              - network: 0.0.0.0/0
                gateway: 192.168.100.1
                metric: 1024
            mtu: 1500
    nameservers:
        - 192.168.100.1
cluster:
  allowSchedulingOnControlPlanes: true
```

Getting the same errors as in the screenshot above.

**Reply by smira** [reply]
I can't really guess what's wrong from this, please see above: `talosctl support` bundle if you do have network access to the machine.

If you don't, then we might need serial console logs, or you need to scroll the logs up in the dashboard (or switch to just logs via Alt+F1) and find the moment network is getting set up, that might sched some light.

But I would also take a step back, and try without any network config - if the DHCP config works, capture how it works and then re-apply it as a static config.

This might be helpful for debugging: https://www.talos.dev/v1.8/learn-more/networking-resources/

**Reply by kavishgr** [reply]
Cool. But before I dive into this, here's what I did in more details:

Talos booted up and received an IP of : `192.168.100.170`.

I want to assign a static IP, for example, `192.168.100.211`.

I generated the configuration with a patch (setting the endpoint to the static IP) like this:

```console
talosctl gen config test https://192.168.100.211:6443 --config-patch-control-plane @controlplane-patch.yaml
```

The patch:

```yaml
machine:
  network:
    hostname: controlplane-01
    interfaces:
      - interface: enp0s1
        dhcp: false
        addresses:
          - 192.168.100.211/24
        routes:
          - network: 0.0.0.0/0
            metric: 1024
            mtu: 1500
            gateway: "192.168.100.1"

    nameservers:
      - 192.168.100.1
cluster:
    allowSchedulingOnControlPlanes: true
```

I applied the configuration using the received IP on the console (since the static one wasn’t set up yet):

```console
talosctl apply-config --insecure  -n 192.168.100.170 --file controlplane.yaml
```

After applying the config, Talos rebooted with a bunch of errors, as shown in the screenshot.

Did I make a mistake during these steps, or am I misunderstanding the concepts of endpoints and nodes?

**Reply by smira** [reply]
Your config patch looks good to me, but there are too many unknowns here, e.g. how many network interfaces you have, etc.

The best way is to explore what you have over DHCP, as it looks like your new network config is broken.

When still in maintenance mode, you can do:

```
talosctl get addresses -n 192.168.100.170 --insecure -o yaml
```

And same with `routes`, `links`.

**Reply by Ferkeltod** [reply]
I did have a probably identical issue, which drove me crazy for the past few days.
The interface names of my machine are `enp0s1` and  `enp0s2` when using predictable interface names, which I did.
The machines initially were booted over PXE->iPXE->UKI-Image EFI, link interface names were like stated above,
the image contained appropriate firmware extensions for Realtek r8169.

`talosctl get links` has shown exactly the same interface names at all times during stages _maintenance_ and _booting_.

When specifying `interface: enp0s1` with `dhcp: false` and static addresses and default gateway, this was simply silently ignored after apply-config and the dhcp server was still being asked, as per its logs and what I could take from `talosctl dmesg` :
`[talos] starting operator {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4/enp1s0"}`

I changed the approach from using interface names to 
```
- deviceSelector:
    busPath: "0000:01:00.0"
```

and it instantly worked as expected. 
I can reproduce the error anytime, but apparently the deviceSelector approach seems to be more reliable than using interface names.

**Comment by astrojerms** [comment]
I had a similar issue with configuring the static IP addresses for my talos cluster as well. After much troubleshooting, I realized that the interface name generated by talos was not the one I had expected (and configured) in in my VM host. I had to configure the deviceSelector option and specify the mac address for the interface, like so:

```
    network:
      hostname: talos-master-00
      interfaces:
        - interface: net0 # The interface name.
          addresses:
            - 172.16.1.111/16
          routes:
            - network: 0.0.0.0/0 # The route's network.
              gateway: 172.16.1.1 # The route's gateway
          dhcp: false
          deviceSelector:
            hardwareAddr: 'aa:bb:cc:ee:11:22'
```

**Reply by kavishgr** [reply]
Nice find. I will give it a try later and get back.

**Reply by kavishgr** [reply]
I'm getting the following error:

```console
error applying new configuration: rpc error: code = InvalidArgument desc = configuration validation failed: 1 error occurred:
	* [networking.os.device.interface], [networking.os.device.deviceSelector]: config sections are mutually exclusive
```

Here's my config:

```yaml
machine:
  network:
    hostname: talos-controlplane-01
    interfaces:
      - interface: enp0s1
        dhcp: false
        deviceSelector:
          hardwareAddr: '00:1c:42:ea:4c:1e'
        addresses:
          - 192.168.100.211/24
        routes:
          - network: 0.0.0.0/0
            metric: 1024
            mtu: 1500
            gateway: "192.168.100.1"

    nameservers:
      - 192.168.100.1
cluster:
    allowSchedulingOnControlPlanes: true
```
