### DISCUSSION TITLE
Why are Kubelet extra mounts for Longhorn needed?

### DISCUSSION THREAD

**Discussion by M4t7e** [siderolabs/talos#9674] [Q&A] [answered]
I'm currently working on integrating Longhorn to a Terraform based Talos deployment and I'm just wondering why this extra mounts for Kubelet are needed according to the [Longhorn Talos documentation](https://longhorn.io/docs/1.7.3/advanced-resources/os-distro-specific/talos-linux-support/#data-path-mounts): 
```yml
machine:
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
```

They say:
> These mounts are necessary to provide access to the host directories, and attach volumes required by Longhorn components.

I'm trying to understand the background behind this requirement. Why does Kubelet need access to these paths when Longhorn already has access to the host path?
