### DISCUSSION TITLE
Adding Disks

### DISCUSSION THREAD

**Discussion by stelb** [siderolabs/talos#9748] [Q&A] [answered]
Hi,

I would like to add a disk for longhorn, it seemed to be simply adding a few lines to machineconfig:

```
machine:
  disks:
    - device: /dev/sdb
      partitions:
        - mountpoint: /var/mnt/storage
```

But this fails, talos does not boot successfully and I can see lines like this:

```
[talos] volume status {"component": "controller-runtime", "controller": "block.volumeManagerController","volume": "/dev/sdb-1", "phase": "failed -> failed", "error": "no disks matched for volume"}
```
what am I missing?

- talos 1.8.3 with Hetzner Cloud Server Image
- without the disks part I can see it's really /dev/sdb

Stefan
