### DISCUSSION TITLE
muting some logs (dhcp)

### DISCUSSION THREAD

**Discussion by Simon-CR** [siderolabs/talos#9777] [General]
While I've found information saying that those log entries are nothing to worry about, they are filling up my console logs.  Is there a way to mute those somehow ? 

`[talos] request/renew failed {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "error": "got an error while processing the request: no matching response packet received", "link": "enxbc241152a2c7"}`

**Comment by smira** [comment]
if you don't need DHCP on that link, disable it with machine configuration. 

Talos runs DHCP by default for any unconfigured network interfaces which has physical link up, so adding something like:

```yaml
machine:
  network:
    interfaces:
      - interface: enxbc241152a2c7
        dhcp: false
```

should disable DHCP.
