### DISCUSSION TITLE
user: warning: [2024-11-25T05:58:48.083493335Z]: [talos] task startAllServices (1/1): service "ext-zpool-importer" to be "up"

### DISCUSSION THREAD

**Discussion by talosnoob** [siderolabs/talos#9795] [Q&A] [answered]
Hello Talos team. 

I have a test cluster that build on virtual machines with 3 control plane nodes and 3 worker nodes. 

I decide to upgrade it from 1.8.2 to 1.8.3 by using image factory:

https://www.talos.dev/v1.8/talos-guides/install/boot-assets/#image-factory

I created schematic file bare-metal.yaml like this: 

```
# bare-metal.yaml
customization:
  extraKernelArgs:
    - net.ifnames=0
  systemExtensions:
    officialExtensions:
      - siderolabs/amd-ucode
      - siderolabs/amdgpu-firmware
      - siderolabs/bnx2-bnx2x
      - siderolabs/i915-ucode
      - siderolabs/intel-ice-firmware
      - siderolabs/intel-ucode
      - siderolabs/qlogic-firmware
      - siderolabs/drbd
      - siderolabs/zfs
``` 

Retrive ID:

```
# curl -X POST --data-binary @bare-metal.yaml https://factory.talos.dev/schematics
{"id":"05cbf47a20da755741810ffe47b14553a6715dffa0f3d801e457c96bae449a63"}

``` 

And tried to upgrade one of my cluster nodes:

```
# talosctl -n 192.168.50.11 upgrade --image factory.talos.dev/installer/05cbf47a20da755741810ffe47b14553a6715dffa0f3d801e457c96bae449a63:v1.8.3
``` 

During upgrade process node stuck in "STAGE: Booting" state and I get the following continuos messages in node console:

```
user: warning: [2024-11-25T05:58:48.083493335Z]: [talos] task startAllServices (1/1): service "ext-zpool-importer" to be "up"
``` 

If I remove the siderolabs/zfs extension from bare-metal.yaml and repeating upgrade to version 1.8.3,  all things completes successfully.

What I'm doing wrong by trying to use siderolabs/zfs extension ?
