### DISCUSSION TITLE
CoreDNS does not resolve extraHosEntries

### DISCUSSION THREAD

**Discussion by lholota** [siderolabs/talos#9822] [Q&A] [answered]
Hi all,
I have a talos cluster set up with the config below:

```
hostDNS:
            enabled: true # Enable host DNS caching resolver.
            forwardKubeDNSToHost: true # Use the host DNS resolver as upstream for Kubernetes CoreDNS pods.
            resolveMemberNames: true
```

I can confirm the change is deployed and the host entry is added to /etc/hosts but even though the host dns is enabled, it is not possible to resolve the host name an nslookup from a container. Is this expected behaviour? If so, what's the easiest way to customize the coredns deployment (i.e. change the coredns ConfigMap)?
