### DISCUSSION TITLE
fsGroup does not change the owner of the mounted directory.

### DISCUSSION THREAD

**Discussion by LennyLip** [siderolabs/talos#9885] [Q&A] [answered]
Hello, I have hostPath PersistentVolume that mounts correctly. I set securityContext/fsGroup as described in [documentation](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod). 

```
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    supplementalGroups: [4000]
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
```

Also I have extraMounts config as described in [documentation](https://www.talos.dev/v1.8/reference/configuration/v1alpha1/config/#Config.machine.kubelet.extraMounts.)

```
machine:
    kubelet:
        extraMounts:
            - destination: /var/lib/example # Destination is the absolute path where the mount will be placed in the container.
              type: bind # Type specifies the mount kind.
              source: /var/lib/example # Source specifies the source path of the mount.
              # Options are fstab style mount options.
              options:
                - bind
                - rshared
                - rw
```

These settings are applied to the pod, but they do not change the owner of the mountPath. The group is still root, not the fsGroup ID

`drwxr-xr-x 2 root root 6 Dec  5 22:38 data `

Does anyone know why this is happening? Thanks.

**Comment by LennyLip** [comment, marked as answer]
Resolved by this code, but I don't understand why is fsGroup is not works directly.

```
      initContainers:
        - name: set-volume-ownership
          image: busybox:1.28
          command: ["sh", "-c", "chown -R 2000:2000 /data/demo"]
          volumeMounts:
            - name: sec-ctx-vol
              mountPath: /data/demo
          securityContext:
            runAsUser: 0 # <-run as root
            runAsGroup: 0
```
