### ISSUE TITLE
[Feature] Allow `talosctl wipe` to work with `--insecure`

### ISSUE THREAD

**Issue by lenaxia** [siderolabs/talos#10011]
## Feature Request

There is currently no way to fully wipe a node and return it to a completely fresh install. When a node is put in maintenance mode, it cannot be wiped because the `wipe` command does not work with `--insecure`

```
$ talosctl -n 192.168.0.123 -e 192.168.0.123 wipe disk sda
rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority"
$ talosctl -n 192.168.0.123 -e 192.168.0.123 wipe disk sda --insecure
unknown flag: --insecure
```

I argue that a full wipe does not constitute a violation of the immutability principle. 

Alternatively, a boot menu option that allows booting from media (PXE or USB) and ignoring the on-disk install would also be acceptable, this way the on disk install could be replaced.  This would be in addition to the option of resetting the on-disk install to maintenance mode.

### Description

Right now there is no way to wipe a node back to a fully fresh Talos install without booting to a livedisk for a different distro and manually wiping the disk. If a node gets into a state where a machine config cannot be completely applied, the node becomes completely unusable with no way for recovery.

#### Example 1

1. Apply the following configuration using `factory.talos.dev/installer/c19375fb8749831132a7d364bf66693aa33bf7ffd7244e4d63258617edd593d0:v1.8.4`
```
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/i915-ucode
            - siderolabs/intel-ucode
            - siderolabs/nvidia-container-toolkit-production
            - siderolabs/nvidia-open-gpu-kernel-modules-production
            - siderolabs/thunderbolt
            - siderolabs/util-linux-tools
            - siderolabs/zfs
```

2. Reboot the node and reset to maintenance mode. 

3. Apply a configuration with a base image and no customizations `factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.8.4`
```
customization: {}
```

If you have no GPU installed, `ext-nvidia-persistenced` will fail to start and the node will not complete installation (see image below)
<img width="1261" alt="image" src="https://github.com/user-attachments/assets/ee1b6f3a-e3bc-4c5b-a3dd-583e189f51f7" />

Resetting, or installing other images does not work to wipe the system extensions. This node is now completely unusable and cannot be recovered without resorting to manual intervention (e.g. PXE boot an ubuntu/arch live disk to wipe /dev/sda).
