### ISSUE TITLE
Talos/PXE No valid client certificate is found

### ISSUE THREAD

**Issue by mwdomino** [siderolabs/talos#10065]
### Description
When installing Talos 1.8.3 via PXE using Sidero Metal the control plane throws errors and never comes up. I see errors about `No valid client certificate is found` as well as errors failing to get the nodes endpoint (which makes sense as the apiserver is not running).

I've attached the `support.zip` as well. I've done my best grepping through the support files as well as diffing against some manually installed (`talosctl apply-config`) hosts.
[support.zip](https://github.com/user-attachments/files/18262416/support.zip)

Talos runs fine on the hosts I manually installed for the management cluster, it is only once we started booting with iPXE that I've seen issues.

This is going to be the first PXE'd staging cluster for us, and it will have a single CP and 2 workers. After this we will have larger clusters being provisioned for production use. Right now the only node I've attempted (and the one this issue is around) is the control plane node for the staging cluster, so this issue exists entirely within a single node. I'll attempt to add the workers once this is resolved.

### Logs
```
talosctl dmesg:
10.50.56.2: user: warning: [2024-12-27T17:28:59.781012101Z]: [talos] controller failed {"component": "controller-runtime", "controller": "k8s.KubeletStaticPodController", "error": "error refreshing pod status: error fetching pod status: an error on the server (\"Authorization error (user=apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)\") has prevented the request from succeeding"}

talosctl logs kubelet:
10.50.56.2: {"ts":1735320625185.2708,"caller":"certificate/transport.go:123","msg":"No valid client certificate is found but the server is not responsive. A restart may be necessary to retrieve new initial credentials.","lastCertificateAvailabilityTime":1735320625185.2795,"shutdownThreshold":"5m0s"}


```

### Environment
- Talos version: [`talosctl version --nodes <problematic nodes>`]
```
Client:
        Tag:         v1.8.3
        SHA:         undefined
        Built:
        Go version:  go1.23.3
        OS/Arch:     linux/amd64
Server:
        NODE:        10.50.56.2
        Tag:         v1.8.3
        SHA:         6494aced
        Built:
        Go version:  go1.22.9
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```

- Kubernetes version: [`kubectl version --short`]
```
no apiserver, no kubectl :(
```
- Platform:
Bare metal servers in our own datacenter. Provisioned with Sidero Metal using PXE

**Comment by smira** [comment]
You have a totally wrong machine configuration, my wild guess you're not setting properly `talosVersion` in the CABPT resources https://github.com/siderolabs/cluster-api-bootstrap-provider-talos#usage.

It should be set to `talosVersion: v1.8` - the version of Talos you created the cluster with.

But I would absolutely recommend to start looking towards Omni and bare-metal infrastructure provider for Omni (coming out soon), instead of relying on Cluster API.

**Comment by mwdomino** [comment]
What is wrong with the machine configuration, specifically, if you can specify?

My talosVersion is specified to `v1.8.3` which seems correct to me?

```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: stage-dal4-edge01
  namespace: sidero-system
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.244.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: stage-dal4-edge01-cp
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MetalCluster
    name: stage-dal4-edge01
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalCluster
metadata:
  name: stage-dal4-edge01
  namespace: sidero-system
spec:
  controlPlaneEndpoint:
    host: 10.50.56.2
    port: 6443
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalMachineTemplate
metadata:
  name: stage-dal4-edge01-cp
  namespace: sidero-system
spec:
  template:
    spec:
      serverClassRef:
        apiVersion: metal.sidero.dev/v1alpha2
        kind: ServerClass
        name: control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: stage-dal4-edge01-cp
  namespace: sidero-system
spec:
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.8.3
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MetalMachineTemplate
    name: stage-dal4-edge01-cp
  replicas: 1
  version: v1.31.1
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: stage-dal4-edge01-workers
  namespace: sidero-system
spec:
  template:
    spec:
      generateType: join
      talosVersion: v1.8.3
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: stage-dal4-edge01-workers
  namespace: sidero-system
spec:
  clusterName: stage-dal4-edge01
  replicas: 2
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: stage-dal4-edge01-workers
      clusterName: stage-dal4-edge01
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: MetalMachineTemplate
        name: stage-dal4-edge01-workers
      version: v1.31.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalMachineTemplate
metadata:
  name: stage-dal4-edge01-workers
  namespace: sidero-system
spec:
  template:
    spec:
      serverClassRef:
        apiVersion: metal.sidero.dev/v1alpha2
        kind: ServerClass
        name: worker
```

I generated this YAML ☝️ using the commands from the docs:

```
╰─ CONTROL_PLANE_ENDPOINT="10.50.56.2" CONTROL_PLANE_PORT=6443 CONTROL_PLANE_SERVERCLASS=control-plane KUBERNETES_VERSION="v1.31.1" TALOS_VERSION="v1.8.3" WORKER_SERVERCLASS=worker clusterctl generate cluster stage-dal4-edge01 -i sidero > stage-dal4-edge01.yaml
```
