### ISSUE TITLE
1.9.1 does not detect USB disks anymore

### ISSUE THREAD

**Issue by spammads** [siderolabs/talos#10076]
## Bug Report
Upgraded from 1.8.4 --> 1.9.1

### Description
I use a Usb-Disk. Lol.
1.8.4 mounts it.
1.9.1 says `192.168.2.23: user: warning: [2024-12-30T15:22:52.695931396Z]: [talos] volume status {"component": "controller-runtime", "controller": "block.VolumeManagerController", "volume": "/dev/disk/by-path/pci-0000:00:14.0-usbv3-0:2:1.0-scsi-0:0:0:0-1", "phase": "failed -> failed", "error": "no disks matched for volume"}`

configuration looks like this:
```yaml
machine:
  disks:
    - device: /dev/disk/by-id/usb-ANYOYO_EC-SP02_012345678923-0:0
    # - device: /dev/disk/by-path/pci-0000:00:14.0-usbv3-0:2:1.0-scsi-0:0:0:0
      partitions:
        - mountpoint: /var/mnt/storage
```
I tried all of these:

- `/dev/disk/by-id/usb-ANYOYO_EC-SP02_012345678923-0:0`
- `/dev/sda`
- `/dev/disk/by-path/pci-0000:00:14.0-usbv3-0:2:1.0-scsi-0:0:0:0`

### Environment

- Talos version: 1.9.1
- Kubernetes version:  1.31.4
- Platform: baremetal

`get disks` lists the disk as `sda`:
<img width="869" alt="Screenshot 2024-12-30 at 16 29 33" src="https://github.com/user-attachments/assets/b7f8bd76-dc21-409a-9349-5323c9a40277" />

`list` under `/dev/disks/by-id` says its there:
<img width="357" alt="Screenshot 2024-12-30 at 16 33 33" src="https://github.com/user-attachments/assets/bb73f6c0-a098-4290-8e87-13574557828e" />
