### ISSUE TITLE
Cannot set up node-role.kubernetes.io/worker as label while using the machine config

### ISSUE THREAD

**Issue by shellwhale** [siderolabs/talos#10122]
### Description
I'm trying to add a node role label using the worker.yaml configuration file but it's not working.
Using kubectl work but it does not with talosctl

```yaml
    # Configures the node labels for the machine.

    # node labels example.
    nodeLabels:
        node-role.kubernetes.io/worker: ""
```

### Logs

> 192.168.0.9: user: warning: [2025-01-13T14:30:03.377030749Z]: [talos] controller failed {"component": "controller-runtime", "controller": "k8s.NodeApplyController", "error": "2 error(s) occurred:\n\tnodes \"talos-gck-fbj\" is forbidden: is not allowed to modify labels: node-role.kubernetes.io/worker\n\tclient rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline"}

Talos is 1.9
