### ISSUE TITLE
VMware OVA Not Configuring Network Interface

### ISSUE THREAD

**Issue by NWarila** [siderolabs/talos#10129]
## Bug Report
For context, this is the first time I am using Talos OS, so there may be an element of "user error." however, I feel I have ruled that out to the best of my ability and am presenting an actual bug.

### Description
OVAs from the Image Factory are not correctly configuring the initial NIC, resulting in inaccessible virtual machines. 

### Logs

Test System 1: System Booted without NIC, restarted with new NIC, picks up DHCP - Issue Bypassed.
![image](https://github.com/user-attachments/assets/39231fcd-24cb-4a28-b64b-7d4a496b0257)

Test System 2: System 1st Boot VMXNet3 (Default) - Issue Persists
![image](https://github.com/user-attachments/assets/efe80d2e-f9c8-40a9-b268-25aad857ca65)

Test System 3: System 1st Boot E1000 - Issue Persists
![image](https://github.com/user-attachments/assets/5bb42245-c403-4ca3-bf0d-2976b457d73c)

### Environment
 - ESXi 8.0.2
 - vCenter 8.0.2
 
### Factory Image
```
customization:
    extraKernelArgs:
        - ip=10.69.128.185:10.69.128.186:10.69.128.1:255.255.255.0:TCNHQ-K8CRTL01:controlplane1:<autoconf>:10.69.128.1::10.69.128.1
    systemExtensions:
        officialExtensions:
            - siderolabs/vmtoolsd-guest-agent
            - 
```

https://factory.talos.dev/?arch=amd64&cmdline=ip%3D10.69.128.185%3A10.69.128.186%3A10.69.128.1%3A255.255.255.0%3ATCNHQ-K8CRTL01%3Acontrolplane1%3A%3Cautoconf%3E%3A10.69.128.1%3A%3A10.69.128.1&cmdline-set=true&extensions=-&extensions=siderolabs%2Fvmtoolsd-guest-agent&platform=vmware&target=cloud&version=1.9.1

- Talos version: 1.9.1
