### ISSUE TITLE
[feature] Configurable node and endpoint grouping

### ISSUE THREAD

**Issue by rothgar** [siderolabs/talos#10138]
## Feature Request
Users need easier ways to query the talos API for a set of machines. Talosctl should support some default and configurable grouping for targets.

### Description

It is often requested that `talosctl` support some special names for node targets such as `all`, `controlplane` and `workers`. We should try to support some of these by default and maybe match them based on node labels (eg `nvidia.com/gpu=1` or `topology.kubernetes.io/zone=us-east-1c`).

Because node labels can be quite long and unintuitive to remember we should probably make it possible to configure target aliases so they can be meaningful to the administrator.

I'm not sure if that's something we can store in the talosconfig file but it could be nice to have an option to set up aliases such as

```
targets:
    edge1:
        - nodeA
        - nodeB
    dumpster-fire:
        labels:
            - topology.kubernetes.io/region=us-east
```
Then a user can target a group of machines in an easier to remember fashion.

If a talosctl API is not suitable for a group of machines (eg talosctl bootstrap) then a single node from the group can be selected (random or in order?) for the command to run.
