### ISSUE TITLE
The deviceSelector picks Interface with state down

### ISSUE THREAD

**Issue by mglants** [siderolabs/talos#10141]
## Bug Report
Device Selector Picks interface with state down
### Description
```
            - deviceSelector:
                physical: true
              vlans:
                - addresses:
                    - 192.168.0.146/25
                  routes:
                    - network: 192.168.0.0/24
                      gateway: 192.168.0.129
                  vlanId: 4009
                  mtu: 1400
              dhcp: true
```
Talos writes routes to disabled interface
### Logs
```
EDITED  network     RouteStatus   inet4//192.168.0.128/25/0                                      64        192.168.0.128/25                                 enp9s0.4009       0
EDITED   network     RouteStatus   inet4/192.168.0.129/192.168.0.0/24/1024                        1         192.168.0.0/24                  192.168.0.129    enp9s0.4009       1024
EDITED   network     RouteStatus   local/inet4//192.168.0.146/32/0                                64        192.168.0.146/32                                 enp9s0.4009       0
EDITED   network     RouteStatus   local/inet4//192.168.0.255/32/0                                64        192.168.0.255/32      
```
```
EDITED   network     LinkStatus   enp9s0.4009       2         ether      vlan     a8:a1:59:eb:e6:2b                                 lowerLayerDown   false
```
### Environment

- Talos version: 1.7.7
- Kubernetes version: 1.28.2
- Platform: Metal
