### ISSUE TITLE
Upgrade from 1.8.x to 1.9.x fails due to `install disk selector is invalid: selector on uuid is not supported`

### ISSUE THREAD

**Issue by james-callahan** [siderolabs/talos#10182]
## Bug Report

Upgrading to Talos 1.9.x fails with:
> install disk selector is invalid: selector on uuid is not supported

### Description

I'm currently running Talos 1.8.3

Attempting to upgrade to Talos 1.9.x it has failed with e.g.
```
$ talosctl upgrade --image  factory.talos.dev/installer-secureboot/4f90c5adef451e23d081bf5336fdafb845b69981d6c84a36e8ce2130445e21d4:v1.9.2 
WARNING: 10.1.1.107: server version 1.8.3 is older than client version 1.9.2
◲ watching nodes: [10.1.1.107]
    * 10.1.1.107: 1 error(s) occurred:
    sequence error: sequence failed: error running phase 10 in upgrade sequence: task 1/1: failed, task "upgrade" failed: exit code 1
```

My `machine.install` section look like (as seen in `get mc`):
```yaml
    install:
         disk: /dev/sda # The disk used for installations.
         # Look up disk using disk attributes like model, size, serial and others.
         diskSelector:
             uuid: 00000000-0000-0001-00a0-7523447b6ec5 # Disk UUID `/sys/block/<dev>/uuid`.
         image: factory.talos.dev/installer-secureboot/f19ad7b4a5d29151f3a59ef2d9c581cf89e77142e52f0abb5022e8f0b95ad0b9:v1.7.6
         wipe: true # Indicates if the installation disk should be wiped at installation time.
```

### Logs
Using 
```
talosctl upgrade --image  factory.talos.dev/installer-secureboot/4f90c5adef451e23d081bf5336fdafb845b69981d6c84a36e8ce2130445e21d4:v1.9.2  --debug 
```
I can see the error of:

```
user: warning: [2025-01-21T04:24:25.085871182Z]: [talos] task upgrade (1/1): performing upgrade via "factory.talos.dev/installer-secureboot/4f90c5adef451e23d081bf5336fdafb845b69981d6c84a36e8ce2130445e21d4:v1.9.2"
user: warning: [2025-01-21T04:24:25.168169182Z]: 2025/01/21 04:24:25 running Talos installer v1.9.2
user: warning: [2025-01-21T04:24:25.170547182Z]: Error: machine configuration is invalid: 1 error occurred:
user: warning: [2025-01-21T04:24:25.170555182Z]:  * install disk selector is invalid: selector on uuid is not supported
```

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:
