### ISSUE TITLE
Allow "talosctl list" with --insecure

### ISSUE THREAD

**Issue by Syntax3rror404** [siderolabs/talos#10296]
## Feature Request
Since https://github.com/siderolabs/talos/issues/8367 is only for the ephemeral talos disk, we need the list command to get the id from additonal disks to know what we need to add to the machineconfig for bootstrapping. For example for longhorn uscase. 

To workaround this issue, you can first install talos without the mounts and disks and then afterwards you can list the ids and patch and reboot the machines again. 

Example how this looks like in config: 
```
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
  disks:
    # get via talosctl --nodes 192.168.20.74 list /dev/disk/by-id
    - device: "/dev/disk/by-id/nvme-TS2TMTE220S_H537060498"
      partitions:
        - mountpoint: /var/lib/longhorn
```

### Description
Allow "talosctl list" with --insecure for getting disk id.
