### ISSUE TITLE
1.9.3 with dvb extension results in factory returning 500s

### ISSUE THREAD

**Issue by samip5** [siderolabs/talos#10293]
### Description

Schematic with the following extensions result in 500s from the official factory:
```
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/dvb-cx23885
            - siderolabs/i915
            - siderolabs/intel-ucode
```

### Logs

```
10.0.105.35: user: warning: [2025-02-05T06:46:07.59350026Z]: [talos] validating "factory.talos.dev/installer/6d6198a792c9fa0358a1d6805530d9301b4ab9faa07cfbe3690ee0b138e6b025:v1.9.3"
10.0.105.35: user: warning: [2025-02-05T06:46:26.32221326Z]: level=info msg=fetch failed after status: 500 Internal Server Error host=factory.talos.dev image=factory.talos.dev/installer/6d6198a792c9fa0358a1d6805530d9301b4ab9faa07cfbe3690ee0b138e6b025:v1.9.3
10.0.105.35: user: warning: [2025-02-05T06:46:26.52743726Z]: [talos] retrying error: failed to pull image "factory.talos.dev/installer/6d6198a792c9fa0358a1d6805530d9301b4ab9faa07cfbe3690ee0b138e6b025:v1.9.3": failed to resolve reference "factory.talos.dev/installer/6d6198a792c9fa0358a1d6805530d9301b4ab9faa07cfbe3690ee0b138e6b025:v1.9.3": unexpected status from HEAD request to https://factory.talos.dev/v2/installer/6d6198a792c9fa0358a1d6805530d9301b4ab9faa07cfbe3690ee0b138e6b025/manifests/v1.9.3: 500 Internal Server Error
```

### Environment

- Talos version: v1.9.2
- Kubernetes version: v1.31.0
- Platform: Metal
