### ISSUE TITLE
Installation fails on xcp-ng VM with diskSelector

### ISSUE THREAD

**Issue by blackliner** [siderolabs/talos#10315]
## Bug Report

`talosctl --talosconfig talosconfig -n 192.168.1.152 apply-config --file worker.yaml --insecure` fails for a machine in maintenance mode, not being able to find the disk with a diskSelector. I tried `<=1TB` and `>=8GB` in the `worker.yaml`

`disk.transport != ""` is the issue IMHO, not sure why that is empty though.

First try:
```yaml
  install:
    diskSelector:
      size: '<= 1TB'
    image: ghcr.io/siderolabs/installer:v1.9.3
```
Error:
```
$ talosctl --talosconfig talosconfig -n 192.168.1.152 apply-config --file worker.yaml --insecure
error applying new configuration: rpc error: code = InvalidArgument desc = runtime configuration validation failed: 1 error occurred:
        * no disks matched the expression: disk.size <= 1000000000000u && disk.transport != "" && !disk.readonly && !disk.cdrom
```
Second try:
```yaml
  install:
    diskSelector:
      size: '>= 8GB'
    image: ghcr.io/siderolabs/installer:v1.9.3
```
Error:
```
$ talosctl --talosconfig talosconfig -n 192.168.1.152 apply-config --file worker.yaml --insecure
error applying new configuration: rpc error: code = InvalidArgument desc = runtime configuration validation failed: 1 error occurred:
        * no disks matched the expression: disk.size >= 8000000000u && disk.transport != "" && !disk.readonly && !disk.cdrom
```

Disk info from the relevant node:
```
$ talosctl --talosconfig talosconfig -n 192.168.1.152 get disks --insecure
NODE   NAMESPACE   TYPE   ID      VERSION   SIZE     READ ONLY   TRANSPORT   ROTATIONAL   WWID   MODEL          SERIAL
       runtime     Disk   loop0   1         74 MB    true
       runtime     Disk   sr0     1         105 MB   false       ata                             QEMU DVD-ROM
       runtime     Disk   xvda    1         34 GB    false
```

### Workaround

Hardcoded the disk to `/dev/xvda`.

### Environment

- Talos version: 1.9.3
- Kubernetes version: 1.32.1
- Platform: xcp-ng 8.3

**Comment by smira** [comment]
Might be a duplicate of #10292, please attach full output of `talosctl get disks -o yaml`.

**Comment by blackliner** [comment]
`config.patch`
```yaml
machine:
  install:
    # https://factory.talos.dev/?arch=amd64&board=undefined&cmdline-set=true&extensions=-&extensions=siderolabs%2Fxen-guest-agent&platform=nocloud&secureboot=undefined&target=cloud&version=1.9.4
    # customization:
    #   systemExtensions:
    #     officialExtensions:
    #       - siderolabs/xen-guest-agent
    image: factory.talos.dev/installer/53b20d86399013eadfd44ee49804c1fef069bfdee3b43f3f3f5a2f57c03338ac:v1.9.5
    disk:
      $patch: delete
    diskSelector:
      size: ">= 8GB"
      transport: ""
  kubelet:
    nodeIP:
      validSubnets:
        - 10.32.0.0/24
```

```bash
talosctl -n 10.32.0.13 -e 10.32.0.13 get --insecure disks                                                Py cloud_infra_stacks
NODE   NAMESPACE   TYPE   ID      VERSION   SIZE     READ ONLY   TRANSPORT   ROTATIONAL   WWID   MODEL          SERIAL
       runtime     Disk   loop0   1         4.1 kB   true                                                       
       runtime     Disk   loop1   1         684 kB   true                                                       
       runtime     Disk   loop2   1         74 MB    true                                                       
       runtime     Disk   sr0     1         106 MB   false       ata                             QEMU DVD-ROM   
       runtime     Disk   xvda    1         137 GB   false 
```
