### ISSUE TITLE
Better formatting for talosctl get machineconfig

### ISSUE THREAD

**Issue by stereobutter** [siderolabs/talos#10399]
## Feature Request
Format the machine config string returned by `talosctl get machineconfig -o yaml` as yaml multiline block scalar.

### Description
In versions v1.8 and v1.9 `talosctl get machineconfig -o yaml` returns something like

```yaml
node: 192.168.255.10
metadata:
    namespace: config
    type: MachineConfigs.config.talos.dev
    id: v1alpha1
    version: 1
    owner:
    phase: running
    created: 2025-02-20T06:53:24Z
    updated: 2025-02-20T06:53:24Z
spec: "cluster:\n  aggregatorCA:\n    crt: <redacted>\n    key: <redacted>\n  allowSchedulingOnControlPlanes: true\n  apiServer:\n    admissionControl:\n      - configuration:\n          apiVersion: pod-security.admission.config.k8s.io/v1alpha1\n          defaults:\n      ..."
```

which is hard to read compared to

```yaml
node: 192.168.255.10
metadata:
    namespace: config
    type: MachineConfigs.config.talos.dev
    id: v1alpha1
    version: 1
    owner:
    phase: running
    created: 2025-02-20T06:53:24Z
    updated: 2025-02-20T06:53:24Z
spec: |  # <--- notice the block style
  cluster:
    aggregatorCA:
      crt: <redacted>
      key: <redacted>
    allowSchedulingOnControlPlanes: true
    apiServer:
      admissionControl:
        - configuration:
            apiVersion: pod-security.admission.config.k8s.io/v1alpha1
            defaults:
       ...
```
