### ISSUE TITLE
VIP not working when using predictable interface names

### ISSUE THREAD

**Issue by arnetogo** [siderolabs/talos#10402]
## Bug Report

Defining a network interface in the MachineConfig by using predictable interface names in conjunction a VIP on the same interface, the VIP never gets assigned to any of the control planes.

### Description

Talos in multi home network. Defining the VIP interface using predictable interface names e.g. `interface: enx5254007a66a0` and bootstrapping the cluster the VIP IP never gets assigned to any of the control plane nodes.
Other aspects of network configuration, e.g. static routes or IP config gets correctly applied using the same notation. 

```
node: 192.168.100.10
spec: |
    machine:
        type: controlplane
        kubelet:
            nodeIP:
                validSubnets:
                    - 10.0.1.0/24
        network:
            hostname: talos-ctl-1
            interfaces:
                - interface: enx525400e343ec
                  dhcp: true
                - interface: enx5254007a66a0
                  dhcp: true
                  vip:
                    ip: 10.0.1.100
---
node: 192.168.100.11
spec: |
    machine:
        type: controlplane
        kubelet:
            nodeIP:
                validSubnets:
                    - 10.0.1.0/24
        network:
            hostname: talos-ctl-2
            interfaces:
                - interface: enx5254002ad493
                  dhcp: true
                - interface: enx52540083dfe1
                  dhcp: true
                  vip:
                    ip: 10.0.1.100
---
node: 192.168.100.12
spec: |
    machine:
        type: controlplane
        kubelet:
            nodeIP:
                validSubnets:
                    - 10.0.1.0/24
        network:
            hostname: talos-ctl-3
            interfaces:
                - interface: enx525400e94231
                  dhcp: true
                - interface: enx525400fcd77e
                  dhcp: true
                  vip:
                    ip: 10.0.1.100
```

the controlPlane endpoint is configured to point to the VIP IP:
```
    cluster:
        controlPlane:
            endpoint: https://10.0.1.100:6443
```

Getting the members after bootstrap reveals that all IPs have been assinged, dispite the VIP IP.
```
talosctl -n 192.168.100.10 get members
NODE             NAMESPACE   TYPE     ID            VERSION   HOSTNAME      MACHINE TYPE   OS               ADDRESSES
192.168.100.10   cluster     Member   talos-ctl-1   1         talos-ctl-1   controlplane   Talos (v1.9.4)   ["10.0.1.10","192.168.100.10"]
192.168.100.10   cluster     Member   talos-ctl-2   1         talos-ctl-2   controlplane   Talos (v1.9.4)   ["10.0.1.11","192.168.100.11"]
192.168.100.10   cluster     Member   talos-ctl-3   2         talos-ctl-3   controlplane   Talos (v1.9.4)   ["10.0.1.12","192.168.100.12","192.168.100.100"]
192.168.100.10   cluster     Member   talos-wrk-1   1         talos-wrk-1   worker         Talos (v1.9.4)   ["10.0.1.5","192.168.100.5"]
```

And since VIP depends on etcd, the etcd status:
```
talosctl -n 192.168.100.10 etcd members
NODE             ID                 HOSTNAME      PEER URLS                CLIENT URLS              LEARNER
192.168.100.10   22ea434a682f6cd4   talos-ctl-1   https://10.0.1.10:2380   https://10.0.1.10:2379   false
192.168.100.10   389235218e3daff1   talos-ctl-2   https://10.0.1.11:2380   https://10.0.1.11:2379   false
192.168.100.10   4a570fc739140c71   talos-ctl-3   https://10.0.1.12:2380   https://10.0.1.12:2379   false
```

The controller runtime log indicates an error:
```
 user: warning: [2025-02-21T15:11:39.678140007Z]: [talos] kubernetes endpoint watch error {"component": "controller-runtime", "controller": "k8s.EndpointController", "error": "failed to    
 list *v1.Endpoints: Get \"https://10.0.1.100:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&limit=500&resourceVersion=0\": dial tcp 10.0.1.100:6443:
```

Nevertheless, the cluster is in Ready State:

for completeness the relevant output from `talosctl get links`:
```NODE             NAMESPACE   TYPE         ID             VERSION   TYPE       KIND     HW ADDR                                           OPER STATE   LINK STATE
192.168.100.10   network     LinkStatus   ens6           2         ether               52:54:00:e3:43:ec                                 up           true
192.168.100.10   network     LinkStatus   ens7           2         ether               52:54:00:7a:66:a0                                 up           true
----
192.168.100.11   network     LinkStatus   ens6           3         ether               52:54:00:2a:d4:93                                 up           true
192.168.100.11   network     LinkStatus   ens7           3         ether               52:54:00:83:df:e1                                 up           true
----
192.168.100.12   network     LinkStatus   ens6           3         ether               52:54:00:e9:42:31                                 up           true
192.168.100.12   network     LinkStatus   ens7           3         ether               52:54:00:fc:d7:7e                                 up           true
```

when changing the machineConfig network configuration to identify the interfaces by one of their actual aliases:

```
node: 192.168.100.10
spec: |
    machine:
        network:
            interfaces:
                - interface: ens7
                  dhcp: true
                  vip:
                    ip: 10.0.1.100
---
node: 192.168.100.11
spec: |
    machine:
        network:
            interfaces:
                - interface: ens7
                  dhcp: true
                  vip:
                    ip: 10.0.1.100
---
node: 192.168.100.12
spec: |
    machine:
        network:
            hostname: talos-ctl-3
            interfaces:
                - interface: ens7
                  dhcp: true
                  vip:
                    ip: 10.0.1.100
```

the VIP IP gets assigned as expected:

```
talosctl -n 192.168.100.10 get members
NODE             NAMESPACE   TYPE     ID            VERSION   HOSTNAME      MACHINE TYPE   OS               ADDRESSES
192.168.100.10   cluster     Member   talos-ctl-1   2         talos-ctl-1   controlplane   Talos (v1.9.4)   ["10.0.1.10","10.0.1.100","192.168.100.10"]
192.168.100.10   cluster     Member   talos-ctl-2   1         talos-ctl-2   controlplane   Talos (v1.9.4)   ["10.0.1.11","192.168.100.11"]
192.168.100.10   cluster     Member   talos-ctl-3   2         talos-ctl-3   controlplane   Talos (v1.9.4)   ["10.0.1.12","192.168.100.12","192.168.100.100"]
192.168.100.10   cluster     Member   talos-wrk-1   1         talos-wrk-1   worker         Talos (v1.9.4)   ["10.0.1.5","192.168.100.5"]
```

it has to be noted that kubePrism is enabled, so Talos, k8s and node status is ready, despite the VIP IP is not set. I would expect that VIP config also expects this notation or an exception is documented.

### Environment

- Talos version: v1.9.4
- Kubernetes version: 1.31.6
- Platform: metal/libvirt
