### ISSUE TITLE
Unable to Remove Duplicate iscsi-tools System Extension

### ISSUE THREAD

**Issue by logg926** [siderolabs/talos#10404]
### Description
Unable to remove or deduplicate system extensions on a control plane node. The node has two versions of `iscsi-tools` (v0.1.1 and v0.1.4) installed simultaneously. All attempts to remove the older version or consolidate to a single version have failed.

### Current State
Running `talosctl get extensions` shows:
```
NODE              NAMESPACE   TYPE              ID                                          VERSION   NAME          VERSION
<control-plane-ip>   runtime     ExtensionStatus   000.ghcr.io-siderolabs-iscsi-tools-v0.1.1   1         iscsi-tools   v0.1.1
<control-plane-ip>   runtime     ExtensionStatus   001.ghcr.io-siderolabs-iscsi-tools-v0.1.4   1         iscsi-tools   v0.1.4
```

The `/etc/extensions.yaml` content shows:
```yaml
layers:
    - image: 000.ghcr.io-siderolabs-iscsi-tools-v0.1.1.sqsh
      metadata:
        name: iscsi-tools
        version: v0.1.1
        author: Sidero Labs
        description: |
            This system extension provides iscsi-tools.
        compatibility:
            talos:
                version: '>= v1.1.0'
    - image: 001.ghcr.io-siderolabs-iscsi-tools-v0.1.4.sqsh
      metadata:
        name: iscsi-tools
        version: v0.1.4
        author: Sidero Labs
        description: |
            This system extension provides iscsi-tools.
        compatibility:
            talos:
                version: '>= v1.1.0'
```

### Attempted Solutions

We tried multiple approaches to resolve this issue, in the following order:

1. **Direct patch to specify only v0.1.4**:
```yaml
machine:
  install:
    extensions:
      - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4
```
Error: `duplicate system extension "ghcr.io/siderolabs/iscsi-tools:v0.1.4"`

2. **Clear all extensions**:
```yaml
machine:
  install:
    extensions: []
```
Result: "Apply was skipped: no changes detected"

3. **Reset node**:
```bash
talosctl -n <control-plane-ip> reset --graceful=false --reboot --system-labels-to-wipe=STATE --system-labels-to-wipe=EPHEMERAL
```
Result: Node reboots but extensions remain

4. **Wipe and reinstall**:
```yaml
machine:
  install:
    extensions:
      - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4
    wipe: true
```
Error: Same duplicate extension error

### Environment
- Talos version: v1.9.2
- Kubernetes version: v1.32.0
- Node type: Control plane
- Node OS: Talos (v1.9.2)
- Kernel version: 6.12.9-talos

5. **Apply complete machine config replacement**:
```yaml
machine:
  type: controlplane
  install:
    extensions:
      - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4
```
Result: Same duplicate extension error

6. **Attempt to modify /etc/extensions.yaml directly**:
- Retrieved current extensions.yaml
- Created modified version with only v0.1.4
- No direct way to write back the modified file

7. **Investigate extension files**:
- Checked various system directories (/usr/install-extensions/, /var/system-extensions/)
- Unable to locate or directly manage the .sqsh files
- Extensions appear to be managed through an internal system

8. **Bootstrap attempt**:
- Tried to bootstrap the node again
- Extensions persisted through the process

9. **Reset with specific partition wipe**:
```bash
talosctl reset --graceful=false --reboot --system-labels-to-wipe=STATE --system-labels-to-wipe=EPHEMERAL
```
- Node rebooted but extensions remained
- Lost connection during reset as expected
- After reboot, both extensions still present

### Questions
1. Is there a way to forcefully remove a specific system extension?
2. Is there a direct way to modify `/etc/extensions.yaml` or remove the squashfs files?
3. What's the recommended approach for deduplicating system extensions?

### Additional Finding: Machine Config vs Actual State Discrepancy

We've discovered an interesting discrepancy between the machine configuration and the actual state of extensions on another control plane node:

1. When running `talosctl get extensions`, the output shows only the schematic extension:
```
NODE             NAMESPACE   TYPE              ID   VERSION   NAME        VERSION
<control-plane2>   runtime     ExtensionStatus   0    1         schematic  
```

2. However, when checking the machine config (`talosctl get mc`), it shows both versions of iscsi-tools are configured:
```yaml
machine:
  install:
    extensions:
      - image: ghcr.io/siderolabs/iscsi-tools:v0.1.1
      - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4
```

3. When trying to add iscsi-tools:v0.1.4 to this node, we get the same duplicate error:
```
rpc error: code = InvalidArgument desc = 1 error occurred:
* duplicate system extension "ghcr.io/siderolabs/iscsi-tools:v0.1.4"
```

This suggests there might be a deeper issue with how system extensions are tracked and managed, as there's a mismatch between:
- What's in the machine configuration
- What's shown by the extensions command
- What the system considers to be installed when validating changes

### Worker Node Investigation

We investigated two worker nodes and found inconsistent behavior:

**Worker Node 1**:
```yaml
# Machine Config (extensions section)
machine:
  install:
    extensions:
      - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4
```

**Worker Node 2**:
```yaml
# Machine Config (extensions section)
machine:
  install:
    extensions:
      - image: ghcr.io/siderolabs/iscsi-tools:v0.1.1
      - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4
      - image: ghcr.io/siderolabs/util-linux-tools:v1.5.0
```

However, when running `talosctl get extensions` on both nodes:
```
NODE             NAMESPACE   TYPE              ID   VERSION   NAME        VERSION
worker-1         runtime     ExtensionStatus   0    1         schematic  
worker-2         runtime     ExtensionStatus   0    1         schematic  
```

This reveals that:
1. The duplicate extension issue exists on both control plane and worker nodes
2. Some nodes have clean configs (only v0.1.4) while others have duplicates
3. The `get extensions` command shows only schematic regardless of what's in the machine config
4. Even nodes with clean configs in machine config still error with 'duplicate extension' when trying to apply changes

### Impact
This prevents us from properly managing iscsi-tools on our nodes, which is required for Longhorn storage to work correctly.
