### ISSUE TITLE
Failed to check br_netfilter

### ISSUE THREAD

**Issue by Conor-Behard333** [siderolabs/talos#10430]
## Bug Report
Flannel (v0.26.1) errors out on deployment of a kubernetes control node (with scheduling enabled) when deployed in a container

### Description
I have Talos deployed in a kubernetes cluster as a pod. I use a container in the same pod to configure and setup a single node cluster using the default CNI configured (Flannel). 

I had this working a few days ago, however something has changed (not sure what) that has resulted in getting the following error when the kube-flannel pod is created: 
`Failed to check br_netfilter: stat /proc/sys/net/bridge/bridge-nf-call-iptables: no such file or directory`

I apply the following patch to the config of the control plane:
```YAML
machine:
    features:
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
cluster:
    allowSchedulingOnControlPlanes: true
    apiServer:
        admissionControl:
            $patch: delete
        disablePodSecurityPolicy: true # Disable PodSecurityPolicy in the API server and default manifests.
```

### Logs
Defaulted container "kube-flannel" out of: kube-flannel, install-config (init)
I0226 16:42:12.522751       1 main.go:212] CLI flags config: {etcdEndpoints:http://127.0.0.1:4001,http://127.0.0.1:2379 etcdPrefix:/coreos.com/network etcdKeyfile: etcdCertfile: etcdCAFile: etcdUsername: etcdPassword: version:false kubeSubnetMgr:true kubeApiUrl: kubeAnnotationPrefix:flannel.alpha.coreos.com kubeConfigFile: iface:[] ifaceRegex:[] ipMasq:true ifaceCanReach: subnetFile:/run/flannel/subnet.env publicIP: publicIPv6: subnetLeaseRenewMargin:60 healthzIP:0.0.0.0 healthzPort:0 iptablesResyncSeconds:5 iptablesForwardRules:true netConfPath:/etc/kube-flannel/net-conf.json setNodeNetworkUnavailable:true}
W0226 16:42:12.522852       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0226 16:42:12.533563       1 kube.go:139] Waiting 10m0s for node controller to sync
I0226 16:42:12.533635       1 kube.go:469] Starting kube subnet manager
I0226 16:42:13.533761       1 kube.go:146] Node controller sync successful
I0226 16:42:13.533798       1 main.go:232] Created subnet manager: Kubernetes Subnet Manager - coder-conorroberts-test1
I0226 16:42:13.533806       1 main.go:235] Installing signal handlers
I0226 16:42:13.534046       1 main.go:469] Found network config - Backend type: vxlan
E0226 16:42:13.534109       1 main.go:269] Failed to check br_netfilter: stat /proc/sys/net/bridge/bridge-nf-call-iptables: no such file or directory

### Environment

- Talos version: [v1.9.2]
- Kubernetes version: [v1.28.9]
- Platform: kubernetes
