### ISSUE TITLE
Talos 1.9.4 seems to ignore insecureSkipVerify for registries

### ISSUE THREAD

**Issue by gelato** [siderolabs/talos#10450]
## Bug Report

Talos 1.9.4 seems like is ignoring this configuration: https://www.talos.dev/v1.9/reference/configuration/v1alpha1/config/#Config.machine.registries.config.-

### Description

After upgrade I started receiving following log messages:

```
192.168.108.209: user: warning: [2025-03-02T18:17:04.548908252Z]: [talos] retrying error: failed to pull image "ghcr.io/siderolabs/kubelet:v1.32.2": failed to resolve reference "ghcr.io/siderolabs/kubelet:v1.32.2": TLS config specified for non-HTTPS registry: "harbor.casa"
```

As a result cluster died and remained that way until I commented this configuration:

```
machine:
  registries:
    config:
      harbor.casa:
        # The TLS configuration for the registry.
        tls:
          insecureSkipVerify: true
    mirrors:
      docker.io:
        endpoints:
          - http://harbor.casa/v2/local-dreg
        overridePath: true
      ghcr.io:
        endpoints:
          - http://harbor.casa/v2/local-github
        overridePath: true
      gcr.io:
        endpoints:
          - http://harbor.casa/v2/local-gcr
        overridePath: true
      registry.k8s.io:
        endpoints:
          - http://harbor.casa/v2/local-k8s
        overridePath: true
      quay.io:
        endpoints:
          - http://harbor.casa/v2/local-quay
        overridePath: true
      hub.docker.com:
        endpoints:
          - http://harbor.casa/v2/local-dhub
        overridePath: true
```

### Logs

```
192.168.108.209: user: warning: [2025-03-02T17:24:48.993222949Z]: [talos] kubernetes endpoint watch error {"component": "controller-runtime", "controller": "k8s.EndpointController", "error": "failed to list *v1.Endpoints: Get \"https://192.168.108.250:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&limit=500&resourceVersion=0\": dial tcp 192.168.108.250:6443: connect: no route to host"}
192.168.108.209: user: warning: [2025-03-02T17:24:53.348516949Z]: [talos] task startAllServices (1/1): service "kubelet" to be "up"
192.168.108.209: user: warning: [2025-03-02T17:25:08.348080949Z]: [talos] task startAllServices (1/1): service "kubelet" to be "up"
192.168.108.209: user: warning: [2025-03-02T17:25:23.348232949Z]: [talos] task startAllServices (1/1): service "kubelet" to be "up"
192.168.108.209: user: warning: [2025-03-02T17:25:38.349324949Z]: [talos] task startAllServices (1/1): service "kubelet" to be "up"
192.168.108.209: user: warning: [2025-03-02T17:25:44.833970949Z]: [talos] kubernetes endpoint watch error {"component": "controller-runtime", "controller": "k8s.EndpointController", "error": "failed to list *v1.Endpoints: Get \"https://192.168.108.250:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&limit=500&resourceVersion=0\": dial tcp 192.168.108.250:6443: connect: no route to host"}
192.168.108.209: user: warning: [2025-03-02T17:25:53.349334949Z]: [talos] task startAllServices (1/1): service "kubelet" to be "up"
192.168.108.209: user: warning: [2025-03-02T17:26:08.349145949Z]: [talos] task startAllServices (1/1): service "kubelet" to be "up"
192.168.108.209: user: warning: [2025-03-02T17:26:13.563983949Z]: [talos] service[kubelet](Failed): Failed to run pre stage: 2 error(s) occurred:
192.168.108.209: user: warning: [2025-03-02T17:26:13.564023949Z]:  failed to pull image "ghcr.io/siderolabs/kubelet:v1.32.2": failed to resolve reference "ghcr.io/siderolabs/kubelet:v1.32.2": TLS config specified for non-HTTPS registry: "harbor.casa"
192.168.108.209: user: warning: [2025-03-02T17:26:13.564045949Z]:  timeout
192.168.108.209: user: warning: [2025-03-02T17:26:23.349150949Z]: [talos] task startAllServices (1/1): service "kubelet" to be "up"
192.168.108.209: user: warning: [2025-03-02T17:26:38.349895949Z]: [talos] task startAllServices (1/1): service "kubelet" to be "up"
192.168.108.209: user: warning: [2025-03-02T17:26:39.458966949Z]: [talos] kubernetes endpoint watch error {"component": "controller-runtime", "controller": "k8s.EndpointController", "error": "failed to list *v1.Endpoints: Get \"https://192.168.108.250:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&limit=500&resourceVersion=0\": dial tcp 192.168.108.250:6443: connect: no route to host"}
192.168.108.209: user: warning: [2025-03-02T17:26:53.350042949Z]: [talos] task startAllServices (1/1): service "kubelet" to be "up"
192.168.108.209: user: warning: [2025-03-02T17:27:08.350181949Z]: [talos] task startAllServices (1/1): service "kubelet" to be "up"
192.168.108.209: user: warning: [2025-03-02T17:27:23.350630949Z]: [talos] task startAllServices (1/1): service "kubelet" to be "up"
192.168.108.209: user: warning: [2025-03-02T17:27:26.979254949Z]: [talos] kubernetes endpoint watch error {"component": "controller-runtime", "controller": "k8s.EndpointController", "error": "failed to list *v1.Endpoints: Get \"https://192.168.108.250:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&limit=500&resourceVersion=0\": dial tcp 192.168.108.250:6443: connect: no route to host"}
```

### Environment

- Talos version: 
```
Client:
	Tag:         v1.9.4
	SHA:         c863a561
	Built:
	Go version:  go1.23.6
	OS/Arch:     darwin/arm64
Server:
	NODE:        192.168.108.149
	Tag:         v1.9.4
	SHA:         c863a561
	Built:
	Go version:  go1.23.6
	OS/Arch:     linux/amd64
	Enabled:     RBAC
```
- Kubernetes version: [`kubectl version`]
```
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.32.2
```
(this is after fixing a problem with registries)
- Platform:
x86

**Comment by smira** [comment]
I'm not sure what do you mean, you have `http://harbor.casa` specified, not `https://`, so how can it be TLS insecure?

You need to figure out what you're looking for there, either http or https, and fix the config accordingly.

**Comment by gelato** [comment]
Ok, I get the mistake with http:// part, but it was working that way before 1.9.4.
But still, here is what I get trying to pull from harbor.casa:
```
48m         Warning   Failed             pod/wyoming-gigaam-ctc-74bcd57b85-cmpb9    Failed to pull image "harbor.casa/library/wyoming-gigaam-ctc:latest": failed to pull and unpack image "harbor.casa/library/wyoming-gigaam-ctc:latest": failed to resolve reference "harbor.casa/library/wyoming-gigaam-ctc:latest": failed to do request: Head "https://harbor.casa/v2/library/wyoming-gigaam-ctc/manifests/latest": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

Having this in config:
```
machine:
  registries:
    config:
      harbor.casa:
        tls:
          insecureSkipVerify: true
```
