### ISSUE TITLE
DHCP errors when using bond interface in 802.3ad mode

### ISSUE THREAD

**Issue by apfuzz** [siderolabs/talos#10467]
### Description

After changing a bond interface mode from "balance-rr" to "802.3ad" the console starts showing DHCP error messages constantly. This is unexpected because the interface has a static IP address and DHCP is specifically set to "false". The messages stop if I change back to "balance-rr" then reappear when I go to "802.3ad" again so it appears to be something specifically related to this mode. My current network config is below.

```
❯ talosctl -n 10.101.200.24 get mc v1alpha1 -o yaml | yq .spec | yq .machine.network
interfaces:
  - interface: bond0
    addresses:
      - 10.101.200.24/24
    routes:
      - network: 0.0.0.0/0
        gateway: 10.101.200.1
    bond:
      interfaces:
        - enp130s0f0
        - enp130s0f1
      mode: 802.3ad
      miimon: 100
    dhcp: false
nameservers:
  - 192.168.6.253
  - 192.168.6.252
```

### Logs

```
10.101.200.24: user: warning: [2025-03-04T17:46:38.701156538Z]: [talos] request/renew failed {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "error": "unable to receive an offer: got an error while the discovery request: no matching response packet received", "link": "enp130s0f0"}
10.101.200.24: user: warning: [2025-03-04T17:47:19.025344538Z]: [talos] request/renew failed {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "error": "unable to receive an offer: got an error while the discovery request: no matching response packet received", "link": "enp130s0f0"}
10.101.200.24: user: warning: [2025-03-04T17:47:59.349536538Z]: [talos] request/renew failed {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "error": "unable to receive an offer: got an error while the discovery request: no matching response packet received", "link": "enp130s0f0"}
10.101.200.24: user: warning: [2025-03-04T17:48:39.677747538Z]: [talos] request/renew failed {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "error": "unable to receive an offer: got an error while the discovery request: no matching response packet received", "link": "enp130s0f0"}
10.101.200.24: user: warning: [2025-03-04T17:49:20.001930538Z]: [talos] request/renew failed {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "error": "unable to receive an offer: got an error while the discovery request: no matching response packet received", "link": "enp130s0f0"}
10.101.200.24: user: warning: [2025-03-04T17:50:00.334115538Z]: [talos] request/renew failed {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "error": "unable to receive an offer: got an error while the discovery request: no matching response packet received", "link": "enp130s0f0"}
10.101.200.24: user: warning: [2025-03-04T17:50:40.658288538Z]: [talos] request/renew failed {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "error": "unable to receive an offer: got an error while the discovery request: no matching response packet received", "link": "enp130s0f0"}
10.101.200.24: user: warning: [2025-03-04T17:51:20.978492538Z]: [talos] request/renew failed {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "error": "unable to receive an offer: got an error while the discovery request: no matching response packet received", "link": "enp130s0f0"}
10.101.200.24: user: warning: [2025-03-04T17:52:01.302681538Z]: [talos] request/renew failed {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "error": "unable to receive an offer: got an error while the discovery request: no matching response packet received", "link": "enp130s0f0"}
10.101.200.24: user: warning: [2025-03-04T17:52:41.622861538Z]: [talos] request/renew failed {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "error": "unable to receive an offer: got an error while the discovery request: no matching response packet received", "link": "enp130s0f0"}
```

### Environment

- Talos version:

```
Client:
        Tag:         v1.8.4
        SHA:         3c151c8a
        Built:       
        Go version:  go1.22.10
        OS/Arch:     darwin/arm64
Server:
        NODE:        10.101.200.24
        Tag:         v1.8.4
        SHA:         3c151c8a
        Built:       
        Go version:  go1.22.10
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```

- Kubernetes version:

```
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.9
Kubecolor Version: v0.5.0
```

- Platform: metal

**Comment by smira** [comment]
It shouldn't run DHCP on enslaved links, please submit a talosctl support bundle.

**Comment by apfuzz** [comment]
Attached

[support.zip](https://github.com/user-attachments/files/19076691/support.zip)

**Comment by smira** [comment]
As some information is hidden in the support.zip (for security purposes), I might need something more please to understand the issue:

```
talosctl get operatorspecs -o yaml 
talosctl get operatorspecs --namespace=network-config -o yaml

talosctl get linkspecs -o yaml 
talosctl get linkspecs --namespace=network-config -o yaml
```

**Comment by smira** [comment]
Ah, you have it enabled in the platform config:

```yaml
node: 10.101.200.24
metadata:
    namespace: network
    type: OperatorSpecs.net.talos.dev
    id: dhcp4/enp130s0f0
    version: 2
    owner: network.OperatorMergeController
    phase: running
    created: 2025-02-28T03:16:24Z
    updated: 2025-02-28T03:16:26Z
spec:
    operator: dhcp4
    linkName: enp130s0f0
    requireUp: true
    dhcp4:
        routeMetric: 1024
    layer: platform
```

I guess you used the dashboard to set the network config manually. 

That's why you have it.
