### ISSUE TITLE
cryptsetup failing in 1.9.4, successful in 1.8.3

### ISSUE THREAD

**Issue by bartlaarhoven** [siderolabs/talos#10473]
### Description

After upgrade from 1.8.3 to 1.9.4, we noticed that encrypted PVs couldn't be mounted anymore on the Talos node that was upgraded. Other nodes (still on 1.8.3) were still capable of mounting the same PVs.

Booted the upgraded node back to 1.8.3, and mounting the volumes worked again. Booted again into 1.9.4, the issue returned. Decided to rollback to 1.8.3 for the time being. I couldn't relate it to any part of the release notes, so therefore this issue.

### Configuration

Encrypted storageclass using:

```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
...
parameters:
...
    encrypted: "true"
    encryptionKMSID: example-secret-name
...
```

### Logs

Pod event logs:

```
MountVolume.MountDevice failed for volume "pvc-ba495824-4fd2-470e-a13b-c389d5cb0a60" : rpc error: code = Internal desc = an error (exit status 1) occurred while running cryptsetup args: [luksOpen /dev/rbd4 luks-rbd-0001-0009-rook-ceph-0000000000000008-e1890dfc-b7e1-4692-a46d-7dc871010d67 --disable-keyring -d /dev/stdin]
```

csi-rbdplugin logs:

```
2025-03-05T09:42:11.843928203Z W0305 09:42:11.843768  247407 rbd_attach.go:238] nbd modprobe failed (an error (exit status 1) occurred while running modprobe args: [nbd]): "modprobe: ERROR: could not insert 'nbd': Operation not permitted\n"
2025-03-05T09:42:48.289039584Z E0305 09:42:48.288918  247407 crypto.go:283] ID: 14 Req-ID: 0001-0009-rook-ceph-0000000000000008-b7d268cc-e8bf-450e-8765-f4e3fc125954 failed to open device "/dev/rbd5" (an error (exit status 1) occurred while running cryptsetup args: [luksOpen /dev/rbd5 luks-rbd-0001-0009-rook-ceph-0000000000000008-b7d268cc-e8bf-450e-8765-f4e3fc125954 --disable-keyring -d /dev/stdin]): Failed to open key file.
2025-03-05T09:42:48.289077695Z E0305 09:42:48.288962  247407 encryption.go:300] ID: 14 Req-ID: 0001-0009-rook-ceph-0000000000000008-b7d268cc-e8bf-450e-8765-f4e3fc125954 failed to open device replicatedpool/csi-vol-b7d268cc-e8bf-450e-8765-f4e3fc125954: an error (exit status 1) occurred while running cryptsetup args: [luksOpen /dev/rbd5 luks-rbd-0001-0009-rook-ceph-0000000000000008-b7d268cc-e8bf-450e-8765-f4e3fc125954 --disable-keyring -d /dev/stdin]
2025-03-05T09:42:48.383675741Z E0305 09:42:48.383560  247407 utils.go:271] ID: 14 Req-ID: 0001-0009-rook-ceph-0000000000000008-b7d268cc-e8bf-450e-8765-f4e3fc125954 GRPC error: rpc error: code = Internal desc = an error (exit status 1) occurred while running cryptsetup args: [luksOpen /dev/rbd5 luks-rbd-0001-0009-rook-ceph-0000000000000008-b7d268cc-e8bf-450e-8765-f4e3fc125954 --disable-keyring -d /dev/stdin]
```

### Environment

- Talos version: 1.9.4 / 1.8.3
- Kubernetes version: 1.31.3
- Platform: Rook 1.16.4 / Ceph v19.2.1-20250202

**Comment by smira** [comment]
This should have nothing to do with Talos in general, unless you can pin to Talos, as it's your CSI. 

No idea if Ceph is using `cryptesetup` from the host or doesn't, it certainly got updated in Talos 1.9, but if that fails, it would be a bug on Ceph side.

**Comment by smira** [comment]
And also you need to verify whether Ceph is using host cryptsetup, or its own bundled version. If it uses its own version, it's totally not a Talos issue directly.

**Comment by smira** [comment]
`cryptsetup` is already included in base Talos.

**Comment by asbarbati** [comment]
Hi smira,
The identical problem is being observed on my system, which runs Talos v1.9.3 and Longhorn, configured as follows.

Environment:
* LongHorn: v1.8.0
* TalosOS: v1.9.3

Extension loaded:
* siderolabs/iscsi-tools
* siderolabs/qemu-guest-agent
* siderolabs/util-linux-tools

Storageclass:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-crypto-apps
parameters:
  csi.storage.k8s.io/node-publish-secret-name: longhorn-crypto
  csi.storage.k8s.io/node-publish-secret-namespace: apps
  csi.storage.k8s.io/node-stage-secret-name: longhorn-crypto
  csi.storage.k8s.io/node-stage-secret-namespace: apps
  csi.storage.k8s.io/provisioner-secret-name: longhorn-crypto
  csi.storage.k8s.io/provisioner-secret-namespace: apps
  encrypted: "true"
  fromBackup: ""
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
allowVolumeExpansion: true
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
```

Secret:
```
apiVersion: v1
data:
  CRYPTO_KEY_PROVIDER: c2VjcmV0
  CRYPTO_KEY_VALUE: <censored>
kind: Secret
metadata:
  name: longhorn-crypto
  namespace: apps
type: Opaque
```

When attempting to provision a new volume via that storage class, the output of the kubectl describe command is as follows:
```
MountVolume.MountDevice failed for volume "pvc-ec8f2ea3-4bb7-445d-bf99-fd8a0a76ddf4" : rpc error: code = Internal desc = failed to encrypt device /dev/longhorn/pvc-ec8f2ea3-4bb7-445d-bf99-fd8a0a76ddf4 with LUKS: failed to execute: /usr/bin/nsenter [nsenter --mount=/host/proc/247942/ns/mnt --ipc=/host/proc/247942/ns/ipc cryptsetup -q luksFormat --type luks2 --cipher aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/longhorn/pvc-ec8f2ea3-4bb7-445d-bf99-fd8a0a76ddf4 -d /dev/stdin], output , stderr Failed to open key file.
```

Should further information be necessary, including potentially from system logs, please do not hesitate to inform me.
Thank you

**Comment by smira** [comment]
I don't quite know what the issue is - from the looks of it, it seems to be a bug in Longhorn. 

Like `--mount=/host/proc/247942/ns/mnt` - what is the PID? It's not PID1, so not sure which mount namespace it even tries to enter? Does it execute host cryptsetup or its own?

The message says 'Failed to open key file', while the key file should be `-d /dev/stdin` ? The docs on cryptsetup say it should be `-d -`.

I can easily reproduce this from a privileged pod:

```
/ # nsenter -t 1 -m cryptsetup  -q luksFormat --type luks2 --cipher aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/loop1 -d /dev/stdin
Failed to open key file.
/ # nsenter -t 1 -m cryptsetup  -q luksFormat --type luks2 --cipher aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/loop1 -d -
Enter passphrase for /fff:
/ #
```

You can see that `-d /dev/stdin` doesn't work at all. 

See [cryptsetup man](https://man7.org/linux/man-pages/man8/cryptsetup-luksFormat.8.html), search for `--key-file`.

So there's not much we can do on Talos side.

**Comment by smira** [comment]
> Longhorn uses -d /dev/stdin because -d - requires interactive input. If you run the following command directly for testing, it should fail due to the missing piped input into /dev/stdin:

This is not true. The proper way is to follow cryptsetup documentation:

```
/ # echo "passphrase" | nsenter -t 1 -m cryptsetup  -q luksFormat --type luks2 --ciphe
r aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/loop1  -d /dev/std
in
Failed to open key file.
/ # echo -n "passphrase" | nsenter -t 1 -m cryptsetup  -q luksFormat --type luks2 --ciphe
r aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/loop1  -d -
/ # (successfully encrypted)
```

The `-d /dev/stdin` simply doesn't work.

**Comment by bartlaarhoven** [comment]
Great that the problem is solved now in Longhorn, should a similar issue be created at Rook/Ceph side?

**Comment by dedene** [comment]
> if i dont forget, I'll create an issue there in the next week

I'm running into this issue as well, but using encrypted ceph volumes using ceph-csi. @moo-im-a-cow did you already have a chance to create an issue in https://github.com/ceph/ceph-csi ? 🙏

**Comment by dedene** [comment]
> > Longhorn uses -d /dev/stdin because -d - requires interactive input. If you run the following command directly for testing, it should fail due to the missing piped input into /dev/stdin:
> 
> This is not true. The proper way is to follow cryptsetup documentation:
> 
> ```
> / # echo "passphrase" | nsenter -t 1 -m cryptsetup  -q luksFormat --type luks2 --ciphe
> r aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/loop1  -d /dev/std
> in
> Failed to open key file.
> / # echo -n "passphrase" | nsenter -t 1 -m cryptsetup  -q luksFormat --type luks2 --ciphe
> r aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/loop1  -d -
> / # (successfully encrypted)
> ```
> 
> The `-d /dev/stdin` simply doesn't work.

@smira just to better understand the issue: if nothing changed between Talos 1.8 and 1.9, any idea on why the encrypted volumes do work on 1.8 but not on 1.9?

**Comment by bartlaarhoven** [comment]
I tried creating the issue at Ceph-side; see https://github.com/ceph/ceph-csi/issues/5306

**Comment by bartlaarhoven** [comment]
PR was merged into ceph-csi `devel` branch and will be included in the next release (latest release is currently 3.14.0, so probably 3.14.1 or 3.15.0). 🥳 

For other Rook users, like me, that means:
 
1. Wait for the Ceph CSI release
2. Wait until Rook includes the new Ceph CSI release (Rook 1.17.0/1.17.1 contain 3.14.0)
3. Upgrade to that Rook release
4. Finally upgrading to a Talos release newer than 1.8.x

**Comment by ianatha** [comment]
Just in case it helps someone else, I did a (rather ugly) workaround for this issue with Longhorn. Applied a patch to Longhorn's Helm (which we manage via FluxCD) so that an initContainer patches `longhorn-csi-plugin` as to replace `-d /dev/stdin` with `-d -`. The patch  contains a checksum guard to ensure it only patches the known version.

```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
[...]
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: DaemonSet
              name: longhorn-csi-plugin
            patch: |-
              - op: add
                path: /spec/template/spec/volumes/-
                value:
                  - name: patched-nsmounter
                    emptyDir: {}
              - op: add
                path: /spec/template/spec/containers/name=longhorn-csi-plugin/volumeMounts/-
                value:
                  - name: patched-nsmounter
                    mountPath: /usr/local/sbin/nsmounter
                    subPath: nsmounter
              - op: add
                path: /spec/template/spec/initContainers/-
                value:
                  - name: patch-nsmounter
                    image: "longhornio/longhorn-manager:v1.8.1"
                    command: ["/bin/sh","-c"]
                    volumeMounts:
                      - name: patched-nsmounter
                        mountPath: /mnt/nsmounter
                    args:
                      - |
                        # copy original script into our shared volume
                        cp /usr/local/sbin/nsmounter /mnt/nsmounter/nsmounter

                        # only patch if the checksum matches
                        if [ "$(sha256sum /usr/local/sbin/nsmounter | cut -d' ' -f1)" = "dc2cc05398fcbe34768f2753f446ab1a3480d001e2022c4581d3201515835ffb" ]; then
                          sed -i '$i\
                          rewrite_args=()\
                          while [[ $# -gt 0 ]]; do\
                          if [[ $1 == "-d" && $2 == "/dev/stdin" ]]; then\
                            rewrite_args+=("-d" "-")\
                            shift 2\
                          else\
                            rewrite_args+=("$1")\
                            shift\
                          fi\
                          done\
                          set -- "${rewrite_args[@]}"' /mnt/nsmounter/nsmounter
                        fi

                        chmod +x /mnt/nsmounter/nsmounter
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: v1.8.1
[...]
```
