### ISSUE TITLE
Firewall set to allow everything, but still connections are broken after enabling it

### ISSUE THREAD

**Issue by kees-closed** [siderolabs/talos#10536]
## Bug Report

### Description
I've created a simple firewall config, for testing. But even that seems to break my Talos machines. The firewall setup below by default does not drop packets. I also added both TCP and UDP and the full port range possible. But when I push this config I see errors that port 123 and 53 cannot be reached on my router (which is also the default gateway), probably more things are not working, it's hard to read the logs since the font is too big on screen connected. But when I don't include this ingress firewall, everything works fine.

```yaml
---
apiVersion: v1alpha1
kind: NetworkDefaultActionConfig
ingress: accept # Default action for all not explicitly configured ingress traffic: accept or block.
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: k8s_control_plane-udp # Name of the config document.
# Port selector defines which ports and protocols on the host are affected by the rule.
portSelector:
    # Ports defines a list of port ranges or single ports.
    ports:
        - 1-65535
    protocol: udp # Protocol defines traffic protocol (e.g. TCP or UDP).
# Ingress defines which source subnets are allowed to access the host ports/protocols defined by the `portSelector`.
ingress:
    - subnet: 0.0.0.0/0 # Subnet defines a source subnet.
    - subnet: ::/0 # Subnet defines a source subnet.
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: data_control_plane-tcp # Name of the config document.
# Port selector defines which ports and protocols on the host are affected by the rule.
portSelector:
    # Ports defines a list of port ranges or single ports.
    ports:
        - 1-65535
    protocol: tcp # Protocol defines traffic protocol (e.g. TCP or UDP).
# Ingress defines which source subnets are allowed to access the host ports/protocols defined by the `portSelector`.
ingress:
    - subnet: 0.0.0.0/0 # Subnet defines a source subnet.
    - subnet: ::/0 # Subnet defines a source subnet.
```

The reason I have the above config, to allow everything, was because my intended config didn't seem to work. So to troubleshoot it better, I applied the above firewall that allowed everything. But even then things don't work anymore.

Below is the firewall I actually want to apply, but also doesn't work.

```yaml
---
apiVersion: v1alpha1
kind: NetworkDefaultActionConfig
ingress: block # Default action for all not explicitly configured ingress traffic: accept or block.
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: public # Name of the config document.
# Port selector defines which ports and protocols on the host are affected by the rule.
portSelector:
    # Ports defines a list of port ranges or single ports.
    ports:
        - 25
        - 80
        - 110
        - 143
        - 443
        - 465
        - 587
        - 993
        - 995
    protocol: tcp # Protocol defines traffic protocol (e.g. TCP or UDP).
# Ingress defines which source subnets are allowed to access the host ports/protocols defined by the `portSelector`.
ingress:
    - subnet: 172.27.10.0/24 # Subnet defines a source subnet.
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: k8s_control_plane-tcp # Name of the config document.
# Port selector defines which ports and protocols on the host are affected by the rule.
portSelector:
    # Ports defines a list of port ranges or single ports.
    ports:
        - 1024-65535
    protocol: tcp # Protocol defines traffic protocol (e.g. TCP or UDP).
# Ingress defines which source subnets are allowed to access the host ports/protocols defined by the `portSelector`.
ingress:
    - subnet: 172.27.11.0/24 # Subnet defines a source subnet.
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: k8s_control_plane-udp # Name of the config document.
# Port selector defines which ports and protocols on the host are affected by the rule.
portSelector:
    # Ports defines a list of port ranges or single ports.
    ports:
        - 1024-65535
    protocol: udp # Protocol defines traffic protocol (e.g. TCP or UDP).
# Ingress defines which source subnets are allowed to access the host ports/protocols defined by the `portSelector`.
ingress:
    - subnet: 172.27.11.0/24 # Subnet defines a source subnet.
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: data_control_plane-tcp # Name of the config document.
# Port selector defines which ports and protocols on the host are affected by the rule.
portSelector:
    # Ports defines a list of port ranges or single ports.
    ports:
        - 1024-65535
    protocol: tcp # Protocol defines traffic protocol (e.g. TCP or UDP).
# Ingress defines which source subnets are allowed to access the host ports/protocols defined by the `portSelector`.
ingress:
    - subnet: 172.27.13.0/24 # Subnet defines a source subnet.
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: data_control_plane-udp # Name of the config document.
# Port selector defines which ports and protocols on the host are affected by the rule.
portSelector:
    # Ports defines a list of port ranges or single ports.
    ports:
        - 1024-65535
    protocol: udp # Protocol defines traffic protocol (e.g. TCP or UDP).
# Ingress defines which source subnets are allowed to access the host ports/protocols defined by the `portSelector`.
ingress:
    - subnet: 172.27.13.0/24 # Subnet defines a source subnet.
```


### Logs
Because I cannot connect to the Talos API anymore when the firewall is enabled (even when it should allow everything) I cannot show specific logs.

The best what I can show is this, I pushed the config with `--mode try`. But this doesn't show any useful insights.

```sh
 user: warning: [2025-03-15T16:01:15.780283162Z]: [talos] apply config request: mode try                                                                                                                                                                                                                                                                                                     
 user: warning: [2025-03-15T16:01:15.806353162Z]: [talos] nftables chains updated {"component": "controller-runtime", "controller": "network.NfTablesChainController", "chains": ["ingress"]}                                                                                                                                                                                                
 user: warning: [2025-03-15T16:02:15.787149162Z]: [talos] rolling back the configuration                                                                                                                                                                                                                                                                                                     
 user: warning: [2025-03-15T16:02:15.821781162Z]: [talos] nftables chains updated {"component": "controller-runtime", "controller": "network.NfTablesChainController", "chains": []} 
```

### Environment

- Talos version: 1.9.5
- Kubernetes version: 1.32.3
- Platform: Raspberry Pi 4
