### ISSUE TITLE
Some workers becomes NotReady after 6-10 hours

### ISSUE THREAD

**Issue by xeor** [siderolabs/talos#10584]
### Description
I've have a couple of intel NUC's that I am installing Talos on. There is 1 master and 4 workers. 1 worker is pretty stable, but at least 2 of the other have a strange issue and after 6-10 hours, they become NotReady.

It looks like the kubelet is the problem. It is still running, but health-check is failing:

```sh
talosctl --nodes kw3 service kubelet
NODE                  kw3
ID                    kubelet
STATE                 Running
HEALTH                Fail
LAST HEALTH MESSAGE   Get "http://127.0.0.1:10248/healthz": context deadline exceeded
EVENTS                [Running]: Health check failed: Get "http://127.0.0.1:10248/healthz": context deadline exceeded (18h57m0s ago)
                      [Running]: Health check successful (21h34m5s ago)
                      [Running]: Started task kubelet (PID 2601) for container kubelet (21h34m7s ago)
                      [Preparing]: Creating service runner (21h34m7s ago)
                      [Preparing]: Running pre state (21h34m8s ago)
                      [Waiting]: Waiting for time sync (21h34m11s ago)
                      [Waiting]: Waiting for service "cri" to be "up", time sync, network (21h34m12s ago)
                      [Starting]: Starting service (21h34m12s ago)

talosctl -n kw3 get extensions
NODE   NAMESPACE   TYPE              ID            VERSION   NAME               VERSION
kw3    runtime     ExtensionStatus   0             1         i915               20250109-v1.9.4
kw3    runtime     ExtensionStatus   1             1         intel-ucode        20250211
kw3    runtime     ExtensionStatus   2             1         iscsi-tools        v0.1.6
kw3    runtime     ExtensionStatus   3             1         kata-containers    3.3.0
kw3    runtime     ExtensionStatus   4             1         mei                v1.9.4
kw3    runtime     ExtensionStatus   5             1         util-linux-tools   2.40.4
kw3    runtime     ExtensionStatus   6             1         schematic          083d1ff61d972160576ea5677699aff6cd85078f92982ed48b7bf2fb4f50d05a
kw3    runtime     ExtensionStatus   modules.dep   1         modules.dep        6.12.13-talos
```

### Config

```yaml
cluster:
    network:
        cni:
            # We are installing cilium instead
            name: none

    proxy:
        disabled: true

machine:
    # https://www.talos.dev/v1.9/reference/configuration/v1alpha1/config/#Config.machine.network
    network:
        nameservers:
            - 10.32.64.1

    install:
        # Should match the hash in pxe boot, see realms/s1/k8s/apps/netboot/netbootxyz/README.md
        # https://www.talos.dev/v1.9/talos-guides/configuration/system-extensions/
        image: factory.talos.dev/installer/083d1ff61d972160576ea5677699aff6cd85078f92982ed48b7bf2fb4f50d05a:v1.9.5

        extraKernelArgs:
            - talos.platform=metal
            - net.ifnames=0

        # https://www.talos.dev/v1.9/reference/configuration/v1alpha1/config/#Config.machine.install.diskSelector
        diskSelector:
            size: "> 64GB"

        wipe: true

    time:
        servers:
            - 0.no.pool.ntp.org
            - 1.no.pool.ntp.org
            - 2.no.pool.ntp.org
            - 3.no.pool.ntp.org

```

and

```yaml
machine:
    kubelet:
        # https://longhorn.io/docs/1.8.1/advanced-resources/os-distro-specific/talos-linux-support/#data-path-mounts
        extraMounts:
            - destination: /var/lib/longhorn
              type: bind
              source: /var/lib/longhorn
              options:
                  - bind
                  - rshared
                  - rw

    # https://longhorn.io/docs/1.8.1/advanced-resources/os-distro-specific/talos-linux-support/#v2-data-engine
    sysctls:
        vm.nr_hugepages: "1024"
    kernel:
        modules:
            - name: nvme_tcp
            - name: vfio_pci

```

### Logs

In support.zip

### Environment

- Talos version: v1.9.4 (but was a problem at 1.9.1+ as well)
- Kubernetes version: v1.32.1
- Platform: talos, cilium, longhorn

[support.zip](https://github.com/user-attachments/files/19411509/support.zip)
