### ISSUE TITLE
Inconsistent behaviour when configuring static IPv6 with SLAAC+RA enabled network

### ISSUE THREAD

**Issue by mhymny** [siderolabs/talos#10649]
### Description
I found that when I tried to disable autoconfiguration(help me if there's anything wrong, I tried many combinations)
```
    install:
        disk: /dev/sda
        wipe: true
        extraKernelArgs:
            - console=ttyS0,115200n8
            - talos.dashboard.disabled=1
            - net.ipv6.conf.default.autoconf=0
            - net.ipv6.conf.default.accept_ra=0

    sysctls:
        net.ipv6.conf.ens2.autoconf: "0"
        net.ipv6.conf.ens2.accept_ra: "0"
        net.ipv6.conf.ens6.autoconf: "0"
        net.ipv6.conf.ens6.accept_ra: "0"
```
and a static IPv6 configuration
```
            - interface: ens2
              dhcp: false
              addresses:
                  - 1234:1234:1234::2/64
              routes:
                  - network: ::/0
                    gateway: 1234:1234:1234::1
```
there seems to be some sort of race condition.
Sometimes everything works well and I only have my routes, then again after a reboot it seems like routes have been imported. I then get error complaining that the route I tried to add already exists.
### Logs
On good days, talos reports only `1234:1234:1234::2` as the ip
On bad days I get:
```
[1234:1234:1234::2 1234:1234:1234:0:4321:ff:4321:4321]
...
controller failed {"component": "controller-runtime", "controller": "network.RouteSpecController", "error": "1 error occurred:\n\t* error adding route: netlink receive: file exists, message {Family:10 DstLength:0 SrcLength:0 Tos:0 Table:0 Protocol:4 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:1234:1234:1234::1 OutIface:8 Priority:1024 Table:254 Mark:0 Pref:<nil> Expires:<nil> Metrics:<nil> Multipath:[]}}\n\n"}
```
### Environment

- Talos version: 1.9.2
- Platform:
