### ISSUE TITLE
Machine config's registries ignored

### ISSUE THREAD

**Issue by gelato** [siderolabs/talos#10647]
### Description
Registries configuration changed - now all my specified machine config registries are ignored. On hosts new _backup folder emerged with my previous configs. New configs consist of such configuration:

```
talosctl cat -n 192.168.108.238 /etc/cri/conf.d/hosts/docker.io/hosts.toml

server = 'https://registry-1.docker.io'

[host.'http://192.168.108.238:29999']
capabilities = ['pull', 'resolve']

[host.'http://192.168.108.238:30021']
capabilities = ['pull', 'resolve']%
```

Old ones:

```
[vanholder:~]$ talosctl cat -n 192.168.108.238 /etc/cri/conf.d/hosts/_backup/docker.io/hosts.toml
[host]
  [host.'https://harbor.casa/v2/local-dreg']
    capabilities = ['pull', 'resolve']
    override_path = true
    skip_verify = true
```

Part of my machine config:

```
registries:
    mirrors:
      docker.io:
        endpoints:
          - https://harbor.casa/v2/local-dreg
        overridePath: true
      gcr.io:
        endpoints:
          - https://harbor.casa/v2/local-gcr
        overridePath: true
      ghcr.io:
        endpoints:
          - https://harbor.casa/v2/local-github
        overridePath: true
      hub.docker.com:
        endpoints:
          - https://harbor.casa/v2/local-dhub
        overridePath: true
      quay.io:
        endpoints:
          - https://harbor.casa/v2/local-quay
        overridePath: true
      registry.k8s.io:
        endpoints:
          - https://harbor.casa/v2/local-k8s
        overridePath: true
    config:
      harbor.casa:
        tls:
          insecureSkipVerify: true
```

I really do not understand how that happened.

### Logs

None

### Environment

- Talos version: 
```
Client:
	Tag:         v1.9.4
	SHA:         c863a561
	Built:
	Go version:  go1.23.6
	OS/Arch:     darwin/arm64
Server:
	NODE:        192.168.108.238
	Tag:         v1.9.4
	SHA:         c863a561
	Built:
	Go version:  go1.23.6
	OS/Arch:     linux/amd64
	Enabled:     RBAC
```
- Kubernetes version:

```
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.32.3
```

- Platform: baremetal
