### ISSUE TITLE
Internal load balancer to few control planes on worker servers

### ISSUE THREAD

**Issue by plansten** [siderolabs/talos#10656]
## Feature Request
Internal load balancer (nginx) to few control planes on worker servers
### Description
For example, like in kubespray.
So that it is also possible to add a worker node with the Talos OS to a cluster that was configured using kubespray.
Example:
```
cluster:
    id: <...> # Globally unique identifier for this cluster (base64 encoded random 32 bytes).
    secret: <...> # Shared secret of cluster (base64 encoded random 32 bytes).
    # Provides control plane specific configuration options.
    controlPlane:
        endpoint: https://172.31.33.1:6443 - this
        endpoints: ["https://172.31.33.1:6443", "https://172.31.33.2:6443"] - replace to
    clusterName: dev # Configures the cluster's name.
    # Provides cluster specific network configuration options.
    network:
        dnsDomain: cluster.local # The domain used by Kubernetes DNS.
        # The pod subnet CIDR.
        podSubnets:
            - 10.233.64.0/18
        # The service subnet CIDR.
        serviceSubnets:
            - 10.233.0.0/18
```
