### ISSUE TITLE
Allow custom configuration for system volumes (e.g. ETCD)

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#10678]
### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version`]
- Platform:

**Comment by SoulKyu** [comment]
What you have in mind with "configuration for system volumes" is something like this ? : 

```
apiVersion: v1alpha1
kind: VolumeConfig
name: ETCD
provisioning:
  diskSelector:
    match: disk.transport == 'nvme'
  minSize: 2GB
  maxSize: 40GB
  grow: false
```

Does EPHEMERAL part of system storage ? In my point of view, system storage is everything in VolumeConfig regarding the documentation.

So having a way to configure more deeply partition that are handled by VolumeConfig would be amazing, such has, container data, logs, etc...

I would love to help contributing on this, but don't know what you exactly have in mind
