### ISSUE TITLE
Network/link failure with Talos 1.9 and systemd-udev

### ISSUE THREAD

**Issue by askedrelic** [siderolabs/talos#10751]
## Bug Report
When installing Talos 1.9.5 on bare-metal machine, the network only partially comes online and prevents install of Talos; the Talos install image fails to download due to network timeout. The same Talos config will successfully install with 1.8.4. I'm assuming this is due to the systemd-udev changes.

`{"msg":"2025/04/17 22:25:59.508100 level=info msg=fetch failed error=failed to do request: Head \"https://factory.talos.dev/v2/installer/562d094853f6544b86a90de00827ae1eebaf25ca374b3db212458f98895ee041/manifests/v1.9.5\": net/http: TLS handshake timeout host=factory.talos.dev image=factory.talos.dev/installer/562d094853f6544b86a90de00827ae1eebaf25ca374b3db212458f98895ee041:v1.9.5","talos-level":"info","talos-service":"machined","talos-time":"2025-04-17T22:25:59.508127521Z"}`

### Description
I'm installing Talos on a datacenter Dell Nvidia DGX H100 system, with multiple network devices (previously https://github.com/siderolabs/talos/issues/9701 ). From a working Ubuntu 22 install, I download a Talos Factory image, overwrite the existing Ubuntu install disk using dd, then reboot to Talos maintenance mode, and then `talosctl apply-config` to finish the install. I don't have physical access to the system and primary debug via the kernel/talos json logs.

I'm trying to upgrade our install process now for Talos 1.9 and can't get the install to complete. It's also strange, that the network does partially come online and send TCP logs, but other requests fail. Any advice on how to debug this or what systemd-udev is doing differently would be appreciated.

### Logs

Talos 1.9.5 factory schema:
https://factory.talos.dev/image/5c959848398b1df6a0e585fd3a411007804fba32f9d91729e21f926a89eebe08/v1.9.5/metal-amd64.iso
```
customization:
    extraKernelArgs:
      - talos.platform=metal
      - talos.halt_if_installed=0
      - ip=10.15.17.1::10.15.17.6:255.255.255.0:test-hosename:enp157s0f0np0:off:8.8.8.8:8.8.4.4
    systemExtensions:
        officialExtensions:
        - siderolabs/nvidia-container-toolkit-production
        - siderolabs/nonfree-kmod-nvidia-production
        - siderolabs/nvidia-fabricmanager-production
```

Machine link info, from maintenance mode. There are 6 primary interfaces, enp157s0f0np0 is the actual connected interface that I target
```
talosctl -n 10.15.17.1 get links -i
        NODE   NAMESPACE   TYPE         ID              VERSION   TYPE         KIND     HW ADDR                                                       OPER STATE   LINK STATE
               network     LinkStatus   bond0           1         ether        bond     9e:8f:d5:d5:59:0a                                             down         false
               network     LinkStatus   dummy0          1         ether        dummy    22:b3:6b:bf:4c:db                                             down         false
               network     LinkStatus   eno8303         1         ether                 c4:cb:e1:ab:65:92                                             down         false
               network     LinkStatus   eno8403         1         ether                 c4:cb:e1:ab:65:93                                             down         false
               network     LinkStatus   enp157s0f0np0   1         ether                 94:6d:ae:c2:9b:58                                             down         true
               network     LinkStatus   enp157s0f1np1   1         ether                 94:6d:ae:c2:9b:59                                             down         false
               network     LinkStatus   enp27s0f0np0    1         ether                 94:6d:ae:c2:9b:78                                             down         false
               network     LinkStatus   enp27s0f1np1    1         ether                 94:6d:ae:c2:9b:79                                             down         false
               network     LinkStatus   ibp26s0         1         infiniband   ipoib    00:00:00:a5:fe:80:00:00:00:00:00:00:a0:88:c2:03:00:04:15:08   down         false
               network     LinkStatus   ip6tnl0         1         tunnel6      ip6tnl   00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00               down         false
               network     LinkStatus   lo              1         loopback              00:00:00:00:00:00                                             down         false
               network     LinkStatus   sit0            1         sit          sit      00:00:00:00                                                   down         false
               network     LinkStatus   teql0           1         void                                                                                down         false
               network     LinkStatus   tunl0           1         ipip         ipip     00:00:00:00                                                   down         false
```

Route info, from maintenance mode.
```
   talosctl -n 10.15.17.1 get routes -i
        NODE   NAMESPACE   TYPE          ID                                                           VERSION   DESTINATION                     GATEWAY      LINK            METRIC
               network     RouteStatus   enp157s0f0np0/inet6//fe80::/64/256                           1         fe80::/64                                    enp157s0f0np0   256
               network     RouteStatus   inet4//10.15.17.0/24/0                                       1         10.15.17.0/24                                enp157s0f0np0   0
               network     RouteStatus   inet4/10.15.17.6//1024                                       1                                         10.15.17.6   enp157s0f0np0   1024
               network     RouteStatus   local/enp157s0f0np0/inet6//fe80::/128/0                      1         fe80::/128                                   enp157s0f0np0   0
               network     RouteStatus   local/enp157s0f0np0/inet6//fe80::966d:aeff:fec2:9b58/128/0   1         fe80::966d:aeff:fec2:9b58/128                enp157s0f0np0   0
               network     RouteStatus   local/enp157s0f0np0/inet6//ff00::/8/256                      1         ff00::/8                                     enp157s0f0np0   256
               network     RouteStatus   local/inet4//10.15.17.1/32/0                                 1         10.15.17.1/32                                enp157s0f0np0   0
               network     RouteStatus   local/inet4//10.15.17.255/32/0                               1         10.15.17.255/32                              enp157s0f0np0   0
               network     RouteStatus   local/inet4//127.0.0.0/8/0                                   1         127.0.0.0/8                                  lo              0
               network     RouteStatus   local/inet4//127.0.0.1/32/0                                  1         127.0.0.1/32                                 lo              0
               network     RouteStatus   local/inet4//127.255.255.255/32/0                            1         127.255.255.255/32                           lo              0
               network     RouteStatus   local/lo/inet6//::1/128/0                                    1         ::1/128                                      lo              0
```

For the Talos config, here is the primary machine network config with 6 interfaces from above. I match on the mac addr and specifically disable the 5 interfaces that aren't enabled. I've tried many combinations here; under Talos 1.8 I don't need to define all of these and it just works, but as part of the debug, I've been configuring all the interfaces available.
```
machine:
  logging:
    destinations:
      - endpoint: "tcp://xxx"
        format: "json_lines"

  certSANs:
    - "xxxx-node-public-ip"
    - "10.15.47.97"

  network:
    nameservers:
      - 8.8.8.8
      - 1.1.1.1
    interfaces:
      - deviceSelector:
          hardwareAddr: "94:6d:ae:c2:a9:a0"
        addresses:
          - "10.15.47.97/29"
          - "xxxx-node-public-ip/32"
          
        routes:
          - network: 0.0.0.0/0
            gateway: "10.15.47.102"
            metric: 1024
        mtu: 1500
        dhcp: false
      - deviceSelector:
          hardwareAddr: "94:6d:ae:c2:c9:40"
        ignore: true
      - deviceSelector:
          hardwareAddr: "94:6d:ae:c2:c9:41"
        ignore: true
      - deviceSelector:
          hardwareAddr: "94:6d:ae:c2:a9:a1"
        ignore: true
      - deviceSelector:
          hardwareAddr: "c4:cb:e1:ab:57:6c"
        dhcp: false
        mtu: 1500
      - deviceSelector:
          hardwareAddr: "c4:cb:e1:ab:57:6d"
        dhcp: false
        mtu: 1500
        ignore: true
```

Initial boot logs here: https://gist.github.com/askedrelic/72f0c7a371caa2ff845d95ec91a9e4db

### Environment

- Talos version: 1.9.5
- Kubernetes version: 1.30.3, worker node
- Platform: bare metal
