### ISSUE TITLE
Unable to download NFSD kernel module from factory

### ISSUE THREAD

**Issue by krn-robin** [siderolabs/talos#10761]
## Bug Report

Unable to download NFSD kernel module from factory

### Description

All combinations of trying to download the nfsd kernel module fail in an “internal server error”.

### Steps to recreate:

```yaml
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/nfsd
```

Trying to download the ISO results in an `internal server error`. 

### Environment

- Talos version: 1.10.0-beta0
