### ISSUE TITLE
Unable to boot Talos with dummy interface only: node IP not selected

### ISSUE THREAD

**Issue by mi-bauer** [siderolabs/talos#10808]
I am trying to boot Talos without a physical network connection. (The reason this is needed for my use case is described [here](https://github.com/siderolabs/talos/discussions/10794#discussioncomment-12945951).)

To support this, I configured a dummy interface to provide a static IP, as Talos requires a valid Node IP for Kubernetes to spawn workloads. My configuration looks like this:

```yaml
kubelet:
  image: ghcr.io/siderolabs/kubelet:v1.31.2
  defaultRuntimeSeccompProfileEnabled: true
  disableManifestsDirectory: true
  nodeIP:
    validSubnets:
      - 10.2.0.10/32
network:
  kubespan:
    enabled: false
  interfaces:
    - interface: dummy0
      dummy: true
      addresses:
        - "10.2.0.10/24"
      routes:
        - network: 10.2.0.0/24
          metric: 1024
    - interface: enx4251c45e1b57
      mtu: 1500
      dhcp: true
time:
  disabled: true
  servers:
    - time.cloudflare.com
  bootTimeout: "0m30s"
```

### Problem

I expect the IP from the `dummy0` interface (`10.2.0.10`) to be selected as the Node IP.

However, when booting without a physical network connection, the boot process gets stuck, and I see this log message:
```
# no-ethernet.log
[    6.072987] [talos] no suitable node IP found, please make sure .machine.kubelet.nodeIP filters and pod/service subnets are set up correctly {"component": "controller-runtime", "controller": "k8s.NodeIPController"}
```
Full logs: [no-ethernet.log](https://github.com/user-attachments/files/19908265/no-ethernet.log)

If I boot with a physical connection to a router, Talos picks the IP from the Ethernet interface, not from the dummy interface. Logs in this case show:
```
# with-router.log
[   17.100210] [talos] node IP skipped, please use .machine.kubelet.nodeIP to provide explicit subnet for the node IP {"component": "controller-runtime", "controller": "k8s.NodeIPController", "address": "10.2.0.10"}
```
Full logs: [with-router.log](https://github.com/user-attachments/files/19908269/with-router.log)

Note that `.machine.kubelet.nodeIP` was explicitly configured, as shown above.

### Impact

This issue prevents using Talos in environments where a physical network connection is not available.

### Environment

- Talos version: 1.8.2
- Kubernetes version: v1.31.2
- Platform: arm64
