### ISSUE TITLE
local storage documentation - label update required

### ISSUE THREAD

**Issue by russalex** [siderolabs/talos#10817]
### Description

[kustomization.yaml](https://www.talos.dev/v1.9/kubernetes-guides/configuration/local-storage/) provided by the local-storage documentation needs a few more labels.  As documented the label is:
```
- patch: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: local-path-storage
      labels:
        pod-security.kubernetes.io/enforce: privileged
```
When running I get the error shown below. Fixed the issue by adding a few more labels (don't know if all these are required, but it's what I added to get local-path-storage working):
```
    metadata:
      name: local-path-storage
      labels:
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
        pod-security.kubernetes.io/warn: privileged
```

### Error
Using the [kustomization.yaml](https://www.talos.dev/v1.9/kubernetes-guides/configuration/local-storage/) provided
Command:  `kustomize build | kubectl apply -f -`

Output:
```
namespace/local-path-storage created
storageclass.storage.k8s.io/local-path created
serviceaccount/local-path-provisioner-service-account created
role.rbac.authorization.k8s.io/local-path-provisioner-role created
clusterrole.rbac.authorization.k8s.io/local-path-provisioner-role created
rolebinding.rbac.authorization.k8s.io/local-path-provisioner-bind created
clusterrolebinding.rbac.authorization.k8s.io/local-path-provisioner-bind created
configmap/local-path-config created
Warning: would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "local-path-provisioner" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "local-path-provisioner" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "local-path-provisioner" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "local-path-provisioner" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
deployment.apps/local-path-provisioner created

```
### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
```
Client:
        Tag:         v1.9.5
        SHA:         d07f6daa
        Built:
        Go version:  go1.23.7
        OS/Arch:     windows/amd64
Server:
        NODE:        192.168.100.103
        Tag:         v1.9.5
        SHA:         d07f6daa
        Built:
        Go version:  go1.23.7
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```
- Kubernetes version: [`kubectl version`]
```
Client Version: v1.33.0
Kustomize Version: v5.6.0
Server Version: v1.32.3
```
- Platform:  TalosOS running on Proxmox
