### ISSUE TITLE
nocloud platform: bug: buffer overrun: namespace "runtime" type "VolumeMountRequests.block.talos.dev" on talos v1.10

### ISSUE THREAD

**Issue by hegerdes** [siderolabs/talos#10845]
## Bug Report
On a newly created node, talos v1.10 can run into an issue regarding `VolumeMountRequests` and will not successfully boot.

### Description
On a newly created node, talos v1.10 can run into an issue in which it states:
```
[talos] controller runtime goroutine error: fatal controller runtime error: controller runtime watch error: buffer overrun: namespace "runtime" type "VolumeMountRequests.block.talos.dev"
```
After this it only prints warnings regarding service `apid, kubelet, cri` to be up. Seems like the `apid` services does not start, since I can not get a connection to the node. The same issue was reported in this discussion: https://github.com/siderolabs/talos/discussions/10591#discussioncomment-12605260

The issue does only seem to happen sporadically. About 1 out of 10 machines. A reboot typically fixes the error. Error might be caused by a race condition. Error happend on arm64 and amd64.

The talos conf I provided below was assembled by the talos terraform provider v0.7.x.

### Logs
```
[talos] controller runtime goroutine error: fatal controller runtime error: controller runtime watch error: buffer overrun: namespace "runtime" type "VolumeMountRequests.block.talos.dev"
```
That's all I have...

### Environment
Hetzner Cloud

Note:  Node 10.0.1.8 is okay, node 10.0.2.8 is the one crashing
```
Client:
        Tag:         v1.10.0
        SHA:         e6bd8304
        Built:
        Go version:  go1.24.2
        OS/Arch:     windows/amd64
Server:
WARNING: 1 error occurred:
        * 10.0.2.8: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 10.0.2.8:50000: i/o timeout"
        NODE:        10.0.1.8
        Tag:         v1.10.0
        SHA:         e6bd8304
        Built:
        Go version:  go1.24.2
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```

- Talos version: 1.10.0
- Kubernetes version: 1.33.0
- Platform: armd64 & arm64

<details>
<summary>Machine Conf</summary>

```yaml
version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token: xxx
    ca:
        crt: xxx
        key: xxx
    certSANs: [deleted]
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.33.0
        extraArgs:
            cloud-provider: external
            rotate-server-certificates: "true"
        extraMounts:
            - destination: /var/openebs/local
              type: bind
              source: /var/openebs/local
              options:
                - rbind
                - rshared
                - rw
        extraConfig:
            failSwapOn: true
            featureGates:
                UserNamespacesPodSecurityStandards: true
                UserNamespacesSupport: true
            maxParallelImagePulls: 8
            maxPods: 220
            nodeStatusMaxImages: 100
            readOnlyPort: 0
            serializeImagePulls: false
            serverTLSBootstrap: true
        defaultRuntimeSeccompProfileEnabled: true
        nodeIP:
            validSubnets:
                - 10.0.0.0/16
                - 2000::/3
        disableManifestsDirectory: true
    network:
        nameservers:
            - 1.1.1.1
            - 1.0.0.1
            - 2606:4700:4700::1111
            - 2606:4700:4700::1001
        extraHostEntries:
            - ip: 10.0.0.10
              aliases: [deleted]
        kubespan:
            enabled: true
    install:
        disk: /dev/sda
        image: ghcr.io/siderolabs/installer:v1.9.2
        wipe: false
    sysctls:
        kernel.pid_max: "4194304"
        kernel.randomize_va_space: "2"
        net.ipv4.icmp_echo_ignore_broadcasts: "1"
        net.ipv4.icmp_ignore_bogus_error_responses: "1"
        net.ipv4.ip_local_port_range: 10240 65535
        net.ipv4.tcp_fastopen: "1"
        net.ipv4.tcp_rfc1337: "1"
        net.ipv4.tcp_syncookies: "1"
        user.max_user_namespaces: "15000"
        vm.nr_hugepages: "1024"
        vm.overcommit_memory: "1"
    features:
        rbac: true
        stableHostname: true
        kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
                - os:reader
                - os:etcd:backup
            allowedKubernetesNamespaces:
                - kube-system
                - cluster-autoscaler
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
            resolveMemberNames: true
    nodeLabels:
        openebs.io/engine: mayastor
        pool: talos-controlplane-amd64
```

</details>
