### ISSUE TITLE
Error: failed to probe bootloader on upgrade: file does not exist

### ISSUE THREAD

**Issue by mattdmoore** [siderolabs/talos#10859]
### Description

Trying to upgrade my Turing RK1 from 1.10.0-beta.0 to 1.10.0 fails with `Error: failed to probe bootloader on upgrade: file does not exist.` 

Image used: 
```
overlay:
    image: siderolabs/sbc-rockchip
    name: turingrk1
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/panfrost
            - siderolabs/util-linux-tools
```

### Logs

```
 user: warning: [2025-05-01T13:12:50.810075878Z]: 2025/05/01 13:12:51 running pre-flight checks
 user: warning: [2025-05-01T13:12:50.816972878Z]: 2025/05/01 13:12:51 host Talos version: v1.10.0-beta.0
 user: warning: [2025-05-01T13:12:50.829655878Z]: 2025/05/01 13:12:51 host Kubernetes versions: kubelet: 1.32.0, kube-
 apiserver: 1.32.0, kube-scheduler: 1.32.0, kube-controller-manager: 1.32.0
 user: warning: [2025-05-01T13:12:50.845149878Z]: 2025/05/01 13:12:51 all pre-flight checks successful
 kern:    info: [2025-05-01T13:12:50.848318878Z]:  mmcblk0: p1 p2 p3 p4
 user: warning: [2025-05-01T13:12:50.851887878Z]: Error: failed to probe bootloader on upgrade: file does not exist
 user: warning: [2025-05-01T13:12:50.863568878Z]: Usage:
 user: warning: [2025-05-01T13:12:50.865817878Z]:   installer install [flags]
```
[support.zip](https://github.com/user-attachments/files/20000178/support.zip)

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
  Client:
          Tag:         v1.9.5
          SHA:         undefined
          Built:
          Go version:  go1.24.1
          OS/Arch:     linux/amd64
  Server:
          NODE:        stubb
          Tag:         v1.10.0-beta.0
          SHA:         92dbf198
          Built:
          Go version:  go1.24.2
          OS/Arch:     linux/arm64
          Enabled:     RBAC
- Kubernetes version: [`kubectl version`]
  Client Version: v1.32.3
  Kustomize Version: v5.5.0
  Server Version: v1.32.0
- Platform: Turing RK1

**Comment by frezbo** [comment]
would upgrading to beta.1 work?

**Comment by mattdmoore** [comment]
@frezbo Just gave it a shot but no luck, exact same error trying to go from beta.0 to beta.1

**Comment by frezbo** [comment]
could you attach a support.zip and also `talosctl get securitystate -o yaml`

**Comment by frezbo** [comment]
I wonder if you had an alpha.3 version before and did an upgrade, which had some bugs

**Comment by mattdmoore** [comment]
I already flashed this node with the 1.10 image just to make sure it'd work, but I have a second node still on 1.10-beta.0 that I can leave like that for testing purposes

- Do you want a new support.zip? I already tucked one away in the bug report above, not sure if you missed it or need a fresh one
- I never upgraded from an alpha version, I flashed all the nodes directly from a 1.10-beta.0 image (previously was running on 1.9.5)

Securitystate:
```
node: stubb
metadata:
    namespace: runtime
    type: SecurityStates.talos.dev
    id: securitystate
    version: 1
    owner: runtime.SecurityStateController
    phase: running
    created: 1970-01-01T00:00:08Z
    updated: 1970-01-01T00:00:08Z
spec:
    secureBoot: false
    selinuxState: enabled, permissive
    bootedWithUKI: true
```
