### ISSUE TITLE
EthernetConfig not being applied

### ISSUE THREAD

**Issue by georgeboot** [siderolabs/talos#10851]
### Description
I have added the following to my machineconfig:
```yaml
apiVersion: v1alpha1
kind: EthernetConfig
name: ens25f0np0
features:
    rx-gro: true
    tx-scatter-gather: true
rings:
    rx: 8160
    tx: 8160
    rx-buf-len: 4096
    tx-push: true
channels:
    combined: 1
```

I've applied the machineconfig, and `talosctl -n xxx get machineconfig -o yaml` shows the config.

However, running `talosctl -n xxx get ethernetstatus ens25f0np0 -o yaml` shows the original settings.

Debugging via `kubectl debug -n kube-system -it --image alpine node/xxx` and then `ethtool -g ens25f0np0` confirms the ring parameters have not been updated.

### Logs
```
user: warning: [2025-05-01T09:36:08.290118512Z]: [talos] controller failed {"component": "controller-runtime", "controller": "network.EthernetSpecController", "error": "failed to reconcile Ethernet specs: error configuring \"ens25f0np0\": error updating      
 rings: netlink receive: operation not supported, offset: 64, message: \"setting rx buf len not supported\""}
```

### Environment

- Talos version: v1.10.0
- Kubernetes version: v1.32.3
