### ISSUE TITLE
Can't disable dhcp address configuration on bond0 with config

### ISSUE THREAD

**Issue by grebokra** [siderolabs/talos#10882]
### Description
I'm running Talos in *static* QEMU virtual machines. Each VM has dual network interfaces that are implemented with Mellanox SR-IOV virtual functions and need to be configured as a bond in order to allow traffic to pass through them (dc network requirement).
I have created virtual machine image using factory with a custom kernel cmdline so that the newly created Talos virtual machines can aquire tmp address via dhcp and be accessible over network so I can apply configuration to them:
```
bond=bond0:eth0,eth1:mode=balance-xor:1500 ip=:::::bond0:dhcp net.ifnames=0
```
This works without an issue and nodes are accessible via tmp dhcp addresses.
In configuration for each node I have static address configured on the bond and a `dhcp: false` parameter.

Unfortunately bond0 interface contunues to have dhcp configured after config is applied (This is unexpected, because i specify `dhcp: false` in config)

Here is the typical config-patch for talos node:
```
---
machine:
  network:
    hostname: node54.talos.testing.internal
    interfaces:
    - addresses:
      - 192.168.0.54/24
      bond:
        interfaces:
        - eth0
        - eth1
        lpInterval: 1
        miimon: 100
        mode: balance-xor
        updelay: 10000
        xmitHashPolicy: layer3+4
      dhcp: false
      interface: bond0
      mtu: 9170
      routes:
      - gateway: 192.168.0.1
        network: 0.0.0.0/0
    nameservers:
    - 192.168.0.1
    - 192.168.0.2
  time:
    servers:
    - /dev/ptp0
```

Can you please give me some advice on how to address the issue I've encountered? Is it possible to completely disable DHCP configuration via config?

I suspect this behaviour to be a bug, but I may be doing something wrong, so some help would be greatly appreciated.

### Logs
-

### Environment
- Talos version: v1.9.5
- Kubernetes version: -
- Platform: libvirt + qemu
