### ISSUE TITLE
[1.10.0] etcd won't start after upgrade due to SELinux disabled

### ISSUE THREAD

**Issue by mtb-xt** [siderolabs/talos#10881]
### Description

Metal platform, old Fujitsu Primergy TX120 S3P server. 

After upgrading from 1.9.5 to 1.10.0 (which was slightly botched due to TPM issue #10847) - I disabled the TPM to finish upgrading, and the node started, but **etcd** won't start, saying that the SElinux label is specified, but it's disabled or not supported.

### Logs

```
172.21.100.8: user: warning: [2025-05-03T09:29:43.026356962Z]: [talos] service[etcd](Waiting): Error running Containerd(etcd), going to restart forever: failed to create task: "etcd": failed to create shim task: OCI runtime create failed: runc create failed: selinux label is specified in config, but selinux is disabled or not supported
172.21.100.8: user: warning: [2025-05-03T09:29:48.057332962Z]: [talos] service[etcd](Waiting): Error running Containerd(etcd), going to restart forever: failed to create task: "etcd": failed to create shim task: OCI runtime create failed: runc create failed: selinux label is specified in config, but selinux is disabled or not supported
```

### Environment

- Talos version: v1.10.0
- Kubernetes version: v1.31.4
- Platform: metal

![Image](https://github.com/user-attachments/assets/6b62c354-ba35-4106-adc3-65fcba6d956c)

**Comment by mtb-xt** [comment]
Well, I got it working by applying this to my machineconfig (thanks, ChatGPT!), but still:

```
machine:
  baseRuntimeSpecOverrides:
    linux:
      selinux: null
```

**Comment by dsseng** [comment]
Have you disabled SELinux (e.g. to enable AppArmor) via kernel cmdline parameters? Could you please run `talosctl get securitystate` against this node?

This seems rather weird, because even if SELinux was to be disabled we check for that when configuring containerd options

**Comment by mtb-xt** [comment]
@dsseng I haven't touched SElinux via kernel cmdline parameters, but I do set IP address initially via them, like this (if it matters):

```
# Your image schematic ID is: 982aa2f8ffcf4a2efe8db98d27fe627791803f2f041ca06a76693a4a45743b13 
customization:
    extraKernelArgs:
        - bond=bond0:enp0s25,enp3s0:mode=802.3ad,miimon=100,updelay=200,downdelay=200,xmit_hash_policy=layer2+3
        - 'ip=172.21.100.8::172.21.100.254:255.255.255.0:off:bond0::1.1.1.1:8.8.8.8:'
```

The machine was running happily with 1.9.5.

`talosctl get securitystate`:

```
❯ talosctl -n 172.21.100.8  get securitystate 
NODE           NAMESPACE   TYPE            ID              VERSION   SECUREBOOT   UKISIGNINGKEYFINGERPRINT   PCRSIGNINGKEYFINGERPRINT   SELINUXSTATE
172.21.100.8   runtime     SecurityState   securitystate   1         false                                                              enabled, permissive

hwr-microcluster/talos on  main [✘!?] 
❯ talosctl -n 172.21.100.8  get securitystate  -o yaml
node: 172.21.100.8
metadata:
    namespace: runtime
    type: SecurityStates.talos.dev
    id: securitystate
    version: 1
    owner: runtime.SecurityStateController
    phase: running
    created: 2025-05-03T09:55:25Z
    updated: 2025-05-03T09:55:25Z
spec:
    secureBoot: false
    selinuxState: enabled, permissive
```


Happy to provide the support bundle too, but is it secure to post it online? Should I send it somewhere instead?

**Comment by frezbo** [comment]
so to confirm the machine was on 1.9.5 with the schematic id `982aa2f8ffcf4a2efe8db98d27fe627791803f2f041ca06a76693a4a45743b13` and was upgraded, right?

**Comment by dsseng** [comment]
>     selinuxState: enabled, permissive

Okay, so SELinux is enabled, however containerd fails as if SELinux were disabled but still requested. Rather weird.

Could you please post a support bundle here (it should not contain any sensitive data, unless you consider local node IPs like 172.21.100.8 to be confidential)

**Comment by mtb-xt** [comment]
> so to confirm the machine was on 1.9.5 with the schematic id `982aa2f8ffcf4a2efe8db98d27fe627791803f2f041ca06a76693a4a45743b13` and was upgraded, right?
correct.

@dsseng okay got it, here's the bundle 

[support.zip](https://github.com/user-attachments/files/20054705/support.zip)

**Comment by dsseng** [comment]
> > so to confirm the machine was on 1.9.5 with the schematic id `982aa2f8ffcf4a2efe8db98d27fe627791803f2f041ca06a76693a4a45743b13` and was upgraded, right?
> 
> yes, that's correct.
> 
> [@dsseng](https://github.com/dsseng) okay got it, here's the bundle
> 
> [support.zip](https://github.com/user-attachments/files/20054705/support.zip)

etcd seems to have started normally here, are you sure this is the support bundle from the failed boot?

**Comment by mtb-xt** [comment]
I don't have any other nodes to try, my other machine like this is a worker. sorry

**Comment by frezbo** [comment]
Could you also do a `talosctl read /proc/cmdline`

**Comment by mtb-xt** [comment]
> Could you also do a `talosctl read /proc/cmdline`

❯ talosctl -e 172.21.100.8  -n 172.23.100.10    read /proc/cmdline
talos.platform=metal talos.config=none console=tty0 console=ttyS0 init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 printk.devkmsg=on ima_template=ima-ng ima_appraise=fix ima_hash=sha512 selinux=1

**Comment by frezbo** [comment]
Could you try dropping `talos.config=none` seems weird, (needs an upgrade to drop it)

**Comment by mtb-xt** [comment]
> Could you try dropping `talos.config=none` seems weird, (needs an upgrade to drop it)

sorry, but how do I drop it? I didn't edit anything in kernel parameters in the image factory

**Comment by frezbo** [comment]
> > Could you try dropping `talos.config=none` seems weird, (needs an upgrade to drop it)
> 
> sorry, but how do I drop it? I didn't edit anything in kernel parameters in the image factory

okay, thought that was added additionally, ignore

**Comment by mtb-xt** [comment]
> > > Could you try dropping `talos.config=none` seems weird, (needs an upgrade to drop it)
> > 
> > 
> > sorry, but how do I drop it? I didn't edit anything in kernel parameters in the image factory
> 
> okay, thought that was added additionally, ignore

For reference, this is the schematic for this machine:

```
❯ cat schematics/regulus.yaml 
---
#Your image schematic ID is: 9eb31ae525fdc7eacaa73ef773a872ab68a1c581b2014972ef82579d6381ce83
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/drbd
            - siderolabs/intel-ucode
            - siderolabs/iscsi-tools
            - siderolabs/mdadm
            - siderolabs/tailscale
```
