### ISSUE TITLE
ETCD encryption configuration

### ISSUE THREAD

**Issue by oliverbaehler** [siderolabs/talos#10899]
## Feature Request

Hi, I was playing around with etcd encryption and Talos, or rather trying to embed a kmsv2 provider to encrypt all `secrets` and `configmaps` at REST. However i have noticed, that currently it's only possible to pass one key to the template here: https://github.com/siderolabs/talos/blob/main/internal/app/machined/pkg/controllers/k8s/templates/kube-system-encryption-config-template.yaml

If I understood correctly, it's also not possible to overwrite that file. This causes some problems with ETCD encryptions:

- no other resources than `secrets` can be encrypted
- key rotation is not possible
- other kms than static keys on the controlplanes are not possible.

I was wondering if we could improve this by either:
- Being able to supply a custom-path to a user-defined encryption-configuration
- Having the Encryption-Config inline [as with the AuditPolicy](https://www.talos.dev/v1.3/introduction/what-is-new/#kube-apiserver-custom-audit-policy)

Wondering what your thoughts are about this. I can probably contribute the feature, if we agree on an implementation.

**Comment by smira** [comment]
I think customizing encryption configuration would be a great additional feature!

**Comment by frezbo** [comment]
ETCD specific machine config document would be great

**Comment by oliverbaehler** [comment]
@frezbo Just for clarification, i would propose something like this:

```yaml
cluster:
    apiServer:
        encryptionProviderConfig:
            apiVersion: apiserver.config.k8s.io/v1
            kind: EncryptionConfiguration
            resources:
              - resources:
                  - secrets
                  - configmaps
                providers:
                  - aescbc:
                      keys:
                        - name: key1
                          secret: "${ETCD_ENCRYPTION_KEY_1}"
                        - name: key2
                          secret: "${ETCD_ENCRYPTION_KEY_2}"
```

I would place it under `cluster.apiServer.encryptionProviderConfig` because it should always be the same for all the cps. From the kubernetes-docs:

> For cluster configurations with two or more control plane nodes, the encryption configuration should be identical across each control plane node. If there is a difference in the encryption provider configuration between control plane nodes, this difference may mean that the kube-apiserver can't decrypt data.

If that's alright I will try to get back with a PR soon. 🍀
