### ISSUE TITLE
Option to wipe user volume/disk at installation time

### ISSUE THREAD

**Issue by originaltrini0** [siderolabs/talos#10917]
## Feature Request
I suggest adding the attribute `provisioning.deviceSelector.wipe` to a UserVolumeConfig document.

### Description
If one wants to use a UserVolumeConfig document against a disk with existing partitions, it results in a volume in a failed state:
```
talosctl -n 192.168.108.41 -e 192.168.108.41 get volumestatus u-data -o yaml
node: 192.168.108.41
metadata:
    namespace: runtime
    type: VolumeStatuses.block.talos.dev
    id: u-data
    version: 1
    owner: block.VolumeManagerController
    phase: running
    created: 2025-05-03T10:32:14Z
    updated: 2025-05-03T10:32:14Z
    labels:
        talos.dev/user-volume:
spec:
    phase: failed
    type: partition
    mountSpec:
        targetPath: data
        selinuxLabel: system_u:object_r:ephemeral_t:s0
        projectQuotaSupport: false
        parentId: /var/mnt
        fileMode: 493
    errorMessage: 'error creating partition: error allocating partition: partition size must be greater than sector size'   
```

The goal is to provide an option similar to `machine.install.wipe` that wipes a disk at installation time.

More info can be found at:
https://taloscommunity.slack.com/archives/CMARMBC4E/p1746545905207229

Thanks
