### ISSUE TITLE
Flannel extra args not auto propagated to daemonset

### ISSUE THREAD

**Issue by Xnyle** [siderolabs/talos#10923]
## Bug Report

Flannel extra args not auto propagated to pods, pods not being restarted.

### Description

Changed and applied machineconfig with

```
cluster:
  network:
    cni:
      name: flannel
      flannel:
        extraArgs:
          - --iface=wgX
```

This does not change the existing daemonset and therefore has no effect.
Manually changing the daemonset does what I want.
Not sure if/where is this a bug and if maybe later on talos will overwrite the daemonset again without the flags.

### Environment

- Talos version: 1.10.0
- Kubernetes version: 1.32.0
- Platform: bare metal
