### ISSUE TITLE
ApiServer extraArgs do not seem to get propagated (AuthorizeNodeWithSelectors)

### ISSUE THREAD

**Issue by Xnyle** [siderolabs/talos#10924]
## Bug Report

https://www.talos.dev/v1.10/talos-guides/discovery/ states that in order for k8s registry to work AuthorizeNodeWithSelectors has to be disabled
Adding a feature gate on apiServer in machineconfig and applying that does not seem to make a difference.

talosctl get members / identities / affiliates still only lists own node.
All nodes additionally have been restarted after applying.
K8s communication is working though.

### Description

This is the applied config snippet

```
cluster:
  apiServer:
    extraArgs:
      # needed for k8s talos registry to work (changed with k8s 1.32 to default true)
      feature-gates: AuthorizeNodeWithSelectors=false 
```

### Question

How do I get apiserver logs? apiserver Is not a valid target for services?

### Additonal Info

I would use external reg if that didn't have its own "vendor lock in / license feature gate"

### Environment

- Talos version: 1.10.0
- Kubernetes version: 1.32
- Platform: bare metal
