### ISSUE TITLE
Network Config: `HostnameCoinfg`

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#10952]
### Hostname

```yaml
version: v1alpha1
kind: HostnameConfig
auto: stable # provide stable hostname based on machine identity
static: my-hostname # mutually exclusive with `auto`
```

Fields:

- `auto`: specifies automatic hostname assignment, might be either `off` or `stable`. If `off` is specified, Talos doesn’t assign a hostname at all, and the hostname should come either via DHCP, or platform metadata. If `stable` is used, it is equivalent to specifying `features: stableHostname` (hostname is generated based on unique machine identity, e.g. `talos-2xf-ab4`).
- `static`: set a static hostname as specified, a hostname `worker` or a FQDN [`worker.example.org`](http://worker.example.org) can be specified.

**Replaces** `machine.network.hostname`, `machine.features.stableHostname` (conflicts)
