### ISSUE TITLE
Network Config:  `ExtraHostConfig`

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#10953]
### Static Hosts

```yaml
version: v1alpha1
kind: StaticHostConfig
name: 10.3.4.5 # IPv4 or IPv6, unique
hostnames:
  - my-server1
  - my-server1.example.org
```

This literally renders to `/etc/hosts`.

**Replaces** `machine.network.extraHostEntries` (can be merged with)
