### ISSUE TITLE
Network Config: `LinkAliasConfig`

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#10956]
### Link Aliasing

Link aliasing is optional, Talos provides predictable interface names by default, and these can be used directly.

There are two main reasons for link aliasing:

- interface name is not known, but some properties are known, e.g. the MAC address or the driver
- renaming links to have logical names, e.g. `int0` and `ext0` to distinguish private/public links

As soon as the link was aliased, its alias can be used interchangeably with the primary name in any of the configuration documents.

Only a single link should match for the alias to be in place.

```yaml
version: v1alpha1
kind: LinkAliasConfig
name: int0 # alias name
match:
  selector: link.hardware_addr.startswith("01:02:03:ee:") && link.physical
```

- `name` specific the alias to be created
- `match.selector` specifies a CEL expression (similar to disk match) to select a link, the details of the expression are TBD at the moment; selector only matches physical links, i.e. it never matches VLANs, bonds, etc.

> [!NOTE]  
> Link aliasing should get better support in general, e.g. showing link aliases in `get links`, `get addresses`, etc.
It should be nice, easy and intuitive to use link aliases.
