### ISSUE TITLE
Network Config: `LinkConfig`

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#10957]
### Link Configuration

```yaml
version: v1alpha1
kind: LinkConfig
name: en0sp2 # either primary name or an alias
mtu: 1500 # optional
up: true # defaults to true, can be brought down with `false`
addresses:
  - 10.3.5.1/24
  - 20a1:fe1d::1/64
routes:
  - destination: 10.3.4.0/24 # route destination, if not set defaults to * (default gateway)
    gateway: 10.3.4.1 # if not set, creates "on-link" route
    source: 10.3.5.1 # optional
    metric: 1024 # optional, defaults to 1024
    mtu: 1500 # optional, defaults to unset
    table: main # optional, defaults to main
```

This configures basic settings for the link, including static addressing.

- `name` name of the link (or alias); `LinkConfig` never creates links, it only applies to already existing links
- `mtu` overrides link MTU
- `up` defaults to `true` (if the `LinkConfig` document is present), can be used to force link down with `false`
- `addresses` is a list of static addresses assigned to the link
- `routes` block configures static routes, almost identical to existing `v1alpha1.Config`

**Replaces** `machine.network.interfaces.{addresses,routes,up,mtu}` and other nested configuration.

It should be machine configuration validation error to have a `LinkConfig` and `BondConfig`, `VLANConfig` , `BridgeConfig` for the same link name.
