### ISSUE TITLE
Network Config: `ResolverConfig`

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#10954]
### Resolvers

```yaml
version: v1alpha1
kind: ResolverConfig
resolvers:
  - address: 1.1.1.1
    protocol: DNS # default
  - address: 8.8.8.8
    hostname: dns.google
    protocol: DoT # DNS over TLS
searchDomains:
  disableDefault: false # default value
  extra: # optional
    - example.org
```

> [!WARNING]  
> We don’t have DNS over TLS implemented yet

- `resolvers` is a list of DNS resolvers to use, `protocol` can be omitted, in that case only `address` should be specified (DNS over TLS is mentioned here for completeness only, see https://github.com/siderolabs/talos/issues/9999)
- `searchDomains` configures search domains in `/etc/resolv.conf`, they don’t affect DNS resolution, but affect client resolver inside a program, this section is optional
    - `disableDefault` disables default extraction of the domain of the hostname (if specified as FQDN)
    - `extra` specifies a list of additional entries to add to search domains

**Replaces** `machine.network.nameservers`, `machine.network.searchDomains` , `machine.network.disableSearchDomain`
