### ISSUE TITLE
Network Config: `TimeSyncConfig`

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#10955]
### Time Sync

```yaml
version: v1alpha1
kind: TimeSyncConfig
enabled: true # default value, set to false to disable
bootTimeout: 2m # unset means no boot timeout
ntp: # mutually exclusive with ptp
  servers:
    - time.cloudflare.com
ptp: # mutually exclusive with ntp
  devices:
    - /dev/ptp0
```

> [!WARNING]  
> Time sync config might go to its own namespace `time`, but documented here as it’s still closely related to network, and it’s critical for initial boot.

- `enabled` defaults to `true`, can be disabled e.g. to run your own NTP server
- `bootTimeout` is used to not to block the boot forever if the time can’t be synced, after specified time is assumed to be in sync despite no sync being done
- `ntp` and `ptp` specify either network or local ways to sync the time.

**Replaces** `machine.time` (conflicts)
