### ISSUE TITLE
Network Config: Virtual IPs

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#10959]
### Virtual IP

There are several kinds of Virtual IPs:

- layer 2 (assumes all machines are on the same layer 2 network)
- specific implementations for floating IPs:
    - HCloud (Hetzner Cloud)
    - Equinix Metal

```yaml
version: v1alpha1
kind: Layer2VIPConfig
name: 10.3.4.5 # the VIP itself
link: en0sp2
```

```yaml
version: v1alpha1
kind: HCloudVIPConfig
name: 10.3.4.5 # the floating IP
link: en0sp2
deviceID: ...
networkID: ...
apiToken: ... # documentation TBD, copy from existing
```

> [!CAUTION]
> Let's skip Equinix Metal VIP, as EM is shutting down.

```yaml
version: v1alpha1
kind: EquinixMetalConfig
name: 10.3.4.5 # the floating IP
link: en0sp2
projectID: ...
deviceID: ...
apiToken: ...
```
