### ISSUE TITLE
Network Config: `WireguardConfig`

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#10963]
### Wireguard

```yaml
version: v1alpha1
kind: WireguardConfig
name: wg0 # Wireguard link name
privateKey: ABCDEF... # a private key (base64 encoded).
listenPort: 3000 # optional
firewallMark: 16 # optional, fw mark
peers:
    - publicKey: ABCDEF... # Public key of the peer (base64 encoded).
      endpoint: 192.168.1.2:51822 # peer endpoint, optional
      persistentKeepaliveInterval: 10s # Specifies the persistent keepalive interval for this peer.
      allowedIPs:
        - 192.168.1.0/24
# embedded from LinkConfig, optional
mtu: 1500
up: true
addresses: [...]
routes: [...]
```
