### ISSUE TITLE
Network Config: `BondConfig`

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#10960]
### Bonds

Bond configuration document creates and configures the bond, it also embeds `LinkConfig` fields.

```yaml
version: v1alpha1
kind: BondConfig
name: bond0 # name of the link
links: # links which are bonded, NB: order is important
  - int0
  - int1
settings: # Note: more settings follow, see existing configuration
  mode: 802.3ad
  lacpRate: fast
  ...
# embedded from LinkConfig, optional
mtu: 1500
up: true
addresses: [...]
routes: [...]
```

`BondConfig` conflicts with `VLANConfig`, `BridgeConfig`, `WireguardConfig` and `LinkConfig` with the same `name`.
