### ISSUE TITLE
Network Config: `VLANConfig`

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#10961]
### VLANs

VLAN configuration document creates and configures the VLAN, it also embeds `LinkConfig` fields.

```yaml
version: v1alpha1
kind: VLANConfig
name: en0sp2.17 # VLAN link name
parent: en0sp2 # parent link
vlanID: 17
vlanMode: 802.1q # also 802.1ad available, defaults to 802.1q
# embedded from LinkConfig, optional
mtu: 1500
up: true
addresses: [...]
routes: [...]
```

`VLANConfig` conflicts with `BondConfig`, `BridgeConfig`, `WireguardConfig` and `LinkConfig` with the same `name`.
