### ISSUE TITLE
Support virtiofs within Talos

### ISSUE THREAD

**Issue by Skaronator** [siderolabs/talos#10974]
## Feature Request

I'd love to have the option to use virtiofs with Talos. This would allow a simple setup where the host can easily pass files to the Talos VM.

This feature was already requested in #5318, but was automatically closed by stale bot.

### Description

Official docs: https://virtio-fs.gitlab.io

**Comment by nberlee** [comment]
I would like it as well, but there is a workaround:

I am using a staticpod in the talos machineconfig, this starts before any other kubernetes pod:
```
machine:
    pods:
        - apiVersion: v1
          kind: Pod
          metadata:
            name: media-mounter
            namespace: kube-system
          spec:
            containers:
                - command:
                    - sh
                    - -c
                    - |
                      mkdir -p /host/var/mnt/Data
                      mkdir -p /host/var/mnt/appcache
                      mount -N1 -t virtiofs Data /var/mnt/Data
                      mount -N1 -t virtiofs appcache /var/mnt/appcache
                  image: debian:bookworm-slim
                  name: mounter
                  securityContext:
                    privileged: true
                  volumeMounts:
                    - mountPath: /host
                      name: host-root
            hostNetwork: true
            hostPID: true
            restartPolicy: Never
            volumes:
                - hostPath:
                    path: /
                  name: host-root
```

**Comment by smira** [comment]
Please see https://github.com/siderolabs/talos/issues/10995 - does it address the need?

**Comment by Skaronator** [comment]
I think for virtiofs we need virtiofsd within the Talos in order to work with a generic mount, but that could be provided by an extension.

**Comment by nberlee** [comment]
virtiofsd is the serverside, this is proxmox, or in my case unraid. So unless you are trying to share something local to talos, you are unlikely to need virtiofsd.

**Comment by nberlee** [comment]
No need for anything extra, the workaround has been  working for me for a long time in Talos with virtiofs. So yes, #10995 should address this

**Comment by Skaronator** [comment]
Alrighty, thanks for clarifying!

**Comment by divStar** [comment]
@nberlee thank you for the workaround! So basically you pass the virtiofs mount args when e.g. creating a QEMU Talos VM (or multiple VMs if need be), then have the static pod, that basically mounts the folders in the guest (Talos VM) and makes it so you can use local storage providers (e.g. hostPath) for PVs/PVCs and perhaps even existing media, right?

If the mounted folder is a ZFS dataset, should I include and configure ZFS in Talos for this to work?

**Comment by nberlee** [comment]
>So basically you pass the virtiofs mount args when e.g. creating a QEMU Talos VM

@divStar this is the relevant domain xml from QEMU from the example above for your understanding . This exposes `Data` and `appcache` virtiofs shares to the Talos VM.

The `source dir` is the directory on the Host (unraid in my case)
```xml
<domain type='kvm'>
  ...
  <devices>
  ...
    <filesystem type='mount' accessmode='passthrough'>
      <driver type='virtiofs' queue='1024'/>
      <binary path='/usr/libexec/virtiofsd' xattr='on'>
        <sandbox mode='chroot'/>
      </binary>
      <source dir='/mnt/user/Data'/>
      <target dir='Data'/>
      <address type='pci' domain='0x0000' bus='0x01' slot='0x00' function='0x0'/>
    </filesystem>
    <filesystem type='mount' accessmode='passthrough'>
      <driver type='virtiofs' queue='1024'/>
      <binary path='/usr/libexec/virtiofsd' xattr='on'>
       	<sandbox mode='chroot'/>
      </binary>
      <source dir='/mnt/cache/appcache'/>
      <target dir='appcache'/>
      <address type='pci' domain='0x0000' bus='0x02' slot='0x00' function='0x0'/>
    </filesystem>
```

> and makes it so you can use local storage provider (e.g. hostPath)

Yes, i am just using hostPath on that Talos VM guest. using `/var/mnt/Data/something` and `/var/mnt/appcache/something` 

> If the mounted folder is a ZFS dataset, should i include and configure ZFS in Talos for this to work?

No, much like a networkshare the client is unaware of the filesystem of the server and the underlayingf blockdevice on the server. So Talos is agnostic to ZFS in this case.

**Comment by divStar** [comment]
I'm sorry - just making sure: I still **do need** the static pod approach, because Talos doesn't know how to mount the passed through `virtiofs` data, but the Debian pod does, right?

So I do need to pass the args as you described in the newest comment AND add the static pod to actually mount the virtiofs blobs and thereby ultimately expose it to Talos, right?

Once I got it to work, I'll try to write a guide on this, because this is amazing from what I can tell (no networking, hopefully near native performance).

**Comment by divStar** [comment]
Thanks @nberlee ! I was finally able to first mount the `virtiofs` directory mappings and then use a static pod (albeit I used `alpine:latest` with just the `mount` package) to mount them into the host.

<details>
<summary>Final <a href="https://github.com/divStar/homelab/blob/master/modules/cluster-setup/modules/talos-create-vm/control_plane_patches/04-mount-virtiofs.yaml.tftpl"><code>04-mount-virtiofs.yaml.tftpl</code></a> file I used</summary>

```yaml
machine:
    pods:
        - apiVersion: v1
          kind: Pod
          metadata:
            name: media-mounter
            namespace: kube-system
          spec:
            containers:
                - command:
                    - sh
                    - -c
                    - |
                      exec > /host/var/log/alpine-staticpod.log 2>&1
                      echo "Update APK..."
                      apk update
                      echo "Install mount..."
                      apk add --no-cache mount
                      echo "Mounting virtiofs..."
                      # Iterate over all supplied virtiofs mappings and mount them to the host (`-N1`)
                      %{~ for vfs_mapping in vfs_mappings ~}
                      mkdir -p /host/var/mnt/${vfs_mapping}
                      mount -N1 -t virtiofs ${vfs_mapping} /var/mnt/${vfs_mapping}
                      %{~ endfor ~}
                  image: alpine:latest
                  name: mounter
                  securityContext:
                    privileged: true
                  volumeMounts:
                    - mountPath: /host
                      name: host-root
            hostNetwork: true
            hostPID: true
            restartPolicy: Never
            volumes:
                - hostPath:
                    path: /
                  name: host-root
```
</details>
