### ISSUE TITLE
inconsistencies validating routes in network configuration containing vlans

### ISSUE THREAD

**Issue by nicoonoclaste** [siderolabs/talos#10985]
## Bug Report

I am attempting to install a Talos cluster from scratch, on bare metal, where each node is connected to an access switch over a “trunk” port, i.e. exposing multiple tagged VLANs (and no untagged one).  During setup, only a single VLAN is configured: 802.1q id 32, IPv4 prefix 192.168.32/24

After `talosctl apply-config`, the machine installs Talos to disk, reboots, and the network does not come up.  Error messages are visible on the console, about failing to parse the network configuration.

### Description

Following the documentation, I do the following
- run `talosctl gen config --with-examples=false rkube https://192.168.32.80:6443`
- boot node off ISO image, adding the following to the kernel's cmdline:
```
vlan=enp1s0.32:enp1s0 ip=192.168.32.81::192.168.32.254:255.255.255.0:rkube-1:enp1s0.32:::::
```
- confirm the node is reachable over the network
- `talosctl apply-config --insecure -n 192.168.32.81 --file controlplane.yaml -p @rkube-1.yaml` with the following patch file
```yaml
machine:
  install:
    disk: /dev/nvme0n1

  network:
    hostname: rkube-1
    interfaces:
      - interface: enp1s0
        dhcp: false
        vlans:
          - vlanId: 32
            vip:
              ip: 192.168.32.80
            dhcp: false
            addresses:
              - 192.168.32.81/24
            routes:
              - network: 0/0
                gateway: 192.168.32.254
    nameservers:
      - 192.168.32.254
      - 9.9.9.9
      - 149.112.112.112  # quad9 fallback address
```

`talosctl` successfully parses the configuration, but the actual node-side code apparently does not; using the same kernel cmdline arguments as for the install medium, enables the node to bring up networking, at which point everything seems to work normally: authenticated access functions, and the cluster can be bootstrapped.

### Logs

Sorry, couldn't find out how to get the relevant logs out.

### Environment

- Talos version: `1.10.0` on client, `1.10.1` ISO image
- ~~Kubernetes version: [`kubectl version`]~~
- Platform: amd64
