### ISSUE TITLE
Talos Fails to Load Config in Private Subnet with "expected a mapping node" Error

### ISSUE THREAD

**Issue by yeshwanth1312** [siderolabs/talos#11019]
### Description
Talos fails to load the machine config when launching an EC2 instance in a private subnet, even though:

The same config works perfectly when launching in a public subnet.

`[talos] controller failed {"component": "controller-runtime", "controller": "config.AcquireController", "error": "failed to load config via platform aws: recovered: expected a mapping node"}`

- Confirmed the instance has internet access via NAT Gateway.
- Outbound rules allow all traffic (0.0.0.0/0).
- This exact config works fine in a public subnet, but consistently fails in a private one.
- Instance metadata service (IMDS) is reachable from inside the instance.

Any ideas on what might be causing this in a private subnet setup? Could there be a difference in how machine config is injected or fetched in this case?
Appreciate any guidance

### Logs
`[talos] controller failed {"component": "controller-runtime", "controller": "config.AcquireController", "error": "failed to load config via platform aws: recovered: expected a mapping node"}`

### Environment

Cloud Provider

AWS

**Comment by smira** [comment]
The error looks like invalid YAML is submitted in the AWS instance data.

**Comment by smira** [comment]
IMDS access doesn't depend on the firewall/NAT/etc.

**Comment by yeshwanth1312** [comment]
> The error looks like invalid YAML is submitted in the AWS instance data.

Thanks for the quick response. That makes sense regarding the YAML validation.

However, I’m still puzzled why the same instance data works fine when launching in a public subnet but fails in a private subnet. 

Would appreciate any insight into why this might behave differently between subnet types, even when the user data is identical.

**Comment by smira** [comment]
I would expect that the instance data is not a Talos machine configuration. If you have steps to reproduce, we can try and debug this, but so far it looks like wrong YAML.

**Comment by amadeuspzs** [comment]
I have the same error message when auto-scaling via Karpenter. The contents of userData (after base64 -d and manual redaction are)

```yaml
---
version: v1alpha1
debug: false
persist: true
machine:
  type: worker
  token: REDACTED
  ca:
    crt: REDACTED
    key: ""
  certSANs:
    - REDACTED.elb.eu-west-2.amazonaws.com
  kubelet:
    image: ghcr.io/siderolabs/kubelet:v1.33.1
    defaultRuntimeSeccompProfileEnabled: true
    disableManifestsDirectory: true
  network: {}
  install:
    disk: /dev/xvda
    image: ghcr.io/siderolabs/installer:v1.10.3
    wipe: false
  time:
    servers:
      - 169.254.169.123
  features:
    rbac: true
    stableHostname: true
    apidCheckExtKeyUsage: true
    diskQuotaSupport: true
    kubePrism:
      enabled: true
      port: 7445
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: true
cluster:
  id: REDACTED
  secret: REDACTED
  controlPlane:
    endpoint: https://REDACTED.elb.eu-west-2.amazonaws.com:6443
  clusterName: REDACTED
  network:
    cni:
      name: none
    dnsDomain: cluster.local
    podSubnets:
      - 10.244.0.0/16
    serviceSubnets:
      - 10.96.0.0/12
  token: REDACTED
  ca:
    crt: REDACTED
    key: ""
  proxy:
    disabled: true
  discovery:
    enabled: true
    registries:
      kubernetes:
        disabled: true
      service: {}
```

This works fine when deployed in a private_subnet via terraform `aws_instance.user_data`, so while I have the same error, it does not appear related to which subnet.

I am using a custom AMI generated using the following factory customization against `1.10.5`:

```yaml
---
customization:
  systemExtensions:
    officialExtensions:
      - siderolabs/intel-ucode
```
