### ISSUE TITLE
Feature: NVMe namespaces management

### ISSUE THREAD

**Issue by maxpain** [siderolabs/talos#11068]
## Feature Request
Add support for NVMe namespaces management via machineconfig

**Comment by ElXreno** [comment]
Still relevant.

**Comment by maxpain** [comment]
Still relevant.

**Comment by pranav767** [comment]
I'd love to work on this.

Plan:

1. Add nvme package to [go-blockdevice](https://github.com/siderolabs/go-blockdevice/tree/v2) Translate C structs from [linux/nvme_ioctl.h](https://github.com/linux-nvme/libnvme/blob/master/src/nvme/ioctl.h#L71) to Go matching C UAPI exactly, use `SYS_IOCTL` with computed ioctl numbers via kernel's `_IOWR` [macro](https://github.com/linux-nvme/nvme-snsd/blob/96a7f7e8d36505d7360f38c4cc65b6ae8df18737/src/snsd_nvme.h#L75C9-L75C29) (same pattern, but not as simple as `BLKPG_ADD_PARTITION` in [device_partitions_linux.go](https://github.com/siderolabs/go-blockdevice/blob/v2/block/device_partitions_linux.go)
{Might Have to check on certain permissions required here to perform operations}

      -  `nvme/ioctl.go` — Go structs matching kernel UAPI:
          -  `nvmePassthruCmd` (matches struct nvme_passthru_cmd)
          -  `nvmePassthruCmd64` (matches struct nvme_passthru_cmd64)
          -   Admin opcodes,NS management selectors, Identify CNS values
          -   Compute ioctl numbers: `NVME_IOCTL_ADMIN_CMD = iowr('N', 0x41, sizeof(nvmePassthruCmd))`
      -  `nvme/identify.go` — NVMe Identify commands:
          -  IdentifyController, IdentifyNamespace, ListActiveNamespaces.
      -  `nvme/namespace.go`  — Namespace management operations:
          -  CreateNamespace, DeleteNamespace, ResizeNamespace, AttachNamespace,DetachNamespace (using `NS_MGMT`, `NS_ATTACH`, `NS_DETACH`
      -  `nvme/controller.go` - List Controller, read model/serial/firmware/transport from sysfs

2. Create First class talos resources fro NVMe
    -  `NVMeControllers` ( DevicePath, Model, Serial, FirmwareRev, Transport, MaxNamespaces, NumberOfNamespaces), `NVMeNamespaces` (ControllerID, NSID, DevicePath, Size, EUI64, NGUID, UUID) , `NVMeNamespaceConfigs` (ControllerSelector (CEL expression), Namespaces)

3. Create Talos Controllers

   -  `NVMeControllerDiscoveryController` watches for controller add/remove events (Input: None, Output: NVMeController)
   - `NVMeNamespaceDiscoveryController` for each NVMeController enumerates namespaces. (Input: NVMeController, Output: NVMeNamespace)
   - `nvme_config.go` reconciles desired vs actual namespaces, reads  `NVMeNamespaceConfig` and compares with discovered `NVMeNamespace` resources i.e. calls create/delete/resize via `go-blockdevice` (Inputs: NVMeNamespaceConfig, NVMeController, NVMeNamespace, Output: NVMeNamespace)
   
4. Add Machine Config Support.

 -  Add `NVMENamespaceConfig` to machine config,
 -  `NVMENamespaceConfig` (Controllers  `[]NVMEControllerConfig`)
 -  `NVMEControllerConfig` (Selector, `Namespaces []NVMENamespaceEntry`)  
 -  `NVMENamespaceEntry`:  NSID , Size, Remove (bool)

**Config controller which converts machine config to `NVMeNamespaceConfig` resources**

Example Config:

```
nvme:
    controllers:
      # Select NVMe controllers by CEL expression
      - selector: 'nvme.transport == "pcie" && nvme.model.contains("Samsung")'
        namespaces:
          # Create 3 namespaces on matching controllers
          - size: 500GB
          - size: 500GB
          - size: 1TB
      
      # Another controller selection
      - selector: 'nvme.transport == "rdma"'
        namespaces:
          - size: 2TB
          - size: 1TB
          # Delete a specific namespace by NSID
          - nsid: 3
            remove: true
      
      # Auto-assign NSID (0 = let controller choose)
      - selector: 'nvme.serial == "ABC123DEF456"'
        namespaces:
          - size: 100GB  # NSID will be auto-assigned
          - nsid: 5
            size: 500GB  # Explicit NSID

```


5. Dashboard integration.

  -  Add `ScreenNVMENamespaces` constant
  -  Create `NewNVMENamespacesGrid` component showing controllers + namespaces in a table.
  -  Register in [dashboard.go](https://github.com/siderolabs/talos/blob/main/internal/pkg/dashboard/dashboard.go)

6. CLI support

  -  `talosctl get nvmecontrollers` — list NVMe controllers
  -  `talosctl get nvmenamespaces` — list NVMe namespaces
  -  `talosctl get nvmenamespaceconfigs` — list namespace configs


Tests: Add Unit tests for go-blockdevice, Integration tests for controllers,  add e2e tests.


AFAIK, NVMe is currently only recognized as a disk and there is no concept of namespaces yet in talos, and don't know if we need to be carefull on other talos disk/block storages in talos while implementing this such as potential conflicts.


Let me know how you feel about the above plan/ we need more discussion on this.
