### ISSUE TITLE
Talos in Promox fails with "error running phase 2" and "no system disk found"

### ISSUE THREAD

**Issue by seilerre** [siderolabs/talos#11097]
## Bug Report

We are looking to move from K3s to Talos. However I can't get Talos to install. I followed the Proxmox guide at https://www.talos.dev/v1.10/talos-guides/install/virtualized-platforms/proxmox/

Disks
```sh
talosctl get disks --endpoints 172.19.10.20 -n 172.19.10.20 --insecure
NODE   NAMESPACE   TYPE   ID      VERSION   SIZE     READ ONLY   TRANSPORT   ROTATIONAL   WWID   MODEL           SERIAL
       runtime     Disk   loop0   2         4.1 kB   true
       runtime     Disk   loop1   2         79 MB    true
       runtime     Disk   sda     2         34 GB    false       virtio      true                QEMU HARDDISK
       runtime     Disk   sr0     2         320 MB   false       ata                             QEMU DVD-ROM
```

```yaml
talosctl get disk sda --endpoints 172.19.10.20 -n 172.19.10.20 --insecure -oyaml
node:
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: sda
    version: 2
    owner: block.DisksController
    phase: running
    created: 2025-05-26T08:06:06Z
    updated: 2025-05-26T08:06:17Z
spec:
    dev_path: /dev/sda
    size: 34359738368
    pretty_size: 34 GB
    io_size: 512
    sector_size: 512
    readonly: false
    cdrom: false
    model: QEMU HARDDISK
    modalias: scsi:t-0x00
    bus_path: /pci0000:00/0000:00:05.0/0000:01:01.0/virtio2/host2/target2:0:0/2:0:0:0
    sub_system: /sys/class/block
    transport: virtio
    rotational: true
    symlinks:
        - /dev/disk/by-diskseq/13
        - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0
        - /dev/disk/by-path/pci-0000:01:01.0-scsi-0:0:0:0
```

controlplane.yaml

```yaml
    install:
        disk: /dev/sda # The disk used for installations.
        image: ghcr.io/siderolabs/installer:v1.10.0 # Allows for supplying the image used to perform the installation.
        wipe: true # Indicates if the installation disk should be wiped at installation time.
```

before Apply:

<img width="1021" alt="Image" src="https://github.com/user-attachments/assets/b399208b-8771-4363-b20c-ebdfb3807457" />

after apply:

<img width="1019" alt="Image" src="https://github.com/user-attachments/assets/04fb2331-7a28-49b4-ac4f-94024f15c7c0" />

Then

<img width="1024" alt="Image" src="https://github.com/user-attachments/assets/f960c3b6-c60d-4617-8f88-680f14aa7abc" />

Talos proceeds to reboot, showing the following:

<img width="1032" alt="Image" src="https://github.com/user-attachments/assets/f1080d7f-6ecd-4764-97ea-293a5cb6e504" />

### Environment

- Talos version: 1.10.0
- Kubernetes version: 1.33
- Platform: Proxmox
