### ISSUE TITLE
x509 errors after upgrade/reset to 1.10.2

### ISSUE THREAD

**Issue by soulwhisper** [siderolabs/talos#11099]
### Description
original image is v1.10.1, after upgrade to v1.10.2. I reset cluster with `talosctl reset --system-labels-to-wipe STATE --system-labels-to-wipe EPHEMERAL --graceful=false --wait=false --reboot`.

when applying clusterconfig and bootstrap, errors popup:

```shell
error executing bootstrap: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate is valid for exarch-02, exarch-02.homelab.internal, k8s.homelab.internal, talos, talos.default, not 172.19.82.101:50000,172.19.82.102:50000,172.19.82.103:50000"
```
If I change endpoint to `k8s.homelab.internal` in talosconfig, all good then.

There is no vip configs in my talosconfig, only certSans "[k8s.homelab.internal,127.0.0.1]", kube-prism is enabled.
I tried to remove all certSans, same results.

**Comment by soulwhisper** [comment]
I create a fresh new `v1.10.1` cluster with exactly the same config (certSANs, no vip, endpoints are IPs). All good.

**Comment by soulwhisper** [comment]
I need to clarify. Do you mean talosconfig like below is incorrect? This config report x509 errors above. If it is wrong, how do I set multiple IPs as endpoints.
```yaml
context: main
contexts:
    main:
        endpoints:
            - 172.19.82.101
            - 172.19.82.102
            - 172.19.82.103
        nodes:
            - 172.19.82.101
            - 172.19.82.102
            - 172.19.82.103
       ca: <reducted>
       crt: <reducted>
       key: <reducted>
```
