### ISSUE TITLE
UserVolumeConfig cannot find mdadm devices

### ISSUE THREAD

**Issue by DavidIlie** [siderolabs/talos#11098]
## Bug Report

I've defined a UserVolumeConfig by both accessing the symlink ID and also the dev/md127 path, and it errors out that it cannot be found.

### Description

```yaml
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: mdadm-raid-storage
provisioning:
  diskSelector:
    match: disk.dev_path == "/dev/md127"
  minSize: 2.5GiB
filesystem:
  type: ext4
```

It's weird how I have to set minSize when the volume is 1.9TB already, so I am not sure what to put here

```yaml
---
node: 192.168.100.180
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: md127
    version: 2
    owner: block.DisksController
    phase: running
    created: 2025-05-25T14:01:44Z
    updated: 2025-05-25T14:01:44Z
spec:
    dev_path: /dev/md127
    size: 1920123011072
    pretty_size: 1.9 TB
    io_size: 1048576
    sector_size: 512
    readonly: false
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
    secondary_disks:
        - sda
        - sdb
    symlinks:
        - /dev/disk/by-id/md-name-analytics:raid0
        - /dev/disk/by-id/md-uuid-84cea633:2d661ed8:2cd6ec11:cd0a534e
        - /dev/disk/by-uuid/4280f60a-aeb9-41d4-bd7d-ce0a3f8255d4
```

### Logs

``` user: warning: [2025-05-25T14:30:21.945186478Z]: [talos] volume status {"component": "controller-runtime", "controller": "block.VolumeManagerController", "volume": "u-mdadm-raid-storage",
 "phase": "failed -> failed", "error": "no disks matched for volume"}
 user: warning: [2025-05-25T14:30:21.952968478Z]: [talos] volume status {"component": "controller-runtime", "controller": "block.VolumeManagerController", "volume": "u-mdadm-raid-storage",
 "phase": "failed -> failed", "error": "no disks matched for volume"}```

### Environment

- Talos version:
```Client:
	Tag:         v1.9.3
	SHA:         d40df438
	Built:
	Go version:  go1.23.5
	OS/Arch:     darwin/arm64
Server:
	NODE:        192.168.100.180
	Tag:         v1.10.2
	SHA:         1cf5914b
	Built:
	Go version:  go1.24.3
	OS/Arch:     linux/amd64
	Enabled:     RBAC```
- Kubernetes version: v1.33.1
- Platform: macOS
