### ISSUE TITLE
support enabling projectQuotaSupport for user volumes

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#11090]
### Discussed in https://github.com/siderolabs/talos/discussions/11081

<div type='discussions-op-text'>

<sup>Originally posted by **n-asenov** May 23, 2025</sup>
I have created a user volume with the following config 
```yaml
machine:
    features:
      diskQuotaSupport: true
```

```yaml
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: openebs
provisioning:
    diskSelector:
        match: disk.transport == 'virtio' && !system_disk
    grow: true
    minSize: 64GB
```
but then the volume has projectQuotaSupport set to false

```yaml
---
node: 192.168.0.30
metadata:
    namespace: runtime
    type: VolumeStatuses.block.talos.dev
    id: u-openebs
    version: 3
    owner: block.VolumeManagerController
    phase: running
    created: 2025-05-22T20:18:23Z
    updated: 2025-05-22T20:18:24Z
    labels:
        talos.dev/user-volume:
    finalizers:
        - block.MountController
spec:
    phase: ready
    type: partition
    location: /dev/sdb1
    mountLocation: /dev/sdb1
    partitionIndex: 1
    parentLocation: /dev/sdb
    partitionUUID: fabae336-a9ce-4fd7-9839-aaff0b0490c0
    size: 68717379584
    prettySize: 69 GB
    filesystem: xfs
    mountSpec:
        targetPath: openebs
        selinuxLabel: system_u:object_r:ephemeral_t:s0
        projectQuotaSupport: false
        parentId: /var/mnt
        fileMode: 493
```

Is it possible to set projectQuotaSupport to true?</div>
