### ISSUE TITLE
bring back support for .machine.install.extraKernelArgs

### ISSUE THREAD

**Issue by abckey** [siderolabs/talos#11145]
## Feature Request

Talos v1.10 comes with breaking changes in uefi installation with new UKI, it ignores `.machine.install.extraKernelArgs`, where we used to inject node specific kernel arguments during installation/upgrade.

Injecting node specific kernel arguments is a must for our deployment, generating per node image is a no-go considering the number of nodes we are dealing with.

So we ask to bring back support for `.machine.install.extraKernelArgs`

### Description

With systemd-boot and UKI, I assume this can be achieved by adding `.machine.install.extraKernelArgs` as a loader entry.

ref: https://wiki.archlinux.org/title/Systemd-boot#Adding_loaders

If woud be great if the support could be backported to v1.10.

**Comment by frezbo** [comment]
This will not work with Secureboot, loader.conf kernel arguments will be ignored

**Comment by abckey** [comment]
> This will not work with Secureboot, loader.conf kernel arguments will be ignored

yep, I understand that. We are not using secureboot anyway

**Comment by smira** [comment]
I don't think we want to create `.machine.install.extraKernelArgs` back as it was very confusing mechanism. The only way I can imagine this going forward is to add an option to force to use GRUB bootloader even if installing on 1.10. Then you get your old behavior, but you lose all the benefits of new boot scheme, but that's what you're looking for?

Basically it's equivalent to upgrade from 1.9 to 1.10 when GRUB would be still used.

**Comment by varet80** [comment]
In the case for instance, I need to change the amd_pstate. how can I achieve that with the new way?

**Comment by smira** [comment]
> In the case for instance, I need to change the amd_pstate. how can I achieve that with the new way?

Basically, you would use Image Factory all the way like you might be already doing for other reasons.

**Comment by vlada-dudr** [comment]
It might be interesting to somehow build in factory url generator. So instead of specifying the installer image one could write down all the options needed and correct image hash would be generated. It would be also useful to expect mirroring registries.

So something like (it's just idea, without any proper structure):
```yaml
installer:
  extensions: [zfs]
  platform: metal
  kernelArgs: []
  registry: mirror.corp.example.com
  version: 1.10.3
```
Would be identical to specifying installer image `mirror.corp.example.com/metal-installer/4dd8e3a8b6203d3c14f049da8db4d3bb0d6d3e70c5e89dfcc1e709e81914f63c:v1.10.3`

**Comment by smira** [comment]
Image Factory has API https://github.com/siderolabs/image-factory/#http-frontend-api

Talos itself is not bound to the Image Factory (and doesn't have to), you can make all of this possible outside of Talos.

**Comment by Nomsplease** [comment]
> > In the case for instance, I need to change the amd_pstate. how can I achieve that with the new way?
> 
> Basically, you would use Image Factory all the way like you might be already doing for other reasons.

@smira the factory site states that the kernel arguments provided only work for the boot image and not for the install images. The site also still says to use the kernelargs field.

```
Please note that kernel command line customization is only accepted for the initial boot images (ISO, PXE, disk image) and is ignored for installer images. For upgrade/install command line customization, use the machine.install.extraKernelArgs machine configuration field.
```

What is the proposed solution to add kernel args back into the kernels to achieve this same functionality, or was this functionality just removed all together without a replacement?

**Comment by smira** [comment]
This is incorrect/outdated notes.

If `talosctl get securitystate` returns `bootedWithUki: true`, you can use simple upgrade to a new schematic to update kernel args. 

You would see UKI boot for all 1.10+ new installs on Talos with UEFI-compatible hardware (which is all of modern hardware minus SBCs).

**Comment by Nomsplease** [comment]
The issue here is that people are confused due to the lack of easily digestible documentation on using kernel arguments via the factory images. As a Talhelper user, I do not use the factory site directly; instead, I moved my kernel arguments from machine patches into the schematic customization so the images are generated with the kernel arguments.

This can be as simple as having better documentation around this, as well as more consistent wording across the products. Having "Outdated" notes within an app that most of the users would use is a poor user experience; this alone can lead to user confusion.

For the future visitors. I moved my args to this in my Talos config file:
```
    machineSpec:
      mode: metal
      arch: amd64
      secureboot: false
    schematic:
      customization:
        extraKernelArgs: &intel-extraKernelArgs
          - -init_on_alloc                      # Less security, faster puter
          - -init_on_free                       # Less security, faster puter
          - -selinux                            # Less security, faster puter
          - apparmor=0                          # Less security, faster puter
          # - i915.enable_guc=3                   # Meteor Lake CPU / iGPU
          - init_on_alloc=0                     # Less security, faster puter
          - init_on_free=0                      # Less security, faster puter
          - intel_iommu=on                      # PCI Passthrough
          - iommu=pt                            # PCI Passthrough
          - mitigations=off                     # Less security, faster puter
          - module_blacklist=igc                # Disable onboard NIC
          - security=none                       # Less security, faster puter
          # - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU / iGPU
          - talos.auditd.disabled=1             # Less security, faster puter
        systemExtensions: &intel-officialExtensions
            officialExtensions:
                - siderolabs/i915
                - siderolabs/intel-ucode
                - siderolabs/mei
```
