### ISSUE TITLE
Registry Mirroring Fails After Initial Setup Until Manual Config Edit

### ISSUE THREAD

**Issue by spa086** [siderolabs/talos#11164]
### Description
After installing Talos Linux and configuring registry mirrors in the machine config, images are not pulled from the mirrored registry (git.example.com:4567) as expected. The mirror is set to use an endpoint (https://registry.example.xyz/v2/art) with overridePath: true.
The issue is resolved only after manually editing the machine config via talosctl edit machineconfig, toggling the overridePath parameter between true and false (i.e., set it to false, save, then set it back to true and save again). After this procedure, registry mirroring starts working as intended.
### Expected Behavior:
Images should be pulled from the mirrored registry immediately after initial configuration, without requiring manual intervention or config edits.

### Current Behavior:
Images are not pulled from the mirror until the machine config is manually edited and the overridePath parameter is toggled.

###Logs
There are no errors or anything interesting in the logs.

### Environment

```yaml
machine:
  registries:
    config:
      registry.example.xyz:
        auth:
          username: "robot-k8s"
          password: "secret"
    mirrors:
      git.example.com:4567:
        endpoints:
          - https://registry.example.xyz/v2/art
        overridePath: true
```
- Talos version: 
Client:
        Tag:         v1.10.3
        SHA:         dde2cebc
        Built:       
        Go version:  go1.24.3
        OS/Arch:     linux/amd64
Server:
        NODE:        192.168.2.3
        Tag:         v1.10.3
        SHA:         dde2cebc
        Built:       
        Go version:  go1.24.3
        OS/Arch:     linux/amd64
        Enabled:     RBAC 
- Kubernetes version:
 Client Version: v1.33.1
Kustomize Version: v5.6.0
Server Version: v1.33.1 
- Platform: nocloud (proxmox)
