### ISSUE TITLE
Broken System after bootstrap on dedicated hardware (Hetzner)

### ISSUE THREAD

**Issue by VonNao** [siderolabs/talos#11170]
## Bug Report

Broken System after bootstrap on Hetzner Dedicated Server

### Description
We deployed talos 1.10.2 via talhelper on a hetzner dedicated server. Writing the image to filesystem with dd resulted in a bootable talos. After the first boot we can apply our talosconfig against so host which resluts in a fully functional system. We than tried to reboot/upgrade the system to 1.10.3 which did all the preflight checks successful. The system reboots and comes up after a certain time in a broken state as seen the both screenshots. 

![Image](https://github.com/user-attachments/assets/37c71427-ada8-480f-8a21-bd0450136679)
![Image](https://github.com/user-attachments/assets/b83b8d62-c3b1-4590-925b-35c074a696cc)

The System also changes from /dev/nvme0n0 to /dev/sda with qemu harddisk

```
NODE   NAMESPACE   TYPE               ID          VERSION   TYPE        SIZE     DISCOVERED   LABEL   PARTITIONLABEL
       runtime     DiscoveredVolume   loop0       1         disk        148 kB   squashfs             
       runtime     DiscoveredVolume   loop2       1         disk        471 kB   squashfs             
       runtime     DiscoveredVolume   loop3       1         disk        209 MB   squashfs             
       runtime     DiscoveredVolume   loop4       1         disk        79 MB    squashfs             
       runtime     DiscoveredVolume   loop5       1         disk        78 MB    squashfs             
       runtime     DiscoveredVolume   nvme0n1     2         disk        1.9 TB   gpt                  
       runtime     DiscoveredVolume   nvme0n1p1   1         partition   1.2 GB   vfat         EFI     EFI
       runtime     DiscoveredVolume   nvme0n1p4   1         partition   1.0 MB   talosmeta            META
       runtime     DiscoveredVolume   nvme1n1     1         disk        1.9 TB
```

```
NODE            NAMESPACE   TYPE               ID      VERSION   TYPE        SIZE     DISCOVERED   LABEL       PARTITIONLABEL
hidden-ip   runtime     DiscoveredVolume   loop0   1         disk        77 MB    squashfs                 
hidden-ip   runtime     DiscoveredVolume   sda     1         disk        1.9 TB   gpt                      
hidden-ip   runtime     DiscoveredVolume   sda1    1         partition   1.2 GB   vfat         EFI         EFI
hidden-ip   runtime     DiscoveredVolume   sda2    1         partition   105 MB   xfs          STATE       STATE
hidden-ip   runtime     DiscoveredVolume   sda4    1         partition   1.0 MB   talosmeta                META
hidden-ip   runtime     DiscoveredVolume   sda5    1         partition   1.9 TB   xfs          EPHEMERAL   EPHEMERAL
hidden-ip   runtime     DiscoveredVolume   sdb     1         disk        1.9 TB
```

```
clusterName: he-c01

talosVersion: 1.10.2
kubernetesVersion: 1.33.1

endpoint: https://hidden-ip:6443

additionalMachineCertSans: &sans
  - hidden-ip
  - 127.0.0.1
additionalApiServerCertSans: *sans

nodes:
  # control plane nodes
  - hostname: he-c01cp43001p
    controlPlane: true
    ipAddress: hidden-ip
    networkInterfaces:
      - interface: eth0
        addresses:
          - hidden-ip/32
        routes:
          - network: hidden-ip/32
          - network: 0.0.0.0/0
            gateway: hidden-gateway
        dhcp: false
    nameservers:
      - 185.12.64.1
      - 185.12.64.2
    #installDisk: /dev/nvme0n1
    installDiskSelector:
      id: /dev/disk/by-id/nvme-eui.01000000000000008ce38ee3067c1a4b

controlPlane:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/nonfree-kmod-nvidia-production
          - siderolabs/nvidia-container-toolkit-production

  patches:
    - |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |
              [plugins]
                [plugins."io.containerd.cri.v1.runtime"]
                  [plugins."io.containerd.cri.v1.runtime".containerd]
                    default_runtime_name = "nvidia"
        kernel:
          modules:
            - name: nvidia
            - name: nvidia_uvm
            - name: nvidia_drm
            - name: nvidia_modeset
        sysctls:
          net.core.bpf_jit_harden: 1
        features:
          rbac: true
          stableHostname: true
          apidCheckExtKeyUsage: true
          diskQuotaSupport: true
          kubePrism:
            enabled: true
            port: 7445
          hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles: ["os:admin"]
            allowedKubernetesNamespaces: ["system-upgrade"]
        kubelet:
          extraMounts:
            - destination: /var/mnt/extra
              type: bind
              source: /var/mnt/extra
              options:
                - bind
                - rshared
                - rw
        time:
          servers:
            - ntp1.hetzner.de
            - ntp2.hetzner.de
            - ntp3.hetzner.de
      cluster:
        network:
          cni:
            name: none
        proxy:
          disabled: true
        allowSchedulingOnControlPlanes: true

```

### Environment

- Talos version: 1.10.2/3
- Kubernetes version: 1.33.1
- Platform: metal
