### ISSUE TITLE
Talos bootstraping getting stuck on Proxmox with "VirtIO SCSI single" controller

### ISSUE THREAD

**Issue by SlavikCA** [siderolabs/talos#11173]
## Bug Report
I followed this guide:
https://www.talos.dev/v1.10/talos-guides/install/virtualized-platforms/proxmox/

to install Talos on my Proxmox Hypervisor, which is:
- Proxmox 8.4 with kernel updated to 6.11.11-2-pve
- Intel Xeon Gold 5218
- NVMe 4TB drive

I created VM:
- CPU: 4 cores
- RAM: 16GB RAM
- controller: VirtIO SCSI single
- disk: 48GB disk 

Started VM. It started without any issues, got the IP.

Started install with taloctl and install stuck:

<img width="967" alt="Image" src="https://github.com/user-attachments/assets/3155b27f-a242-420d-a71e-2a3cd313cb15" />

## Workaround:

If in VM I use `controller: VirtIO SCSI` (not single) - everything is working fine.

### Environment

- Talos version: 1.10.3

I used following `patch.yaml`:

```
machine:
  kubelet:
    nodeIP:
      validSubnets:
      - 192.168.0.0/24
    extraConfig:
      maxPods: 512
  kernel:
    modules:
    - name: openvswitch
    - name: drbd
      parameters:
        - usermode_helper=disabled
    - name: zfs
    - name: spl
    - name: vfio_pci
    - name: vfio_iommu_type1
```

**Comment by smira** [comment]
I think your issue is something different.

Please make sure you have serial console enabled, e.g. with extra kernel args in the Image Factory: `-console console=tty0 console=ttyS0`, and inspect full logs in Proxmox. This will help you to understand the problem better.

**Comment by divStar** [comment]
I actually encountered the same issue today using Proxmox 9.0.3 and Talos 1.11.3.

When using `virtio-scsi-single`, my setup is stuck in a long wait (10 or so minutes), then attempts to proceed but never gets anywhere. If I switch to `virtio-scsi-pci`, everything seems to work as expected.

Edit: so I can only guess, but I **think** the issue was, that in the QEMU setup I specified other sizes than in the Talos patches.

<details>
<summary>Terraform QEMU VM setup excerpt - only using 64GB storage</summary>

```hcl
resource "proxmox_virtual_environment_vm" "this" {
...
  disk {
    datastore_id = var.node_datastore_id
    interface    = "scsi1"
    iothread     = true
    cache        = "writethrough"
    discard      = "on"
    ssd          = true
    file_format  = "raw"
    size         = 64
    serial       = "kube"
  }

  disk {
    datastore_id = var.node_datastore_id
    interface    = "scsi2"
    iothread     = true
    cache        = "writethrough"
    discard      = "on"
    ssd          = true
    file_format  = "raw"
    size         = 64
    serial       = "storage"
  }
...
}
```
</details>

<details>
<summary>Talos patches specify 256GB though</summary>

```yml
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: "disk.symlinks.exists(s, s.endsWith('scsi1'))"
  maxSize: 256GB # <- should be 64GB here
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: pv-storage
provisioning:
  diskSelector:
    match: "disk.symlinks.exists(s, s.endsWith('scsi2'))"
  maxSize: 256GB # <- should be 64GB here
filesystem:
  type: ext4
```
</details>

Once I adjusted the values to match, it seems, that `virtio-scsi-single` worked as expected (apparently `virtio-scsi-pci` didn't care).

**I cannot confirm it on a simplified `test-talos` setup though.** So maybe there are additional requirements (such as passing through `virtiofs` resources and mounting them). If I am confidently able to reproduce it, I'll provide a git repository.
