### ISSUE TITLE
Feature Request: Add the ability to control the MAC address on a bridge

### ISSUE THREAD

**Issue by nicolerenee** [siderolabs/talos#11225]
## Feature Request

Would like the ability to set the MAC address of a bridge in the machine config. The config would look something like this:
```
network:
  interfaces:
    - interface: br0
      bridge:
        macAddress: 00:1A:2B:3C:4D:5E
        interfaces:
          - enp3s0
        stp:
          enabled: true
```

### Description

Currently it is not possible to set the MAC address of a bridge when you create one with Talos. Unfortunately the MAC address with the default config will change based on the ports that are connected to it. I'm running kubevirt and using network monitoring that's tying bandwidth to the source MAC address. Linux calculates the bridge address from the member ports when a MAC address is not specified. This makes it where the bridge MAC changes which makes it hard to accurately track the network usage coming from the host itself via the MAC address.
