### ISSUE TITLE
kind: UserVolumeConfig does not mount to kubelet

### ISSUE THREAD

**Issue by Syntax3rror404** [siderolabs/talos#11222]
## Bug Report

UserVolumeConfig does not mount the UserVolumeConfig to the kubelet correctly. 

### Description

For example I use the following UserVolumeConfig

```
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: longhorn
provisioning:
  diskSelector:
    match: disk.transport == "nvme" && disk.model == "WD_BLACK SN770 2TB" && !system_disk
  maxSize: 1800GB
filesystem:
  type: xfs
```

Expected mount to be on `/var/mnt/longhorn`

But the mount is missing on the node m1 see

![Image](https://github.com/user-attachments/assets/a6ece25a-a7e1-49c7-9faf-e6c17ce371fa)

The other nodes use on top of the UserVolumeConfig

```
kubelet:
    extraMounts:
      - destination: /var/mnt/longhorn
        type: bind
        source: /var/mnt/longhorn
        options:
          - bind
          - rshared
          - rw
```

Which fixes the missing mount

### Logs

```
 user: warning: [2025-06-15T13:20:22.758944599Z]: [talos] partition created {"component": "controller-runtime", "controller": "block.VolumeManagerController", "volume": "u-longhorn", "disk": "/dev/nvme0n1",
 "partition": 2, "label": "u-longhorn", "size": "187 GiB"}
 user: warning: [2025-06-15T13:20:22.861267599Z]: [talos] formatting filesystem {"component": "controller-runtime", "controller": "block.VolumeManagerController", "volume": "u-longhorn", "device": "/dev/
 nvme0n1p2", "filesystem": "xfs"}
 user: warning: [2025-06-15T13:20:23.000950599Z]: [talos] volume status {"component": "controller-runtime", "controller": "block.VolumeManagerController", "volume": "u-longhorn", "phase": "failed -> ready",
 "location": "/dev/nvme0n1p2", "parentLocation": "/dev/nvme0n1"}
 kern:  notice: [2025-06-15T13:20:23.003662599Z]: XFS (nvme0n1p2): Mounting V5 Filesystem 8990ea33-0be4-4e6b-9a5d-889670147621
 kern:    info: [2025-06-15T13:20:23.010544599Z]: XFS (nvme0n1p2): Ending clean mount
 user: warning: [2025-06-15T13:20:23.012686599Z]: [talos] volume mount {"component": "controller-runtime", "controller": "block.MountController", "volume": "u-longhorn", "source": "/dev/nvme0n1p2", "target":
 "/var/mnt/longhorn", "filesystem": "xfs", "read_only": false}
 kern:    info: [2025-06-15T13:29:02.101616599Z]: eth0: renamed from tmp3c09b
 kern:    info: [2025-06-15T13:29:59.979290599Z]: eth0: renamed from tmp79c2c
 user: warning: [2025-06-15T13:32:26.397318599Z]: [talos] apply config request: mode auto(no_reboot)
 kern:  notice: [2025-06-15T13:32:26.407099599Z]: XFS (nvme1n1p5): Mounting V5 Filesystem 43650210-278f-4f0a-91a5-cbd31fd69f3a
 kern:    info: [2025-06-15T13:32:26.412724599Z]: XFS (nvme1n1p5): Ending clean mount
 user: warning: [2025-06-15T13:32:26.413704599Z]: [talos] volume mount {"component": "controller-runtime", "controller": "block.MountController", "volume": "STATE", "source": "/dev/nvme1n1p5", "target": "/
 system/state", "filesystem": "xfs", "read_only": false}
 user: warning: [2025-06-15T13:32:26.414490599Z]: [talos] machine configuration persisted to STATE {"component": "controller-runtime", "controller": "config.PersistenceController"}
 kern:  notice: [2025-06-15T13:32:26.423698599Z]: XFS (nvme1n1p5): Unmounting Filesystem 43650210-278f-4f0a-91a5-cbd31fd69f3a
 user: warning: [2025-06-15T13:32:26.436486599Z]: [talos] volume unmount {"component": "controller-runtime", "controller": "block.MountController", "volume": "STATE", "source": "/dev/nvme1n1p5", "target": "/
 system/state", "filesystem": "xfs"}
```

### Environment

- Talos version: 1.10.4
- Kubernetes version: v1.32.5
- Platform: Baremetal
