### ISSUE TITLE
failed to determine platform on talos 1.10

### ISSUE THREAD

**Issue by WinterNis** [siderolabs/talos#11236]
## Bug Report

When installing talos `1.10` (metal image) on an OVH "dedicated" (baremetal) server (ref `RISE-S-2 | AMD RYZEN 7 9700x`), we are encountering the following issue:

![Image](https://github.com/user-attachments/assets/72be213b-ab4b-4b78-a9a8-03c788842088)

Sorry it’s a screenshot because we only have kvm, but the error is the following:

> failed to determine platform

It looks like somehow the platform kernel params is not correctly detected anymore ? Or absent ? 

If we do upgrades from `1.9` to `1.10`, there is no issue. In our case it only happens when installing a fresh server with 1.10.
Tested with `1.10.2`, `1.10.3` and `1.10.4`

It’s somehow similar to this other issue (https://github.com/siderolabs/talos/issues/11210)

So we investigated a bit and tried to "fix" it by changing back the boot loader to `grub` using this configuration in imager (as explained in the [1.10 release notes](https://github.com/siderolabs/talos/releases/tag/v1.10.0))

```
output:
  kind: image
  imageOptions:
    bootloader: grub
```

It was _REALLY_ painful to do so as `imager` do not expose `imageOptions` override through command line arguments, but in the end we managed to build our image. 

**And actually, it worked.**

So, we are not sure to understand if this is a bug or not. 
These are recent servers that do support UEFI, AFAIK. We clearly see the `refind` interface during boot on the kvm. 

Maybe somehow the kernel args containing the platform information gets wiped ? 

We are not sure what we can do to investigate this further.

### Environment

- Talos version: `1.10.4`, but also tested with `1.10.2` and `1.10.3`
- Kubernetes version: Not relevant
- Platform: `metal`

**Comment by smira** [comment]
It's not clear how you end up with platform not being detected, but you seem to be building an installer image without a platform specified. 

Please ensure your installer image matches the docs (if using Image Factory): https://factory.talos.dev/?arch=amd64&cmdline-set=true&extensions=-&platform=metal&target=metal&version=1.10.4

**Comment by WinterNis** [comment]
Hi @smira,

We are not using Image Factory, we are using `imager` directly to build our images.

Here are imager profiles **that do not work** (we have the described issue when we use images from these profiles):

Installer:
```
arch: amd64
platform: metal
secureboot: false
version: v1.10.4
input:
  kernel:
    path: /usr/install/amd64/vmlinuz
  initramfs:
    path: /usr/install/amd64/initramfs.xz
  sdStub:
    path: /usr/install/amd64/systemd-stub.efi
  sdBoot:
    path: /usr/install/amd64/systemd-boot.efi
  baseInstaller:
    imageRef: ghcr.io/siderolabs/installer:v1.10.4
  imageCache:
    imageRef: ""
    ociPath: /image-cache
output:
  kind: installer
  outFormat: raw
```

metal image:

```
arch: amd64
platform: metal
secureboot: false
version: v1.10.4
input:
  kernel:
    path: /usr/install/amd64/vmlinuz
  initramfs:
    path: /usr/install/amd64/initramfs.xz
  sdStub:
    path: /usr/install/amd64/systemd-stub.efi
  sdBoot:
    path: /usr/install/amd64/systemd-boot.efi
  baseInstaller:
    imageRef: ghcr.io/siderolabs/installer:v1.10.4
  imageCache:
    imageRef: ""
    ociPath: /image-cache
output:
  kind: image
  imageOptions:
    diskSize: 3405774848
    diskFormat: raw
    bootloader: dual-boot
  outFormat: .zst
```

Here are imager profiles **that do work** (we do not have the issue when we use images from these profiles):

```
arch: amd64
platform: metal
secureboot: false
version: v1.10.4
input:
  kernel:
    path: /usr/install/amd64/vmlinuz
  initramfs:
    path: /usr/install/amd64/initramfs.xz
  sdStub:
    path: /usr/install/amd64/systemd-stub.efi
  sdBoot:
    path: /usr/install/amd64/systemd-boot.efi
  baseInstaller:
    imageRef: ghcr.io/siderolabs/installer:v1.10.4
  imageCache:
    imageRef: ""
    ociPath: /image-cache
output:
  kind: installer
  imageOptions:
    diskSize: 0
    bootloader: grub
  outFormat: raw
```

Metal image:

```
arch: amd64
platform: metal
secureboot: false
version: v1.10.4
input:
  kernel:
    path: /usr/install/amd64/vmlinuz
  initramfs:
    path: /usr/install/amd64/initramfs.xz
  sdStub:
    path: /usr/install/amd64/systemd-stub.efi
  sdBoot:
    path: /usr/install/amd64/systemd-boot.efi
  baseInstaller:
    imageRef: ghcr.io/siderolabs/installer:v1.10.4
  imageCache:
    imageRef: ""
    ociPath: /image-cache
output:
  kind: image
  imageOptions:
    diskSize: 2356150272
    diskFormat: raw
    bootloader: grub
  outFormat: .zst
```

As far as I can observe, the only difference between the profiles that work and do not work, is the bootloader type.

AFAIK, the platform is correctly specified in the profiles.

In the imager logs, we can see that the platform is correctly set as kernel args

```
kernel command line: talos.platform=metal console=tty0 init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 printk.devkmsg=on ima_template=ima-ng ima_appraise=fix ima_hash=sha512 selinux=1
```
