### ISSUE TITLE
Talos defines public ip as private

### ISSUE THREAD

**Issue by DevOpsPop** [siderolabs/talos#11249]
## Bug Report

![Image](https://github.com/user-attachments/assets/5de8ee82-5fdd-467e-bc04-f96bdd96e840)

![Image](https://github.com/user-attachments/assets/ed8c90fe-9459-4b49-a02f-06ec51d9abd4)

### Description
When setting up a cluster of 3 masters and a worker, on one of the nodes the public and private ip switched places.
If re-set up the cluster, it happens on a different node.  Because of it, I have wrong endpoints in talos and k8s service
All nodes same type in Hetzner cloud with empty network in mc.
Also installed hcloud-cloud-controller-manager chart.
### Configs
CP nodes
```
machine:
  sysctls:
    net.core.somaxconn: 65535
    net.core.netdev_max_backlog: 4096
  features:
    hostDNS:
      forwardKubeDNSToHost: false
    kubePrism:
      enabled: true
      port: 7445
    kubernetesTalosAPIAccess:
      enabled: true
      allowedRoles:
        - os:reader
      allowedKubernetesNamespaces:
        - kube-system
  time:
      servers:
          - ntp1.hetzner.de
          - ntp2.hetzner.com
          - ntp3.hetzner.net
          - time.cloudflare.com
cluster:
  etcd:
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
  controllerManager:
    extraArgs:
      bind-address: 0.0.0.0
  scheduler:
    extraArgs:
      bind-address: 0.0.0.0
  externalCloudProvider:
    enabled: true
  network:
    cni:
      name: none
  proxy:
    disabled: true
  allowSchedulingOnControlPlanes: false

```

worker nodes
```
machine:
  features:
    hostDNS:
      forwardKubeDNSToHost: false
    kubePrism:
      enabled: true
      port: 7445
  time:
      servers:
          - ntp1.hetzner.de
          - ntp2.hetzner.com
          - ntp3.hetzner.net
          - time.cloudflare.com
cluster:
  externalCloudProvider:
    enabled: true
  network:
    cni:
      name: none
  proxy:
    disabled: true
```

### Environment

- Talos version: 1.10.4
- Kubernetes version: 1.33
- Platform: linux
