### ISSUE TITLE
More flexible disk selector for install disk

### ISSUE THREAD

**Issue by stereobutter** [siderolabs/talos#11255]
## Feature Request
Allow using the [new more powerful disk selector](https://www.talos.dev/v1.10/reference/configuration/block/volumeconfig/#VolumeConfig.provisioning.diskSelector) from `VolumeConfig` for `machine.install.disk` as well.

### Description
What has happened to me in the past (and some users recently) is that the talos installation accidentally ended up on the usb drive that the .iso was booted from. What would really help is if you could do something like this to select the first (and often only) non-usb disk on a machine. 

```yaml
machine:
    install:
        diskSelector:
            match: disk.size > 64u * GiB && !disk.busPath.contains('usb')

```
