### ISSUE TITLE
ARM64 node pulling AMD64 image

### ISSUE THREAD

**Issue by hydazz** [siderolabs/talos#11268]
## Bug Report

### Description
I have a mixed arch cluster, 3 amd64 nodes and 1 arm64 node,
occasionally the arm node appears to pull the amd64 version of an image (based on `exec format error` in the logs)

I can't pinpoint what's causing this and its quite annoying, I did not have this issue using kubeadmin and Debian before switching to Talos

I am using Spegel, which I thought was causing this, so I've limited it to running on amd64 nodes - issue still persists

I have cleared the containerd image cache `crictl rmi --prune` - issue still persists

I am pretty new to talos, so unsure what im doing wrong here, or how to diagnose this further

does not affect all images, unsure what links the ones that don't work

I also know mixed arch clusters are not good, but I spent a lot of money on this little SBC, so might as well put it to use 🙂, and im pretty sure this issue is unrelated to the other nodes

```
kgp -A -o wide | grep nebula
databases           cloudnative-pg-7b4b56df57-29ns8                          1/1     Running            3 (20m ago)     25m     10.42.3.14      nebula      <none>           <none>
databases           mariadb-operator-5d4cb9794b-8nbhz                        1/1     Running            3 (20m ago)     26m     10.42.3.175     nebula      <none>           <none>
databases           mariadb-operator-cert-controller-68d8fc5bb7-kmh8f        1/1     Running            3 (20m ago)     25m     10.42.3.69      nebula      <none>           <none>
databases           mariadb-operator-webhook-649f979d87-bq889                1/1     Running            3 (20m ago)     25m     10.42.3.24      nebula      <none>           <none>
external-secrets    onepassword-fb8bc6d6-n7vv6                               0/2     CrashLoopBackOff   14 (5m1s ago)   16m     10.42.3.139     nebula      <none>           <none>
flux-system         helm-controller-76dfdbb89b-msmts                         1/1     Running            3 (20m ago)     25m     10.42.3.66      nebula      <none>           <none>
flux-system         source-controller-67df565497-bc74p                       1/1     Running            3 (20m ago)     26m     10.42.3.82      nebula      <none>           <none>
kube-system         cilium-9jd6g                                             1/1     Running            4 (20m ago)     97m     192.168.42.11   nebula      <none>           <none>
kube-system         cilium-envoy-mx775                                       1/1     Running            4 (20m ago)     97m     192.168.42.11   nebula      <none>           <none>
kube-system         cilium-operator-6b64959c5d-rfgxw                         1/1     Running            3 (20m ago)     25m     192.168.42.11   nebula      <none>           <none>
kube-system         descheduler-6d545ccbdb-xg7w9                             1/1     Running            3 (20m ago)     26m     10.42.3.150     nebula      <none>           <none>
kube-system         kube-apiserver-nebula                                    1/1     Running            0               20m     192.168.42.11   nebula      <none>           <none>
kube-system         kube-controller-manager-nebula                           1/1     Running            0               20m     192.168.42.11   nebula      <none>           <none>
kube-system         kube-scheduler-nebula                                    1/1     Running            0               20m     192.168.42.11   nebula      <none>           <none>
kube-system         node-feature-discovery-worker-knn7f                      1/1     Running            7 (20m ago)     97m     10.42.3.225     nebula      <none>           <none>
kube-system         snapshot-controller-6df7569ccd-mjzct                     1/1     Running            3 (20m ago)     25m     10.42.3.55      nebula      <none>           <none>
longhorn-system     engine-image-ei-e09d8caa-6jvtn                           1/1     Running            29 (20m ago)    47h     10.42.3.58      nebula      <none>           <none>
longhorn-system     instance-manager-60f73d3754d1c68181b5605009bc006b        1/1     Running            0               19m     10.42.3.108     nebula      <none>           <none>
longhorn-system     longhorn-csi-plugin-v9xzb                                3/3     Running            10 (20m ago)    97m     10.42.3.168     nebula      <none>           <none>
longhorn-system     longhorn-manager-fmq9w                                   2/2     Running            59 (20m ago)    47h     10.42.3.6       nebula      <none>           <none>
longhorn-system     longhorn-ui-6b44759848-rx7wn                             1/1     Running            3 (20m ago)     26m     10.42.3.87      nebula      <none>           <none>
media-managers      flaresolverr-74594f9d8d-pqhh7                            1/1     Running            3 (20m ago)     26m     10.42.3.5       nebula      <none>           <none>
network             cloudflare-dns-5dd599894b-p4ffd                          1/1     Running            3 (20m ago)     25m     10.42.3.245     nebula      <none>           <none>
observability       keda-admission-webhooks-667fd447f5-fl4pq                 1/1     Running            3 (20m ago)     25m     10.42.3.219     nebula      <none>           <none>
observability       keda-operator-metrics-apiserver-7b8b4cfb4f-rlz4h         1/1     Running            3 (20m ago)     26m     10.42.3.165     nebula      <none>           <none>
observability       node-exporter-wdfg6                                      1/1     Running            4 (20m ago)     97m     192.168.42.11   nebula      <none>           <none>
observability       promtail-djd67                                           1/1     Running            4 (20m ago)     97m     10.42.3.3       nebula      <none>           <none>
volsync-system      volsync-76d6578f5f-9gl42                                 2/2     Running            8 (20m ago)     26m     10.42.3.234     nebula      <none>           <none>
```

### Logs
onepassword-connect:
Pod logs (one specific)
```
│ api exec /bin/connect-api: exec format error                                                                                                                                                                             │
│ sync exec /bin/connect-sync: exec format error                                                                                                                                                                           │
│ stream closed EOF for external-secrets/onepassword-fb8bc6d6-n7vv6 (api)                                                                                                                                                  │
│ stream closed EOF for external-secrets/onepassword-fb8bc6d6-n7vv6 (sync) 
```
image for pod above:
```
│ Containers:                                                                                                                                                                                                              │
│   api:                                                                                                                                                                                                                   │
│     Container ID:   containerd://55b7e0836b47fb0e13473e5d9fd08785ab52be5e132c8f5e306c96b8db3afa51                                                                                                                        │
│     Image:          docker.io/1password/connect-api:1.7.3@sha256:0601c7614e102eada268dbda6ba4b5886ce77713be2c332ec6a2fd0f028484ba                                                                                        │
│     Image ID:       docker.io/1password/connect-api@sha256:0601c7614e102eada268dbda6ba4b5886ce77713be2c332ec6a2fd0f028484ba 
```
image details:
```json
docker manifest inspect 'docker.io/1password/connect-api:1.7.3@sha256:0601c7614e102eada268dbda6ba4b5886ce77713be2c332ec6a2fd0f028484ba'
 {
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 3319,
         "digest": "sha256:06f09441c062c2419876937463f8a8293f3e05f00f615ada47f86abef6abfa24",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 3319,
         "digest": "sha256:8eb3efa4c6c4f3949db8cf645f43ab327d55f452d6147422d6d091739e51c191",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
```
kubelet logs:
```json
192.168.42.11: {"ts":1751116665931.853,"caller":"kubelet/kubelet_volumes.go:263","msg":"There were many similar errors. Turn up verbosity to see them.","numErrs":2,"err":"orphaned pod \"7f3389bb-0b90-4906-ab27-75edb8ac267b\" found, but error occurred when trying to remove the volumes dir: not a directory"}
192.168.42.11: {"ts":1751116666915.0598,"caller":"topologymanager/scope.go:117","msg":"RemoveContainer","v":0,"containerID":"30373871dd529c3db965f4a1e462d6a8253ba503e42bd518fa96b72a138cb31a"}
192.168.42.11: {"ts":1751116666915.1042,"caller":"topologymanager/scope.go:117","msg":"RemoveContainer","v":0,"containerID":"a150e72456f81eff70df57e5d9392bb914d0a77f896ee41b9ef69c733b1b5ccc"}
192.168.42.11: {"ts":1751116666915.4878,"caller":"kubelet/pod_workers.go:1301","msg":"Error syncing pod, skipping","pod":{"name":"onepassword-fb8bc6d6-n7vv6","namespace":"external-secrets"},"podUID":"9d794baf-5dd8-4086-a364-ab81e2044100","err":"[failed to \"StartContainer\" for \"api\" with CrashLoopBackOff: \"back-off 1m20s restarting failed container=api pod=onepassword-fb8bc6d6-n7vv6_external-secrets(9d794baf-5dd8-4086-a364-ab81e2044100)\", failed to \"StartContainer\" for \"sync\" with CrashLoopBackOff: \"back-off 1m20s restarting failed container=sync pod=onepassword-fb8bc6d6-n7vv6_external-secrets(9d794baf-5dd8-4086-a364-ab81e2044100)\"]","errCauses":[{"error":"failed to \"StartContainer\" for \"api\" with CrashLoopBackOff: \"back-off 1m20s restarting failed container=api pod=onepassword-fb8bc6d6-n7vv6_external-secrets(9d794baf-5dd8-4086-a364-ab81e2044100)\""},{"error":"failed to \"StartContainer\" for \"sync\" with CrashLoopBackOff: \"back-off 1m20s restarting failed container=sync pod=onepassword-fb8bc6d6-n7vv6_external-secrets(9d794baf-5dd8-4086-a364-ab81e2044100)\""}]}
192.168.42.11: {"ts":1751116667926.9424,"caller":"kubelet/kubelet_volumes.go:263","msg":"There were many similar errors. Turn up verbosity to see them.","numErrs":2,"err":"orphaned pod \"7f3389bb-0b90-4906-ab27-75edb8ac267b\" found, but error occurred when trying to remove the volumes dir: not a directory"}
192.168.42.11: {"ts":1751116669928.06,"caller":"kubelet/kubelet_volumes.go:263","msg":"There were many similar errors. Turn up verbosity to see them.","numErrs":2,"err":"orphaned pod \"7f3389bb-0b90-4906-ab27-75edb8ac267b\" found, but error occurred when trying to remove the volumes dir: not a directory"}
192.168.42.11: {"ts":1751116671926.8884,"caller":"kubelet/kubelet_volumes.go:263","msg":"There were many similar errors. Turn up verbosity to see them.","numErrs":2,"err":"orphaned pod \"7f3389bb-0b90-4906-ab27-75edb8ac267b\" found, but error occurred when trying to remove the volumes dir: not a directory"}
192.168.42.11: {"ts":1751116673922.2976,"caller":"kubelet/kubelet_volumes.go:263","msg":"There were many similar errors. Turn up verbosity to see them.","numErrs":2,"err":"orphaned pod \"7f3389bb-0b90-4906-ab27-75edb8ac267b\" found, but error occurred when trying to remove the volumes dir: not a directory"}
192.168.42.11: {"ts":1751116675929.6929,"caller":"kubelet/kubelet_volumes.go:263","msg":"There were many similar errors. Turn up verbosity to see them.","numErrs":2,"err":"orphaned pod \"7f3389bb-0b90-4906-ab27-75edb8ac267b\" found, but error occurred when trying to remove the volumes dir: not a directory"}
192.168.42.11: {"ts":1751116677933.5222,"caller":"kubelet/kubelet_volumes.go:263","msg":"There were many similar errors. Turn up verbosity to see them.","numErrs":2,"err":"orphaned pod \"7f3389bb-0b90-4906-ab27-75edb8ac267b\" found, but error occurred when trying to remove the volumes dir: not a directory"}
192.168.42.11: {"ts":1751116679921.9338,"caller":"kubelet/kubelet_volumes.go:263","msg":"There were many similar errors. Turn up verbosity to see them.","numErrs":2,"err":"orphaned pod \"7f3389bb-0b90-4906-ab27-75edb8ac267b\" found, but error occurred when trying to remove the volumes dir: not a directory"}
192.168.42.11: {"ts":1751116681916.7957,"caller":"topologymanager/scope.go:117","msg":"RemoveContainer","v":0,"containerID":"30373871dd529c3db965f4a1e462d6a8253ba503e42bd518fa96b72a138cb31a"}
192.168.42.11: {"ts":1751116681916.892,"caller":"topologymanager/scope.go:117","msg":"RemoveContainer","v":0,"containerID":"a150e72456f81eff70df57e5d9392bb914d0a77f896ee41b9ef69c733b1b5ccc"}
192.168.42.11: {"ts":1751116681924.9658,"caller":"kubelet/kubelet_volumes.go:263","msg":"There were many similar errors. Turn up verbosity to see them.","numErrs":2,"err":"orphaned pod \"7f3389bb-0b90-4906-ab27-75edb8ac267b\" found, but error occurred when trying to remove the volumes dir: not a directory"}
192.168.42.11: {"ts":1751116682604.811,"caller":"topologymanager/scope.go:117","msg":"RemoveContainer","v":0,"containerID":"a150e72456f81eff70df57e5d9392bb914d0a77f896ee41b9ef69c733b1b5ccc"}
192.168.42.11: {"ts":1751116682605.4585,"caller":"topologymanager/scope.go:117","msg":"RemoveContainer","v":0,"containerID":"5e2655c9cea0d642f2b7cc5a8b7f7ae6178ba45f8893cb58ffc2ca38c6ad1eb0"}
192.168.42.11: {"ts":1751116682605.5012,"caller":"topologymanager/scope.go:117","msg":"RemoveContainer","v":0,"containerID":"7585f77150a3c4e68ca219f570f0db0c09098b56a1775f2d25b764b0e9d4ea95"}
192.168.42.11: {"ts":1751116682605.8706,"caller":"kubelet/pod_workers.go:1301","msg":"Error syncing pod, skipping","pod":{"name":"onepassword-fb8bc6d6-n7vv6","namespace":"external-secrets"},"podUID":"9d794baf-5dd8-4086-a364-ab81e2044100","err":"[failed to \"StartContainer\" for \"api\" with CrashLoopBackOff: \"back-off 2m40s restarting failed container=api pod=onepassword-fb8bc6d6-n7vv6_external-secrets(9d794baf-5dd8-4086-a364-ab81e2044100)\", failed to \"StartContainer\" for \"sync\" with CrashLoopBackOff: \"back-off 2m40s restarting failed container=sync pod=onepassword-fb8bc6d6-n7vv6_external-secrets(9d794baf-5dd8-4086-a364-ab81e2044100)\"]","errCauses":[{"error":"failed to \"StartContainer\" for \"api\" with CrashLoopBackOff: \"back-off 2m40s restarting failed container=api pod=onepassword-fb8bc6d6-n7vv6_external-secrets(9d794baf-5dd8-4086-a364-ab81e2044100)\""},{"error":"failed to \"StartContainer\" for \"sync\" with CrashLoopBackOff: \"back-off 2m40s restarting failed container=sync pod=onepassword-fb8bc6d6-n7vv6_external-secrets(9d794baf-5dd8-4086-a364-ab81e2044100)\""}]}
192.168.42.11: {"ts":1751116682630.398,"caller":"topologymanager/scope.go:117","msg":"RemoveContainer","v":0,"containerID":"30373871dd529c3db965f4a1e462d6a8253ba503e42bd518fa96b72a138cb31a"}
192.168.42.11: {"ts":1751116683926.371,"caller":"kubelet/kubelet_volumes.go:263","msg":"There were many similar errors. Turn up verbosity to see them.","numErrs":2,"err":"orphaned pod \"7f3389bb-0b90-4906-ab27-75edb8ac267b\" found, but error occurred when trying to remove the volumes dir: not a directory"}
```
overseerr:
```
│ exec /sbin/tini: exec format error                                                                                                                                                                                       │
│ stream closed EOF for media-managers/overseerr-67748b7f8b-qxgml (app) 
```

```
│ Containers:                                                                                                                                                                                                              │
│   app:                                                                                                                                                                                                                   │
│     Container ID:   containerd://7afc799947a33481dfceb32c6851be1d9cd4b959b8f2bda272608fbc9ac4da8f                                                                                                                        │
│     Image:          ghcr.io/sct/overseerr:1.34.0@sha256:4f38f58d68555004d3f487a4c5cbe2823e6a0942d946a25a2d9391d8492240a4                                                                                                 │
│     Image ID:       ghcr.io/sct/overseerr@sha256:4f38f58d68555004d3f487a4c5cbe2823e6a0942d946a25a2d9391d8492240a4 
```

```
docker manifest inspect 'ghcr.io/sct/overseerr:1.34.0@sha256:4f38f58d68555004d3f487a4c5cbe2823e6a0942d946a25a2d9391d8492240a4'
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1626,
         "digest": "sha256:a71728427cf46627b34e99b54dde5dd883faea89a5650a8c60964502058e9582",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1626,
         "digest": "sha256:ae37cc5558ace1dcd1b49fc1cd9e9a84524eeda93c2cb93fd9dc9014e3bfee57",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
```
jenkins:
```
│ init exec /usr/bin/sh: exec format error                                                                                                                                                                                 │
│ stream closed EOF for jenkins/jenkins-0 (init) 
```

```
│     Container ID:  containerd://5905b5bd854904c6bd6d862b1ec69e406368b4c76fb0062112a951f2e28a1a07                                                                                                                         │
│     Image:         docker.io/jenkins/jenkins:2.504.3-jdk21                                                                                                                                                               │
│     Image ID:      docker.io/jenkins/jenkins@sha256:f4607803bd1ee4dc91b1695b07d3a04c77b4f575a507ff65375af888e1497662
```

```
docker manifest inspect 'docker.io/jenkins/jenkins@sha256:f4607803bd1ee4dc91b1695b07d3a04c77b4f575a507ff65375af888e1497662'
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 2577,
         "digest": "sha256:81ff732e74ce05d2892bd49e87677937ce9a5ccdc93e77c1450fecae01cad233",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 2577,
         "digest": "sha256:0c894dae76ff9685105d6a56bbc172e95dbfbf05c58dafff54ad190bcafc2bb3",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
```

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
```
Client:
	Tag:         v1.10.4
	SHA:         3c119bf8
	Built:       
	Go version:  go1.24.4
	OS/Arch:     darwin/arm64
Server:
	NODE:        192.168.42.11
	Tag:         v1.10.4
	SHA:         3c119bf8
	Built:       
	Go version:  go1.24.4
	OS/Arch:     linux/arm64
	Enabled:     RBAC
```
- Kubernetes version: [`kubectl version`]
```
Client Version: v1.33.1
Kustomize Version: v5.6.0
Server Version: v1.33.2
```
- Platform:
Orange Pi 5+
config:
```yaml
version: v1alpha1
debug: false
persist: true
machine:
  type: controlplane
  token: xxx
  ca:
    crt: xxx
    key: xxx
  certSANs:
    - 127.0.0.1
    - 192.168.42.100
  kubelet:
    image: ghcr.io/siderolabs/kubelet:v1.33.2
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      serializeImagePulls: false
    defaultRuntimeSeccompProfileEnabled: true
    nodeIP:
      validSubnets:
        - 192.168.42.0/24
        - 2404:e80:661b:42::/64
    disableManifestsDirectory: true
  network:
    hostname: nebula
    interfaces:
      - deviceSelector:
          hardwareAddr: c0:74:2b:ff:13:37
          physical: true
        addresses:
          - 192.168.42.11/24
          - 2404:e80:661b:42::11/64
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.42.1
        vlans:
          - addresses:
              - 10.0.43.11/16
            routes: []
            dhcp: false
            vlanId: 125
        mtu: 1500
        dhcp: false
        vip:
          ip: 192.168.42.100
    nameservers:
      - 1.1.1.1
      - 1.0.0.1
    disableSearchDomain: true
  install:
    disk: /dev/nvme0n1
    image: factory.talos.dev/metal-installer/50f575e04855a715dc03da230bef1575b63de2299adc18b7f106155d1742be61:v1.10.4
    wipe: false
  files:
    - content: |
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
      permissions: 0o644
      path: /etc/cri/conf.d/20-customization.part
      op: create
    - content: |
        [ NFSMount_Global_Options ]
        nfsvers=4.2
        hard=True
        nconnect=16
        noatime=True
      permissions: 0o644
      path: /etc/nfsmount.conf
      op: overwrite
  time:
    disabled: false
    servers:
      - 162.159.200.1
      - 162.159.200.123
  sysctls:
    fs.inotify.max_user_instances: "8192"
    fs.inotify.max_user_watches: "1048576"
    net.core.rmem_max: "7500000"
    net.core.wmem_max: "7500000"
    net.ipv6.conf.all.forwarding: "1"
  features:
    rbac: true
    stableHostname: true
    apidCheckExtKeyUsage: true
    diskQuotaSupport: true
    kubePrism:
      enabled: true
      port: 7445
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: false
      resolveMemberNames: true
  nodeLabels:
    node.kubernetes.io/exclude-from-external-load-balancers: ""
cluster:
  id: xxx
  secret: xxx
  controlPlane:
    endpoint: https://192.168.42.100:6443
  clusterName: kubernetes
  network:
    cni:
      name: none
    dnsDomain: cluster.local
    podSubnets:
      - 10.42.0.0/16
      - fd42::/48
    serviceSubnets:
      - 10.43.0.0/16
      - fd43::/112
  token: xxx
  secretboxEncryptionSecret: xxx
  ca:
    crt: xxx
    key: xxx
  aggregatorCA:
    crt: xxx
    key: xxx
  serviceAccount:
    key: xxx
  apiServer:
    image: registry.k8s.io/kube-apiserver:v1.33.2
    extraArgs:
      enable-aggregator-routing: "true"
      feature-gates: MutatingAdmissionPolicy=true
      runtime-config: admissionregistration.k8s.io/v1alpha1=true
    certSANs:
      - 192.168.42.100
      - 127.0.0.1
      - 192.168.42.100
    disablePodSecurityPolicy: true
    auditPolicy:
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
        - level: Metadata
  controllerManager:
    image: registry.k8s.io/kube-controller-manager:v1.33.2
    extraArgs:
      bind-address: 0.0.0.0
  proxy:
    disabled: true
    image: registry.k8s.io/kube-proxy:v1.33.2
  scheduler:
    image: registry.k8s.io/kube-scheduler:v1.33.2
    extraArgs:
      bind-address: 0.0.0.0
    config:
      apiVersion: kubescheduler.config.k8s.io/v1
      kind: KubeSchedulerConfiguration
      profiles:
        - pluginConfig:
            - args:
                defaultConstraints:
                  - maxSkew: 1
                    topologyKey: kubernetes.io/hostname
                    whenUnsatisfiable: ScheduleAnyway
                defaultingType: List
              name: PodTopologySpread
          plugins:
            score:
              disabled:
                - name: ImageLocality
          schedulerName: default-scheduler
  discovery:
    enabled: true
    registries:
      kubernetes:
        disabled: true
      service: {}
  etcd:
    ca:
      crt: xxx
      key: xxx
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
    advertisedSubnets:
      - 192.168.42.0/24
  coreDNS:
    disabled: true
  allowSchedulingOnControlPlanes: true
```
