### ISSUE TITLE
context scoped extra Manifests

### ISSUE THREAD

**Issue by la7eralus** [siderolabs/talos#12113]
First of all: Thanks for making Talos, I really love it, and I only scratched the surface.

## Feature Request
Option, to apply extra Manifests to a distinct namespace (e.g. kubectl **-n \<namespace\>** -f \<urltomanifest\>.

### Description
As part of my cluster bootstrap, I use extraManifests to install argocd via the install.yml, that contains about 22000 lines of non namespaced lines of code. Since the extraManifests have no option for the target namespace, the manifest will be applied to the default namespace (not really best practice for argocd) of my shiny new talos kubernetes cluster. Providing a namespace option would greatly enhance the extraManifests usefulness. 
If my proposal doesn't align with your roadmap or architecture: Do you have an alternative way, that could help me here?

**Comment by franciscoxaviersp** [comment]
I managed to do this with a job that applies the official manifests.
Talos documentation on installing cillium has a similar approach that uses cillium cli instead of kubectl ([docs](https://www.talos.dev/v1.10/kubernetes-guides/network/deploying-cilium/#method-5-using-a-job)).
Example: (namespace has to be created before)
```
inlineManifests:
  - name: argocd-namespace
    contents: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: argocd
  - name: argocd-installer
    contents: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: argocd-installer
        namespace: kube-system
      spec:
        template:
          spec:
            serviceAccountName: argocd-installer
            containers:
            - name: installer
              image: bitnami/kubectl:latest
              command:
              - /bin/sh
              - -c
              - |
                kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/ha/install.yaml
            restartPolicy: OnFailure
        backoffLimit: 3
      ---
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: argocd-installer
        namespace: kube-system
      ---
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: argocd-installer
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        name: argocd-installer
        namespace: kube-system
```
