### ISSUE TITLE
talosctl cluster create: support for insecureSkipVerify for the registry mirror

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#2592]

**Comment by willemm** [comment]
Can I assume from this that it is not currently supported to bootstrap a machine (via sidero) if I want to use an air-gapped local docker registry with a self-signed certificate?

**Comment by andrewrynhard** [comment]
@willemm This should work with Sidero. The trick there is defining the correct `configPatch`: https://www.sidero.dev/docs/v0.1/guides/patching.

**Comment by willemm** [comment]
I think I got the configPatch correct.  The boot screen, when it wants to pull ghcr.io/talos-systems/installer:v0.7.1 is showing that it's trying to retrieve https://<our local machine>/v2/ghcr.io/talos-systems/installer/manifests/v0.7.1?ns=ghcr.io

But then it fails with the error: x509 certificate signed by unknown authority

When I check the configdata yaml I download from the management server, it has "insecureSkipVerify: true" in the correct position (under machine/registries/config/registry.insecure/tls) right next to the ../mirrors/ghcr.io/endpoints bit which it did pick up (as evidenced by it trying to download from our local machine)

So given the title of this issue, I assume (and would like to verify) that this is not yet supported. ^^

**Comment by smira** [comment]
@willemm would you mind posting your config patch so that we can check it? 

`insecureSkipVerify` should work

**Comment by willemm** [comment]
```
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: default
spec:
  configPatches:
  - op: add
    path: /machine/install/disk
    value: /dev/sda
  - op: add
    path: /machine/registries
    value:
      mirrors:
        ghcr.io:
          endpoints:
            - https://our.artifactory.server/v2/ghcr.io/
        k8s.gcr.io:
          endpoints:
            - https://our.artifactory.server/v2/k8s.gcr.io/
      config:
        registry.insecure:
          tls:
            insecureSkipVerify: true
  - op: add
    path: /machine/files
    value:
      - path: /etc/ssl/certs/ca-certificates
        permissions: 0644
        op: append
        content: |
          -----BEGIN CERTIFICATE-----
          Elided: certificate data
          -----END CERTIFICATE-----
  qualifiers:
    cpu:
      - manufacturer: Intel(R) Corporation
        version: Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz
```

(I first tried to give it our corporate rootca which is used to ssl-sign the cert of our local server but that didn't work either)

**Comment by andrewrynhard** [comment]
Posting here for posterity. Issue is that `registry.insecure` is an example hostname. In this case it should be `our.artifactory.server`.

**Comment by smira** [comment]
Probably our docs are a bit confusing, but entries under `config:` for `/machine/registries` are hostnames of the endpoints, so your patch should be:

```
- op: add
    path: /machine/registries
    value:
      mirrors:
        ghcr.io:
          endpoints:
            - https://our.artifactory.server/v2/ghcr.io/
        k8s.gcr.io:
          endpoints:
            - https://our.artifactory.server/v2/k8s.gcr.io/
      config:
        our.artifactory.server:
          tls:
            insecureSkipVerify: true
```

(s/registry.insecure/our.artifactory.server)

This page https://www.talos.dev/docs/v0.8/reference/configuration/#registriesconfig has examples
