### ISSUE TITLE
Containerd registry refactoring

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#3836]
## Feature Request

https://github.com/containerd/containerd/releases/tag/v1.5.0

registry.config_path

```toml
[plugins."io.containerd.grpc.v1.cri".registry]
   config_path = "/etc/containerd/certs.d"
```

```toml
server = "https://registry-1.docker.io"    # Exclude this to not use upstream

[host."https://public-mirror.example.com"]
  capabilities = ["pull"]                  # Requires less trust, won't resolve tag to digest from this host
[host."https://docker-mirror.internal"]
  capabilities = ["pull", "resolve"]
  ca = "docker-mirror.crt"                 # Or absolute path /etc/containerd/certs.d/docker.io/docker-mirror.crt
```

* containerd can reload registry configs without restart.
* capabilities parameters
