### ISSUE TITLE
SystemDisk and DATA partition

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#4041]
## Feature Request

May be this casein be useful only on bare-metal setup.

I have only 1Tb disk on the server. And i want to store some data (cache/database replica/zfs cache/and other cases) on this disk.
Sometimes the bad things happen with containerd/kubelet and very easy solution to solve it - just format the EPHEMERAL store. But we can lost the data (case from the slack)

So, proposal:

Add feature to create special (DATA) partition on the system disk.

```yaml
  install:
    dataMountPoint: /var/data
    ephemeralDiskSize: 64GB

    diskSelector:
      size: ">128GB"
    bootloader: true
  systemDiskEncryption:
    state:
      provider: luks2
      keys:
        - nodeID: {}
          slot: 0
    ephemeral:
      provider: luks2
      keys:
        - nodeID: {}
          slot: 0
    data:
      provider: luks2
      keys:
        - nodeID: {}
          slot: 0
```

I've added 2 new keys
* ephemeralDiskSize - if exist - the installer resize the ephemeral partition to this size, and all other free space allocate the the DATA partition
* dataMountPoint - if exist - format the DATA partition and mount it.

And keep possible to encrypt DATA store too. 

Thanks.

**Comment by sergelogvinov** [comment]
UPD.

```yaml

  install:
    dataMountPoint: /var/data
    osSize: 64GB # RenameMe

    diskSelector:
      size: ">128GB"
    bootloader: true
  systemDiskEncryption:
    state:
      provider: luks2
      keys:
        - nodeID: {}
          slot: 0
    ephemeral:
      provider: luks2
      keys:
        - nodeID: {}
          slot: 0
    data:
      provider: luks2
      keys:
        - nodeID: {}
          slot: 0
```

osSize (or another name) - full size of all system partitions (BOOT+META+STATE+EPHEMERAL)
We define the full size of the system which helps to upgrade system if count of partitions change.

**Comment by hobyte** [comment]
Is there any Update on this feature Request? In https://github.com/siderolabs/go-blockdevice/pull/50#issuecomment-929360451, the data partition is defered to v0.14, so is this feature still in development or is ist usable?

**Comment by smira** [comment]
there's still no clear decision on whether we want to have `DATA` partition or not on the system disk

**Comment by nickbp** [comment]
I was surprised to discover that I couldn't just configure this as part of the `machine.disks` config:
```
    - device: /dev/sda
      partitions:
      - mountpoint: /
        size: 64 GB
      - mountpoint: /var/mnt/data
        # size: rest of disk
```

(This technically validates as-is today, but doesn't seem to get anywhere)
