### ISSUE TITLE
signal mount status via resources

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#4133]
## Feature Request

In our mount code, create matching resource when something gets mounted and remove it when it gets unmounted.

Those resources can be used in controllers to start/stop doing some work. E.g. `STATE` partition mount status can be used to track when `STATE` can be used as a cache (e.g. for node ID).

### Description

```yaml
metadata:
  type: MountStatuses.runtime.talos.dev
  id: /system/state
spec:
  label: STATE
  source: /dev/sda5
  destination: /system/state
  ...
  flags: ...
```
