### ISSUE TITLE
KubeSpan and trusted zones

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#4369]
## Feature Request

Add capabilities to set CIDR subnet which disable wireguard encryptions.
Node to node encryption adds latency between pods on different nodes.
If you have huge traffic inside one datacenter and mtu 9000 it could potentially affect the service. 

It will be nice to have this feature...

**Comment by smira** [comment]
1. Filtering subnets which are sent over KubeSpan (basically limit the packet masking process, today KubeSpan targets all node addresses in the cluster except itself).
2. Filtering endpoints which can be used to establish a Wireguard tunnel (today we use all node addresses plus endpoints learned from other connections).

**Comment by smira** [comment]
Machine config example:

```yaml
machine:
  network:
     kubespan:
       enabled: true
       filterSubnets:
          destinations: # traffic to the subnets should go directly bypassing KubeSpan
             - 10.0.0.0/8
             - "!10.2.0.0/16"
           endpoints: # endpoints will be filtered before being attempted
             - 192.168.35.0/24
             - 172.20.0.0/16
```

Filtering is local to each machine, so proper filtering should be set up on each node. Two nodes should have symmetric filters for destinations, otherwise traffic might not flow correctly.
