### ISSUE TITLE
machine configuration to manage firewall

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#4421]
See https://github.com/sbezverk/nftableslib

First goal: define minimal but usable rule configuration we could put to the machine configuration. Format should be extensible in the future if we want to expand later.

- only ingress traffic
- if the port is defined in the rule, block everything which is not listed in `ingress:` section
- if the port is not defined in any rule, `NetworkDefaultAction` is applied

```yaml
kind: NetworkRuleConfig
portSelector:
  ports: [6443, 10250]
  protocol: tcp
ingress:
  - cidr: 10.0.0.0/8
  - cidr: 2000:fd00::/16
---
kind: NetworkRuleConfig
portSelector:
  ports: [80, 1000-2000]
  protocol: tcp
ingress:
  - cidr: 192.168.0.0/16
    except: 192.168.64.0/24
---
kind: NetworkDefaultActionConfig
ingress: allow/block
```
