### ISSUE TITLE
Update the release notes extraKernelArgs to sysctl.kernel.kexec_load_disabled=1

### ISSUE THREAD

**Issue by rgl** [siderolabs/talos#4445]
## Bug Report

The release notes at https://github.com/talos-systems/talos/releases/tag/v0.13.1 and https://github.com/talos-systems/talos/releases/tag/v0.14.0-alpha.0 describe the way to disable kexec as:

```yml
install:
  extraKernelArgs:
    - kexec_load_disabled=1
```

But that does not actually work. Instead it should be:

```yml
install:
  extraKernelArgs:
    - sysctl.kernel.kexec_load_disabled=1
```
