### ISSUE TITLE
MachineConfig.disks nofail and other options

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#4594]
Currently Talos reboots system if machine.disks.* is not found.

1. It will be grate skip that error, it helps to fix disk problems or any issues.
2. second disk can be hdd/ssd/nvmv and better to set mount options like ```noatime,discard```

machineconfig proposal

```yaml
machine:
  disks:
    - device: /dev/sdb
      nofail: true (default false)
      partitions:
        - mountpoint: /var/mnt/extra
          options: (default not exist)
            - noatime
            - discard
            - nofail
```
