### ISSUE TITLE
Example: rancher/local-path-provisioner

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#4938]
Very useful case to use with Talos cluster (home-lab-solution)

I'd like to save here one trick.
If you got the disk-pressure issue, and tryin to delete ```pvc```, the local-path helper cannot delete the store. 

Solution is
* add the tolerations and priorityClass to the helper
* use the /var/* folder to store the hostpath

```yaml
# part of  local-path-config configmap
  config.json: |-
    {
      "nodePathMap":[
        {
          "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths":["/var/local-path"] # example folder
        }
      ]
    }

  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      priorityClassName: system-node-critical
      tolerations:
      - key: node.kubernetes.io/disk-pressure
        operator: Exists
        effect: NoSchedule
      containers:
      - name: helper-pod
        image: busybox
        imagePullPolicy: IfNotPresent
```
