### ISSUE TITLE
talos enters reboot loop after installing on nvme

### ISSUE THREAD

**Issue by kilpikos** [siderolabs/talos#4985]
### Description

Installing Talos on Samsung SSD 980 500GB `/dev/nvme0n1` enters reboot loop with following error:

```
task mountEphemeralPartition (1/1): failed: error resizing filesystem: xfs_growfs: XFS_IOC_FSGROWFSDATA xfsctl failed: No space left on device
phase ephemeral (7/19) failed
```

Config was created with `talosctl gen config` command. Booting is via syslinux.efi PXE, 0.14.2 initrd and vmlinuz over http. This part seems to work just fine.

Same happens whether encrypting the disk or not. Also, I've been doing `nvme sanitize` between installs, both by resetting the key and zeroing the drive, to make sure the disk is "clean".

However, if I install it on 4TB WDC WD40EFZX-68A `/dev/sda`, it works (only change in controller.yaml being the disk). Or if I use Talos v0.13.5, it works (v0.15.0-alpha.2 does not work either).

### Logs

I'm unable to pull logs as it's in reboot loop.

Checked the disk layout by booting to Arch installer, and the disk layout looks like:

```
Found valid GPT with protective MBR; using GPT.
Disk /dev/nvme0n1: 976773168 sectors, 465.8 GiB
Model: Samsung SSD 980 500GB                   
Sector size (logical/physical): 512/512 bytes
Disk identifier (GUID): x-y-z
Partition table holds up to 128 entries
Main partition table begins at sector 2 and ends at sector 33
First usable sector is 34, last usable sector is 976773134
Partitions will be aligned on 64-sector boundaries
Total free space is 30 sectors (15.0 KiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1              64          204863   100.0 MiB   EF00  EFI
   2          204864          206911   1024.0 KiB  EF02  BIOS
   3          206912          821311   300.0 MiB   8300  BOOT
   4          821312          823359   1024.0 KiB  8300  META
   5          823360         1028159   100.0 MiB   8300  STATE
   6         1028160       976773134   465.3 GiB   8300  EPHEMERAL
```

### Environment

- Talos version: 0.14.2, 0.15.0-alpha.2
- Kubernetes version: N/A
- Platform: metal, zen3, b450, 1 nvme, 2 hdd

**Comment by kilpikos** [comment]
pretty much the default, only changed the disk (and added nomodeset):
```
    # Used to provide instructions for installations.
    install:
        disk: /dev/nvme0n1 # The disk used for installations.
        image: ghcr.io/talos-systems/installer:v0.14.2 # Allows for supplying the image used to perform the installation.
        bootloader: true # Indicates if a bootloader should be installed.
        wipe: false # Indicates if the installation disk should be wiped at installation time.

        # # Look up disk using disk attributes like model, size, serial and others.
        # diskSelector:
        #     size: 4GB # Disk size.
        #     model: WDC* # Disk model `/sys/block/<dev>/device/model`.

        # # Allows for supplying extra kernel args via the bootloader.
        extraKernelArgs:
            - nomodeset
        #     - talos.platform=metal
        #     - reboot=k
```
