### ISSUE TITLE
`apply-config` should disallow invalid extraVolumes in apiServer config

### ISSUE THREAD

**Issue by BobyMCbobs** [siderolabs/talos#5132]
### Description
If invalid config is set, `talosctl` should respond with failure on extraVolumes configuration for apiServer.

e.g:
```yaml
cluster:
  apiServer:
    extraVolumes:
      - hostPath: /etc/kubernetes/audit
```

This should fail since the requirement of the path beginning with _/var_
Currently, the node remains in a crashloop state

### Logs
`create operation not allowed outside of /var`

### Environment

- Talos version: v1.0.0-beta.0
- Kubernetes version: v1.23.4
- Platform: qemu
