### ISSUE TITLE
Unable to apply first-time machine configuration when using registry mirror

### ISSUE THREAD

**Issue by lcrockett** [siderolabs/talos#5195]
## Bug Report
It seems i'm unable to apply machine configuration to a newly provisioned node when using registry mirrors. The mirrors seem to work OK from other non-Talos nodes within the same network segment or if specified absolute in Talos machine configuration, however during deployment of Talos I seem to be unable to use registry mirrors as intended.

We have direct network access to our registry mirror (`Harbor`), which accepts HTTPS connections on port 443 and has a valid signed public certificate.

If we use absolute pointers to images that link to our registry mirror, there are no issues installing Talos, if we keep the original pointers and have `containerd` do the translation it seems to go belly up. See the 2 configurations here below depicting the difference between a unsuccessful and a successful Talos installation machine configuration.

We provision nodes using the Talos `v1.0.0-beta.2` OpenStack image and then apply prepared machine configuration using `talosctl apply-config --insecure ......`. Once applied we'd generally bootstrap whichever control plane shouts it's ready using `talosctl bootstrap .......`. Due to this issue we never reach the bootstrap stage as Talos is unable to deploy itself succesfully.

Considering the log output, are there options to see the actual response from the process pulling the image ? Considering the log message `unexpected media type text/html` i'm suspecting it may lead to useful extra information about what's going on. Most likely it will allow us to identify where and how it tries to pull images from.

Unfortunately we don't have access to our registry mirror logs to determine if it actually reaches the registry mirror and which URL's it's trying to use pulling images.

Any clues or options for us to further debug ? Setting the `debug` value to `true` doesn't render us with more useful information. Trying out earlier versions (`v1.0.0-beta.1` | `v1.0.0-beta.0` | `v0.14.3`) does not change this behaviour.

### Description

<details>
  <summary>Talos generated machine configuration :: Not working :: Using registry mirror</summary>

```yaml
version: v1alpha1
debug: false
persist: true
machine:
  type: controlplane
  token: <redacted>
  ca:
    crt: <redacted>
    key: <redacted>
  certSANs:
    - talos-control-plane-a8b.subnetwork.domain.tld
    - talos-control-plane.subnetwork.domain.tld
  kubelet:
    image: ghcr.io/talos-systems/kubelet:v1.23.5
    extraArgs:
      rotate-server-certificates: true
  network:
    hostname: talos-control-plane-a8b.subnetwork.domain.tld
    interfaces:
      - interface: eth0
        mtu: 1450
        dhcp: true
        vip:
          ip: <redacted>
  install:
    disk: /dev/vda
    extraKernelArgs:
      - initcall_blacklist=aoe_init
    image: ghcr.io/talos-systems/installer:v1.0.0-beta.2
    bootloader: true
    wipe: true
  files:
    - content: |
        -----BEGIN CERTIFICATE-----
        <redacted>
        -----END CERTIFICATE-----
      permissions: 0o644
      path: /etc/ssl/certs/ca-certificates
      op: append
  env:
    http_proxy: http://proxy.domain.tld:8080/
    https_proxy: http://proxy.domain.tld:8080/
    no_proxy: 10.123.23.0/24,0.0.0.0/32,.subnetwork.domain.tld,harbor.domain.tld
  time:
    disabled: false
    servers:
      - <redacted>
  sysctls:
    fs.inotify.max_user_instances: "256"
    net.ipv4.tcp_keepalive_intvl: "60"
    net.ipv4.tcp_keepalive_time: "600"
  registries:
    mirrors:
      docker.io:
        endpoints:
          - https://harbor.domain.tld/docker
      gcr.io:
        endpoints:
          - https://harbor.domain.tld/gcr
      ghcr.io:
        endpoints:
          - https://harbor.domain.tld/ghcr
      k8s.gcr.io:
        endpoints:
          - https://harbor.domain.tld/k8s
      quay.io:
        endpoints:
          - https://harbor.domain.tld/quay.io
  systemDiskEncryption:
    state:
      provider: luks2
      keys:
        - nodeID: {}
          slot: 0
    ephemeral:
      provider: luks2
      keys:
        - nodeID: {}
          slot: 0
  features:
    rbac: true
cluster:
  id: <redacted>
  secret: <redacted>
  controlPlane:
    endpoint: https://talos-control-plane.subnetwork.domain.tld:6443
  clusterName: <redacted>
  network:
    cni:
      name: none
    dnsDomain: cluster.local
    podSubnets:
      - 10.244.0.0/16
    serviceSubnets:
      - 10.96.0.0/12
  token: <redacted>
  aescbcEncryptionSecret: <redacted>
  ca:
    crt: <redacted>
    key: <redacted>
  aggregatorCA:
    crt: <redacted>
    key: <redacted>
  serviceAccount:
    key: <redacted>
  apiServer:
    image: k8s.gcr.io/kube-apiserver:v1.23.5
    extraArgs:
      enable-aggregator-routing: true
    certSANs:
      - talos-control-plane.subnetwork.domain.tld
    disablePodSecurityPolicy: true
    admissionControl:
      - name: PodSecurity
        configuration:
          apiVersion: pod-security.admission.config.k8s.io/v1alpha1
          defaults:
            audit: restricted
            audit-version: latest
            enforce: baseline
            enforce-version: latest
            warn: restricted
            warn-version: latest
          exemptions:
            namespaces:
              - kube-system
            runtimeClasses: []
            usernames: []
          kind: PodSecurityConfiguration
  controllerManager:
    image: k8s.gcr.io/kube-controller-manager:v1.23.5
  proxy:
    disabled: true
  scheduler:
    image: k8s.gcr.io/kube-scheduler:v1.23.5
  etcd:
    ca:
      crt: <redacted>
      key: <redacted>
  extraManifests:
    - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
    - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/high-availability.yaml
  inlineManifests:
    - name: cilium
      contents: |
        ---
        # Source: https://www.talos.dev/docs/v0.14/guides/deploying-cilium/#method-4-helm-manifests-inline-install
        apiVersion: v1
        kind: Namespace
        <snip snip>
```
</details>

<details>
  <summary>Talos generated machine configuration :: Working :: Using absolute image pointers</summary>

```yaml
version: v1alpha1
debug: false
persist: true
machine:
  type: controlplane
  token: <redacted>
  ca:
    crt: <redacted>
    key: <redacted>
  certSANs:
    - talos-control-plane-a8b.subnetwork.domain.tld
    - talos-control-plane.subnetwork.domain.tld
  kubelet:
    image: harbor.domain.tld/ghcr/talos-systems/kubelet:v1.23.5
    extraArgs:
      rotate-server-certificates: true
  network:
    hostname: talos-control-plane-a8b.subnetwork.domain.tld
    interfaces:
      - interface: eth0
        mtu: 1450
        dhcp: true
        vip:
          ip: <redacted>
  install:
    disk: /dev/vda
    extraKernelArgs:
      - initcall_blacklist=aoe_init
    image: harbor.domain.tld/ghcr/talos-systems/installer:v1.0.0-beta.2
    bootloader: true
    wipe: true
  files:
    - content: |
        -----BEGIN CERTIFICATE-----
        <redacted>
        -----END CERTIFICATE-----
      permissions: 0o644
      path: /etc/ssl/certs/ca-certificates
      op: append
  env:
    http_proxy: http://proxy.domain.tld:8080/
    https_proxy: http://proxy.domain.tld:8080/
    no_proxy: 10.123.23.0/24,0.0.0.0/32,.subnetwork.domain.tld,harbor.domain.tld
  time:
    disabled: false
    servers:
      - <redacted>
  sysctls:
    fs.inotify.max_user_instances: "256"
    net.ipv4.tcp_keepalive_intvl: "60"
    net.ipv4.tcp_keepalive_time: "600"
  systemDiskEncryption:
    state:
      provider: luks2
      keys:
        - nodeID: {}
          slot: 0
    ephemeral:
      provider: luks2
      keys:
        - nodeID: {}
          slot: 0
  features:
    rbac: true
cluster:
  id: <redacted>
  secret: <redacted>
  controlPlane:
    endpoint: https://talos-control-plane.subnetwork.domain.tld:6443
  clusterName: <redacted>
  network:
    cni:
      name: none
    dnsDomain: cluster.local
    podSubnets:
      - 10.244.0.0/16
    serviceSubnets:
      - 10.96.0.0/12
  token: <redacted>
  aescbcEncryptionSecret: <redacted>
  ca:
    crt: <redacted>
    key: <redacted>
  aggregatorCA:
    crt: <redacted>
    key: <redacted>
  serviceAccount:
    key: <redacted>
  apiServer:
    image: harbor.domain.tld/k8s/kube-apiserver:v1.23.5
    extraArgs:
      enable-aggregator-routing: true
    certSANs:
      - talos-control-plane.subnetwork.domain.tld
    disablePodSecurityPolicy: true
    admissionControl:
      - name: PodSecurity
        configuration:
          apiVersion: pod-security.admission.config.k8s.io/v1alpha1
          defaults:
            audit: restricted
            audit-version: latest
            enforce: baseline
            enforce-version: latest
            warn: restricted
            warn-version: latest
          exemptions:
            namespaces:
              - kube-system
            runtimeClasses: []
            usernames: []
          kind: PodSecurityConfiguration
  controllerManager:
    image: harbor.domain.tld/k8s/kube-controller-manager:v1.23.5
  proxy:
    disabled: true
  scheduler:
    image: harbor.domain.tld/k8s/kube-scheduler:v1.23.5
  etcd:
    image: harbor.domain.tld/gcr/etcd-development/etcd:v3.5.2
    ca:
      crt: <redacted>
      key: <redacted>
  coreDNS:
    image: harbor.domain.tld/docker/coredns/coredns:1.9.0
  extraManifests:
    - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
    - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/high-availability.yaml
  inlineManifests:
    - name: cilium
      contents: |
        ---
        # Source: https://www.talos.dev/docs/v0.14/guides/deploying-cilium/#method-4-helm-manifests-inline-install
        apiVersion: v1
        kind: Namespace
        <snip snip>
```
</details>

<details>
  <summary>Talos generated machine configuration :: Diff between non-working / working :: Left = non-working</summary>

```diff
14c14
<     image: ghcr.io/talos-systems/kubelet:v1.23.5
---
>     image: harbor.domain.tld/ghcr/talos-systems/kubelet:v1.23.5
29c29
<     image: ghcr.io/talos-systems/installer:v1.0.0-beta.2
---
>     image: harbor.domain.tld/ghcr/talos-systems/installer:v1.0.0-beta.2
52,68d51
<   registries:
<     mirrors:
<       docker.io:
<         endpoints:
<           - https://harbor.domain.tld/docker
<       gcr.io:
<         endpoints:
<           - https://harbor.domain.tld/gcr
<       ghcr.io:
<         endpoints:
<           - https://harbor.domain.tld/ghcr
<       k8s.gcr.io:
<         endpoints:
<           - https://harbor.domain.tld/k8s
<       quay.io:
<         endpoints:
<           - https://harbor.domain.tld/quay.io
107c90
<     image: k8s.gcr.io/kube-apiserver:v1.23.5
---
>     image: harbor.domain.tld/k8s/kube-apiserver:v1.23.5
131c114
<     image: k8s.gcr.io/kube-controller-manager:v1.23.5
---
>     image: harbor.domain.tld/k8s/kube-controller-manager:v1.23.5
135c118
<     image: k8s.gcr.io/kube-scheduler:v1.23.5
---
>     image: harbor.domain.tld/k8s/kube-scheduler:v1.23.5
136a120
>     image: harbor.domain.tld/gcr/etcd-development/etcd:v3.5.2
139a124,125
>   coreDNS:
>     image: harbor.domain.tld/docker/coredns/coredns:1.9.0
```  
</details>

### Logs

Console logs:
```shell
[ 1438.154645] [talos] service[cri](Running): Process Process(["/bin/containerd" "--address" "/run/containerd/containerd.sock" "--config" "/etc/cri/containerd.toml"]) started with PID 2603
[ 1438.213340] [talos] service[trustd](Running): Started task trustd (PID 2640) for container trustd
[ 1439.128867] [talos] service[etcd](Waiting): Waiting for service "cri" to be "up"
[ 1439.135533] [talos] service[cri](Running): Health check successful
[ 1439.136866] [talos] service[etcd](Preparing): Running pre state
[ 1439.141406] [talos] service[trustd](Running): Health check successful
[33mWARN[0m[1437] reference for unknown type: text/html         [33mdigest[0m="sha256:34d70ea66cf31c2cffa020863d58e993ccdaa1e06b52af3f96bf9517d1bd9995" [33mmediatype[0m=text/html [33msize[0m=901
[ 1439.271439] [talos] service[kubelet](Waiting): Waiting for service "cri" to be "up", time sync, network
[ 1439.274108] [talos] service[kubelet](Preparing): Running pre state
[ 1439.299779] [talos] service[etcd](Failed): Failed to run pre stage: failed to pull image "gcr.io/etcd-development/etcd:v3.5.2": 1 error(s) occurred:
[ 1439.302663]  failed to pull image "gcr.io/etcd-development/etcd:v3.5.2": failed to unpack image on snapshotter : unexpected media type text/html for sha256:34d70ea66cf31c2cffa020863d58e993ccdaa1e06b52af3f96bf9517d1bd9995: not found
[33mWARN[0m[1437] reference for unknown type: text/html         [33mdigest[0m="sha256:34d70ea66cf31c2cffa020863d58e993ccdaa1e06b52af3f96bf9517d1bd9995" [33mmediatype[0m=text/html [33msize[0m=901
[ 1439.396440] [talos] service[kubelet](Failed): Failed to run pre stage: 1 error(s) occurred:
[ 1439.398358]  failed to pull image "ghcr.io/talos-systems/kubelet:v1.23.5": failed to unpack image on snapshotter : unexpected media type text/html for sha256:34d70ea66cf31c2cffa020863d58e993ccdaa1e06b52af3f96bf9517d1bd9995: not found
[ 1454.858051] [talos] downloaded manifest "https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml" {"component": "controller-runtime", "controller": "k8s.ExtraManifestController"}
[ 1455.765175] [talos] downloaded manifest "https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/high-availability.yaml" {"component": "controller-runtime", "controller": "k8s.ExtraManifestController"}
```

### Environment

- Talos version: [`v1.0.0-beta.2`]
- Kubernetes version: [`1.23.5`]
- Platform: OpenStack

**Comment by frezbo** [comment]
does the harbor instance require auth, i see 401 in the logs

**Comment by lcrockett** [comment]
Only for namespaces that are non-public. The namespaces that act as registry mirrors are public and can be accessed without authentication. Hence why Talos deploys itself successfully when using absolute image pointers (`harbor.domain.tld/ghcr/talos-systems/kubelet:v1.23.5`). So we know that Harbor is actually working and serving out images as intended.

**Comment by rhaludir** [comment]
Harbor's docker API exists at its /v2/ endpoint; requests to just the base FQDN result in an attempt to serve the web UI via HTML.

So what you want your registry entries to look like for Harbor would be (i.e.):
```
registries:
    mirrors:
      docker.io:
        endpoints:
          - https://harbor.domain.tld/v2/docker
      gcr.io:
        endpoints:
          - https://harbor.domain.tld/v2/gcr
      ghcr.io:
        endpoints:
          - https://harbor.domain.tld/v2/ghcr
```

Hope this helps.
