### ISSUE TITLE
bond interface order is not preserved from machine configuration to resources

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#5207]
E.g. in the machine configuration:

```yaml
- name: bond0
  bond:
     interfaces:
        - eth1
        - eth0
```

When this gets converted to internal networking resources, order of links becomes alphabetical (based on resource IDs), and actual link order will be `eth0`, `eth1`
