### ISSUE TITLE
Registry TLS configuration is no longer optional

### ISSUE THREAD

**Issue by ammmze** [siderolabs/talos#5262]
## Bug Report
It looks like in Talos 1.0.0, the registry TLS configuration cannot be omitted.

### Description
In previous versions of Talos (e.g. I was on 0.14.0), I was able to configure image registry authentication details without specifying TLS configuration. When upgrading to 1.0.0, I began noticing some controller in Talos panicking when using the following registry configuration.

```yaml
# Used to configure the machine's container image registry mirrors.
registries:
    # Specifies TLS & auth configuration for HTTPS image registries.
    config:
        ghcr.io:
            # The auth configuration for this registry.
            auth:
                username: omitted # Optional registry authentication.
                password: omitted # Optional registry authentication.

```

### Logs
```
192.168.32.2: kern:    info: [2022-03-31T06:49:27.0704028Z]: init[1007]: segfault at 18 ip 0000000001acb0bb sp 000000c000689758 error 4 in init[400000+1ffd000]
192.168.32.2: kern:    info: [2022-03-31T06:49:27.0749598Z]: Code: 05 0a 35 cb 00 48 89 d1 e8 e2 76 94 fe 66 90 84 db 0f 85 6b ff ff ff 48 8b 4c 24 40 48 8b 51 20 48 8b 84 24 b8 00 00 00 ff d2 <48> 8b 48 18 48 89 d8 ff d1 48 85 c0 74 04 31 c0 eb 46 48 8b 4c 24
192.168.32.2: user: warning: [2022-03-31T06:49:27.0776998Z]: [talos] controller failed {"component": "controller-runtime", "controller": "files.CRIRegistryConfigController", "error": "controller \x5c"files.CRIRegistryConfigController\x5c" panicked: runtime error: invalid memory address or nil pointer dereference\x5cn\x5cngoroutine 221 [running]:\x5cnruntime/debug.Stack()\x5cn\x5ct/toolchain/go/src/runtime/debug/stack.go:24 +0x65\x5cngithub.com/cosi-project/runtime/pkg/controller/runtime.(*adapter).runOnce.func2()\x5cn\x5ct/.cache/mod/github.com/cosi-project/runtime@v0.0.0-20211216175730-264f8fcd1a4f/pkg/controller/runtime/adapter.go:401 +0x5d\x5cnpanic({0x27b6760, 0x4be7170})\x5cn\x5ct/toolchain/go/src/runtime/panic.go:1038 +0x215\x5cngithub.com/talos-systems/talos/internal/pkg/containers/cri/containerd.GenerateHosts({0x326a410, 0xc00028c4c8}, {0xc000845fb0, 0x15})\x5cn\x5ct/src/internal/pkg/containers/cri/containerd/hosts.go:154 +0x55b\x5cngithub.com/talos-systems/talos/internal/app/machined/pkg/controllers/files.(*CRIRegistryConfigController).Run(0xc000b0a000, {0x32...
```

### Environment

- Talos version:
  - ```
    Client:
        Tag:         v1.0.0
        SHA:         80167fd2
        Built:
        Go version:  go1.17.8
        OS/Arch:     darwin/amd64
    Server:
        NODE:        192.168.32.2
        Tag:         v1.0.0
        SHA:         80167fd2
        Built:
        Go version:  go1.17.8
        OS/Arch:     linux/amd64
        Enabled:     RBAC
    ```
- Kubernetes version: 
  - `Client Version: v1.23.1`
  - `Server Version: v1.23.5`
- Platform: Baremetal
