### ISSUE TITLE
talosctl config-patch failing

### ISSUE THREAD

**Issue by adamstirk-ct** [siderolabs/talos#5276]
### Description

I'm trying to apply a patch to the talos config but the patch is failing to apply when I run `talosctl gen config test https://test:6443 --config-patch @vmware.patch` and I get the following error.

```
generating PKI and tokens
failed to generate config bundle: error patching configs: failure applying rfc6902 patches to talos machine config: add operation does not apply: doc is missing path: "/cluster/extraManifests/-": missing value
```

The contents of vmware.patch are:
```yaml
- op: add
  path: /cluster/extraManifests/-
  value: "https://raw.githubusercontent.com/mologie/talos-vmtoolsd/master/deploy/unstable.yaml"
```

If I apply the same patch to the control plane by running `talosctl gen config test https://test:6443 --config-patch-control-plane @vmware.patch` it sucessfully applies it to the controlplane.yaml.

```
generating PKI and tokens
created /path/controlplane.yaml
created /path/worker.yaml
created /path/talosconfig
```

### Environment

- Talos version: v1.0.0
- Platform: Linux

**Comment by Unix4ever** [comment]
Hello! The reason why it doesn't work is that `/cluster/extraManifests` doesn't exist in the config by default.
You can fix the patch itself by changing it to:
```yaml
- op: add
  path: /cluster/extraManifests
  value: ["https://raw.githubusercontent.com/mologie/talos-vmtoolsd/master/deploy/unstable.yaml"]
```
