### ISSUE TITLE
[RFE] Expose network bridging options in MachineConfig

### ISSUE THREAD

**Issue by usrbinkat** [siderolabs/talos#5414]
### Description
Some deployment scenarios benefit from the creation of bridge type network interfaces. Requesting MachineConfig [NetworkConfig](https://www.talos.dev/v1.0/reference/configuration/#networkconfig) support declarative bridge interface configuration.

**Comment by Ulexus** [comment]
We seem to have lost the ability to define bridge interfaces in our machine config at all, in fact.

**Comment by smira** [comment]
```yaml
machine:
   network:
    interfaces:
      - name: bridge0
        bridge:
          stp:
            enabled: true/false # default true
          interfaces:
             - eth0
             - eth1
```

1. The link can't be part of a bridge and a bond at the same time.
2. The bridge can't be part of a bond.
3. The bond can be part of a bridge.
4. VLAN should be available on the bridge.
5. The bridge can't be part of a bridge.
6. The bridge slaves can't have any network configuration (like bond slaves).
