### ISSUE TITLE
Add support to wipe additional disks

### ISSUE THREAD

**Issue by ammmze** [siderolabs/talos#5485]
## Feature Request

It would be great if the talos installer could wipe additional disks during install and/or upgrade.

### Description

I envision something like the following configuration to wipe additional disks. It would allow you wipe multiple additional disks based on given selectors similar to the [install disk selector](https://www.talos.dev/v1.0/reference/configuration/#installdiskselector). Perhaps it would be useful wipe the disk on upgrade?

```yaml
machine:
  install:
    wipeDisks:
      # wipe disks that are 4GB on install or upgrade
      - on: [install, upgrade]
        selector:
          size: 4GB
      # wipe western digital disks
      - on: [install]
        selector:
          model: WDC*
```
