### ISSUE TITLE
kube-proxy extraArgs ignored

### ISSUE THREAD

**Issue by fredgate** [siderolabs/talos#5505]
## Bug Report
kube-proxy pod runs without args specified in the machine configuration file with key `cluster.proxy.extraArgs`

### Description

To change the bind address of kube-proxy for metrics, I edit the configuration file of each node as it :
```
cluster:
  ....
  proxy:
    image: 'k8s.gcr.io/kube-proxy:v1.21.6'
    extraArgs:
      metrics-bind-address: '10.80.1.1:10249'
```
and then apply it.
When I watch the pod, I see that the corresponding kube-proxy is restarted (but not recreated), and if I describe it, I see that its command line arguments did not change :
```
  containers:
  - name: kueb-proxy
    command:
    - /usr/local/bin/kube-proxy
    - --cluster-cidr=10.244.0.0/16
    - --conntrack-max-per-core=0
    - --hostname-override=$(NODE_NAME)
    - --kubeconfig=/etc/kubernetes/kubeconfig
    - --proxy-mode=iptables
```
I tried to delete the pod; it was recreated but still with the same command line.

When I changed the `cluster.scheduler.extraArgs` and `cluster.controllerManager.extraArgs` the corresponding pods were successfully recreated with the new command.

### Environment

- Talos version: `0.14.1`
- Kubernetes version: `1.21.6`
- Platform: `amd64`

**Comment by smira** [comment]
Talos doesn't update the manifests automatically for safety reasons. You need to run `talosctl upgrade-k8s -n <controlplanenodeIP> --to v1.23.5` to make it re-apply the manifests.

**Comment by smira** [comment]
https://www.talos.dev/v1.0/kubernetes-guides/upgrading-kubernetes/

**Comment by fredgate** [comment]
Yes but I don't want to upgrade kubernetes version. Just add a parameter to the `kube-proxy` command line.

Can I run the `upgrade-k8s` with the actual version ?
`talosctl upgrade-k8s -n <controlplanenodeIP> --to v1.21.6`

**Comment by frezbo** [comment]
| Can I run the upgrade-k8s with the actual version ?

yes, you can do `talosctl upgrade-k8s --to=<existing version>` This will pick up the k8s related changes in the manifest and apply them, other component versiosn will remain the same. You could see the diff with `talosctl upgrade-k8s --to=<existing version> --dry-run`

**Comment by smira** [comment]
I just noticed you're on 0.14, but it already supports this flow: https://www.talos.dev/v0.14/guides/upgrading-kubernetes/

**Comment by mrwulf** [comment]
I think this is an actual (and ongoing!) issue- I'm running v1.2.2 with kubernetes 1.23.4 and am seeing the same problem. I've just run through `talos apply-config`, `talos upgrade`, and `talos upgrade-k8s` again and the kube-proxy daemonset is still missing all of the extraArgs.

MachineConfig:
```
cluster:
  proxy:
    image: k8s.gcr.io/kube-proxy:v1.24.4
    extraArgs:
      feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
      metrics-bind-address: 0.0.0.0:10249
```

Daemonset:
```
      - command:
        - /usr/local/bin/kube-proxy
        - --cluster-cidr=10.244.0.0/16
        - --conntrack-max-per-core=0
        - --hostname-override=$(NODE_NAME)
        - --kubeconfig=/etc/kubernetes/kubeconfig
        - --proxy-mode=iptables
```
