### ISSUE TITLE
Support passing kernel module arguments

### ISSUE THREAD

**Issue by frezbo** [siderolabs/talos#5568]
## Feature Request

Support passing in kernel module arguments in talos machine config

### Description

Possible syntax:

```yaml
modules:
  - name: nvidia
    args:
      - foo=bar
```
