### ISSUE TITLE
User disk encryption

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#5735]
## Feature Request

Make possible to encrypt additional disks at boot time.

### Description

Talos takes us cloud agnostic solution. You can have one control plane for different worker nodes in different cloud providers. (virtual machine/bare-metal)

Most of CSIs love one type of environment. (the same type of the disk in the server) Someone can encrypt the disk, someone not. It is very hard to manage them.

And best way to do it on Talos side. Format/encrypt/mount additional disks at boot time. Or format/encrypt the disk and pass raw-block device to CSI.

For example, you want to make a database recovery tests and use spot instance with nvme. Unfortunately your spot-instance can be evicted. And the VM cannot clean the disk properly. If Talos encrypt the disk, your data is safe.

**Comment by smira** [comment]
```yaml
machine:
  disks:
    - device: /dev/sdb # The name of the disk to use.
      encryption: # optional, existing `EncryptionConfig` type
         keys:
            - nodeID: {}
              slot: 0
            - static: { passphrase: "xyz" }
              slot: 1
            - auto: {} # generate the passphrase automatically, store it in the `STATE`
              slot: 2
      # A list of partitions to create on the disk.
      partitions:
         - mountpoint: /var/mnt/extra
```
