### ISSUE TITLE
Support signature algorithm: SHA256-RSA (needed for kubeadm clusters)

### ISSUE THREAD

**Issue by wjentner** [siderolabs/talos#5783]
## Feature Request

I'm trying to add talos to an existing cluster that was created by kubeadm.
When trying to join a control plane node, etcd fails with:
```
[talos] controller failed {"component": "controller-runtime", "controller": "secrets.EtcdController", "error": "error generating etcd client certs: failed generating client key pair: unsupported signature algorithm: SHA256-RSA"}
```

### Description

For testing purposes, I've created a single node cluster that was initialized by kubeadm (v1.22.11):
```
kubeadm init --apiserver-advertise-address 192.168.0.2 --pod-network-cidr 11.224.0.0/16
```

| Hostname  | IP |
| ------------- | ------------- |
| test-master1  | 192.168.0.2  |
| talos-192-168-0-3 | 192.168.0.3  |

I then modified the controlplane.yaml as follows (cleaned of commented stuff):
```yaml
version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token: m9p44m...
    ca:
        crt: LS0tLS1CRUd...
        key: LS0tLS1CRUd...

    certSANs: []

    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.22.11

    network:
      interfaces:
        - interface: eth0
          addresses:
            - 192.168.0.3/21
          routes:
            - network: 0.0.0.0/0
              gateway: 192.168.0.1
          dhcp: false

    install:
        disk: /dev/sda
        image: ghcr.io/siderolabs/installer:v1.0.6
        bootloader: true
        wipe: false

    features:
        rbac: true

cluster:
    id: 6tPyMbyi...
    secret: AgjXkxQ76...
    controlPlane:
        endpoint: https://192.168.0.2:6443 
    clusterName: test-kubernetes

    network:
        dnsDomain: cluster.local 
        podSubnets:
            - 11.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12

        cni:
            name: custom
            urls:
                - https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml
                - https://projectcalico.docs.tigera.io/manifests/custom-resources.yaml
    
    # Obtain with `kubeadm create token`
    token: 9pr82f.8ntw9levfzpnes6k
    aescbcEncryptionSecret: FanOkB65uT...
    ca:
        # Obtain with ` cat /etc/kubernetes/pki/ca.crt | base64 -w0`
        crt: LS0tLS1CRUd...
        # Obtain with ` cat /etc/kubernetes/pki/ca.key | base64 -w0`
        key: LS0tLS1CRUd...

    aggregatorCA:
        crt: LS0tLS1CRUd...
        key: LS0tLS1CRUd...

    serviceAccount:
        key: LS0tLS1CRUd...


    apiServer:
        image: k8s.gcr.io/kube-apiserver:v1.22.11

        certSANs:
            - 192.168.0.2
            - 192.168.0.3
        disablePodSecurityPolicy: true

        extraArgs:
            # connect to the existing etcd and the new one
            etcd-servers: "https://192.168.0.2:2379,https://192.168.0.3:2379"

    controllerManager:
        image: k8s.gcr.io/kube-controller-manager:v1.22.11 


    proxy:
        image: k8s.gcr.io/kube-proxy:v1.22.11


    scheduler:
        image: k8s.gcr.io/kube-scheduler:v1.22.11


    discovery:
        enabled: true
        registries:
            kubernetes: {}
            service: {}

    etcd:
        ca:
            # Obtain with `cat /etc/kubernetes/pki/etcd/ca.crt | base64 -w0`
            crt: LS0tLS1CRUd...
            # Obtain with `cat /etc/kubernetes/pki/etcd/ca.key | base64 -w0`
            key: LS0tLS1CRUd...
        extraArgs:
            # connect to the existing cluster
            initial-cluster: "test-master1=https://192.168.0.2:2380,talos-192-168-0-3=https://192.168.0.3:2380"
            # do not attempt to overwrite the data
            initial-cluster-state: existing

    extraManifests: []

    inlineManifests: []
```
