### ISSUE TITLE
High-level Talos machine status

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#5789]
## Feature Request

Introduce a resource with the following structure:

Talos status:

```yaml
metadata:
  type: MachineStatus.talos.dev
spec:
   stage: <stage>
   status:
       ready: true/false # in Running/Booting stage
       # only if !ready, conditions depend on the $phase
       unmetConditions:
           - name: servicesReady
             reason: `etcd` is unhealthy
           - name: timeSync
             reason: can't resolve pool.ntp.org
           # - name: etcdHealthy
           #   severity: ... (later on)
           # - name: kubeletHealthy
           # - name: k8sControlPlaneHealthy
           # - name: networkReady
```

On resource change, Talos event should be emitted.

Stages:

- Booting (merge with Initializing?)
- Installing
- Maintenance
- Running
- Rebooting
- Shutting down
- Resetting
- Upgrading

```mermaid
graph TD;
    Booting-->Installing;
    Installing-->Rebooting;
    Booting-->Maintenance;
    Maintenance-->Booting;
    Booting-->Running;
    Running-->Upgrading;
    Running-->ShuttingDown;
    Running-->Resetting;
    Resetting-->Rebooting;
    Upgrading-->Rebooting;
    Resetting-->ShuttingDown;
```

### Description

Implementation ideas:

* controller which owns the resource and listens to existing events and transforms the resource accordingly
* put hooks to the sequencer/phases/... to mutate the resource
* emit additional events from the sequencer/phases/tasks, and make controller listen to them and mutate the resource
