### ISSUE TITLE
Upgrade hangs on 'task startAllServices (1/1): service "etcd" to be "up"'

### ISSUE THREAD

**Issue by scrayos** [siderolabs/talos#5794]
### Description

When I tried to upgrade a control-plane-node from version 1.0.6 to 1.1.0 (also happened during the upgrade from 1.0.5 to 1.0.6), the control plane node could not re-enter the cluster. I was able to observe the state of the cluster with `talosctl dmesg -f` during the upgrade and I've attached it below.

The only components that are installed on the cluster are cilium (in strict mode), rook-ceph  and rook-ceph-cluster. All of them are installed through helm.

### Configuration

This is the configuration for the control-plane-nodes (without the secrets of course):
```yaml
version: 'v1alpha1'
debug: false
persist: true
machine:
  type: 'controlplane'
  token: '<token>'
  ca:
    crt: '<certificate>'
    key: '<key>'
  network:
    nameservers:
    - '1.1.1.1'
    - '1.0.0.1'
    - '8.8.8.8'
    - '8.8.4.4'
  install:
    disk: '/dev/sda'
    image: 'ghcr.io/siderolabs/installer:v1.1.0'
    bootloader: true
    wipe: true
  time:
    disabled: false
    servers:
    - 'time.cloudflare.com'
    - 'time.google.com'
    - 'pool.ntp.org'
  sysctls:
    kernel.sysrq: 0
  features:
    # we do not need or use RBAC for the Talos API, only for Kubernetes
    rbac: false
cluster:
  id: '<id>'
  secret: '<secret>'
  controlPlane:
    endpoint: 'https://control.example.com:6443'
    localAPIServerPort: 6443
  clusterName: 'example-production'
  network:
    cni:
      # set no CNI, as we set it with helm to Cilium (eBPF)
      name: 'none'
    dnsDomain: 'cluster.local'
    podSubnets:
    - '10.244.0.0/16'
    serviceSubnets:
    - '10.96.0.0/12'
  token: '<token>'
  aescbcEncryptionSecret: '<secret>'
  ca:
    crt: '<certificate>'
    key: '<key>'
  aggregatorCA:
    crt: '<certificate>'
    key: '<key>'
  serviceAccount:
    key: '<key>'
  apiServer:
    image: 'k8s.gcr.io/kube-apiserver:v1.23.6'
    extraArgs:
      oidc-issuer-url: 'https://auth.example.com/auth/realms/master'
      oidc-client-id: 'kubernetes'
      oidc-username-claim: 'sub'
      oidc-username-prefix: 'oidc:'
      oidc-groups-claim: 'groups'
      oidc-groups-prefix: 'oidc:'
    certSANs:
    - 'control.scrayos.net'
    # pod security policy is deprecated, so we disable it
    disablePodSecurityPolicy: true
    admissionControl:
    - name: 'PodSecurity'
      configuration:
        apiVersion: 'pod-security.admission.config.k8s.io/v1alpha1'
        kind: 'PodSecurityConfiguration'
        defaults:
          audit: 'restricted'
          audit-version: 'latest'
          enforce: 'baseline'
          enforce-version: 'latest'
          warn: 'restricted'
          warn-version: 'latest'
        exemptions:
          namespaces:
          - 'kube-system'
          - 'rook-ceph'
          runtimeClasses: []
          usernames: []
  controllerManager:
    image: 'k8s.gcr.io/kube-controller-manager:v1.23.6'
  proxy:
    # we disable the kube-proxy because we exclusively use cilium for cluster networking
    disabled: true
  scheduler:
    image: 'k8s.gcr.io/kube-scheduler:v1.23.6'
  discovery:
    enabled: true
    registries:
      kubernetes: {}
      service: {}
  etcd:
    image: 'gcr.io/etcd-development/etcd:v3.5.3'
    ca:
      crt: '<crt>'
      key: '<key>'
  coreDNS:
    image: 'docker.io/coredns/coredns:1.9.2'
  extraManifests: []
  extraManifestHeaders: {}
  inlineManifests: []
  allowSchedulingOnMasters: false
  ```
I also tried deploying a new server without the explicit version pins (except for the installer version) but that also blocked during etcd. During the update from 1.0.5 to 1.0.6 I was only able to "fix" it by deploying a completely new cluster (and then freshly bootstraping etcd).

### Logs

The log from the [talos_log.txt](https://github.com/siderolabs/talos/files/8960762/talos_log.txt)

### Environment

- Talos version: 1.0.6
- Kubernetes version: 1.23.6
- Platform: Hetzner Cloud
- Setup: 3 control-plane nodes, 1 worker-node
