### ISSUE TITLE
Expose generic platform metadata

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#5839]
## Feature Request

Different CCMs (cloud control managers) use different methods to initialize the node.
Make API  call or receive values from meta-server.
Talos platform already knows what the node is. And has node metadata information.

Talos can expose those data through resource API. It will help make universal CCM for Talos (one CCM for all platforms), which will use the values to label the node (and other). I do not think that sharing raw metadata is a good idea. It can have sensitive data. CSI uses its own discovery methods and does not need such data..
 
In most the cases those values are enough:

* zone
* region
* instance id
* providerID (for native CCM)
* labels

Also, nice to have special talos RBAC account to access the data and call methods like
* get addresses
* get routes

**Comment by smira** [comment]
Sounds like interesting idea. I think `os:reader` role can already read any non-sensitive resource which probably includes all of the above.

**Comment by smira** [comment]
```yaml
metadata:
  id: <platform id>
  type: PlatformMetadata.talos.dev
spec:
  zone: us-east-1a
  region: us-east-1
  instanceId: <foo>
  providerId: 1abcd-eff11-45444
  labels:
     rack: rack-5
     position: 1U
```
