### ISSUE TITLE
allow Kubernetes node to be not registered

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#5847]
## Feature Request

Talos has some boot sequence actions which depend on the node being registered (e.g. labeling the node, uncordoning, etc.): we should provide a config option to disable node registration (kubelet `--register-node=false`) and skip those boot sequence actions.

**Comment by smira** [comment]
With `--register-node=false` `kubelet` eventually fails as the node is not registered.

Q: can we make it run forever in 'not registered' state?

**Comment by frezbo** [comment]
Kubelet has the option to run without registering to api server and just allow it to only support static pods:

```yaml
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
staticPodPath: "/etc/kubernetes/manifests"
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: false
authorization:
  mode: AlwaysAllow
clusterDNS:
  - 10.89.0.1
```
An example config is shown below, if the cni plugins are not installed kubelet logs would complain about missing cni's but static pods with `hostNetwork: true` would still work.

Kubelet can then be started as normal.

```bash
/usr/local/bin/kubelet --config=/opt/kubelet/kubelet-config.yaml --container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock
```
