### ISSUE TITLE
publish Kubernetes Node status as a Talos resource

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#5872]
## Feature Request

Status of the matching Kubernetes node:

```yaml
metadata:
  type: NodeStatus.talos.dev
spec:
```

See #5789
