### ISSUE TITLE
Adding extensions during install, doesn't activate the extension until we upgrade the node

### ISSUE THREAD

**Issue by jbmorgado** [siderolabs/talos#5956]
### Description
Adding an extension to during the installation phase like:

```
machine:
  install:
    extensions:
      - image: ghcr.io/siderolabs/iscsi-tools:v0.1.1 # System extension image.
```

Doesn't  pull the image into the node.

The only way to have the node actually pulling the extension is to issue:
```
talosctl -e <VIP IP> -n <NODE IP> upgrade --image=ghcr.io/siderolabs/installer:v1.1.1
```

After the node is upgraded, the extension is finally working on the node.

### Environment

- Talos version:
Client:
        Tag:         v1.1.1
        SHA:         40a050c6
        Built:
        Go version:  go1.18.4
        OS/Arch:     linux/amd64
Server:
        NODE:        192.168.1.212
        Tag:         v1.1.1
        SHA:         40a050c6
        Built:
        Go version:  go1.18.4
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```

- Kubernetes version:
```
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.24.2
```

- Platform:
VSphere 7
