### ISSUE TITLE
Talos API access through an authentication proxy

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#5980]
- server CA validation: might be nothing, if the server CA is publicly trusted
- several client authentication schemes:
   - (as it is today): client cert + key
   - Basic Auth
   - no auth (for development purposes)
   - other types auth (TBD)
 - optional `cluster` field to target a specific cluster behind a proxy
 - endpoint becomes endpoint of the authentication proxy

`talosconfig` today:

```yaml
    talos-default-457:
        endpoints:
            - 172.20.0.2
        ca: LS0tLS1CRUdJTiBDRV
        crt: LS0tLS1CRUd
        key: LS0t
```

`talosconfig` for going through an auth proxy:

```yaml
    talos-via-proxy:
        endpoints:
            - [https://]auth.proxy:453  # scheme is optional, `grpc://` for HTTP/2 h2c
        ca: LS0tLS1CRUdJTiBDRV # optional
        auth:
           basic:
              username: XYZ
              password: UIO
        cluster: my-lovely-cluster-1
```

`talosctl` new flags:

- `--cluster` flag
