### ISSUE TITLE
Talos: allow setting install configuration using a separate document

### ISSUE THREAD

**Issue by Unix4ever** [siderolabs/talos#6060]
The generated config for the machine may look like that:

```yaml
---
version: v1alpha1
kind: InstallConfig
spec:
   preserve: true
   disk: /dev/vda # immutable
   image: ghcr.io/siderolabs/installer:v1.2.0
   extraKernelArgs:
     - ...
   extensions:
     - ...

   # stretch goal
   installer_signature: ... # installer signature that verifies that some 
                            # particular Talos installer was used to install Talos
---
# machine config
version: v1alpha2
kind: MachineConfig
persist: true
machine:
  ...
cluster:
  ...
```

Enhance `talosctl apply-config` to support multidoc YAML configuration.

We can report errors if the user tries to modify fields which are immutable after the OS is installed.
