### ISSUE TITLE
Extension templating/placeholders

### ISSUE THREAD

**Issue by ammmze** [siderolabs/talos#6208]
## Feature Request
It would be great if there was some form of templating, or at least placeholder replacement in the Talos system extension image name/tag. So that it can inject the Talos version into the image tag, something like this:

```yaml
machine:
  install:
    extensions:
      - image: ghcr.io/siderolabs/gasket-driver:5993718-{TALOS_VERSION}
```

### Description
It looks like Talos now supports installing kernel modules via system extensions. However, it sounds like there is a caveat that the module need to be signed and as such would need to be released in step with the Talos version. This means each Talos upgrade would need to install a Talos version specific image. As such, it seems like it would be easy to cause issues during an upgrade by simply forgetting to update the machine config with the talos version you are going to be upgrading to. If we can templatize that image value to allow injecting the Talos version, this could allow that upgrade process to continue to be seamless.
