### ISSUE TITLE
Guide for installing talos with Calico?

### ISSUE THREAD

**Issue by depeo** [siderolabs/talos#6322]
Hello,

Sorry if this is the wrong forum to ask, but I didn't know where else to ask.
I have been trying to install Talos with Calico with this config-patch-control-plane, is it correct?

```
- op: add
  path: /machine/network
  value:
    hostname: k8s-cp-1.cluster.server.pink
    interfaces:
    - interface: eth0
      addresses:
        - 172.21.50.31/23
        - 2c06:25:f1cd:11:50::31/80
      routes:
        - gateway: 2c06:25:f1cd:11:50::1
        - gateway: 172.21.50.1
    nameservers:
    - 172.21.50.1

- op: add
  path: /cluster/controllerManager/extraArgs
  value:
    node-cidr-mask-size-ipv6: 90

- op: add
  path: /machine/install
  value:
    disk: /dev/vda
    wipe: true

- op: add
  path: /cluster/proxy
  value:
    disabled: true

- op: add
  path: /cluster/network
  value:
    dnsDomain: cluster.server.pink
    podSubnets:
    - 10.244.0.0/16
    - 2c06:25:f1cd:11:13::/80
    serviceSubnets:
    - 10.96.0.0/16
    - 2c06:25:f1cd:11:14::/112
- op: add
  path: /cluster/network/cni
  value:
    name: custom
    urls:
    - https://docs.projectcalico.org/manifests/calico.yaml
```
Everything comes up correctly, but in the logs it says "CNI not initialized", and the Kubernetes nodes are "not ready",  I have applied the correct BGP configuration via calioctl and the router is configured. 

I couldn't find any documentation about Calico and Talos, so my patch above is just me guessing.
