### ISSUE TITLE
network route mtu option

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#6324]
## Feature Request

Set MTU size for the route.

### Description

For instance, you have two data-centers and link between (gre/vxvlan and other methods).
Inside datacenter better to use 1500/9000 MTU size, but to reach the nodes from another - we need to use lower MTU size 1400.

This option solves this problem.

```
# machine config
interfaces:
    - interface: eth0 # The interface name.
      addresses:
        - 192.168.2.1/24
      routes:
        - network: 0.0.0.0/0
          gateway: 192.168.2.1
          metric: 1024 
        - network:192.168.1.0/24
          gateway: 192.168.2.1
          mtu: 1400  <-- new value
```
