### ISSUE TITLE
user disks without filesystems

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#6345]
Part of #6325

```yaml
machine:
  disks:
    - device: /dev/sdb # The name of the disk to use.
      partitions:
          - size: 10GiB
            # no mountpoint:, so no filesystem, no mounts
```
