### ISSUE TITLE
Raspberry pi gpio access

### ISSUE THREAD

**Issue by tyriis** [siderolabs/talos#6374]
Hello, I am using a pimoroni fanshim on my raspberry pi 4 devcice in my talos cluster. I can not access the gpio. I am using the official python script it outputs me:

```
pimoroni-fanshim-xt6cx Traceback (most recent call last):
pimoroni-fanshim-xt6cx   File "/app/main.py", line 161, in <module>
pimoroni-fanshim-xt6cx     fanshim = FanShim(disable_button=NOBUTTON, disable_led=NOLED)
pimoroni-fanshim-xt6cx   File "/opt/venv/lib/python3.10/site-packages/fanshim/__init__.py", line 32, in __init__
pimoroni-fanshim-xt6cx     GPIO.setup(self._pin_fancontrol, GPIO.OUT)
pimoroni-fanshim-xt6cx RuntimeError: No access to /dev/mem.  Try running as root!
```

The pod is configured with full privileges:

```yaml
containers:
  - name: pimoroni-fanshim
    securityContext:
    privileged: true
    runAsUser: 0
    allowPrivilegeEscalation: true
    runAsNonRoot: false
    capabilities:
      add:
        - ALL
```

Would really love to make it work to cool the little guy down.
Did I just missed something in my talos config or in my definition to mount /dev/mem f.e.? (this configuration even without the root user has worked in a cluster based on raspbian).

mounting the indicated /dev/mem into my pod and adjusting the privileges:

```
Traceback (most recent call last):
  File "/app/main.py", line 11, in <module>
    from fanshim import FanShim
  File "/opt/venv/lib/python3.10/site-packages/fanshim/__init__.py", line 1, in <module>
    import RPi.GPIO as GPIO
  File "/opt/venv/lib/python3.10/site-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!
```

after googling i was pointed to an older version of RPi.GPIO, but this is the latest build

```yaml
securityContext:
  runAsUser: 0
  allowPrivilegeEscalation: false
  capabilities:
    add:
      - ALL
```
