### ISSUE TITLE
Cannot create more than 92 VLAN subinterfaces on bond

### ISSUE THREAD

**Issue by hainesbg** [siderolabs/talos#6477]
## Bug Report
Unable to create more than 92 VLAN subinterfaces on bond without the installer hanging and eventually failing while attempting to contact an NTP server (erroring with network unreachable).

### Description
Using Sidero on Gen14 Dell hardware, the following configPatch works, however adding any more VLANs to the array results in a failed installation, apparently due to an inability to reach an NTP server due to a "network unreachable" on the console.

```
      - op: add
        path: /machine/network/interfaces
        value:
        - interface: bond0
          bond:
            mode: 802.3ad
            lacpRate: fast
            xmitHashPolicy: layer2+3
          dhcp: true
          mtu: 9000
          vlans:

          - vlanId: 3072
            dhcp: false
          - vlanId: 3073
            dhcp: false
          - vlanId: 3074
            dhcp: false
          - vlanId: 3075
            dhcp: false
          - vlanId: 3076
            dhcp: false
          - vlanId: 3077
            dhcp: false
          - vlanId: 3078
            dhcp: false
          - vlanId: 3079
            dhcp: false
          - vlanId: 3080
            dhcp: false
          - vlanId: 3081
            dhcp: false
          - vlanId: 3082
            dhcp: false
          - vlanId: 3083
            dhcp: false
          - vlanId: 3084
            dhcp: false
          - vlanId: 3085
            dhcp: false
          - vlanId: 3086
            dhcp: false
          - vlanId: 3087
            dhcp: false
          - vlanId: 3088
            dhcp: false
          - vlanId: 3089
            dhcp: false
          - vlanId: 3090
            dhcp: false
          - vlanId: 3091
            dhcp: false
          - vlanId: 3092
            dhcp: false
          - vlanId: 3093
            dhcp: false
          - vlanId: 3094
            dhcp: false
          - vlanId: 3095
            dhcp: false
          - vlanId: 3096
            dhcp: false
          - vlanId: 3097
            dhcp: false
          - vlanId: 3098
            dhcp: false
          - vlanId: 3099
            dhcp: false
          - vlanId: 3100
            dhcp: false
          - vlanId: 3101
            dhcp: false
          - vlanId: 3102
            dhcp: false
          - vlanId: 3103
            dhcp: false

          - vlanId: 3104
            dhcp: false
          - vlanId: 3105
            dhcp: false
          - vlanId: 3106
            dhcp: false
          - vlanId: 3107
            dhcp: false
          - vlanId: 3108
            dhcp: false
          - vlanId: 3109
            dhcp: false
          - vlanId: 3110
            dhcp: false
          - vlanId: 3111
            dhcp: false
          - vlanId: 3112
            dhcp: false
          - vlanId: 3113
            dhcp: false
          - vlanId: 3114
            dhcp: false
          - vlanId: 3115
            dhcp: false
          - vlanId: 3116
            dhcp: false
          - vlanId: 3117
            dhcp: false
          - vlanId: 3118
            dhcp: false
          - vlanId: 3119
            dhcp: false
          - vlanId: 3120
            dhcp: false
          - vlanId: 3121
            dhcp: false
          - vlanId: 3122
            dhcp: false
          - vlanId: 3123
            dhcp: false
          - vlanId: 3124
            dhcp: false
          - vlanId: 3125
            dhcp: false
          - vlanId: 3126
            dhcp: false
          - vlanId: 3127
            dhcp: false
          - vlanId: 3128
            dhcp: false
          - vlanId: 3129
            dhcp: false
          - vlanId: 3130
            dhcp: false
          - vlanId: 3131
            dhcp: false
          - vlanId: 3132
            dhcp: false
          - vlanId: 3133
            dhcp: false
          - vlanId: 3134
            dhcp: false
          - vlanId: 3135
            dhcp: false

          - vlanId: 3136
            dhcp: false
          - vlanId: 3137
            dhcp: false
          - vlanId: 3138
            dhcp: false
          - vlanId: 3139
            dhcp: false
          - vlanId: 3140
            dhcp: false
          - vlanId: 3141
            dhcp: false
          - vlanId: 3142
            dhcp: false
          - vlanId: 3143
            dhcp: false
          - vlanId: 3144
            dhcp: false
          - vlanId: 3145
            dhcp: false
          - vlanId: 3146
            dhcp: false
          - vlanId: 3147
            dhcp: false
          - vlanId: 3148
            dhcp: false
          - vlanId: 3149
            dhcp: false
          - vlanId: 3150
            dhcp: false
          - vlanId: 3151
            dhcp: false

          - vlanId: 3152
            dhcp: false
          - vlanId: 3153
            dhcp: false
          - vlanId: 3154
            dhcp: false
          - vlanId: 3155
            dhcp: false
          - vlanId: 3156
            dhcp: false
          - vlanId: 3157
            dhcp: false
          - vlanId: 3158
            dhcp: false
          - vlanId: 3159
            dhcp: false

          - vlanId: 3160
            dhcp: false
          - vlanId: 3161
            dhcp: false
          - vlanId: 3162
            dhcp: false
          - vlanId: 3163
            dhcp: false
```

### Logs
```
{"clock":108193638,"cluster":"cluster-0","facility":"user","machine":"cluster-0-cp-dmrdb","metal_machine":"cluster-0-cp-h6pgn","msg":"[talos] fetching machine config from: \"http://10.160.0.24:8081/configdata?uuid=4c4c4544-0036-5210-8058-b8c04f4d3833\"\n","namespace":"default","priority":"warning","seq":1540,"server_uuid":"4c4c4544-0036-5210-8058-b8c04f4d3833","talos-level":"warn","talos-time":"2022-11-03T16:26:31.947073586Z"}
{"clock":108354078,"cluster":"cluster-0","facility":"user","machine":"cluster-0-cp-dmrdb","metal_machine":"cluster-0-cp-h6pgn","msg":"[talos] adjusting time (jump) by 6.953275848s via 23.157.160.168, state TIME_OK, status STA_NANO {\"component\": \"controller-runtime\", \"controller\": \"time.SyncController\"}\n","namespace":"default","priority":"warning","seq":1541,"server_uuid":"4c4c4544-0036-5210-8058-b8c04f4d3833","talos-level":"warn","talos-time":"2022-11-03T16:26:32.107513586Z"}
{"clock":108570686,"cluster":"cluster-0","facility":"user","machine":"cluster-0-cp-dmrdb","metal_machine":"cluster-0-cp-h6pgn","msg":"[talos] synchronized RTC with system clock {\"component\": \"controller-runtime\", \"controller\": \"time.SyncController\"}\n","namespace":"default","priority":"warning","seq":1542,"server_uuid":"4c4c4544-0036-5210-8058-b8c04f4d3833","talos-level":"warn","talos-time":"2022-11-03T16:26:32.324121586Z"}
{"clock":108733575,"cluster":"cluster-0","facility":"user","machine":"cluster-0-cp-dmrdb","metal_machine":"cluster-0-cp-h6pgn","msg":"[talos] task loadConfig (1/1): storing config in memory\n","namespace":"default","priority":"warning","seq":1543,"server_uuid":"4c4c4544-0036-5210-8058-b8c04f4d3833","talos-level":"warn","talos-time":"2022-11-03T16:26:32.487010586Z"}
{"clock":108822952,"cluster":"cluster-0","facility":"user","machine":"cluster-0-cp-dmrdb","metal_machine":"cluster-0-cp-h6pgn","msg":"[talos] task loadConfig (1/1): done, 781.302106ms\n","namespace":"default","priority":"warning","seq":1544,"server_uuid":"4c4c4544-0036-5210-8058-b8c04f4d3833","talos-level":"warn","talos-time":"2022-11-03T16:26:32.576387586Z"}
{"clock":108903991,"cluster":"cluster-0","facility":"user","machine":"cluster-0-cp-dmrdb","metal_machine":"cluster-0-cp-h6pgn","msg":"[talos] phase config (5/5): done, 930.463429ms\n","namespace":"default","priority":"warning","seq":1545,"server_uuid":"4c4c4544-0036-5210-8058-b8c04f4d3833","talos-level":"warn","talos-time":"2022-11-03T16:26:32.657426586Z"}
{"clock":108981116,"cluster":"cluster-0","facility":"user","machine":"cluster-0-cp-dmrdb","metal_machine":"cluster-0-cp-h6pgn","msg":"[talos] setting time servers {\"component\": \"controller-runtime\", \"controller\": \"network.TimeServerSpecController\", \"addresses\": [\"172.17.0.5\"]}\n","namespace":"default","priority":"warning","seq":1546,"server_uuid":"4c4c4544-0036-5210-8058-b8c04f4d3833","talos-level":"warn","talos-time":"2022-11-03T16:26:32.734551586Z"}
{"clock":109170669,"cluster":"cluster-0","facility":"user","machine":"cluster-0-cp-dmrdb","metal_machine":"cluster-0-cp-h6pgn","msg":"[talos] initialize sequence: done: 9.769918493s\n","namespace":"default","priority":"warning","seq":1547,"server_uuid":"4c4c4544-0036-5210-8058-b8c04f4d3833","talos-level":"warn","talos-time":"2022-11-03T16:26:32.924104586Z"}
{"clock":109249259,"cluster":"cluster-0","facility":"user","machine":"cluster-0-cp-dmrdb","metal_machine":"cluster-0-cp-h6pgn","msg":"[talos] adjusting time (slew) by 2.180353ms via 172.17.0.5, state TIME_OK, status STA_PLL | STA_NANO {\"component\": \"controller-runtime\", \"controller\": \"time.SyncController\"}\n","namespace":"default","priority":"warning","seq":1548,"server_uuid":"4c4c4544-0036-5210-8058-b8c04f4d3833","talos-level":"warn","talos-time":"2022-11-03T16:26:33.002694586Z"}
{"clock":109471616,"cluster":"cluster-0","facility":"user","machine":"cluster-0-cp-dmrdb","metal_machine":"cluster-0-cp-h6pgn","msg":"[talos] install sequence: 13 phase(s)\n","namespace":"default","priority":"warning","seq":1549,"server_uuid":"4c4c4544-0036-5210-8058-b8c04f4d3833","talos-level":"warn","talos-time":"2022-11-03T16:26:33.225051586Z"}
{"clock":109539427,"cluster":"cluster-0","facility":"user","machine":"cluster-0-cp-dmrdb","metal_machine":"cluster-0-cp-h6pgn","msg":"[talos] phase validateConfig (1/13): 1 tasks(s)\n","namespace":"default","priority":"warning","seq":1550,"server_uuid":"4c4c4544-0036-5210-8058-b8c04f4d3833","talos-level":"warn","talos-time":"2022-11-03T16:26:33.292862586Z"}
{"clock":109617721,"cluster":"cluster-0","facility":"user","machine":"cluster-0-cp-dmrdb","metal_machine":"cluster-0-cp-h6pgn","msg":"[talos] task validateConfig (1/1): starting\n","namespace":"default","priority":"warning","seq":1551,"server_uuid":"4c4c4544-0036-5210-8058-b8c04f4d3833","talos-level":"warn","talos-time":"2022-11-03T16:26:33.371156586Z"}
```

### Environment

- Talos version: v1.2.0 (according to the logs in sidero-controller-manager's serverlogs)
- Kubernetes version: v1.22.15
- Platform: Intel x86-64
