### ISSUE TITLE
bootstrap: time is not in sync yet

### ISSUE THREAD

**Issue by pratikbin** [siderolabs/talos#6493]
### Description

```shell
cd /tmp \
  && wget -O /tmp/talos.tar.gz \
  https://github.com/siderolabs/talos/releases/download/v1.2.6/metal-amd64.tar.gz \
  && tar xzOf talos.tar.gz | dd of=/dev/nvme0n1 && sync

export NODE_IP=xx.xx.xx.xx
talosctl gen config "asguard-test" "https://$NODE_IP:6443"

talosctl apply-config --insecure \
  --nodes $NODE_IP \
  --file ./controlplane.yaml

sed -i 's/127.0.0.1/$$NODE_IP/g' talosconfig
talosctl --talosconfig talosconfig bootstrap --nodes $NODE_IP
```

![image](https://user-images.githubusercontent.com/68642400/201508104-76d04a71-36c8-404c-b276-d064bbfa1242.png)

### Logs

```log
$ talosctl --talosconfig talosconfig bootstrap --nodes $NODE_IP

error executing bootstrap: 1 error occurred:
        * xx.xx.xx.xx: rpc error: code = FailedPrecondition desc = time is not in sync yet
```

### Environment

```yaml
...
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.25.3 # The `image` field is an optional reference to an alternative kubelet image.
        defaultRuntimeSeccompProfileEnabled: true # Enable container runtime default Seccomp profile.

...

```

```shell
$ talosctl version  
Client:
        Tag:         v1.2.6
        SHA:         6ca8b2ac
        Built:       
        Go version:  go1.19.2
        OS/Arch:     darwin/amd64
...
```

- Platform: Hetzner robot server with `x86`

**Comment by pratikbin** [comment]
Tried enabling... But same issue

```yaml
...
    # # Example configuration for cloudflare ntp server.
    time:
        disabled: false # Indicates if the time service is disabled for the machine.
        # Specifies time (NTP) servers to use for setting the system time.
        servers:
            - time.cloudflare.com
        bootTimeout: 2m0s # Specifies the timeout when the node time is considered to be in sync unlocking the boot sequence.
...
```

![image](https://user-images.githubusercontent.com/68642400/201508061-36cb918c-33fd-461b-88b5-65d29baaaa3f.png)

**Comment by pratikbin** [comment]
After a few minutes, I was able `talosctl --talosconfig talosconfig bootstrap --nodes $NODE_IP` but `kubectl get po` is timing out

![image](https://user-images.githubusercontent.com/68642400/201508266-63c8d018-5198-4ca1-bb18-4aa6af0e6a04.png)

**Comment by smira** [comment]
What is this question in this issue? Hetzner seems to be blocking NTP traffic, there's nothing we can do about it on Talos side.

Hetzner seems to be running its own NTP servers: https://community.hetzner.com/tutorials/install-and-configure-ntp

You need to either use NTP servers which work in your environment or disable NTP.

Timeout on accessing Kubernets control plane might be completely unrelated: https://www.talos.dev/v1.2/advanced/troubleshooting-control-plane/

**Comment by pratikbin** [comment]
Not getting anything in `kubectl get pod` or it's not even timing out

**Comment by pratikbin** [comment]
@smira how can I disable NTP?

**Comment by pratikbin** [comment]
> @smira how can I disable NTP?

Got it.

```yaml
...
    # # Example configuration for cloudflare ntp server.
    time:
        disabled: true # Indicates if the time service is disabled for the machine.
        # Specifies time (NTP) servers to use for setting the system time.
...

```
