### ISSUE TITLE
Publish IBM Cloud VPC Gen2 Image

### ISSUE THREAD

**Issue by FischerLGLN** [siderolabs/talos#6637]
## Feature Request
Publishing an IBM Cloud compatible Image would allow us to use their GPUs via Edge Computing.
### Description
I think the platform dependent code needs to be added here: https://github.com/siderolabs/talos/tree/main/internal/app/machined/pkg/runtime/v1alpha1/platform

I can provide docs instructions how to create LoadBalancer and Server instances via CLI.
Since I have an IBM Cloud Account, how can I build an image for this platform?
Thanks!

**Comment by FischerLGLN** [comment]
Similar Issue: https://github.com/siderolabs/talos/issues/6638

**Comment by smira** [comment]
In general, Talos platform is required if the cloud provides additional metadata that Talos could use - e.g. user metadata, network configuration, etc.

Generic `metal` should still boot, but it won't have any specific support for the IBM Cloud.

Developing and supporting a new platform is a significant amount of work and testing to make this possible.

**Comment by FischerLGLN** [comment]
> In general, Talos platform is required if the cloud provides additional metadata that Talos could use - e.g. user metadata, network configuration, etc.
> 
> Generic `metal` should still boot, but it won't have any specific support for the IBM Cloud.
> 
> Developing and supporting a new platform is a significant amount of work and testing to make this possible.

Thanks! Using the metal image in a VM environment leads to a DHCP error:
renew failed ... dhcp4 error ... no matching response packet received ... link: "eth0"

The network interface in the IBM VM has the name primary instead of eth0.

@smira Can I change that in worker.yaml and set DHCP to false, since I already get a IP assigned through VM?

```yaml
network:
        # Configures KubeSpan feature.
        kubespan:
            enabled: true # Enable the KubeSpan feature.
        
        # # `interfaces` is used to define the network interface configuration.
        # interfaces:
        #     - interface: primary
        #       dhcp: false
```
