### ISSUE TITLE
Custom resource and ManifestApplyController

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#6663]
## Bug Report

I am trying to check everything before [CCM](https://github.com/siderolabs/talos-cloud-controller-manager) release. 
And have config-apply error `error creating /v1/ServiceAccount/talos-cloud-controller-manager: the server does not allow this method on the requested resource`

Part of the machine config

```yaml
  externalCloudProvider:
    enabled: true
    manifests:
      - https://raw.githubusercontent.com/siderolabs/talos-cloud-controller-manager/main/docs/deploy/cloud-controller-manager.yml
```

### Logs

```
172.16.0.11: user: warning: [2022-12-19T14:50:07.815678619Z]: [talos] controller failed {"component": "controller-runtime", "controller": "k8s.ManifestApplyController", "error": "4 errors occurred:\x5cn\x5ct* error creating /v1/ServiceAccount/talos-cloud-controller-manager: the server does not allow this method on the requested resource\x5cn\x5ct* error creating mapping for object talos.dev/v1alpha1/ServiceAccount/talos-cloud-controller-manager-talos-secrets: no matches for kind \x5c"ServiceAccount\x5c" in version \x5c"talos.dev/v1alpha1\x5c"\x5cn\x5ct* error creating /v1/ConfigMap/talos-cloud-controller-manager: the server does not allow this method on the requested resource\x5cn\x5ct* error creating apps/v1/Deployment/talos-cloud-controller-manager: the server does not allow this method on the requested resource\x5cn\x5cn"}
...
# and infinity loop
172.16.0.11: user: warning: [2022-12-19T14:52:39.217470342Z]: [talos] controller failed {"component": "controller-runtime", "controller": "k8s.ManifestApplyController", "error": "error creating talos.dev/v1alpha1/ServiceAccount/talos-cloud-controller-manager-talos-secrets: the server could not find the requested resource"}

```

### Environment

- Talos version: [1.3.0]
- Kubernetes version: [`kubectl version --short`]
- Platform:
