### ISSUE TITLE
Restart extension service does not work

### ISSUE THREAD

**Issue by abckey** [siderolabs/talos#6707]
## Bug Report
Restart extension service does not work

### Description
Restart an extension service cause the service get into "Finished" status, not restarted

### Logs

```
* before restart
> talosctl services ext-frr
NODE     10.129.162.51
ID       ext-frr
STATE    Running
HEALTH   ?
EVENTS   [Running]: Started task ext-frr (PID 3231) for container ext-frr (20h20m21s ago)
         [Preparing]: Creating service runner (20h20m23s ago)
         [Preparing]: Running pre state (20h20m23s ago)
         [Waiting]: Waiting for service "containerd" to be "up" (20h20m33s ago)

*  run service restart
> talosctl service ext-frr restart
NODE            RESPONSE
10.129.162.51   Service "ext-frr" restarted

* after service restart
> talosctl services ext-frr
NODE     10.129.162.51
ID       ext-frr
STATE    Finished
HEALTH   ?
EVENTS   [Finished]: Service finished successfully (35s ago)
         [Stopping]: Sending SIGTERM to task ext-frr (PID 3231, container ext-frr) (35s ago)
         [Running]: Started task ext-frr (PID 3231) for container ext-frr (20h24m9s ago)
         [Preparing]: Creating service runner (20h24m10s ago)
         [Preparing]: Running pre state (20h24m10s ago)
         [Waiting]: Waiting for service "containerd" to be "up" (20h24m21s ago)
```

### Environment

- Talos version: [`v1.2.7`]
- Kubernetes version: [`v1.23.14`]
- Platform: Baremetal deployed by sidero

### extension service definition frr.yaml

```
name: frr
container:
  entrypoint: /sbin/tini
  args:
    - --
    - /usr/lib/frr/docker-start
  security:
    writeableRootfs: true
    writeableSysfs: true
restart: always
```
