### ISSUE TITLE
VMware: Use network information from guestinfo.metadata

### ISSUE THREAD

**Issue by ErikLundJensen** [siderolabs/talos#6708]
## Feature Request
Given a setup containing Cluster API with VMware (CAPV) and Talos (CABPT / CACPPT ) and [IPAM InCluster](https://github.com/telekom/cluster-api-ipam-provider-in-cluster) then IP addresses can be allocated of pool of IP addresses.
The field `addressesFromPools` in `VSphereMachineTemplate` specify which pool to use.

CAPV generates the `guestinfo.metadata` with an IP address from the pool for each virtual machine, however, Talos does not read `guestinfo.metadata`.

The Talos implementation of integration with VMware platform should be like the `nocloud` implementation where `guestinfo.metadata` is used and injected into the virtual machine's network configuration.

### Description

Here is a sample of `guestinfo.metadata` produced by CAPV:
```
instance-id: "vmware-test-controlplane-zhnhr"
local-hostname: "vmware-test-controlplane-zhnhr"
wait-on-network:
  ipv4: false
  ipv6: false
network:
  version: 2
  ethernets:
    id0:
      match:
        macaddress: "00:50:41:b3:71:44"
      set-name: "eth0"
      wakeonlan: true
      addresses:
      - "192.168.0.230/24"
      gateway4: "192.168.0.1"
```

The `nocloud` implementation of reading and using `guestinfo.metadata`could be reused in the [VMware platform](https://github.com/siderolabs/talos/blob/96629d5ba6c1ae9d820824fb38f68112bce27f2c/internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go).
[metadata.go](https://github.com/siderolabs/talos/blob/main/internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go)

### Why is this needed?

See detailed explaination here [IPAM support proposal](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/proposal/20220929-ipam-support.md)
