### ISSUE TITLE
Configuration patch adds "mtu: 0" to output machine network config when not specified in patch

### ISSUE THREAD

**Issue by interdependence** [siderolabs/talos#6747]
## Bug Report

Creating a default cluster config using:

```
talosctl gen config <cluster-name> <cluster-endpoint>
```

Then using a patch file containing:
```yaml
machine:
  network:
    hostname: controlplane-1
    interfaces:
      - interface: eth0
        addresses:
          - 192.168.3.2
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.3.1
        dhcp: true
        vip:
          ip: 192.168.3.250
```

Then running:

```
talosctl machineconfig patch controlplane.yaml --patch @controlplane-1.patch --output controlplane-1.yaml
```

Produces:
```yaml
...
    network:
        hostname: controlplane-1
        interfaces:
            - interface: eth0
              addresses:
                - 192.168.3.2
              routes:
                - network: 0.0.0.0/0
                  gateway: 192.168.3.1
              mtu: 0
              dhcp: true
              vip:
                ip: 192.168.3.250
...
```

### Environment

- Talos version:

Client:
	Tag:         v1.3.2
	SHA:         92d60ffd
	Built:       
	Go version:  go1.19.4
	OS/Arch:     linux/amd64
