### ISSUE TITLE
Strategic merge patching on machine.network.interfaces.vlans

### ISSUE THREAD

**Issue by michael-robbins** [siderolabs/talos#6884]
## Feature Request
Currently [strategic merge patches](https://www.talos.dev/v1.3/talos-guides/configuration/patching/#strategic-merge-patches) have an exception of:
> network.interfaces section is merged with the value in the machine config if there is a match on interface: or deviceSelector: keys

Which is awesome! It would be even cooler if we could apply that same 'merged' logic with the `vlans` as well based on the `vlanId` assuming that key is unique?

### Description

You have a config patch that applies to all nodes, adding in a series of VLANs, but you also want to 'strategically merge' in a patch for just control plane nodes that add VIP entries to the VLAN defintions!

Eg. currently have an 'all nodes' config of:
```
  network:
    interfaces:
      - interface: eth0
        dhcp: true
        dhcpOptions:
          routeMetric: 2048
        vlans:
          - vlanId: 103
            dhcp: true
            dhcpOptions:
              routeMetric: 1024
```

And would like to merge that in with a control planes specific config of:
```
  network:
    interfaces:
      - interface: eth0
        vip:
          ip: 192.168.77.130
        vlans:
          - vlanId: 103
            vip:
              ip: 192.168.77.2
```

Which currently results in:
```
    network:
        interfaces:
            - interface: eth0
              vlans:
                - vlanId: 103
                  dhcp: true
                  dhcpOptions:
                    routeMetric: 1024
                - vlanId: 103
                  vip:
                    ip: 192.168.77.2
              dhcp: true
              dhcpOptions:
                routeMetric: 2048
              vip:
                ip: 192.168.77.130
```

But would (ideally) result in:
```
  network:
    interfaces:
      - interface: eth0
        dhcp: true
        dhcpOptions:
          routeMetric: 2048
        vip:
          ip: 192.168.77.130
        vlans:
          - vlanId: 103
            dhcp: true
            dhcpOptions:
              routeMetric: 1024
            vip:
              ip: 192.168.77.2
```
