### ISSUE TITLE
provide a way to get coredumps

### ISSUE THREAD

**Issue by flokli** [siderolabs/talos#6928]
If you have a process segfaulting, it'd be good to be able to extract a coredump.

There seems to be https://github.com/nokia/koredump, but it only interacts with `systemd-coredump` on a regular distro running Kubernetes, so this obviously won't work with Talos.

I'd assume there'd be a Talos API endpoint to retrieve coredumps of recently segfaulted processes instead.

**Comment by flokli** [comment]
Another option would be to treat this similar to [system logs](https://www.talos.dev/v1.5/talos-guides/configuration/logging/#kernel-logs) - specify the path to an endpoint receiving the coredump, maybe HTTP with some request parameters to allow providing some metadata - like name of the node and pod.

That'd avoid having to keep these files on individual machines, and garbage-collecting them eventually, and push all these questions to the endpoint that receives the coredumps.

**Comment by wozniakjan** [comment]
@flokli I had succeeded at getting coredumps simply by setting the following patch for worker nodes
```yaml
machine:
  type: worker
  sysctls:
    kernel.core_pattern: /tmp/core.%e.%p.%t
```
then using `hostPath` mount on relevant pods
```yaml
      volumes:
      - name: tmp-volume
        hostPath:
          path: /tmp/
          type: Directory
```
and finally configuring `ulimit -c` as the first command for the pod
```yaml
    spec:
      containers:
      - command:
        - bash
        - -c
        - |
          set -xeuo pipefail
          ulimit -c unlimited
          /bin/main
```
while it's not a native API for talos and brings some inconvenience with taking extra care about retention and size of the coredumps, it does work. You can fetch the coredumps from the node by creating a `DaemonSet` mounting the `/tmp` as well and periodically reviewing the content.

<details>
  <summary>crashing deployment</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
  namespace: default
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - command:
        - bash
        - -c
        - |
          set -xeuo pipefail
          ulimit -c unlimited
          /bin/main
        image: wozniakjan/cd:latest
        imagePullPolicy: Always
        name: ubuntu
        volumeMounts:
        - mountPath: /tmp/
          name: tmp-volume
      volumes:
      - hostPath:
          path: /tmp/
          type: Directory
        name: tmp-volume
```

</details>

<details>
  <summary>daemonset exposing coredumps</summary>

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: coredump
  labels:
    app: coredump
spec:
  selector:
    matchLabels:
      name: coredump
  template:
    metadata:
      labels:
        name: coredump
    spec:
      containers:
      - name: coredump
        image: ubuntu
        command: ["sleep"]
        args: ["infinity"]
        volumemounts:
        - name: tmp-volume
          mountPath: /tmp/
      volumes:
      - name: tmp-volume
        hostPath:
          path: /tmp/
          type: Directory
```

</details>

<details>
  <summary>talos patch</summary>

```yaml
machine:
  type: worker
  sysctls:
    kernel.core_pattern: /tmp/core.%e.%p.%t
```

</details>

<details>
  <summary>coredumping app</summary>

```c
#include <signal.h> /* signal, SIGSEGV */

#include <unistd.h> /* write, STDOUT_FILENO */

void signal_handler(int sig) {
    (void)sig;
    const char msg[] = "signal received\n";
    write(STDOUT_FILENO, msg, sizeof(msg));
}

int myfunc(int i) {
    *(int *)0 = 1;
    return i + 1;
}

int main(int argc, char **argv) {
    (void)argv;
    signal(SIGSEGV, signal_handler);
    int ret = myfunc(argc);
    return ret;
}
```

</details>
