### ISSUE TITLE
Support for dual stacked VIP

### ISSUE THREAD

**Issue by jamesharr** [siderolabs/talos#6929]
## Feature Request

[Currently in 1.3](https://www.talos.dev/v1.3/reference/configuration/#devicevipconfig), there can only be a single VIP on an interface, and in a dual stack environment, the administrator would have to choose between an IPv4 and an IPv6 address. I'd like support for both IPv4 and IPv6, or even better an arbitrary number of VIPs on an interface.

Sample [DeviceVIPConfig](https://www.talos.dev/v1.3/reference/configuration/#devicevipconfig):
```yaml
vip:
 - ip: 192.0.2.100
 - ip: 2001:db8::100
```

Things that are not quite clear to me:
- Would `equinixMetal` and `hcloud` even support multiple addresses?
- What's a migration path?

### Description

**Comment by jamesharr** [comment]
I also thought of a half-decent way to migrate through API revisions.

```yaml
# deprecated method, still supported
vip:
  ip: ...

# New method
vips:
  - ip: ...
  - ip: ...
  - equinixMetal: ...
  - hcloud: ...
```

I'm guessing someone on the Talos team would have thought of that anyway, but it came to mind today.
