### ISSUE TITLE
Use diskSelector for MachineConfig.disks

### ISSUE THREAD

**Issue by cjyar** [siderolabs/talos#7004]
## Feature Request

Add `MachineDisk.diskSelector`, similar to `InstallConfig.diskSelector`.

### Description

We have this lovely `diskSelector` that can be used to select the install device, regardless of device naming. This is important because device names like /dev/sda can change from one boot to the next, if other devices are attached or detached. It would be nice to use a similar `diskSelector` for `MachineConfig.disks`, to select devices for filesystems other than the install disk. Then I could write something like this:

```yaml
version: v1alpha1
machine:
    install:
        diskSelector:
            model: FAST_SSD
    disks:
    - diskSelector:
        model: BIG_SLOW_DISK
      partitions:
      - mountpoint: /my/storage
```
