### ISSUE TITLE
v1.4.0-alpha.3 - kernel module parameters ignored?

### ISSUE THREAD

**Issue by markbaumgarten** [siderolabs/talos#7008]
### Description

Trying to get nvidia a5000 GPU working.

In order to get unsupported GPU working I have to set the following param:

 NVreg_OpenRmEnableUnsupportedGpus=1 ignored

aka:

```
........
kernel:
        modules:
        - name: nvidia
          parameters:
            - NVreg_OpenRmEnableUnsupportedGpus=1
        - name: nvidia_uvm
        - name: nvidia_drm
        - name: nvidia_modeset
..........
```

Yet it seems to be ignored (my guess is because modules are loaded automatically...?

### Logs
```
10.20.30.29: kern: warning: [2023-03-27T10:39:35.589281007Z]: NVRM: Open nvidia.ko is only ready for use on Data Center GPUs.
10.20.30.29: kern: warning: [2023-03-27T10:39:35.672539007Z]: NVRM: To force use of Open nvidia.ko on other GPUs, see the 
10.20.30.29: kern: warning: [2023-03-27T10:39:35.751701007Z]: NVRM: 'OpenRmEnableUnsupportedGpus' kernel module parameter described 10.20.30.29: kern: warning: [2023-03-27T10:39:35.841226007Z]: NVRM: in the README.
```
### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]

Client:
	Tag:         v1.3.6
	SHA:         5b6176d8
	Built:       
	Go version:  go1.19.7
	OS/Arch:     linux/amd64
Server:
	NODE:        10.20.30.29
	Tag:         v1.4.0-alpha.3
	SHA:         3583eea9
	Built:       
	Go version:  go1.20.2
	OS/Arch:     linux/amd64
	Enabled:     RBAC

- Kubernetes version: [`kubectl version --short`]

1.26.2

- Platform:
??? Sidero metal ?
