### ISSUE TITLE
Support for coredns customizations on bootstrap and via configmap

### ISSUE THREAD

**Issue by leoslf** [siderolabs/talos#7019]
### Description
It would be nice if we can override the `Corefile` in the `coredns` configmap with the fields of another configmap, `coredns-custom`.  This would help to provide easier access to work around hairpinning by adding rewrite rules to coredns.

One of the ways to implement the feature would be as follows.

```diff
diff --git a/internal/app/machined/pkg/controllers/k8s/templates.go b/internal/app/machined/pkg/controllers/k8s/templates.go
index 264079023..f7752feb8 100644
--- a/internal/app/machined/pkg/controllers/k8s/templates.go
+++ b/internal/app/machined/pkg/controllers/k8s/templates.go
@@ -300,7 +300,17 @@ data:
         loop
         reload
         loadbalance
+        import custom/*.override
     }
+    import custom/*.server
+---
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: coredns-custom
+  namespace: kube-system
+data:
+  {{ .CoreDNSCustom | nindent 2 }}
 ---
 apiVersion: apps/v1
 kind: Deployment
@@ -365,6 +375,9 @@ spec:
             - name: config-volume
               mountPath: /etc/coredns
               readOnly: true
+            - name: custom-config-volume
+              mountPath: /etc/coredns/custom
+              readOnly: true
           ports:
             - name: dns
               protocol: UDP
@@ -405,6 +418,10 @@ spec:
             items:
             - key: Corefile
               path: Corefile
+        - name: custom-config-volume
+          configMap:
+            name: coredns-custom
+            optional: true
 `)
 
 var coreDNSSvcTemplate = []byte(`apiVersion: v1
```

New Example for `cluster.coredns` (assuming `custom` maps all the way via protobuf to `CoreDNSCustom`)
```yaml
image: docker.io/coredns/coredns:1.10.1 # The `image` field is an override to the default coredns image.
custom: |-
    hairpinning.override: |
        rewrite name bar.foo.com ingress-nginx-controller.ingress-nginx.svc.cluster.local
        rewrite name baz.foo.com ingress-nginx-controller.ingress-nginx.svc.cluster.local
        rewrite name qux.foo.com ingress-nginx-controller.ingress-nginx.svc.cluster.local

    # just an arbitrary example for the server
    example.io.server: |
        example.io:8053 {
          forward . 8.8.8.8
        }
```

See: https://docs.digitalocean.com/products/kubernetes/how-to/customize-coredns/

**Comment by smira** [comment]
Btw, you can disable Talos provided CoreDNS manifest, and supply your own customized version via inline or extra manifests

**Comment by leoslf** [comment]
Hi @smira,

I know it won't be a priority but it would really be a nice-to-have if it is available out of the box.
The complexity would be about the protocol buffer part as far as I know.

Thanks,
Leo

**Comment by smira** [comment]
I'm not sure what kind of protobuf thing you're referring to. Talos resource protobuf is auto-generated, but I'm torn if that should be a feature of Talos, or it's better done outside.

**Comment by leoslf** [comment]
Thank you for your prompt reply.  The prorobuf was BootstrapManifestsConfigSpec.

I just came across finding an [example](https://www.talos.dev/v1.3/kubernetes-guides/configuration/deploy-metrics-server/) and realized the extra manifests you mentioned could be done on bootstrap.

Thanks a lot, I am closing the feature request.

**Comment by leoslf** [comment]
Just a heads up for those who might look into this feature request in the future: if `coredns` is not installed in bootstrapping by leaving `cluster.coreDNS.disabled == true`, but after (e.g. installing it via `helm`), it would have the pod `kube-flannel` failed and the manually installed `coredns` would also fail since `flannel` is configured before it.

At the end, I am patching the `Deployment` and the `ConfigMap` both named `coredns` after bootstrapping: 
```yaml
# ansible
- name: Patch coredns deployment
  kubernetes.core.k8s_json_patch:
    kind: Deployment
    name: coredns
    namespace: kube-system
    patch:
      - op: replace
        path: /spec/template/spec/containers/0/volumeMounts
        value:
          - name: config-volume
            mountPath: /etc/coredns
            readOnly: true
          - name: custom-config-volume
            mountPath: /etc/coredns/custom
            readOnly: true
      - op: replace
        path: /spec/template/spec/volumes
        value:
          - name: config-volume
            configMap:
              name: coredns
              items:
                - key: Corefile
                  path: Corefile
          - name: custom-config-volume
            configMap:
              name: coredns-custom
              optional: true
  tags:
    - coredns

- name: Patch coredns configmap
  kubernetes.core.k8s_json_patch:
    kind: ConfigMap
    name: coredns
    namespace: kube-system
    patch:
      - op: replace
        path: /data/Corefile
        value: |-
          .:53 {
              errors
              health {
                  lameduck 5s
              }
              ready
              log . {
                  class error
              }
              prometheus :9153

              kubernetes {{ cluster_domain }} in-addr.arpa ip6.arpa {
                  pods insecure
                  fallthrough in-addr.arpa ip6.arpa
              }
              forward . /etc/resolv.conf
              cache 30
              loop
              reload
              loadbalance
              import custom/*.override
          }
          import custom/*.server
  tags:
    - coredns
```

Note that the `cluster_domain` defaults to `cluster.local` (like how talos have it templated in `internal/app/machined/pkg/controllers/k8s/templates.go`).
