### ISSUE TITLE
Second wireguard.peers[].allowedIPs netmask seems to be ignored

### ISSUE THREAD

**Issue by b1r3k** [siderolabs/talos#7063]
### Description

Second allowedIPs netmask seems to be ignored, there is no route to 10.1.0.0/23 subnet. Subnet 10.6.0.0/24 works fine.

```yaml
interfaces:
  - interface: wg0
      addresses:
        - 10.6.0.15/24
      mtu: 1500
      wireguard:
        privateKey: <SERVER_PRIVATE_KEY>
        listenPort: 51820
        peers:
          - publicKey: <CLIENT_PUBLIC_KEY>
            persistentKeepaliveInterval: 10s
            endpoint: <DYNAMIC_DNS_OR_STATIC_IP>:51820
            allowedIPs:
              - 10.6.0.0/24
              - 10.1.0.0/23
```

Tested launching pod:

```
# traceroute 10.6.0.13
traceroute to 10.6.0.13 (10.6.0.13), 30 hops max, 60 byte packets
 1  10.244.3.1 (10.244.3.1)  1.069 ms  0.972 ms  0.924 ms
 2  10-6-0-13.kubernetes.default.svc.cluster.local (10.6.0.13)  26.572 ms  26.524 ms  26.430 ms

# traceroute 10.1.1.7
traceroute to 10.1.1.7 (10.1.1.7), 30 hops max, 60 byte packets
 1  10.244.3.1 (10.244.3.1)  0.982 ms  0.915 ms  0.866 ms
 2  192.168.1.1 (192.168.1.1)  0.797 ms  0.689 ms  0.631 ms
 3  192.168.0.1 (192.168.0.1)  1.034 ms  1.157 ms  1.235 ms
 4  192.168.178.1 (192.168.178.1)  3.806 ms  4.969 ms  6.132 ms
 5  * * *
 6  * * *

```

### Environment

- Talos version:

```
Client:
	Tag:         v1.3.6
	SHA:         5b6176d8
	Built:       
	Go version:  go1.19.7
	OS/Arch:     linux/amd64
Server:
	NODE:        192.168.1.44
	Tag:         v1.3.6
	SHA:         5b6176d8
	Built:       
	Go version:  go1.19.7
	OS/Arch:     linux/amd64
	Enabled:     RBAC
```

- Kubernetes version:
 
```
Client Version: v1.20.2
Server Version: v1.26.2
```

- Platform: amd64
