### ISSUE TITLE
hardcoded mac address in metal-rock64-arm64.img.xz image

### ISSUE THREAD

**Issue by jlgeering** [siderolabs/talos#7095]
## Bug Report

I have 2 Pine64 Rock64 SBC. Using both a dietPi and armbian image, I get a consistant hw / mac eth0 address:

- ce:a3:0b:... for the first one
- de:e8:02:... for the second one

but when using  metal-rock64-arm64.img.xz I get the same address for both boards (and this makes it a bit tricky to run them on the same network):

- 16:d1:15:de:70:4a for talos v1.2.9
- fe:77:61:5b:2a:3a for talos v1.3.6 and v1.3.7
- 4e:e3:dd:59:32:08 for talos v1.4.0-beta.1

interestingly, the address changed from 16:d1:15:de:70:4a to fe:77:61:5b:2a:3a when I upgraded talos from 1.2 to 1.3 (I think)

I do not have this issue with the metal-pine64-arm64.img.xz image (I also have 2 of those SBCs)

### Logs

```
❯ talosctl get link eth0 -n 10.10.99.33 -o yaml
node: 10.10.99.33
metadata:
    namespace: network
    type: LinkStatuses.net.talos.dev
    id: eth0
    version: 4
    owner: network.LinkStatusController
    phase: running
    created: 2016-01-21T08:50:36Z
    updated: 2016-01-21T08:51:14Z
spec:
    index: 8
    type: ether
    linkIndex: 0
    flags: UP,BROADCAST,RUNNING,MULTICAST,LOWER_UP
    hardwareAddr: fe:77:61:5b:2a:3a
    permanentAddr: fe:77:61:5b:2a:3a
    broadcastAddr: ff:ff:ff:ff:ff:ff
    mtu: 1500
    queueDisc: mq
    operationalState: up
    kind: ""
    slaveKind: ""
    driver: rk_gmac-dwmac
    driverVersion: Jan_2016
    linkState: true
    speedMbit: 1000
    port: TwistedPair
    duplex: Full
```

### Environment

- Talos version: 
  - v1.2.9
  - v1.3.6
  - v1.3.7
  - v1.4.0-beta.1
- Kubernetes version: v1.26.3
- Platform: [Pine64 Rock64 SBC](https://www.talos.dev/v1.3/talos-guides/install/single-board-computers/rock64/)

**Comment by jlgeering** [comment]
As a temp workaround, does someone know how to "overwrite" the mac address?

I see no way to configure it in https://www.talos.dev/v1.3/reference/configuration/#device (only ref is as device selector)

**Comment by jlgeering** [comment]
and as a sidenote ... I am also curious about the difference between hardwareAddr and permanentAddr

```
❯ talosctl get link eth0 -n 10.10.99.33 -o yaml
node: 10.10.99.33
metadata:
    namespace: network
    type: LinkStatuses.net.talos.dev
    id: eth0
    version: 4
    ...
spec:
    index: 8
    type: ether
    linkIndex: 0
    flags: UP,BROADCAST,RUNNING,MULTICAST,LOWER_UP
    hardwareAddr: fe:77:61:5b:2a:3a
    permanentAddr: fe:77:61:5b:2a:3a
    ...
```
