### ISSUE TITLE
KubeSpan should not announce 'externalIP' addresses as local to the node

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#7126]
Reported by @steverfrancis, GCP VM reports externalIP as routable, but it's not assigned to the VM, so the traffic gets dropped.

**Comment by smira** [comment]
I can't reproduce, waiting for more info from Steve.

**Comment by steverfrancis** [comment]
To reproduce:
Create GCP machine (I use region and zone us-central1, the default), type E2 medium 4GB.
Boot disk is Custom Image, talos 1.3.7 (that I uploaded the GCP image and made an image of.)
Firewall is set to allow all traffic inbound, on all ports.

Create the CP machine.
Also create a machine in Vultr (again in Chicago, 4GB of memory, talos 1.3.7 image.)

I have a quick script to automate the steps:
```
 more ~/createcluster.sh 
#!/bin/bash
echo talosctl gen config mycluster5 https://$1:6443
talosctl gen config mycluster5 https://$1:6443 --with-kubespan
#cat controlplane.yaml | sed 's/sda/vda/' > ./tmp.foo ; mv ./tmp.foo ./controlplane.yaml
talosctl apply-config --insecure --nodes $1 -e $1 --file ./controlplane.yaml
read -p "When reached waiting for bootstrap...Press enter to continue"
talosctl bootstrap --nodes $1 -e $1 --talosconfig=./talosconfig
talosctl health --nodes $1 -e $1 --talosconfig=./talosconfig
cat worker.yaml | sed 's/sda/vda/' > ./tmp.foo ; mv ./tmp.foo ./worker.yaml
talosctl apply-config --insecure --nodes $2 -e $2 -f worker.yaml
```
~/createcluster.sh 34.172.164.165 207.148.10.224
The control plane is created (seemingly) happily; the worker is created, but loops and reboots with "unable to read client-cert /var/lib/kubelet/pki/kubelet-client-current.pem"

Asking the worker it's view of kubespan peers:
```
talosctl --talosconfig=./talosconfig -n 207.148.10.224 -e 34.172.164.165 get kubespanpeerspecs -o yaml
node: 207.148.10.224
metadata:
    namespace: kubespan
    type: KubeSpanPeerSpecs.kubespan.talos.dev
    id: VLSiU0XMbEOnCx313disAn280PkClUyttIzrZ0DzanA=
    version: 1
    owner: kubespan.PeerSpecController
    phase: running
    created: 2023-04-25T20:52:10Z
    updated: 2023-04-25T20:52:10Z
spec:
    address: fd0e:abd0:86c5:3302:4001:aff:fe80:22
    allowedIPs:
        - 10.128.0.34/32
        - fd0e:abd0:86c5:3302:4001:aff:fe80:22/128
    endpoints:
        - 10.128.0.34:51820
        - 34.172.164.165:51820
    label: cp1
```
and
```
talosctl --talosconfig=./talosconfig -n 207.148.10.224 -e 34.172.164.165 get kubespanpeerstatuses -o yaml
node: 207.148.10.224
metadata:
    namespace: kubespan
    type: KubeSpanPeerStatuses.kubespan.talos.dev
    id: VLSiU0XMbEOnCx313disAn280PkClUyttIzrZ0DzanA=
    version: 9
    owner: kubespan.ManagerController
    phase: running
    created: 2023-04-25T20:52:10Z
    updated: 2023-04-25T20:56:08Z
spec:
    endpoint: 34.172.164.165:51820
    label: cp1
    state: up
    receiveBytes: 42424
    transmitBytes: 98972
    lastHandshakeTime: 2023-04-25T20:54:12.668256405Z
    lastUsedEndpoint: 10.128.0.34:51820
    lastEndpointChange: 2023-04-25T20:52:10.570074212Z
```
