### ISSUE TITLE
Loading of module with unavailable key is rejected

### ISSUE THREAD

**Issue by seedrick** [siderolabs/talos#7174]
I'm following the guide to try to install the nvidia drivers. The upgrade goes through but now I'm getting what I assume to be a module signing error:

`kern:  notice: [2023-05-04T07:37:25.957686413Z]: Loading of module with unavailable key is rejected                                                                                      
 user: warning: [2023-05-04T07:37:25.959281413Z]: [talos] controller failed {"component": "controller-runtime", "controller": runtime.KernelModuleSpecController", "error": "error loading module \x5c"nvidia\x5c": load nvidia failed: key was rejected by service"}`

Checked secure boot in m BIOS and it's off, not sure what to do other than that.

Talos version: 1.4.0
Kubernetes version: 1.26.1
Platform: bare metal

**Comment by frezbo** [comment]
This is usually an indication that the kernel build does not match the module built, what might happen on systems with constraint limits is that buildkit might drop the kernel build cache and when building module, it'll rebuild kernel again, creating a mis-match between kernel built and module build. Check if the kernel is getting re-build when building the kernel modules.

**Comment by seedrick** [comment]
What's would be the smoking gun if that were the case? As in what should I `grep`? Would trying legacy builder help?

**Comment by frezbo** [comment]
you can verify it if this way if you want: https://github.com/siderolabs/talos/blob/main/hack/test/e2e.sh#L51

but an easy thing to check if when the module is getting built, the logs would say using `CACHED: kernel-build` else it's re-building

**Comment by seedrick** [comment]
So I do see `CACHED: kernel-build` up to a certain point but then it's just `kernel-build`.

**Comment by frezbo** [comment]
> up to a certain point but then it's just kernel-build.

seems it's getting re-build, you can try bumping the buildkitd gc cache interval

`docker buildx create --use --bootstrap --config <path to file>`

config file:

```toml
[worker.oci]
  gc = true
  gckeepstorage = 50000

  [[worker.oci.gcpolicy]]
    keepBytes = 10737418240
    keepDuration = 604800
    filters = [ "type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
  [[worker.oci.gcpolicy]]
    all = true
    keepBytes = 53687091200
```
