### ISSUE TITLE
Add write/delete to API

### ISSUE THREAD

**Issue by davidpanic** [siderolabs/talos#7183]
Currently there is no way that I know of to delete or write a specific file or directory on the nodes. The only existing file manipulation APIs are `read` and `list` but there is no `write` or `delete`.

I would like to have this functionality to be able to remove `/var/lib/rook` as it is required for [correct cleanup of a Rook cluster](https://rook.github.io/docs/rook/v1.11/Storage-Configuration/ceph-teardown/?h=clean#delete-the-data-on-hosts).

To work around this I have just run a pod with an alpine container and a local volume, then deleted the directory from within the pod.

**Comment by frezbo** [comment]
this process is documented here: https://www.talos.dev/v1.4/kubernetes-guides/configuration/ceph-with-rook/#talos-linux-rook-metadata-removal

Adding delete api conflicts with talos philosophies.

**Comment by Ulrar** [comment]
Hi,

I've created a linstor snapshot as a test, then deleted it and I'm not stuck with the underlying file in the middle of my volumes. An easy way to delete a file in /var would be useful, I guess my only option now is to figure out how to execute a privileged pod with access to that path to delete the file from there

**Comment by davidpanic** [comment]
@Ulrar This might come in useful, I'ts what I used to delete the rook directory:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-rook-dir
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      nodeName: talos-test-1
      containers:
      - name: cleanup
        image: alpine:latest
        command: ["rm", "-rf",  "/mnt/rook"]
        volumeMounts:
          - name: var-lib
            mountPath: /mnt
      restartPolicy: Never
      volumes:
        - name: var-lib
          hostPath:
            path: /var/lib
```
