### ISSUE TITLE
Support for routing rules and tables

### ISSUE THREAD

**Issue by dedene** [siderolabs/talos#7184]
## Feature Request

Support for routing rules and tables in the machine config

### Description

For various setups on Bare Metal, more advanced routing configuration possibilities are needed. This would allow for things like 

```
ip route add default via 46.105.135.110 dev eth0 table 100
ip rule add from 46.105.135.96/28 table 100
```

See [this discussion](https://github.com/siderolabs/talos/discussions/7177) for an example use case.

**Comment by smira** [comment]
Some notes from implementation point of view:

* routes already support tables, but they are not exposed in the machine config now (easy change)
* routing rules are not exposed as resources yet

**Comment by ffetech** [comment]
Would be great if also something like this would be possible:
`iptables -t nat -A POSTROUTING -s '10.0.0.0/16' -o eth0 -j MASQUERADE`
… to get a talos node to work as NAT gateway.

**Comment by smira** [comment]
> Would be great if also something like this would be possible: `iptables -t nat -A POSTROUTING -s '10.0.0.0/16' -o eth0 -j MASQUERADE` … to get a talos node to work as NAT gateway.

This makes sense, but it is totally different from this issue. This should go to #4421

**Comment by camrossi** [comment]
I need to set a "blackhole" route in my cluster, in general ip route support doing this:
```
ip route add blackhole 1.1.1.1/32
```
So as part of this feature request we could also add `route-type`  support.
For now I did this workaround in my cluster but would like to understand if this is ok or if I am gonna end up with issues down the road:
```
    network:
        interfaces:
            - interface: eth0 # The interface name.
              routes:
                - network: 10.56.0.0/16 
                  gateway: 0.0.0.0 
              dhcp: true

talosctl -n 192.168.11.90  get route | grep 10.56.0.
NODE            NAMESPACE   TYPE          ID                                        VERSION   DESTINATION   GATEWAY  LINK
192.168.11.90   network     RouteStatus   inet4//10.56.0.0/16/1024  1                10.56.0.0/16                         eth0 
```

And it seems to have done the trick but I am not really sure if this is something that is actually supported or not.
