### ISSUE TITLE
Dual stack ipv4/ipv6 cluster

### ISSUE THREAD

**Issue by 2o1o0** [siderolabs/talos#7270]
## Bug Report

### Description

When attempting to create a dual stack cluster, the first node is added properly but others are missing the spec.PodCIDRs information, causing flannel to be stuck in CrashLoopback. spec are available when setup is done in ipv4 only on all nodes. However, when dual stack is "enabled", both host ipv4 and ipv6 are available in node status / kubelet.

Its a 3 node POC with various servers, the talos controler.yml below is working just fine without the dual stack cidr

<details>

<summary>config</summary>

```yaml
version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token: (...)
    ca:
        crt: (...)
        key: (...)
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.27.1
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network: {}
    install:
        disk: /dev/sda
        image: ghcr.io/siderolabs/installer:v1.4.4
        bootloader: true
        wipe: false
        extensions:
            - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4
    registries: {}
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
cluster:
    allowSchedulingOnControlPlanes: true
    id: (...)
    secret: (...)
    controlPlane:
        endpoint: https://kube.my.domain:6443
    clusterName: kube-talos
    network:
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
            - fd00:0:0:1000::/64
        serviceSubnets:
            - 10.96.0.0/12
            - fd00:0:0:2000::/112
    token: (...)
    secretboxEncryptionSecret: (...)
    ca:
        crt: (...)
        key: (...)
    aggregatorCA:
        crt: (...)
        key: (...)
    serviceAccount:
        key: (...)
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.27.1
        certSANs:
            - kube.my.domain
(...)

```
</details>

and the flannel config seems to aligned for dual stack:

```json                                                                                                                              
{                                                                                                                                          
  "Network": "10.244.0.0/16",                                                                                                              
  "IPv6Network": "fd00:0:0:1000::/64",                                                                                                     
  "EnableIPv6": true,                                                                                                                      
  "Backend": {                                                                                                                             
    "Type": "vxlan",                                                                                                                       
    "Port": 4789                                                                                                                           
  }                                                                                                                                        
} 
```

I also made several attempts with more advanced network config, forcing ips, routes and nameservers. But I ended up in the same situation.

Not sure what I am missing here. I've already done some dual stack clusters with kubeadm and calico without this kind of issue. 

### Logs

Spec on faulty node vs spec on first node:
```
spec: {}
```
```
spec:                                                                                                                                                                                                                                                  
  podCIDR: 10.244.0.0/24                                                                                                                                                                                                                               
  podCIDRs:                                                                                                                                                                                                                                            
  - 10.244.0.0/24                                                                                                                                                                                                                                      
  - fd00:0:0:1000::/64 
```

Logs from a flannel pod
```
kube-flannel I0523 20:28:36.783552       1 kube.go:506] Creating the node lease for IPv4. This is the n.Spec.PodCIDRs: [10.244.0.0/24 fd00:0:0:1000::/64]                                                                                              
kube-flannel I0523 20:28:36.783576       1 kube.go:539] Creating the node lease for IPv6. This is the n.Spec.PodCIDRs: [10.244.0.0/24 fd00:0:0:1000::/64]                                                                                              
kube-flannel I0523 20:28:37.781156       1 kube.go:151] Node controller sync successful                                                                                                                                                                
kube-flannel I0523 20:28:37.781201       1 main.go:231] Created subnet manager: Kubernetes Subnet Manager - server-rs140                                                                                                                               
kube-flannel I0523 20:28:37.781209       1 main.go:234] Installing signal handlers                                                                                                                                                                     
kube-flannel I0523 20:28:37.781396       1 main.go:542] Found network config - Backend type: vxlan                                                                                                                                                     
kube-flannel I0523 20:28:37.781414       1 match.go:206] Determining IP address of default interface                                                                                                                                                   
kube-flannel I0523 20:28:37.782873       1 match.go:259] Using interface with name eth2 and address 192.168.4.103                                                                                                                                      
kube-flannel I0523 20:28:37.782905       1 match.go:262] Using interface with name eth2 and v6 address 2a0d:3344:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx
kube-flannel I0523 20:28:37.782914       1 match.go:281] Defaulting external address to interface address (192.168.4.103)                                                                                                                              
kube-flannel I0523 20:28:37.782922       1 match.go:294] Defaulting external v6 address to interface address (2a0d:3344:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx)                                                                                                   
kube-flannel I0523 20:28:37.782991       1 vxlan.go:140] VXLAN config: VNI=1 Port=4789 GBP=false Learning=false DirectRouting=false                                                                                                                    
kube-flannel E0523 20:28:37.783391       1 main.go:334] Error registering network: failed to acquire lease: node "server-rs140" pod cidr not assigned                                                                                                  
kube-flannel I0523 20:28:37.783421       1 main.go:522] Stopping shutdownHandler...                                                                                                                                                                    
kube-flannel W0523 20:28:37.783492       1 reflector.go:347] github.com/flannel-io/flannel/pkg/subnet/kube/kube.go:486: watch of *v1.Node ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has 
prevented the request from succeeding  
```

### Environment

- Talos version: v1.4.4
- Kubernetes version: Client & Server Version: v1.27.1
- Platform: Lab of various servers working perfectly in single stack ipv4
