### ISSUE TITLE
controlplane node stuck after upgrade (remote error: tls: internal error)

### ISSUE THREAD

**Issue by jlgeering** [siderolabs/talos#7317]
### Description

I'm having some troubles upgrading my control-plane nodes (or setting up new control-plane nodes). After the upgrade (in this case to 1.4.5) they are getting stuck at task uncordonNode

only happened on control-plane nodes, and sometimes it resolves itself after a while (only happened once, mostly it stays stuck)

current fix is to change the role to worker until the node is ready and then setting it back to controlplane

### Logs

10.10.99.22: user: warning: [2023-06-01T08:05:25.769080166Z]: [talos] task uncordonNode (1/1): starting
10.10.99.22: user: warning: [2023-06-01T08:05:25.845540166Z]: [talos] retrying error: node not ready
10.10.99.22: user: warning: [2023-06-01T08:05:33.332576166Z]: [talos] controller failed {"component": "controller-runtime", "controller": "k8s.KubeletStaticPodController", "error": "error refreshing pod status: error fetching pod status: Get \x5c"https://127.0.0.1:10250/pods/?timeout=30s\x5c": remote error: tls: internal error"}
10.10.99.22: user: warning: [2023-06-01T08:05:49.241990166Z]: [talos] controller failed {"component": "controller-runtime", "controller": "k8s.KubeletStaticPodController", "error": "error refreshing pod status: error fetching pod status: Get \x5c"https://127.0.0.1:10250/pods/?timeout=30s\x5c": remote error: tls: internal error"}
10.10.99.22: user: warning: [2023-06-01T08:06:05.042627166Z]: [talos] controller failed {"component": "controller-runtime", "controller": "k8s.KubeletStaticPodController", "error": "error refreshing pod status: error fetching pod status: Get \x5c"https://127.0.0.1:10250/pods/?timeout=30s\x5c": remote error: tls: internal error"}

etc...

### Environment

- Talos version: 1.4.5 (1.4.4 and probably 1.4.3 too)
- Kubernetes version: v1.26.1
- Platform: macos for client, bare metal for server

machine config:

```yaml
---
node: 10.10.99.23
spec:
  cluster:
    aggregatorCA: PLACEHOLDER
    apiServer:
      admissionControl:
        - configuration:
            apiVersion: pod-security.admission.config.k8s.io/v1alpha1
            defaults:
              audit: restricted
              audit-version: latest
              enforce: baseline
              enforce-version: latest
              warn: restricted
              warn-version: latest
            exemptions:
              namespaces:
                - kube-system
              runtimeClasses: []
              usernames: []
            kind: PodSecurityConfiguration
          name: PodSecurity
      auditPolicy:
        apiVersion: audit.k8s.io/v1
        kind: Policy
        rules:
          - level: Metadata
      certSANs:
        - cp.hl.PLACEHOLDER
      disablePodSecurityPolicy: true
      image: registry.k8s.io/kube-apiserver:v1.27.1
    ca: PLACEHOLDER
    clusterName: atlantis
    controlPlane:
      endpoint: https://cp.hl.PLACEHOLDER:6443
    controllerManager:
      image: registry.k8s.io/kube-controller-manager:v1.27.1
    discovery:
      enabled: true
      registries:
        kubernetes:
          disabled: true
        service: {}
    etcd:
      ca: PLACEHOLDER
    extraManifests: []
    id: PLACEHOLDER
    inlineManifests: []
    network:
      dnsDomain: cluster.local
      podSubnets:
        - 10.244.0.0/16
      serviceSubnets:
        - 10.96.0.0/12
    proxy:
      image: registry.k8s.io/kube-proxy:v1.27.1
    scheduler:
      image: registry.k8s.io/kube-scheduler:v1.27.1
    secret: PLACEHOLDER
    secretboxEncryptionSecret: PLACEHOLDER
    serviceAccount:
      key: PLACEHOLDER
    token: PLACEHOLDER
  debug: false
  machine:
    ca: PLACEHOLDER
    certSANs: []
    features:
      apidCheckExtKeyUsage: true
      rbac: true
      stableHostname: true
    install:
      bootloader: true
      disk: /dev/sda
      image: ghcr.io/siderolabs/installer:v1.4.4
      wipe: false
    kubelet:
      defaultRuntimeSeccompProfileEnabled: true
      disableManifestsDirectory: true
      extraArgs:
        rotate-server-certificates: 'true'
      image: ghcr.io/siderolabs/kubelet:v1.27.1
    network:
      hostname: atlantis-dm-1
      interfaces:
        - addresses:
            - 10.10.99.23/24
          dhcp: false
          interface: eth0
          routes:
            - gateway: 10.10.99.1
              network: 0.0.0.0/0
          vip:
            ip: 10.10.99.20
    registries: {}
    token: PLACEHOLDER
    type: controlplane
  persist: true
  version: v1alpha1
```
