### ISSUE TITLE
Problem using vlan and bond-interface

### ISSUE THREAD

**Issue by tisatteuto** [siderolabs/talos#7331]
### Bug-Report

**Description**

I use sidero and talos on a docker-bootstrap-cluster and i wanne use a bond-interfaces for cluster internal communication and a vip for the api-access.  Therefor a setup a corresponding server-resource:

```
- apiVersion: metal.sidero.dev/v1alpha2
  kind: Server
    name: 00000000-0000-0000-0000-ac1f6b220c44
  spec:
    accepted: true
    configPatches:
    - op: add
      path: /machine/network
      value:
        interfaces:
        - deviceSelector:
            hardwareAddr: ac:1f:6b:*
          dhcp: true
        - bond:
            deviceSelectors:
            - hardwareAddr: 90:e2:ba:e3:65:a0
            - hardwareAddr: 90:e2:ba:e3:65:a1
            lacpRate: fast
            mode: 802.3ad
            xmitHashPolicy: layer3+4
          interface: bond0
          vlans:
          - addresses:
            - 172.16.19.11/24
            dhcp: false
            vip:
              ip: 172.16.19.10
            vlanId: 2500
```

the install-disk is configured via `serverclass`.

Now i have two problems. First the bond-links not comming up correctly. From the logs/dmesg i get the following error-message:

```
bond0: Warning: No 802.3ad response from the link partner for any adapters in the bond
```

but thats not the case. Btw. i bootstraped this first node, untaint it and start a privileged debug-container in host-network-namespace. In there i saw that the links and the bond seem to be ok:

```
2: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 90:e2:ba:e3:a0:00 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::92e2:baff:fee3:a000/64 scope link 
       valid_lft forever preferred_lft forever
6: eth2: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP group default qlen 1000
    link/ether 90:e2:ba:e3:a0:00 brd ff:ff:ff:ff:ff:ff
7: eth3: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP group default qlen 1000
    link/ether 90:e2:ba:e3:a0:00 brd ff:ff:ff:ff:ff:ff permaddr 90:e2:ba:e3:a0:01
```

and also `/proc/net/bonding/bond0` seems to be ok, but without any active link. With tcpdump i was able see incoming lacp-pdu from our switch:

```
root@talos-sgm-m1i:/# tcpdump -i eth2 -nvel ether proto 0x8809
tcpdump: listening on eth2, link-type EN10MB (Ethernet), snapshot length 262144 bytes
06:45:43.514371 00:25:90:b3:0d:88 > 01:80:c2:00:00:02, ethertype Slow Protocols (0x8809), length 124: LACPv1, length 110
        Actor Information TLV (0x01), length 20
          System 44:38:39:ff:ff:01, System Priority 65535, Key 13, Port 1, Port Priority 255
          State Flags [Activity, Timeout, Aggregation, Synchronization, Default]
        Partner Information TLV (0x02), length 20
          System 00:00:00:00:00:00, System Priority 65535, Key 1, Port 1, Port Priority 255
          State Flags [Activity]
        Collector Information TLV (0x03), length 16
          Max Delay 0
        Terminator TLV (0x00), length 0
```
after removing and reattaching the links to the bond

```
   27  echo -eth2 > /sys/class/net/bond0/bonding/slaves
   28  echo -eth3 > /sys/class/net/bond0/bonding/slaves
   33  echo +eth2 > /sys/class/net/bond0/bonding/slaves
   31  echo +eth3 > /sys/class/net/bond0/bonding/slaves
```

the bond-status becomes up. I also tried to deploy this node with `interfaces` instead of using `deviceSelector` without success. Btw. at the end i wanne use a wildcard-deviceSelector in the serverclass.

The second problem i have is the vlan ontop of that bond-interface. It was configured:

```
20: bond0.2500@bond0: <BROADCAST,MULTICAST> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 90:e2:ba:e3:a0:00 brd ff:ff:ff:ff:ff:ff
    inet 172.16.19.11/24 brd 172.16.19.255 scope global bond0.2500
       valid_lft forever preferred_lft forever
```
But the state is down. Maybe i found the corresponding error-message:
```
[   21.913846] [talos] controller failed {"component": "controller-runtime", "controller": "network.LinkSpecController", "error": "1 error occurred:\n\t* error enslaving/unslaving link \"bond0.2500\" under \"bond0\": netlink receive: device or resource busy\n\n"}
```
I'm not sure, but i think this link shouldn't be enslaved to the bond-interface and maybe that is preventing the interface to be set `up`. If i do that manually via `ip` from the debug-container i shortly lost my api-access (via nodes pxe-ip) but was able to ping the vlan-ip, also if the vlan-interface was `down` again. After some seconds i was able to reconnect via `kubectl exec` into my debug-container.

**Environment**
capi-providers
```
providers:
  - name: "talos"
    url: "https://github.com/siderolabs/cluster-api-bootstrap-provider-talos/releases/v0.6.0/bootstrap-components.yaml"
    type: "BootstrapProvider"
  - name: "talos"
    url: "https://github.com/siderolabs/cluster-api-control-plane-provider-talos/releases/v0.5.1/control-plane-components.yaml"
    type: "ControlPlaneProvider"
  - name: "sidero"
    url: "https://github.com/siderolabs/sidero/releases/v0.6.0-alpha.0/infrastructure-components.yaml"
    type: "InfrastructureProvider"
```
talos
```
apiVersion: metal.sidero.dev/v1alpha2
kind: Environment
metadata:
  name: default
spec:
  initrd:
    url: https://github.com/siderolabs/talos/releases/download/v1.4.5/initramfs-amd64.xz
  kernel:
    args:
    - console=tty0
    - console=ttyS0
    - console=ttyS1,115200n8
    - consoleblank=0
    - earlyprintk=ttyS0
    - ima_appraise=fix
    - ima_hash=sha512
    - ima_template=ima-ng
    - init_on_alloc=1
    - initrd=initramfs.xz
    - nvme_core.io_timeout=4294967295
    - printk.devkmsg=on
    - pti=on
    - slab_nomerge=
    - talos.platform=metal
    url: https://github.com/siderolabs/talos/releases/download/v1.4.5/vmlinuz-amd64
status:
  conditions:
  - status: "True"
    type: Ready
    url: https://github.com/siderolabs/talos/releases/download/v1.4.5/vmlinuz-amd64
  - status: "True"
    type: Ready
    url: https://github.com/siderolabs/talos/releases/download/v1.4.5/initramfs-amd64.xz
```

Regards
Tino

**Comment by tisatteuto** [comment]
Even without the vlan on the bond-interface and static interface-names a got this error. After setting:

```
    9  ip link set nomaster dev eth2
   10  ip link set nomaster dev eth3
```

eth2 and eth3 gets automatically reenslaved to bond and the bond-state is up. Not sure, but is it possible that a dhclient is running on that interface by default and this prevents them to be enslaved initially to bond0?

**Comment by smira** [comment]
can you provide some short summary of unresolved issues you're having?

**Comment by tisatteuto** [comment]
I have two errors:

- When configuring a bond-interface i got `No 802.3ad response from the link partner for any adapters in the bond` an lacp is not running
- When configuring a vlan on that bond i got `error enslaving/unslaving link \"bond0.2500\" under \"bond0\": netlink receive: device or resource busy`

Regards
Tino

**Comment by smira** [comment]
I'm not sure about the first error, but the second error seems to be Talos picking up vlan interface to be enslaved under the bond. What was the device selector at the point of the failure?

**Comment by tisatteuto** [comment]
```yaml
        - interface: bond0
          bond:
            deviceSelectors:
            - hardwareAddr: 90:e2:ba:e3:a0:00
            - hardwareAddr: 90:e2:ba:e3:a0:01
            lacpRate: fast
            mode: 802.3ad
            xmitHashPolicy: layer3+4
          dhcp: false
          vlans:
           - addresses:
             - 172.16.19.11/24
             dhcp: false
             vlanId: 2500
```
