### ISSUE TITLE
Feature request: Include tags when sending JSON logs

### ISSUE THREAD

**Issue by alubbock** [siderolabs/talos#7356]
### Description

Add a `talos-node` or `hostname` field to the service and kernel logs when sending them over TCP or UDP using json_lines.

The [Talos docs](https://www.talos.dev/v1.4/talos-guides/configuration/logging/) describe how to send logs e.g. to Loki using Fluent-bit. When logs from many nodes are sent to a centralised endpoint, there's no way to tell which node kernel and service logs came from. Adding a field with the node's name would solve this.

**Comment by smira** [comment]
This was discussed I believe couple of times, the issue here is that Talos doesn't know it's `hostname` until it gets actually assigned, and the hostname might change during the boot process. Any centralized logging solution has an idea of the source IP of the log sender, so it could use that to attach proper labels to the logs.

So if implemented, this would look more like "attach the hostname to the logs when known" or something like that.

**Comment by sergelogvinov** [comment]
Probably, we need to add custom key/value to json.

```yaml
destinations:
    - endpoint: tcp://1.2.3.4:12345 # Where to send logs. Supported protocols are "tcp" and "udp".
      format: json_lines
      tags:
         custom_name: custom_value
```
