### ISSUE TITLE
overriding AuditPolicy with strategic config patches is not possible

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#7537]
Default policy is (with machine config generation):

```yaml
auditPolicy:
  apiVersion: audit.k8s.io/v1
  kind: Policy
  rules:
    - level: Metadata
```

with a patch like 

```yaml
cluster:
  apiServer:
    auditPolicy:
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
        - level: None
```

the 'rules' section gets concatenated, instead of being replaced.

Probably `auditPolicy` field should be replaced completely on patching.
