### ISSUE TITLE
ignoring interfaces doesn't work with device selectors

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#7673]
## Bug Report

E.g. 

```yaml
    network:
        interfaces:
            - deviceSelector:
                busPath: "0000:1b:*"
              dhcp: false
              ignore: true
```

Doesn't disable the DHCP/ignores the interface.

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`] 1.4.x
- Kubernetes version: [`kubectl version --short`]
- Platform:
