### ISSUE TITLE
Can't create vlans, got error, possibly due to predictable network interface

### ISSUE THREAD

**Issue by trunet** [siderolabs/talos#7679]
## Bug Report

I'm trying to add vlans, and I got an error in the console:

```
[talos] controller failed {"component": "controller-runtime", "controller": "network.LinkSpecController", "error": "2 errors occurred:\n\t* error creating logical link \"enx72469011805a.11\": netlink receive: numerical result out of range\n\t* error creating logical link \"enx72469011805a.24\": netlink receive: numerical result out of range\n\n"}
```

### Description

Excerpt from my talos configuration:

```
machine:
    network:
        interfaces:
            - deviceSelector:
                hardwareAddr: 5a:31:8e:74:fd:85
              addresses:
                - 192.168.[REDACTED]/24
              routes:
                - network: 0.0.0.0/0
                  gateway: 192.168.[REDACTED]
              vlans:
                - addresses:
                    - 192.168.[REDACTED]/24
                  dhcp: false
                  vlanId: 11
                  mtu: 1500
                - addresses:
                    - 192.168.[REDACTED]/24
                  dhcp: false
                  vlanId: 24
                  mtu: 1500
        nameservers:
            - 192.168.[REDACTED]
            - 192.168.[REDACTED]
...
```

I created a pod with `hostNetwork: true` and installed iproute2 (poor man talos ssh/bash). Tried to create manually. Looks like predictable network interface causes some naming issue:

```
talos02:/# ip link add link enx72469011805a name enx72469011805a.11 type vlan id 11
Error: argument "enx72469011805a.11" is wrong: "name" not a valid ifname
talos02:/# ip link add link enx72469011805a name vlan11 type vlan id 11
talos02:/# ip link sh dev vlan11
22: vlan11@enx72469011805a: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 72:46:90:11:80:5a brd ff:ff:ff:ff:ff:ff
```

### Environment

- Talos version:
```
Client:
        Tag:         v1.5.1
        SHA:         40a22cdf
        Built:
        Go version:  go1.20.7
        OS/Arch:     linux/amd64
Server:
        NODE:        192.168.[REDACTED]
        Tag:         v1.5.1
        SHA:         40a22cdf
        Built:
        Go version:  go1.20.7
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```
- Kubernetes version:
```
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.0
```
- Platform:
