### ISSUE TITLE
add SocketCAN kernel module

### ISSUE THREAD

**Issue by erickaby** [siderolabs/talos#7686]
## Feature Request

I have a use case that requires canbus, from my limited understanding/investigation I believe that the kernel module needs to be added for the CAN protocol to be available.

### Description

Simply I need the below configuration to work. I had no issue with this setup running on k3s cluster on some raspberry pi4s and i want to replicate that it with Talos.

```
# /etc/network/interfaces.d/can0
allow-hotplug can0
iface can0 can static
    bitrate 1000000
    up ifconfig $IFACE txqueuelen 128
```

I read up on https://www.talos.dev/v1.5/advanced/proprietary-kernel-modules/ to add it myself however due to lack of understanding of this subject and maybe information that is outdated on the page I was unable to see this through.

**Comment by frezbo** [comment]
This is the kernel config used by Talos: https://github.com/siderolabs/pkgs/blob/main/kernel/build/config-amd64

the modules can be shipped as a Talos System Extension

It might also need some changes in Talos side to probably support interface options like bitrate

**Comment by erickaby** [comment]
Thanks I'll keep digging into the codebase and attempt building it again

**Comment by erickaby** [comment]
@frezbo 
So, I gave it another shot. However I am still facing issues and not being able to see the interface `can0` available under `ls /sys/class/net` with `hostNetwork: true` on a pod. These are the steps I am taking and I appreciate any help that you can give me to solve this.

I am mostly following [this](https://www.talos.dev/v1.5/advanced/customizing-the-kernel/) guide.

1. Cloned siderolabs/pkgs.git and ran `make kernel-menuconfig USERNAME=erickaby`
2. Modified the CAN bus options
	```sh
	[*] Networking support --->
	    <M> CAN bus subsystem support ---> 
	    <M> Raw CAN Protocol (raw access with CAN-ID filtering)
	    <M> CAN Device Drivers --->
	```
3. Resulting in changes in `/kernel/build/config-arm64` like you linked above (this is for the arm platform for RPI)
4. Built and pushed the kernel to my registry, `make kernel USERNAME=erickaby PLATFORM=linux/arm64 PUSH=true`
5. Created and customised the multi-stage Dockerfile.
	<details>
	<summary>Dockerfile</summary>
	
	```Dockerfile
	FROM scratch AS customization
	
	# this is needed so that Talos copies base kernel modules info and default modules shipped with Talos
	
	COPY --from=ghcr.io/erickaby/kernel:v1.5.0-dirty /lib/modules /kernel/lib/modules
	
	# this copies over the custom modules
	
	COPY --from=ghcr.io/erickaby/kernel:v1.5.0-dirty /lib/modules /lib/modules
	
	
	
	FROM ghcr.io/siderolabs/installer:v1.5.1
	
	COPY --from=ghcr.io/erickaby/kernel:v1.5.0-dirty /boot/vmlinuz /usr/install/${TARGETARCH}/vmlinuz
	```
	
	</details>

6. Build and pushed the above docker image to my registry 
	```sh
	DOCKER_BUILDKIT=0 docker build --build-arg RM="/lib/modules" -t ghcr.io/erickaby/talos/installer:v1.5.1-canbus.1 .
	```

So from here I assume that the kernel would have CAN modules. What is the best way to verify at this point?

I then went on to create a talos extension to enable these modules.

1. Cloned siderolabs/talos-extensions.git and created new module under /network/canbus.
2. I copied the setup from a similar extension (nvidia) and configured the files to match what i am doing
	
	<details>
	<summary>pkg.yaml</summary>
	
	```yaml
	name: canbus
	variant: scratch
	shell: /toolchain/bin/bash
	dependencies:
	 - stage: base
	# The pkgs version for a particular release of Talos as defined in
	# https://github.com/siderolabs/talos/blob/<talos version>/pkg/machinery/gendata/data/pkgs
	#  - image: "{{ .LOCAL_REPO_PREFIX }}/canbus:{{ .BUILD_ARG_PKGS }}"
	steps:
	  - prepare:
	      - |
	        sed -i 's#$VERSION#{{ .VERSION }}#' /pkg/manifest.yaml
	  - install:
	      - |
	        mkdir -p /rootfs/lib/modules \
	          /rootfs/usr/local/lib/modprobe.d
	
	        cp /pkg/files/canbus.conf /rootfs/usr/local/lib/modprobe.d/canbus.conf
	
	        # cp -R /lib/modules/* /rootfs/lib/modules
	finalize:
	  - from: /rootfs
	    to: /rootfs
	  - from: /pkg/manifest.yaml
	    to: /
	```
	
	</details>

3. I then build and pushed to my registry `make canbus PLATFORM=linux/arm64 TAG=v1.0.0 PUSH=true` 

I am not sure if this approach is correct, I am just trying things at this point.

To apply to the actual node I tried a few things in the config file:

```sh
install:
        disk: /dev/mmcblk0
        image: ghcr.io/erickaby/talos/installer:v1.5.1-canbus.1
        wipe: false
        extensions:
            # - image: ghcr.io/siderolabs/qemu-guest-agent:8.0.2
            - image: ghcr.io/ogkevin/rpi-boot-config-loader:v1.0.0
            - image: ghcr.io/erickaby/canbus:v1.0.0
    kernel:
        modules:
        - name: can
        - name: can_raw
        # - name: mttcan
```

This is the first time I have messed around with customising any kernel and from the few guides [[1](https://docs.nvidia.com/drive/drive-os-5.2.0.0L/drive-os/index.html#page/DRIVE_OS_Linux_SDK_Development_Guide/Interfaces/sys_components_tegra_can.html)][[2](http://www.armadeus.org/wiki/index.php?title=CAN_bus_Linux_driver)] out there on enabling CAN bus on linux it looks pretty straight forward.

Any help to guide me in the right direction or tools to help debug would be much appreciated.
