### ISSUE TITLE
IPv6 Duid?

### ISSUE THREAD

**Issue by depeo10** [siderolabs/talos#7730]
Hello,

I know that you want me to use your slack to ask questiions, but when I followed the link, I got the error message:
`This link is no longer active`
Anyway,  I want to configure "static" ipv6 addresses via DHCP, I saw that it was implemented in https://github.com/siderolabs/talos/pull/5086

But I don't understand how to add the duid to the install config? Is there any docs or does anyone know how to configure it?

Thanks!!

**Comment by smira** [comment]
It's part of the machine configuration, so it can only be used when the machine configuration is available: https://www.talos.dev/v1.5/reference/configuration/#dhcpoptions

Something like:

```yaml
machine:
  network:
     interfaces:
         - interface: eth0
           dhcp: true
           dhcpOptions:
               ipv4: false
               ipv6: true
               duidv6: .... # hex string
```
