### ISSUE TITLE
No DNS/Network during node upgrade with Cilium

### ISSUE THREAD

**Issue by napei** [siderolabs/talos#7731]
## Bug Report

When running Cilium as the CNI, as per the documentation and set up using the Cilium CLI, nodes will lose network access and DNS access when upgrading and the upgrade will hang trying to pull a new extension image due to not being able to resolve `ghcr.io`.

### Description

I'm not sure if I've done anything wrong, or if this is somehow intended, but I seem to be unable to upgrade nodes. This may also not be an issue with Talos at all, although it seems similar to #7584.

**What I did:**

- I am attempting to update from `1.5.1` to `1.5.2`
- Applied a patch to update the `drbd` extension on all nodes, which was successful without a reboot (as intended, due to needing an upgrade to apply the change)

  ```json
  [
    {
      "op": "replace",
      "path": "/machine/install/extensions",
      "value": [
        {
          "image": "ghcr.io/siderolabs/drbd:9.2.4-v1.5.2"
        }
      ]
    }
  ]
  ```

- Began to update nodes one-by-one, starting with a controlplane node using `talosctl upgrade -n 10.34.2.3 -i ghcr.io/siderolabs/installer:v1.5.2 --preserve`
  - I am using Rook/Ceph, so I am keeping `--preserve` to make the upgrade a little smoother.
- Cilium was installed with the following manifest, using `cilium install`

  ```yaml
  ipam:
    mode: kubernetes
  kubeProxyReplacement: strict
  securityContext:
    capabilities:
      ciliumAgent:
        - CHOWN
        - KILL
        - NET_ADMIN
        - NET_RAW
        - IPC_LOCK
        - SYS_ADMIN
        - SYS_RESOURCE
        - DAC_OVERRIDE
        - FOWNER
        - SETGID
        - SETUID
      cleanCiliumState:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE
  bpf:
    autoMount:
      enabled: false
  cgroup:
    autoMount:
      enabled: false
    hostRoot: /sys/fs/cgroup
  k8sServiceHost: localhost
  k8sServicePort: 7445
  ```

- The node drains all pods and in the process kills the Cilium pod, then proceeds to pull the drbd image but fails to contact my DNS server `10.34.0.100` to resolve `ghcr.io` (see logs below). The node also becomes unreachable over pings, `talosctl`, and in general the network just doesn't work.
  - I have a VIP set to `10.34.2.100` as well. 
- The node eventually rebooted, but was not upgraded.

### Logs

Not sure how to get logs from the VMs that are unreachable over the network, so I'll provide screenshots from the console window.

Please let me know what else I can do to provide as much info as possible, thanks.

![image](https://github.com/siderolabs/talos/assets/8946502/c7e17789-f536-48f5-82a2-888d244f256e)

### Environment

- Talos version:

  ```text
   talosctl version -n 10.34.2.3
   Client:
           Tag:         v1.5.2
           SHA:         318c66b9
           Built:
           Go version:  go1.20.8
           OS/Arch:     linux/amd64
   Server:
           NODE:        10.34.2.3
           Tag:         v1.5.1
           SHA:         40a22cdf
           Built:
           Go version:  go1.20.7
           OS/Arch:     linux/amd64
           Enabled:     RBAC
  ```

- Kubernetes version:

  ```text
  Client Version: v1.28.1
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.28.0
  ```

- Platform: `VMs running on XCP-ng`

- Cilium Versions/Status:

![image](https://github.com/siderolabs/talos/assets/8946502/908ed6f5-b679-4641-adad-fdd0b9a377d0)
