### ISSUE TITLE
unsupported hash algorithm: 18

### ISSUE THREAD

**Issue by uhthomas** [siderolabs/talos#7810]
### Description

I'm trying to install Talos fresh with system disk encryption and seeing the error `unsupported hash algorithm: 18`.

```yaml
  systemDiskEncryption:
    ephemeral:
      keys:
        - tpm: {}
          slot: 0
    state:
      keys:
        - tpm: {}
          slot: 0
```

### Environment

- Talos version: v1.5.3
- Kubernetes version: N/A
- Platform: bare metal
