### ISSUE TITLE
ethernet link gets down after joining to an OVS bridge.

### ISSUE THREAD

**Issue by cybercoder** [siderolabs/talos#7845]
## Bug Report
When I add ethernet port to the OVS bridge it works for a moment and then gets down with this message:
```
[talos] controller failed {"component": "controller-runtime", "controller": "network.LinkSpecController", "error": "1 error occurred:\n\t* error enslaving/unslaving link \"eno33559296\" under \"\": netlink receive: operation not supported\n\n"}
```
### Description
The ovs dockerfile which i've written and works on a k3s cluster:
```
FROM alpine

RUN apk --update add openvswitch && mkdir -p /host/var/run/openvswitch && mkdir -p /host/var/lib/openvswitch
COPY cmd.sh /cmd.sh
RUN chmod +x /cmd.sh
CMD ["./cmd.sh"]

```
and the ```cmd.sh``` file:
```
#!/bin/sh

ovsdb-tool create /host/var/lib/openvswitch/conf.db 2> /dev/null
ovsdb-server \
   --unixctl=/host/var/run/openvswitch/ovsdb-server.0.ctl \
   --pidfile=/host/var/run/openvswitch/ovsdb-server.pid \
   --remote=punix:/host/var/run/openvswitch/db.sock \
   --overwrite-pidfile \
   --detach \
   /host/var/lib/openvswitch/conf.db

ovs-vswitchd \
   --unixctl=/host/var/run/openvswitch/ovs-vswitchd.0.ctl \
   --pidfile=/host/var/run/openvswitch/ovs-vswitchd.pid \
   --overwrite-pidfile \
    unix:/host/var/run/openvswitch/db.sock
```
And the Daemonset which I've wrote:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ovs
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: ik8s-ovs
  template:
    metadata:
      labels:
        name: ik8s-ovs
    spec:
      
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/storage
        effect: NoSchedule
      - key: node-role.kubernetes.io/storage-node
        effect: NoSchedule
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: vswitch
        imagePullPolicy: Always
        image: registry.example.org/ovs
        securityContext:
          privileged: true
          capabilities:
            add:  
            - NET_ADMIN
            - SYS_MODULE
            - SYS_NICE

        volumeMounts:
        - mountPath: /host/var/run/openvswitch
          name: nodeovsrun
        - mountPath: /host/var/lib/openvswitch
          name: nodeovslib
        - mountPath: /lib/modules
          name: kernel-modules
        # command: [ "/cmd.sh" ]
      volumes:
      - name: nodeovsrun
        hostPath:
          path: /var/run/openvswitch
      - name: nodeovslib
        hostPath:
          path: /var/lib/openvswitch
      - name: kernel-modules
        hostPath:
          path: /lib/modules
```
### Logs
```
[talos] controller failed {"component": "controller-runtime", "controller": "network.LinkSpecController", "error": "1 error occurred:\n\t* error enslaving/unslaving link \"eno33559296\" under \"\": netlink receive: operation not supported\n\n"}
```
### Environment

- Talos version: v1.5.3
- Kubernetes version: v1.28
- Platform: Vmware ESXI

**Comment by smira** [comment]
Talos never touches the links it doesn't own, so I assume your machine config targets that link in some way, so Talos tries to configure it, so you should look first into that.

Either way `talosctl get linkspecs -o yaml` should give you everything that Talos tries to configure.

**Comment by cybercoder** [comment]
> Talos never touches the links it doesn't own, so I assume your machine config targets that link in some way, so Talos tries to configure it, so you should look first into that.
> 
> Either way `talosctl get linkspecs -o yaml` should give you everything that Talos tries to configure.

I've tried that, one node with configuring interface on machine config and antoher one empty, but the result is same:
```
node: 172.16.15.111
metadata:
    namespace: network
    type: LinkSpecs.net.talos.dev
    id: eno33559296
    version: 2
    owner: network.LinkMergeController
    phase: running
    created: 2023-10-09T07:16:08Z
    updated: 2023-10-09T07:16:08Z
    finalizers:
        - network.LinkSpecController
spec:
    name: eno33559296
    logical: false
    up: true
    mtu: 0
    kind: ""
    type: netrom
    layer: default
```

get link :
```
network     LinkStatus   eno33559296       24        ether                    00:0c:29:30:fe:cb                                 down         false
```
