### ISSUE TITLE
unable set sysctl with a dot in the path (vlan interface)

### ISSUE THREAD

**Issue by nberlee** [siderolabs/talos#7878]
## Bug Report

dots in sysctls are always translated to a / whereas a vlan interface is in format `netiface.vlanid` which leads to an / between netiface and vlanid.

### Description
When adding to the machine config:
```yaml
machine:
   network:
      interfaces:
        -  interface: eth0
           vlans:
             - vlanId: 103
               dhcp: false
  sysctls:
    net.ipv6.conf.eth0.103.disable_ipv6: "1"
```
talosctl ls confirms the existence of `/proc/sys/net/ipv6/conf/eth0.103/disable_ipv6`

### Logs
I get the error in dmesg:
```
[talos] controller failed {"component": "controller-runtime", "controller": "runtime.KernelParamSpecController", "error": "1 error occurred:\x5cn\x5ct* open /proc/sys/net/ipv6/conf/eth0/103/disable_ipv6: no such file or directory\x5cn\x5cn"}
```
please note the slash between `eth0` and `103` this should be an `.` but there does not seems to be a way to escape the dot in machine config.  A dot in hex `\x2e`  also does not work as `\` gets escaped with `\x5c`
### Environment

- Talos version: 1.5.4
- Kubernetes version: [`kubectl version --short`]
- Platform: LInux
