### ISSUE TITLE
Add upgrade option "--preserve"  to configuration

### ISSUE THREAD

**Issue by red-lichtie** [siderolabs/talos#7889]
In addition to the upgrade option `--preserve`, it should be possible to also define this in the configuration.

It is easy to forget the option when using rook on Talos, and then the rook configuration data at `/var/lib/rook` is gone. Doing this ensures that special case knowledge is only required during installation and that upgrades can be safely carried out by anyone.

The option should to allow preserving of all data, matching the current `--preserve` functionality. It could also be extended to preserve only certain paths during an upgrade, maybe also adding to the CLI too with `--preserve[=dirName[,dirName]]`, e.g. `--preserve=rook`.

The addition to the configuration could look something like the following.

Current default behaviour:
```yaml
varData:
  preserved: false
  preservedSubDirs: []
```

Upgrade option "--preserve"
```yaml
varData:
  preserved: true 
  preservedSubDirs: []
```

Additional functionality, select which /var/lib sub directories should be preserved, in my case I am only interested in `/var/lib/rook`, any other data can be deleted as usual.
```yaml
varData:
  preserved: true
  preservedSubDirs:
   - rook  #  /var/lib/rook
```
