### ISSUE TITLE
Cilium guide inlineManifests is missing being inside the cluster object

### ISSUE THREAD

**Issue by rgl** [siderolabs/talos#7901]
### Description

The [Cilium guide inlineManifests](https://www.talos.dev/v1.5/kubernetes-guides/network/deploying-cilium/#method-4-helm-manifests-inline-install) is missing being inside the `cluster` object. It should be:

```yaml
cluster: # <--- this is missing from the guide.
  inlineManifests:
    - name: cilium
      contents: |
        --
        # Source: cilium/templates/cilium-agent/serviceaccount.yaml
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: "cilium"
          namespace: kube-system
...
```
