### ISSUE TITLE
Supporting extra config files for k8s components

### ISSUE THREAD

**Issue by frezbo** [siderolabs/talos#7911]
## Feature Request

Kubelet, API server, Kube scheduler etc require extra config files to be passed in as arguments for advanced tweaking. Currently Talos lacks an easy way to configure them. See:

* https://github.com/siderolabs/extensions/issues/241
* https://github.com/siderolabs/talos/issues/7905

### Proposal

Support something in the order of `extraConfigFiles` for the components. Eg:

```
machine:
  kubelet:
    extraConfigFiles:
      - name: credentialproviderconfig.yaml
        value:
          apiVersion: kubelet.config.k8s.io/v1
          kind: CredentialProviderConfig
```

The `value` can be any valid yaml and Talos will not validate the schema.

Talos can write down these files to `/etc/kubernetes/<component-name>.d/` directory and fully managed by the configuration in the machine config.

These folders would be mounted by default by Talos to the corresponding components. The user would still have to pass in `extraArgs/extraConfig` to use these files.
