### ISSUE TITLE
Talos installation with btrfs modul fails

### ISSUE THREAD

**Issue by Gottox** [siderolabs/talos#7966]
### Description

When I bootstrap a node with the btrfs extension the installation fails with a `no such file or directory` error.

The relevant section from my machineconfig:
```yaml
    install:
        disk: /dev/xxx
        image: ghcr.io/siderolabs/installer:v1.6.0-alpha.1
        bootloader: true
        wipe: true
        diskSelector:
            model: xxx
        extensions:
          - image: ghcr.io/siderolabs/btrfs:v1.6.0-alpha.1-9-gaf706ee
```

### Logs

![IMG_20231119_221704_941](https://github.com/siderolabs/talos/assets/1056976/2301a60f-9851-44ca-92be-1e6abfacf183)

### Environment

- Talos version: v1.6.0-alpha.1
- Kubernetes version: none
- Platform: metal
