### ISSUE TITLE
Invalid /lib/modules/6.1.61-talos/modules.builtin.alias.bin file?

### ISSUE THREAD

**Issue by antoninbas** [siderolabs/talos#7980]
## Bug Report

When running a privileged container in Talos and mounting the Node's `/lib/modules` path to `/lib/modules` in the container, my expectation is that running `modprobe <built-in module>` would succeed, as it is normal modprobe behavior.

```
modules.builtin
--------------------------------------------------
This file lists all modules that are built into the kernel. This is used
by modprobe to not fail when trying to load something builtin.
```

However, this is not the case, which I believe is caused by an invalid `/lib/modules/6.1.61-talos/modules.builtin.alias.bin` file. See below for detailed explanation.

### Description

I created a K8s DaemonSet using the following manifest.
<details>
  <summary>YAML manifest 1</summary>
  
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      hostNetwork: true
      priorityClassName: system-cluster-critical
      containers:
      - name: test
        image: antrea/antrea-ubuntu
        command: ["sleep", "3600"]
        securityContext:
          privileged: true
        volumeMounts:
          - name: host-lib-modules
            mountPath: /lib/modules
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 0
      volumes:
        - name: host-lib-modules
          hostPath:
            path: /lib/modules
```

The container image used is irrelevant, but `kmod` is required.

</details>

When exec'ing into the container, running `modprobe <built-in module>` will fail. For example:
```
$ modprobe openvswitch
modprobe: FATAL: Module openvswitch not found in directory /lib/modules/6.1.61-talos
$
```

Running `depmod -a` would be the next logical step. However, with `/lib/modules` being read-only in Talos, running `depmod -a` is not possible. So, to confirm my hypothesis of some invalid file in `/lib/modules`, I modified the DaemonSet. This time I mounted `/lib/modules` to `/host/lib/modules`.

<details>
  <summary>YAML manifest 2</summary>
  
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      hostNetwork: true
      priorityClassName: system-cluster-critical
      containers:
      - name: test
        image: antrea/antrea-ubuntu
        command: ["sleep", "3600"]
        securityContext:
          privileged: true
        volumeMounts:
          - name: host-lib-modules
            mountPath: /lib/modules
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 0
      volumes:
        - name: host-lib-modules
          hostPath:
            path: /lib/modules
```

</details>

This time, after exec'ing into one of the containers, I ran the following:
```
# Copy host's /lib/modules to container's /lib/modules, which is not read-only
$ cp -r /host/lib/modules /lib/
$ modprobe openvswitch
modprobe: FATAL: Module openvswitch not found in directory /lib/modules/6.1.61-talos
# Run depmod
$ depmod -a
# Success! modprobe skips loading the module as it is built-in and does not return an error
$ modprobe openvswitch
$
```
Now we can also run the following:
```
# modules.builtin.alias.bin is the only file that differs, maybe there is something wrong with that file?
$ diff -r /lib/modules/6.1.61-talos /host/lib/modules/6.1.61-talos
Binary files /lib/modules/6.1.61-talos/modules.builtin.alias.bin and /host/lib/modules/6.1.61-talos/modules.builtin.alias.bin differ
# restore the original (invalid?) file
$ cp /lib/modules/6.1.61-talos/modules.builtin.alias.bin /tmp/modules.builtin.alias.bin
$ cp /host/lib/modules/6.1.61-talos/modules.builtin.alias.bin /lib/modules/6.1.61-talos/modules.builtin.alias.bin
# modprobe fails again
$ modprobe openvswitch
modprobe: FATAL: Module openvswitch not found in directory /lib/modules/6.1.61-talos
# restore the working version
$ cp /tmp/modules.builtin.alias.bin /lib/modules/6.1.61-talos/modules.builtin.alias.bin
# back to working!
$ modprobe openvswitch
$
```

I don't have any idea why that file specifically is the problem.
I am also aware that module manipulation may not exactly be a supported use-case. But having `modprobe <built-in module>` be a "no-op" can be quite useful when deploying some CNIs (or other K8s infra components) to Talos clusters.

### Logs

See above

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
```
Client:
	Tag:         v1.5.5
	SHA:         ad7361c7
	Built:       
	Go version:  go1.20.11
	OS/Arch:     linux/amd64
Server:
	NODE:        10.5.0.2
	Tag:         v1.5.5
	SHA:         ad7361c7
	Built:       
	Go version:  go1.20.11
	OS/Arch:     linux/amd64
	Enabled:     RBAC

```
- Kubernetes version: [`kubectl version --short`]
```
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3
```
- Platform: QEMU on Linux
