### ISSUE TITLE
talosctl and client authentication store

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#7998]
### Description

kubectl has auth extension https://kubernetes.io/docs/reference/config-api/client-authentication.v1beta1/
It help to store secrets in trusted places. like https://github.com/chrisns/kubectl-passman and many others.

What do you think about it?
Can we add support solution like kubectl has?

```yaml
context: cluster-name
contexts:
    cluster-name:
      endpoints: # optional
            - IP1
            - IP2
      ca: LS... # optional
      exec:
        apiVersion: client.authentication.talos.dev/v1beta1
        args: []
        command: ''
        env: ''
        provideClusterInfo: false
```
