### ISSUE TITLE
[Feature] Helm integration

### ISSUE THREAD

**Issue by etenzy** [siderolabs/talos#8041]
Integrate Helm to bootstrap

Benefits of Adding a Helm:
- easier customization at an early stage of the cluster (cni, extraManifests)
- easier way to create and maintain presets (cni)
    -> no more go logic, just trigger Helm with “some” values
- no more need for hosted (pre-rendered) manifests

Downsides of Adding a Helm:
- may appear clunky at first
- one more dependency to maintain

### Instead of:
```yaml
cluster:
  network:
    cni:
      name: custom
      urls:
        - http://10.10.0.81/cilium.yaml
  extraManifests:
    - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
```

### You could do:
```yaml
cluster:
  network:
    cni:
      name: custom
      helmChart:
        name: cilium
        namespace: kube-system
        repository: https://helm.cilium.io
        chart: cilium
        version: 1.14.0  
        values:
          ipam:
            mode: kubernetes
          kubeProxyReplacement: true
          securityContext:
            capabilities:
              ciliumAgent:
                - CHOWN
                - KILL
                - NET_ADMIN
                - NET_RAW
                - IPC_LOCK
                - SYS_ADMIN
                - SYS_RESOURCE
                - DAC_OVERRIDE
                - FOWNER
                - SETGID
                - SETUID
              cleanCiliumState:
                - NET_ADMIN
                - SYS_ADMIN
                - SYS_RESOURCE
          cgroup:
            autoMount:
              enabled: false
            hostRoot: /sys/fs/cgroup 
          k8sServiceHost: localhost
          k8sServicePort: 7445
  extraHelmCharts:
    - name: metrics-server
      namespace: kube-system
      repository: https://kubernetes-sigs.github.io/metrics-server
      chart: metrics-server
      version: 3.11.0
```

**Comment by smira** [comment]
we considered that, but most probably not in Talos itself.

I know it would simplify some flows, but Helm is too big to be part of the core OS.

Using Helm externally is perfect fine of course.

**Comment by smira** [comment]
This is even less Talos way. If you want to, you can put it that as a static pod to your cluster, but it won't be what Talos offers by default.

**Comment by jabbas** [comment]
The idea of having possibility to do `helm install ...` during the provisioning is that when upgrading or reconfiguring is piece of cake, you just bump your helm repo with it and do helm upgrade or change your values file and boom.

I came with idea of having the SA with proper (admin) rights bounded to Job that will launch `alpine/k8s` or `alpine/helm` which will be put into `inlineManifests` and has those commands (helm install/upgade) in args:

```
    inlineManifests:
        - name: helm-controler-serviceaccount
          contents: |-
            apiVersion: v1
            kind: ServiceAccount
            metadata:
              name: helm-controller
              namespace: kube-system

            ---

            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            metadata:
              name: cluster-admin
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: cluster-admin
            subjects:
            - kind: ServiceAccount
              name: helm-controller
              namespace: kube-system
        - name: cluster-provisioner
          contents: |-
            apiVersion: batch/v1
            kind: Job
            metadata:
              name: cluster-provisioner
              namespace: kube-system
            spec:
              template:
                spec:
                  serviceAccountName: helm-controller
                  securityContext:
                    seccompProfile:
                      type: RuntimeDefault
                  restartPolicy: OnFailure
                  containers:
                  - name: kubectl
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop: ['ALL']
                    image: alpine/k8s:1.30.2
                    command: ['sh', '-c']
                    args:
                      - |
                        helm repo add metallb https://metallb.github.io/metallb

                        helm repo update

                        kubectl create namespace metallb-system
                        kubectl label namespace metallb-system \
                          pod-security.kubernetes.io/enforce=privileged \
                          pod-security.kubernetes.io/audit=privileged \
                          pod-security.kubernetes.io/warn=privileged
                        helm -n metallb-system upgrade --install metallb metallb/metallb
```

But this way i don't have a `wait-for` that to be finished until setting cluster to be ready.
