### ISSUE TITLE
Talos `v1.6.0` Creates A Bunch Of Extra Interfaces

### ISSUE THREAD

**Issue by dcplaya** [siderolabs/talos#8079]
### Description

Tried upgrading some worker nodes to v1.6.0 and I got a bunch of "warnings" about DHCP requests. `unable to receive an offer: got an error while the discovery request: error writing packet to connection: write packet $MAC_ADDRESS: sendto: no buffer space available`. This error occurred on a bunch of links of devices that don't really exist but I do have VLANs configured in my talos config corresponding to the errors showing but only the VLAN part of the link.
For example, my node shows a link of eth103747e.100 and eth103747e.2, which I have no device corresponding to eth103747e but I do have an eth1.2 and eth1.100.
Downgrading to talos `v1.5.5` and the problem goes away.

### Logs
Here is a screenshot of the worker node (its a VM in Proxmox) as well as a partial output of talosctl get addresses --node work1 and a support bundle of the problem node.
![image](https://github.com/siderolabs/talos/assets/1105320/0e2db597-15e2-4188-aeb6-1cec10a4228f)
![image](https://github.com/siderolabs/talos/assets/1105320/c257855e-2032-4b78-b435-d6baf2125d55)
[support.zip](https://github.com/siderolabs/talos/files/13692124/support.zip)

### Environment

- Talos version: v1.6.0
- Kubernetes version: 1.28.3
- Platform: Proxmox Virtual Machine

**Comment by dcplaya** [comment]
To add a bit more info and thanks to @bjw-s for finding the temporary fix, by adding `driver: virtio_net` to my network selectors, this bug does not happen.

Also, my nodes that do not have VLANs configured does not seem to have this bug when upgrading.

**Comment by smira** [comment]
I wonder if that happens because of the https://www.talos.dev/v1.6/introduction/what-is-new/#network-device-selectors?

what was your device selector before/after?

**Comment by dcplaya** [comment]
This is `talhelper` format but it should convey the difference. Just posted my network stuff but if you want to see the entire talhelper config, its located [here](https://github.com/dcplaya/home-ops/blob/main/talos/cluster-1/talconfig.yaml)

# Before
```
      networkInterfaces:
        - deviceSelector:
            hardwareAddr: "72:f2:0d:00:ac:b4"
          dhcp: true
          mtu: 9000
        - deviceSelector:
            hardwareAddr: "da:29:dc:d9:75:f7"
          dhcp: false
          mtu: 9000
          vlans:
            - vlanId: 2
              dhcp: true
              mtu: 1500
              dhcpOptions:
                routeMetric: 2048
            - vlanId: 100
              dhcp: true
              mtu: 1500
              dhcpOptions:
                routeMetric: 4096
```

# After
```
      networkInterfaces:
        - deviceSelector:
            driver: virtio_net
            hardwareAddr: "72:f2:0d:00:ac:b4"
          dhcp: true
          mtu: 9000
        - deviceSelector:
            driver: virtio_net
            hardwareAddr: "da:29:dc:d9:75:f7"
          dhcp: false
          mtu: 9000
          vlans:
            - vlanId: 2
              dhcp: true
              mtu: 1500
              dhcpOptions:
                routeMetric: 2048
            - vlanId: 100
              dhcp: true
              mtu: 1500
              dhcpOptions:
                routeMetric: 4096
```
