### ISSUE TITLE
Patch merging strategy of slices in the machineconfig can cause unexpected validation errors

### ISSUE THREAD

**Issue by utkuozdemir** [siderolabs/talos#8136]
### Description

Apply the following patch using e.g. `talosctl -n 172.20.0.2 patch mc --patch @patch.yaml`:
```yaml
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: ingress-apid
portSelector:
  ports:
    - 50005
  protocol: tcp
ingress:
  - subnet: 192.168.42.0/24
```

Then re-apply the same patch. You'll get the following error:
```
patched MachineConfigs.config.talos.dev/v1alpha1 at the node 172.20.0.2
1 error occurred:
	* 172.20.0.2: rpc error: code = InvalidArgument desc = 1 error occurred:
	* invalid port range: 50005-50005, overlaps with 50005-50005
```

This happens because when the port ranges are being merged, the slices are simply appended to each other, causing duplicate ports `[50005, 50005]`.

Even if there were no validation and this patch would have persisted, it probably still is an unexpected behavior, as this causes patches to behave in a non-idempotent manner - i.e. an unchanged slice ever-growing with each apply of a patch.

### Proposed Solution

a. Use `merge:replace` on `ports` and `ingress`.
b. Merge slices always in a smarter manner, i.e. when a slice is unchanged, do not append.
c. Merge port ranges in a smarter way.
