### ISSUE TITLE
KubePrism does not append members discovered via the kubernetes registry

### ISSUE THREAD

**Issue by vaskozl** [siderolabs/talos#8143]
## Bug Report

I decided to try out KubePrism today and enabled the kubernetes registry as the docs state that [cluster discovery is used for the endopints](https://www.talos.dev/v1.6/talos-guides/discovery/#registries)

KubePrism controller iterates over members and only appends them if the [ControlPlane struct is not nil](https://github.com/siderolabs/talos/blob/ba88678f1a42b4e9f6c9de25bdc827330cfb254c/internal/app/machined/pkg/controllers/k8s/kubeprism_endpoints.go#L69)

However, when using the kubernetes discovery service [only machineType is set](https://github.com/siderolabs/talos/blob/ba88678f1a42b4e9f6c9de25bdc827330cfb254c/internal/pkg/discovery/registry/kubernetes.go#L101), so controlPlane is always `nil`. 

The `controlPlane` struct with the port is only set when using the discovery service (and not the kubernetes discovery registry).

At present the metadata in the node annotations does not specify the port so that would need to be added.

### Environment

- Talos version: 1.6.1

```
      discovery:
        enabled: true
        registries:
          kubernetes:
            disabled: false
          service:
            disabled: true
```
