### ISSUE TITLE
:bug: DHCP address does not disappear after switching to Static allocation

### ISSUE THREAD

**Issue by ebCrypto** [siderolabs/talos#8146]
## Bug Report
DHCP address does not disappear after switching to Static allocation

### Description
In the talos console on a worker that has been configured to use DHCP: 
  push F3 to access the network config
  change DHCP to static, and assign a 1.2.3.4/24 IP address as well as a Gateway
  Save. 
The Summary page shows 2 IP addresses, the original DHCP address and the new one. Even after waiting for the DHCP lease to expire, the address remains.

### Environment

- Talos version: 1.6.1
- Kubernetes version: 1.29.0
- Platform: PVE

**Comment by smira** [comment]
I can't reproduce this issue, in my case it works as expected.

To provide more information, please send the following:

* a screenshot of the dashboard "Network Config" tab
* an output of `talosctl get addressspecs -o yaml`
* an output of `talosctl get operatorspecs -o yaml`

**Comment by ebCrypto** [comment]
![image](https://github.com/siderolabs/talos/assets/44279886/4e821647-5112-4cfd-9133-f40018f5ae92)

![image](https://github.com/siderolabs/talos/assets/44279886/e6b4c45f-7265-4a19-b98f-d0e9c4aac0be)

```
node: 10.0.15.16
metadata:
    namespace: network
    type: AddressSpecs.net.talos.dev
    id: enxbc2411ffae28/10.0.15.16/24
    version: 2
    owner: network.AddressMergeController
    phase: running
    created: 2024-02-06T03:29:31Z
    updated: 2024-02-06T03:29:31Z
    finalizers:
        - network.AddressSpecController
spec:
    address: 10.0.15.16/24
    linkName: enxbc2411ffae28
    family: inet4
    scope: global
    flags: permanent
    layer: operator
---
node: 10.0.15.16
metadata:
    namespace: network
    type: AddressSpecs.net.talos.dev
    id: enxbc2411ffae28/10.0.15.99/24
    version: 2
    owner: network.AddressMergeController
    phase: running
    created: 2024-02-07T02:26:19Z
    updated: 2024-02-07T02:26:19Z
    finalizers:
        - network.AddressSpecController
spec:
    address: 10.0.15.99/24
    linkName: enxbc2411ffae28
    family: inet4
    scope: global
    flags: permanent
    layer: platform
---
node: 10.0.15.16
metadata:
    namespace: network
    type: AddressSpecs.net.talos.dev
    id: lo/127.0.0.1/8
    version: 2
    owner: network.AddressMergeController
    phase: running
    created: 2024-02-06T03:29:16Z
    updated: 2024-02-06T03:29:16Z
    finalizers:
        - network.AddressSpecController
spec:
    address: 127.0.0.1/8
    linkName: lo
    family: inet4
    scope: host
    flags: permanent
    layer: default
```
```
node: 10.0.15.16
metadata:
    namespace: network
    type: OperatorSpecs.net.talos.dev
    id: dhcp4/enxbc2411ffae28
    version: 2
    owner: network.OperatorMergeController
    phase: running
    created: 2024-02-06T03:29:31Z
    updated: 2024-02-06T03:29:32Z
spec:
    operator: dhcp4
    linkName: enxbc2411ffae28
    requireUp: true
    dhcp4:
        routeMetric: 1024
    layer: configuration
```

**Comment by smira** [comment]
So this explains it: 

```yaml
node: 10.0.15.16
metadata:
    namespace: network
    type: OperatorSpecs.net.talos.dev
    id: dhcp4/enxbc2411ffae28
    version: 2
    owner: network.OperatorMergeController
    phase: running
    created: 2024-02-06T03:29:31Z
    updated: 2024-02-06T03:29:32Z
spec:
    operator: dhcp4
    linkName: enxbc2411ffae28
    requireUp: true
    dhcp4:
        routeMetric: 1024
    layer: configuration
```

you have DHCP enabled via machine configuration, which will always work. If you want to use dashboard's metal network config, as it has lower priority, make sure you don't use machine configuration for the network config.
