### ISSUE TITLE
hardwareAddr in deviceSelector is case sensitive

### ISSUE THREAD

**Issue by robkooper** [siderolabs/talos#8176]
## Bug Report

I had the following section in my controlplane configuration:

```
machine:
  install:
    disk: /dev/sda
  network:
    interfaces:
      - deviceSelector:
          hardwareAddr: "A2:99:*"
        dhcp: true
        vip:
          ip: 10.0.0.45
```

And the VIP address was not set on any node. Changing the `hardwareAddr` to be lower case (a2:99:*) and it worked.

### Description

When checking the hardwareAddr it should do a case insensitive match.

### Environment

- Talos version: 1.6.1
- Kubernetes version: 1.28
- Platform: bare metal
