### ISSUE TITLE
Unable to set node taints

### ISSUE THREAD

**Issue by achevillard** [siderolabs/talos#8193]
Hello,

We recently updated from Talos 1.5.5 to the latest version (1.6.2) and we are facing an issue to set the node taints.

## Versions / Environment

- **Kubernetes:** `1.27.5`
- **Talos:** `1.6.2`
- **Cluster API Operator:** `0.7.0`
- **Cluster API Core:** `1.6.0`
- **Cluster API Infrastructure:** `vSphere 1.8.4`
- **Cluster API Bootstrap:** `Talos 0.6.3`
- **Cluster API CP:** `Talos 0.5.4`
- **VMWare ESXi:** `7.0.3`

## Description

We added `machine.nodeTaints` patch in `TalosConfigTemplate` and we faced an issue. The taints are not present and the previsous node labels disappeared.

> NOTE: When we don't specifify node taints the node labels are present.

**TalosConfig**

```yaml
spec:
  configPatches:
  - op: add
    path: /machine/network
    value:
      interfaces:
      - dhcp: true
        dhcpOptions:
          routeMetric: 1
        interface: eth0
  - op: add
    path: /machine/install
    value:
      extraKernelArgs:
      - net.ifnames=0
  - op: add
    path: /cluster/network/cni
    value:
      name: none
  - op: add
    path: /cluster/proxy
    value:
      disabled: true
  - op: replace
    path: /cluster/controlPlane
    value:
      endpoint: https://172.30.11.11:6443
  - op: add
    path: /machine/certSANs
    value:
    - 172.30.11.11
  - op: add
    path: /machine/time
    value:
      disabled: false
      servers:
      - 172.30.11.1
  - op: add
    path: /machine/kubelet/extraArgs
    value:
      cloud-provider: external
      rotate-server-certificates: true
  - op: add
    path: /machine/nodeLabels
    value:
      bgp-peering-policy: OPNsense
      kubernetes.io/poolname: minio
  - op: add
    path: /machine/nodeTaints
    value:
      minio-tenant: true:NoExecute
  generateType: worker
  talosVersion: v1.6.2
```

**Machined Logs:**

```console
172.30.11.109: 2024/01/23 09:07:47.925498 [talos] controller failed {"component": "controller-runtime", "controller": "k8s.NodeApplyController", "error": "2 error(s) occurred:\n\tnodes \"prod-ovh-gra7-k8s-observability-worker-minio-lxwxn-x2fhp\" is forbidden: node \"prod-ovh-gra7-k8s-observability-worker-minio-lxwxn-x2fhp\" is not allowed to modify taints\n\tclient rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline"}
```
