### ISSUE TITLE
install disk for nocloud image not working with diskSelector

### ISSUE THREAD

**Issue by ryjogo** [siderolabs/talos#8216]
### Description
When setting: machine.install.disk: "/dev/sdb" doesn't seem to select the disk. After talking with @andrewrynhard we tried the diskSelector, to which this still did not work. 

The disk (32GB) is a fresh, attached disk. 

### Logs
install.diskSelector is set to >= 20GB - it should select the 32GB disk. 

```
➜  ~ talosctl -n 10.0.30.214 --talosconfig talosconfig get mc -oyaml | grep install -A3
        install:
            diskSelector:
                size: '>= 20GB'
            wipe: false
```
Yet the installation disk is set to /sda which is 17GB

```
➜  ~ talosctl -n 10.0.30.214 --talosconfig talosconfig disks
NODE          DEV        MODEL           SERIAL   TYPE   UUID   WWID   MODALIAS      NAME   SIZE    BUS_PATH                                                      SUBSYSTEM          READ_ONLY   SYSTEM_DISK
10.0.30.214   /dev/sda   QEMU HARDDISK   -        HDD    -      -      scsi:t-0x00   -      17 GB   /pci0000:00/0000:00:05.0/virtio1/host2/target2:0:0/2:0:0:0/   /sys/class/block               *
10.0.30.214   /dev/sdb   QEMU HARDDISK   -        HDD    -      -      scsi:t-0x00   -      34 GB   /pci0000:00/0000:00:05.0/virtio1/host2/target2:0:0/2:0:0:1/   /sys/class/block
```
I have tried removing the 17GB disk, to ensure that the 32GB disk doesn't have the installation, and boot fails - thus its not installed on the 32GB disk. 

### Environment

- Talos version: v1.6.1
- Platform: Proxmox, with two disks
