### ISSUE TITLE
:bug: Dashboard network tab settings not applied

### ISSUE THREAD

**Issue by rothgar** [siderolabs/talos#8219]
## Bug Report
Changing DNS settings from the network config on the dashboard don't apply

### Description
If I change the DNS settings on the network tab of the dashboard I can see the changes reflected in the "new config" pane but the settings on the summary page still show the DHCP network settings. The machine doesn't have any machineconfig applied and after rebooting the system the network changes are removed

### Environment
dev

- Talos version: [`talosctl version --nodes <problematic nodes>`]
```Client:
        Tag:         v1.6.3
        SHA:         d53e07c1
        Built:       
        Go version:  go1.21.6 X:loopvar
        OS/Arch:     linux/amd64
Server:
        NODE:        192.168.4.3
        Tag:         v1.6.3
        SHA:         d53e07c1
        Built:       
        Go version:  go1.21.6 X:loopvar
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```
- Kubernetes version: [`kubectl version --short`]
```Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1
```
- Platform:

**Comment by smira** [comment]
Ok, so I figured out that in fact it works "as expected" (by the design), but this might be still confusing, but fixing that is not trivial.

The full story is described in the [docs](https://www.talos.dev/v1.6/learn-more/networking-resources/#configuration-sources).

The network config edited via the dashboard is considered to be `platform` layer (same as say AWS metadata server info), and DHCP is an `operator` layer, so DHCP has higher precedence than platform network config.

So if there was a machine config setting, it would have overridden all of the above. Also if DHCP wasn't enabled, or DHCP doesn't send the DNS info, dashboard settings would be used.

## How to debug this via resources

First, let's see all sources of resolver configuration:

```shell
$ talosctl get resolverspecs --namespace network-config  
NODE         NAMESPACE        TYPE           ID                                VERSION
172.20.0.5   network-config   ResolverSpec   default/resolvers                 1
172.20.0.5   network-config   ResolverSpec   dhcp4/enx129321a286eb/resolvers   1
172.20.0.5   network-config   ResolverSpec   platform/resolvers                1
```

We can see we have default, operator (dhcp4) and platform. The precedence is `operator` > `platform` > `default`.

So in your case the `operator` is used, which can be verified with:

```yaml
# talosctl -n 172.20.0.5 get resolverspecs -o yaml
node: 172.20.0.5
metadata:
    namespace: network
    type: ResolverSpecs.net.talos.dev
    id: resolvers
    version: 3
    owner: network.ResolverMergeController
    phase: running
    created: 2024-01-31T10:58:56Z
    updated: 2024-01-31T10:58:59Z
    finalizers:
        - network.ResolverSpecController
spec:
    dnsServers:
        - 8.8.8.8
        - 1.1.1.1
    layer: operator # <<-- this is the final layer which took place
```
