### ISSUE TITLE
Pull BGP peering info out of metadata for equinixMetal platform

### ISSUE THREAD

**Issue by rsmitty** [siderolabs/talos#8267]
We may be missing some other metadata for the EM platform. A user has reported they need a config patch like:

```
machine:
  network:
    interfaces:
      - interface: bond0
        routes:
          - network: 169.254.255.1/32
            gateway: 10.66.160.128
          - network: 169.254.255.2/32
            gateway: 10.66.160.128
```

in order to get BGP peering to work for their nodes there. Looking at https://deploy.equinix.com/developers/docs/metal/bgp/bgp-on-equinix-metal/ it seems that this info could be pulled out of the metadata server as part of the platform setup. We should explore this and include these routes by default if they are present.
