### ISSUE TITLE
[upgrade-k8s] images paths overwrite by const while using private registries 

### ISSUE THREAD

**Issue by mstrohl** [siderolabs/talos#8275]
## Bug Report
Unable to kee private registry image path on upgrade-k8s command
### Description
The command line "talosctl upgrade-k8s --to xxxx" replaced images repository to the default public registry instead of changing tag only
  
### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
1.6.3
- Kubernetes version: [`kubectl version --short`]
1.28.2 to 1.29.0
- Platform:
VM on OpenStack

**Comment by smira** [comment]
Yes, this is not supported as of right now, but you have two ways to get around it:

* update k8s manually according to the [documentation](https://www.talos.dev/v1.6/kubernetes-guides/upgrading-kubernetes/#manual-kubernetes-upgrade)
* use [registry mirrors](https://www.talos.dev/v1.6/talos-guides/configuration/pull-through-cache/) so that the image references are "canonical", but the actual registry used if your private one

**Comment by mstrohl** [comment]
Hello @smira! Thank you to answer. 
Registry mirrors have been setup but it seems to doesn't work like that:
```
    registries:
        mirrors:
            docker.io:
                endpoints:
                    - https://private-registry.example.com/harbor_folder/
                overridePath: true 
            gcr.io:
                endpoints:
                    - https://private-registry.example.com/harbor_folder/
                overridePath: true 
            ghcr.io:
                endpoints:
                    - https://private-registry.example.com/harbor_folder/
                overridePath: true 
            registry.k8s.io:
                endpoints:
                    - https://private-registry.example.com/harbor_folder/
                overridePath: true 
        config:
            private-registry.example.com:
                auth:
                    username: xxxxxx 
                    password: yyyyyyy 
                    auth: zzzzzz 
```
That is why we have forked and tested a change ton the code. The PR will come in a couple of minutes.
