### ISSUE TITLE
Kubelet not starting

### ISSUE THREAD

**Issue by MichaelTrip** [siderolabs/talos#8302]
## Bug Report

I have been trying to deploy Talos on a VM in Proxmox, but the kubelet is not coming up.

### Description
Kubelet not coming up after trying to deploy Talos. 

1. Booted VM from ISO
2. generated config
3. applying config to VM
4. VM reboots after that
5. apply-config for controlplane.yaml
6. After that, bootstrap is issued
7. etcd seems to be started, but kubelet is not starting.

```bash
$: ~/_out# talosctl service
NODE         SERVICE      STATE         HEALTH   LAST CHANGE   LAST EVENT
10.99.1.20   apid         Running       OK       9m22s ago     Health check successful
10.99.1.20   containerd   Running       OK       9m34s ago     Health check successful
10.99.1.20   cri          Running       OK       9m26s ago     Health check successful
10.99.1.20   dashboard    Running       ?        9m28s ago     Process Process(["/sbin/dashboard"]) started with PID 1468
10.99.1.20   etcd         Waiting       ?        8m0s ago      Waiting for etcd spec
10.99.1.20   kubelet      Initialized   ?         ago          <none>
10.99.1.20   machined     Running       OK       9m39s ago     Health check successful
10.99.1.20   trustd       Running       OK       9m27s ago     Health check successful
10.99.1.20   udevd        Running       OK       9m29s ago     Health check successful
$:~/_out# talosctl service kubelet
NODE     10.99.1.20
ID       kubelet
STATE    Initialized
HEALTH   ?

$:~/_out# talosctl logs kubelet
ERROR: rpc error: code = Unknown desc = log "kubelet" was not registered

$:~/_out# talosctl service etcd
NODE     10.99.1.20
ID       etcd
STATE    Waiting
HEALTH   ?
EVENTS   [Waiting]: Waiting for etcd spec (8m51s ago)
         [Waiting]: Waiting for service "cri" to be "up", time sync, network, etcd spec (8m52s ago)
```

I also tried setting a static ip address with the boot parameters, but to no avail. 

### Logs
![Screenshot from 2024-02-12 13-29-54](https://github.com/siderolabs/talos/assets/1826203/06a960bb-b6fa-4663-be87-736502daa9c7)

### Environment

- Talos version: v1.6.3 (also tried the latest version... didn´t work either)
- Kubernetes version:  1.29.1
- Platform: Proxmox

**Comment by smira** [comment]
Please submit the `support.zip` from `talosctl support`.

**Comment by MichaelTrip** [comment]
> Please submit the `support.zip` from `talosctl support`.

[support.zip](https://github.com/siderolabs/talos/files/14238421/support.zip)

here you go. Thanks for the quick response :+1:

**Comment by smira** [comment]
Your host network overlaps with Talos default pod/service Kubernetes network:

```yaml
metadata:
    namespace: network
    type: AddressStatuses.net.talos.dev
    id: enxaeb8dee2dd20/10.99.1.20/24
    version: 1
    owner: network.AddressStatusController
    phase: running
    created: 2024-02-12T12:24:43Z
    updated: 2024-02-12T12:24:43Z
spec:
    address: 10.99.1.20/24
    linkIndex: 8
    linkName: enxaeb8dee2dd20
    family: inet4
    scope: global
    flags: permanent
```

See https://www.talos.dev/v1.6/introduction/troubleshooting/#conflict-on-kubernetes-and-host-subnets for a solution.
