### ISSUE TITLE
fstrim and monitoring for disks

### ISSUE THREAD

**Issue by dsseng** [siderolabs/talos#8314]
## Feature Request
Support periodic FS trimming would not only help bare metal installs, but also thin-provisioned VMs.

hwmon could be useful as well for admins to be able to get CPU/disk/mainboard temperature etc.

### Description
Basically the request. Unsure if these can be enabled via extensions, but perhaps these should be available by default, at least discards/fstrim. Maybe this is achievable using stuff like discard=async as well, but some admins use periodic TRIM.

I could possibly develop fstrim stuff if I have time

**Comment by onedr0p** [comment]
Looks like fstrim can be added as a system extension

https://github.com/siderolabs/extensions?tab=readme-ov-file#tools

**Comment by smira** [comment]
Talos already supports some `fstrim`-related operations on disk wipes. We have some plans for Volume support in Talos, and `fstrim` might be part of that.

**Comment by M4t7e** [comment]
It seems trimming is not supported for encrypted volumes. I just used Longhorn with a LUKS2 encrypted volume and tried to trim manually via the Longhorn UI. That responds with this error: `unable to trim filesystem for volume test: failed to find valid mountpoint`

Discards need to be enabled as they are not by default according to their [docs](https://longhorn.io/docs/1.7.2/nodes-and-volumes/volumes/trim-filesystem/#encrypted-volumes)
<blockquote>
Enter into the node host the volume is attached to.
Enable flag discards for the encrypted volume. The passphrase is recorded in the corresponding secret:

```sh
cryptsetup --allow-discards --persistent refresh <Longhorn volume name>
```

Directly use Longhorn UI to trim the volume or execute fstrim for the mount point of /dev/mapper/<volume name> manually.
</blockquote>

I thought `allow_discards` can be enabled with `EncryptionConfig.options`, but they are only for "additional --perf parameters". Is there any way to enable that for encrypted volumes?

See also: https://github.com/longhorn/longhorn/issues/7836

**Comment by onedr0p** [comment]
According to the docs looks like `xfs_scrub` will bring in TRIM support, there's a PR here

https://github.com/siderolabs/talos/pull/9848

**Comment by onedr0p** [comment]
I'm pretty sure this is still something needed.

**Comment by hugosxm** [comment]
I am quite surprise to see that this is not supported, seems like a major needs for running longhorn or DRBD in a talos cluster. 

Do we have a way to launch a privileged container and run the fstrim by a hostPath mount maybe ?

EDIT : 

Did some tests, this is working ( a bit hacky... ) : 

```yaml

apiVersion: v1
kind: Pod
metadata:
  name: discard
spec:
  containers:
    - name: fstrim
      image: alpine
      command: ["/bin/ash"]
      args: ["-c","fstrim -v /var/mnt/cnpg"]
      securityContext:
        capabilities:
          add:
            - SYS_ADMIN
      volumeMounts:
      - mountPath: /var/mnt/cnpg
        mountPropagation: HostToContainer
        name: cnpg-volume
  volumes:
  - hostPath:
      path: /var/mnt/cnpg
      type: Directory
    name: cnpg-volume
```

My main goal is to trim the UserVolumes because in here you can have shared storage or databases runnings directly on the host for max performance ( HA being managed by the DB and the storage ). So I guess I can run a cronjob with that.

But a "nice and integrated" solution from Talos would be cool :).
