### ISSUE TITLE
Node does not get ready after adding second network interface to the talos configuration

### ISSUE THREAD

**Issue by ManuelSchmitzberger** [siderolabs/talos#8315]
## Bug Report

After adding a second network interface (`interface: enx8a38d0c41d8a`) to our talos configuration, the node does not get into ready state. This issue arises when the second interface configuration is applied. With only one network interface configured, everything functions as expected.

### Description

Additionally, when attempting to start a debug pod on the controller with the second interface configured, connection to the pod is refused with errors indicating an inability to dial the backend on the IP `10.3.3.100:10250`.

The network configuration:
```
            interfaces:
                - interface: enx3e317a9bfe29
                  mtu: 1500 
                  addresses:
                    - 10.3.8.100/22
                  routes:
                    - network: 0.0.0.0/0
                      gateway: 10.3.8.1
                  vip:
                    ip: 10.3.8.110
                - interface: enx8a38d0c41d8a
                  mtu: 1500
                  addresses:
                    - 10.3.3.100/24
                  routes:
                    - network: 10.3.3.0/24
```

The problematic interface is the following:
```
                - interface: enx8a38d0c41d8a
                  mtu: 1500
                  addresses:
                    - 10.3.3.100/24
                  routes:
                    - network: 10.3.3.0/24
```

### Logs

When starting a debug pod on the controller with the second network interface configured, the following error is encountered:
```
warning: couldn't attach to pod/debug-shell-ms-ws, falling back to streaming logs: error dialing backend: dial tcp 10.3.3.100:10250: connect: connection refused
pod "debug-shell-ms-ws" deleted
Error from server: Get "https://10.3.3.100:10250/containerLogs/kube-system/debug-shell-ms-ws/debug-shell": dial tcp 10.3.3.100:10250: connect: connection refused
```

Logs from Talos:
![screenshot_2024-02-14T08:57:17](https://github.com/siderolabs/talos/assets/10824925/4b19a333-e44d-4076-aa10-d93a373a7cbb)

### Environment

Talos version: 
```
Server:
	NODE:        10.3.8.100
	Tag:         v1.6.4
	SHA:         431bcada
	Built:
	Go version:  go1.21.6 X:loopvar
	OS/Arch:     linux/amd64
	Enabled:     RBAC
```
Kubernetes version: 
```
NAME              STATUS   ROLES           AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE         KERNEL-VERSION   CONTAINER-RUNTIME
k8s-controller0   Ready    control-plane   11d   v1.29.1   10.3.8.100    <none>        Talos (v1.6.4)   6.1.74-talos     containerd://1.7.13
```
Platform: VM

### Steps to Reproduce

1.) Configure Talos with a single network interface – node operates as expected.
2.) Add a second network interface to the Talos configuration as specified above.
3.) Observe that the node does not return to a healthy state and debug pod connections are refused.
