### ISSUE TITLE
Following the quickstart leads to "failed to verify certificate"

### ISSUE THREAD

**Issue by echo-devnull** [siderolabs/talos#8442]
## Bug Report
I've tried the ISO and nocloud variants on proxmox.
(https://www.talos.dev/v1.6/talos-guides/install/virtualized-platforms/proxmox/ and https://www.talos.dev/v1.6/talos-guides/install/cloud-platforms/nocloud/#example-proxmox)

I can get the machines to boot up, and I can also "apply" a config after generating:

```sh
talosctl gen config Mar1424 https://10.0.10.22:6443
talosctl apply-config --insecure --nodes 10.0.10.22 --file controlplane.yaml
```

Afterwards, any command I do, for instance a bootstrap, results in:

```
talosctl bootstrap
error executing bootstrap: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of \"x509: Ed25519 verification failure\" while trying to verify candidate authority certificate \"talos\")"
```

![Screenshot from 2024-03-14 20-00-06](https://github.com/siderolabs/talos/assets/5389465/2a9092d5-1387-42fd-8f38-6c241bb6414b)

### Description
So trying to follow the quickstart (https://www.talos.dev/v1.6/talos-guides/install/virtualized-platforms/proxmox/#using-the-cluster

and then, after failing with that, trying the others (that are basically the same) I simply cannot get it to work / connect.
What am I not seeing?

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
```sh
❯ talosctl version --nodes 10.0.10.22
Client:
        Tag:         v1.6.6
        SHA:         7dceba06
        Built:
        Go version:  go1.21.8 X:loopvar
        OS/Arch:     linux/amd64
Server:
error getting version: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of \"x509: Ed25519 verification failure\" while trying to verify candidate authority certificate \"talos\")"
```

```yaml
context: Mar1424
contexts:
    Mar1424:
        endpoints:
            - 127.0.0.1
        ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEJWSWtpTnh2Mk9yNEtZMmlTL2I0L09NQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5EQXpNVFF4T0RVd016SmFGdzB6TkRBek1USXhPRFV3TXpKYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBbVgyZTlSWjJZVGpTZis1SlkzZUpqNDNWOVZTa01Od1ZvWFJxCkRvcDFvVkNqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVeGJOY3hDQVJsRE1MN3AxZgpKSnZGNEdkQ2hDOHdCUVlESzJWd0EwRUFOSWlrVDBqazFuTVowSkwwTTNMUytySUErcWw5K3V3Wk9xT3d4NXZUCkRPdnpxVjVwdkxNdXNGOXNzSExVeW8yKzQrQ1hWVURtODNFVmI4dlJXTWZMQ1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJLVENCM0tBREFnRUNBaEVBaUd1YkV4QmREU01IK2Jud3ZoTG1CVEFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qUXdNekUwTVRnMU1ETXlXaGNOTWpVd016RTBNVGcxTURNeVdqQVRNUkV3RHdZRApWUVFLRXdodmN6cGhaRzFwYmpBcU1BVUdBeXRsY0FNaEFOSjBReS9kWWlyRGs1bjQzVEEvNkZUUkh5cC9nQ3N2CkN4a3F0QlByakpKMG8wZ3dSakFPQmdOVkhROEJBZjhFQkFNQ0I0QXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0h3WURWUjBqQkJnd0ZvQVV4Yk5jeENBUmxETUw3cDFmSkp2RjRHZENoQzh3QlFZREsyVndBMEVBUnI1Ugp2bmNybml0UVVDYnl1ako5Yi9iRUVXdzBYV3dJWGhTTUVJTk0wTWpZbHZScFpCcnZ1d3J2dGlxWnRlcEc3cDV2CjlvcnZRc08ramkrQ2NyN0ZEUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJS0hjS2UrNGxyLzM4RDh3N0JmVCtMVHB5SndHSnZvemdlNVdWKzczK0lhRQotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
```
