### ISSUE TITLE
Do not set a default endpoint value in talosctl gen config

### ISSUE THREAD

**Issue by steverfrancis** [siderolabs/talos#8500]
## Feature Request
Do not supply a default value for endpoints when creating talosconfig via `talosctl gen config`
### Description
``` 
talosctl gen config talos-test https://10.23.40.1:6443 
 more talosconfig 
context: talos-test
contexts:
    talos-test:
        endpoints:
            - 127.0.0.1
```
But connecting to loopback will never work, and results in an unclear error:
`rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:50000: connect: connection refused"`

It is better to not set the endpoint.
The current error is better:
`error constructing client: failed to determine endpoints`
A better error would be, if endpoints are not set, would be:
`endpoints are not set. Please pass in the endpoints to talosctl via the --endpoints flag, or set them in talosconfig`
