### ISSUE TITLE
Default Flannel installation does not account for KubePrism endpoint

### ISSUE THREAD

**Issue by bgagnon** [siderolabs/talos#8501]
### Description

Talos 1.6.6 deploys Flannel and KubePrism by default, but does not update the Flannel arguments to redirect it to the KubePrism endpoint. The impact is that the Flannel pod will `CrashLoopBackoff` on any node that doesn't have connectivity to the control plane node on port `:6443`.

Patching the`DaemonSet` like this is one workaround:

```yaml
     containers:
      - image: ghcr.io/siderolabs/flannel:v0.23.0
        args:
        - --ip-masq
        - --kube-subnet-mgr
        command:
        - /opt/bin/flanneld
        env:
        - name: KUBERNETES_SERVICE_HOST       # kubeprism
          value: 127.0.0.1                    # kubeprism
        - name: KUBERNETES_SERVICE_PORT       # kubeprism
          value: "7445"                       # kubeprism
```

Passing an extra `args` would also do the trick:

```
  -kube-api-url string
    	Kubernetes API server URL. Does not need to be specified if flannel is running in a pod.
```

### Environment

- Talos version: `v1.6.6`
- Kubernetes version: `v1.29.3`
