### ISSUE TITLE
How to allow port 5678 - Error: Invalid NodePort Value in nginx-ingress-n8n Service YAML

### ISSUE THREAD

**Issue by byteshiva** [siderolabs/talos#8513]
**Description:**
When attempting to apply the YAML configuration file `nginx-ingress-n8n-service.yml` using `kubectl apply -f`, an error is encountered regarding the `nodePort` value specified in the service definition. The error message indicates that the provided port, `5678`, falls outside the valid range for NodePort values, which is `30000-32767`.

**How to allow port 5678?**

---

**Steps to Reproduce:**
1. Attempt to apply the YAML configuration file `nginx-ingress-n8n-service.yml` using `kubectl apply -f`.
2. Observe the error message regarding the invalid NodePort value.

**Error Message:**
```
The Service "nginx-ingress-n8n" is invalid: spec.ports[0].nodePort: Invalid value: 5678: provided port is not in the valid range. The range of valid ports is 30000-32767.
```

**Actual Behavior:**
The provided NodePort value, `5678`, is outside the valid range, resulting in an error during service validation.

`nginx-ingress-n8n-service.yml`
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-n8n
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 5678
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ingress-nginx
```

- Talos version: [`v1.6.5`]
- Kubernetes version: [`kubectl version 
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2
`]
- Platform: nixos

Refer:
https://www.talos.dev/v1.6/talos-guides/network/ingress-firewall/
```[tasklist]
### Tasks
```
