### ISSUE TITLE
Unable to setup a second network interface in non-routed network

### ISSUE THREAD

**Issue by cherez0ff** [siderolabs/talos#8519]
### Description
Due to hosting limitation on control of L2, I need Sidero on Talos cluster to have two interfaces - regular with network access (to download images and be kickstarted from normal network), and technical without routing in special VLAN where I can set up DHCP.

Issue is - when I'm creating a talos node with two such interfaces, the 'regular' interfaces work as expected, but second does not get IP, and triggers DHCP requests (because of autocreated operatorspec, apparently)

Providing machineconfig and other data

### Logs
`request/renew failed {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "error": "unable to receive an offer: got an  error while the discovery request: no matching response packet received", "link": "enxbc2411c769a9"}`
`DHCP REQUEST {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "link": "enxbc2411c769a9"}`

### Environment
- Talos version: v1.6.6
- Kubernetes version: v1.29.2
- Platform: Proxmox 8.1.5

### machineconfig
```yaml
version: v1alpha1 # Indicates the schema used to decode the contents.
debug: true # Enable verbose logging to the console.
persist: true
machine:
    type: worker # Defines the role of the machine within the cluster.
    token: 7k2n6o.if514s7rrf4tm8ix # The `token` is used by a machine to join the PKI of the cluster.
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEJra1RSamozYnBPenVLV0xMdGMzZGhNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5EQXpNakl4TURNeU1ETmFGdzB6TkRBek1qQXhNRE15TUROYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBL2h1RC85UU1iVDZ4MkRqSjZGSXp0bjhCT2N1clMvZUlldHRwCllMOTlQaXVqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVR0E3MXowcENxM0Q0TDV6SgpQWVVzN0JUU0NmTXdCUVlESzJWd0EwRUF4cUYvY0QwRHFyNFJGd0ZSMWgydW4xQXpISi9TRTZGaGtHckZvR3orCldMTWRERHRFc285SnBmaHRaMmFEOXMraDhXMVJBSDRJaDN6VkViWDhRTFVZQWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: ""
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.29.2 # The `image` field is an optional reference to an alternative kubelet image.
        defaultRuntimeSeccompProfileEnabled: true # Enable container runtime default Seccomp profile.
        disableManifestsDirectory: true # The `disableManifestsDirectory` field configures the kubelet to get static pod manifests from the /etc/kubernetes/manifests directory.
    network:
        hostname: sc-ams99-obe-dev-test-talos-node2
        interfaces:
            - interface: enbc2411c769a9 # tech interface
              addresses:
                  - 172.31.70.4/26
              routes:
                  - network: 172.31.70.0/26
            - interface: enbc24117e7638 # normal interface
              addresses:
                  - 10.42.1.243/22
              routes:
                  - network: 0.0.0.0/0
                    gateway: 10.42.0.3
                    metric: 1024 # The optional metric for the route.
              mtu: 1500 # The interface's MTU.
        nameservers:
            - 10.42.3.11
    install:
        disk: /dev/sda # The disk used for installations.
        image: ghcr.io/siderolabs/installer:v1.6.6 # Allows for supplying the image used to perform the installation.
        wipe: true # Indicates if the installation disk should be wiped at installation time.
    registries: {}
    features:
        rbac: true # Enable role-based access control (RBAC).
        stableHostname: true # Enable stable default hostname.
        apidCheckExtKeyUsage: true # Enable checks for extended key usage of client certificates in apid.
        diskQuotaSupport: true # Enable XFS project quota support for EPHEMERAL partition and user disks.
        kubePrism:
            enabled: true # Enable KubePrism support - will start local load balacing proxy.
            port: 7445 # KubePrism port.
    time:
        disabled: false # Indicates if the time service is disabled for the machine.
        servers:
            - 10.42.3.11
        bootTimeout: 2m0s # Specifies the timeout when the node time is considered to be in sync unlocking the boot sequence.
cluster:
    id: 4sJPwTpyr9LrTxklh0NOvazrs0RtYNoRY1ILu-I21bo= # Globally unique identifier for this cluster (base64 encoded random 32 bytes).
    secret: oK8pkVXD+KkjtxYvltCfuLJKP8o/qfXT0nSaSQB8OzU= # Shared secret of cluster (base64 encoded random 32 bytes).
    controlPlane:
        endpoint: https://10.42.1.241:6443 # Endpoint is the canonical controlplane endpoint, which can be an IP address or a DNS hostname.
    network:
        dnsDomain: cluster.local # The domain used by Kubernetes DNS.
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: eic5m5.4wzozztacfpfyv5b # The [bootstrap token](https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/) used to join the cluster.
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpRENDQVMrZ0F3SUJBZ0lRVDNkN0NGMTZsbDdTdDU5UW54MkdlekFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTBNRE15TWpFd016SXdNMW9YRFRNME1ETXlNREV3TXpJdwpNMW93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCQ0dySVBxMnNRd2xZR0lLUmZzMjNXSTdocWlwTWxTeXo5T3h6cjZlVU00L2E0ZllxTXcwaWUyZ3JRMk0KNW9oVVhoRldXcFNPNVN3NEUxK0hoZTEyT2dPallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVU4Yk5wcmtiK3ZtYVZzRWpPYmxBbVFpU1lCQzh3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnS1Q4dVJBTWIKZ0hJSE5Xb2pLZTE0L3hlVjc5MTV0eTNKc1p2a0QydU5aVXNDSUhpOVRJc1NveDNxcUZ5cDZpMUk1cG9wUlVIUQp0VVJidTJORGZ2YTRjWkVOCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        key: ""
    discovery:
        enabled: true # Enable the cluster membership discovery feature.
        registries:
            kubernetes:
                disabled: true # Disable Kubernetes discovery registry.
            service: {}
```

![1711974015](https://github.com/siderolabs/talos/assets/63862323/e7e0e953-6319-4ad7-ae81-4e7365a40484)

![1711974023](https://github.com/siderolabs/talos/assets/63862323/a2dfc5b4-2298-467c-bd6b-56162f361da4)
[support.zip](https://github.com/siderolabs/talos/files/14823338/support.zip)
