### ISSUE TITLE
DHCP operator doesn't skip hostname request/response in OpenStack Platform

### ISSUE THREAD

**Issue by rperez95** [siderolabs/talos#8531]
### Description
In the OpenStack platform, Talos hostname assignment should skip hostname request/response in the DHCP Operator using `SkipHostnameRequest` flag. However, despite the fix introduced in PR #6373, we are encountering an issue where the final hostname assigned to Talos machines is still being overridden by the hostname provided by OpenStack's DHCP information.

### Logs
`talosctl logs controller-runtime | grep -i dhcp`
```
10.6.0.153: 2024-04-02T10:10:34.548Z DEBUG starting operator {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4/eth0"}
10.6.0.153: 2024-04-02T10:10:34.549Z DEBUG DHCP REQUEST {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "link": "eth0"}
10.6.0.153: 2024-04-02T10:10:34.601Z DEBUG DHCP ACK {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "link": "eth0", "dhcp": "opcode: BootReply, hwtype: Ethernet, hopcount: 0, transaction ID: 0x904ada6e, num seconds: 0, flags: Unicast (0x00), client IP: 0.0.0.0, your IP: 10.6.0.153, server IP: 10.6.0.2, gateway IP: 0.0.0.0, client MAC: fa:16:3e:a2:cd:c1, server hostname:, bootfile name:, options:, Subnet Mask: ffffff00, Router: 10.6.0.1, Domain Name Server: 8.8.8.8, Host Name: host-10-6-0-153, Domain Name: openstacklocal, Interface MTU: [5 170], Broadcast Address: 10.6.0.255, IP Addresses Lease Time: 24h0m0s, DHCP Message Type: ACK, Server Identifier: 10.6.0.2, Renew Time Value: [0 0 168 192], Rebinding Time Value: [0 1 39 80], Classless Static Route: route to 169.254.169.254/32 via 10.6.0.1; route to 0.0.0.0/0 via 10.6.0.1"}
10.6.0.153: 2024-04-02T10:10:35.636Z DEBUG detected hostname change {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "old": "", "new": "host-10-6-0-153.openstacklocal"}
```

`talosctl  logs controller-runtime | grep -i hostname`
```
10.6.0.153: 2024-04-02T10:10:30.218Z DEBUG controller starting {"component": "controller-runtime", "controller": "network.HostnameConfigController"}
10.6.0.153: 2024-04-02T10:10:30.223Z DEBUG controller starting {"component": "controller-runtime", "controller": "network.HostnameSpecController"}
10.6.0.153: 2024-04-02T10:10:30.223Z DEBUG controller starting {"component": "controller-runtime", "controller": "network.HostnameMergeController"}
10.6.0.153: 2024-04-02T10:10:34.601Z DEBUG DHCP ACK {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "link": "eth0", "dhcp": "opcode: BootReply, hwtype: Ethernet, hopcount: 0, transaction ID: 0x904ada6e, num seconds: 0, flags: Unicast (0x00), client IP: 0.0.0.0, your IP: 10.6.0.153, server IP: 10.6.0.2, gateway IP: 0.0.0.0, client MAC: fa:16:3e:a2:cd:c1, server hostname:, bootfile name:, options:, Subnet Mask: ffffff00, Router: 10.6.0.1, Domain Name Server: 8.8.8.8, Host Name: host-10-6-0-153, Domain Name: openstacklocal, Interface MTU: [5 170], Broadcast Address: 10.6.0.255, IP Addresses Lease Time: 24h0m0s, DHCP Message Type: ACK, Server Identifier: 10.6.0.2, Renew Time Value: [0 0 168 192], Rebinding Time Value: [0 1 39 80], Classless Static Route: route to 169.254.169.254/32 via 10.6.0.1; route to 0.0.0.0/0 via 10.6.0.1"}
10.6.0.153: 2024-04-02T10:10:34.619Z INFO setting hostname {"component": "controller-runtime", "controller": "network.HostnameSpecController", "hostname": "host-10-6-0-153", "domainname": "openstacklocal"}
10.6.0.153: 2024-04-02T10:10:34.645Z INFO setting hostname {"component": "controller-runtime", "controller": "network.HostnameSpecController", "hostname": "host-10-6-0-153", "domainname": "openstacklocal"}
10.6.0.153: 2024-04-02T10:10:35.636Z DEBUG detected hostname change {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "old": "", "new": "host-10-6-0-153.openstacklocal"}
```
`talosctl get hostnamespec --namespace network-config -o yaml`

```
node: 10.6.0.153
metadata:
    namespace: network-config
    type: HostnameSpecs.net.talos.dev
    id: default/hostname
    version: 1
    owner: network.HostnameConfigController
    phase: running
    created: 2024-04-02T10:10:42Z
    updated: 2024-04-02T10:10:42Z
spec:
    hostname: talos-jju-f36
    domainname: ""
    layer: default
---
node: 10.6.0.153
metadata:
    namespace: network-config
    type: HostnameSpecs.net.talos.dev
    id: dhcp4/eth0/hostname
    version: 1
    owner: network.OperatorSpecController
    phase: running
    created: 2024-04-02T10:10:34Z
    updated: 2024-04-02T10:10:34Z
spec:
    hostname: host-10-6-0-153
    domainname: openstacklocal
    layer: operator
---
node: 10.6.0.153
metadata:
    namespace: network-config
    type: HostnameSpecs.net.talos.dev
    id: platform/hostname
    version: 1
    owner: network.PlatformConfigController
    phase: running
    created: 2024-04-02T10:10:41Z
    updated: 2024-04-02T10:10:41Z
spec:
    hostname: cluster-1-controlplane-5j2zk
    domainname: novalocal
    layer: platform
```
`talosctl get operatorspec --namespace network-config -o yaml`

```
node: 10.6.0.153
metadata:
    namespace: network-config
    type: OperatorSpecs.net.talos.dev
    id: default/dhcp4/eth0
    version: 1
    owner: network.OperatorConfigController
    phase: running
    created: 2024-04-02T10:10:33Z
    updated: 2024-04-02T10:10:33Z
spec:
    operator: dhcp4
    linkName: eth0
    requireUp: true
    dhcp4:
        routeMetric: 1024
    layer: default
```

[hostname.log](https://github.com/siderolabs/talos/files/14836200/hostname.log)
[dhcp.log](https://github.com/siderolabs/talos/files/14836201/dhcp.log)

### Environment

- Talos version: v1.6.5
- Kubernetes version: v1.29.3
- Platform: OpenStack

**Comment by rperez95** [comment]
**Update**

After some investigation, @smira identified the root cause of the issue: the current Talos version lacks support for `"type": "bridge"`. Consequently, he proposed a solution by adding it to the switch statement in the openstack.go file:

`https://github.com/siderolabs/talos/blob/fd71a74d0f0083388f6599dde92ec3dae453dc82/internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go#L149-L151`

```
switch netLink.Type {
        case "phy", "vif", "ovs", "bridge":
            linkName := ""
```

To validate this solution, we opted to create a custom Talos image, following the instructions provided in the documentation: [Building Talos Images](https://www.talos.dev/v1.6/advanced/building-images/). The outcome was positive, as the addition allowed Talos to correctly set the hostname, as we shown down below:

`talosctl get hostnamespec --namespace network-config -o yaml`
```
node: 10.6.0.84
metadata:
    namespace: network-config
    type: [HostnameSpecs.net.talos.dev](http://hostnamespecs.net.talos.dev/)
    id: default/hostname
    version: 1
    owner: network.HostnameConfigController
    phase: running
    created: 2024-04-02T14:10:03Z
    updated: 2024-04-02T14:10:03Z
spec:
    hostname: talos-6kl-ro6
    domainname: ""
    layer: default
---
node: 10.6.0.84
metadata:
    namespace: network-config
    type: [HostnameSpecs.net.talos.dev](http://hostnamespecs.net.talos.dev/)
    id: platform/hostname
    version: 1
    owner: network.PlatformConfigController
    phase: running
    created: 2024-04-02T14:10:05Z
    updated: 2024-04-02T14:10:05Z
spec:
    hostname: cluster-1-controlplane-m4snn
    domainname: novalocal
    layer: platform
```
![image](https://github.com/siderolabs/talos/assets/116586749/12905e69-4520-4fc5-b539-cb33b19635b3)

We suggest extending the switch condition to include at least the "bridge" network type, as we have verified its functionality. Additionally, we propose initiating a discussion to incorporate the remaining network types:

- "dvs"
- "hw_veb"
- "hyperv"
- "tap"
- "vhostuser"
