### ISSUE TITLE
[talos + Harbor] failed to pull image due to missing protocol scheme

### ISSUE THREAD

**Issue by remkolems** [siderolabs/talos#8543]
## Bug Report
- [talos] retrying error: failed to pull image "gcr.io/etcd-development/etcd:v3.5.11": failed to resolve reference "gcr.io/etcd-development/etcd:v3.5.11": parse ":///reg.company.com/gcr.io/etcd-development/etcd/manifests/v3.5.11?ns=gcr.io": missing protocol scheme
- ghcr.io failed to resolve reference "ghcr.io/siderolabs/kubelet:v1.29.3": parse ":///reg.company.com/ghcr.io/siderolabs/kubelet/manifests/v1.29.3?ns=ghcr.io": missing protocol scheme

The above is retrieved via: `talosctl -n 10.10.10.11 dmesg`

### Description
1. Configured `Harbor v2.10.1` with reverse proxy + TLS termination (HAProxy) ==> `https://reg.company.com`
2. Configured registry mirrors as:

```yaml
  registries:
    mirrors:
      docker.io:
        endpoints:
          - reg.company.com/docker.io
        overridePath: true
      gcr.io:
        endpoints:
          - reg.company.com/gcr.io
        overridePath: true
      ghcr.io:
        endpoints:
          - reg.company.com/ghcr.io
        overridePath: true
      lscr.io:
        endpoints:
          - reg.company.com/lscr.io
        overridePath: true
      public.ecr.aws:
        endpoints:
          - reg.company.com/public.ecr.aws
        overridePath: true
      quay.io:
        endpoints:
          - reg.company.com/quay.io
        overridePath: true
      registry.gitlab.com:
        endpoints:
          - reg.company.com/registry.gitlab.com
        overridePath: true
      registry.k8s.io:
        endpoints:
          - reg.company.com/registry.k8s.io
        overridePath: true
    config:
      reg.company.com:
        auth:
          username: user-talos
          password: <forme2know>
```

4.  If I disable or completely remove the two registry mirror entries `gcr.io` and `ghcr.io` in the above config, than there are no `missing protocol scheme` errors and a Talos install is successful. The remaining registry mirrors are fine, especially in respect to `registry.k8s.io` (hence: registry.k8s.io/kube-controller-manager:v1.29.3)
5. Removed any restriction within Harbor that could perhaps hinder any pulling. To no avail.

### Questions/remarks
1. Is the `missing protocol scheme` perhaps a known issue?
2. What is meant with `missing protocol scheme`?
3. Until now I've experienced no issue whatsoever with Harbor in respect to pulling/pushing any container to what software platform before.

### Environment
- PoC (three master or control plane nodes)
- Talos version: 1.6.7
- Kubernetes version: 1.29.3
- Platform: baremetal
- Harbor version: 2.10.1 (docker compose/docker v26.0.0; on external dedicated node)
- HAProxy version: 2.8.2-61a0f57 (as package on a dedicated pfSense Plus node)
- Talos cluster install is based on the template [https://github.com/onedr0p/cluster-template](https://github.com/onedr0p/cluster-template)
- Talhelper version: 2.3.10
