### ISSUE TITLE
Allow to set a webhook backend for the audit logs

### ISSUE THREAD

**Issue by Issif** [siderolabs/talos#8597]
## Feature Request

Allow to set a webhook backend for the control plane audit logs.

### Description

The k8s control plane can send its audit logs to a specified webhook endpoint but nothing allow to configure that in Talos for now. See the official [k8s docs](Allow to set a webhook backend for the audit logs) for more details.

We could have a setting like this:
```yaml
cluster:
  apiServer:
    auditWebhook:
      server: http://${IP}:${PORT}/${PATH}
```
which results to create the required config file for the control plane:
```yaml
apiVersion: v1
kind: Config
clusters:
- name: falco
  cluster:
    server: http://${IP}:${PORT}/${PATH}
contexts:
- context:
    cluster: falco
    user: ""
  name: default-context
current-context: default-context
preferences: {}
users: []
```

My current need is to be able to use the [K8s audit logs plugin of Falco](https://github.com/falcosecurity/plugins/tree/main/plugins/k8saudit#kubernetes-audit-events-plugin) with Talos.
