### ISSUE TITLE
skipHostnameRequest not set on configuration layer for openstack

### ISSUE THREAD

**Issue by Wouter0100** [siderolabs/talos#8601]
### Description

After diving into issue https://github.com/siderolabs/talos/issues/8531+ and reading the [Slack thread](https://taloscommunity.slack.com/archives/CMARMBC4E/p1711988319844489), I found a partial solution by upgrading to the latest beta.1 (good to see it's already released!):
```
NAME                 STATUS   ROLES           AGE   VERSION
host-172-16-22-118   Ready    control-plane   17m   v1.26.7
host-172-16-22-245   Ready    control-plane   16m   v1.26.7
host-172-16-22-50    Ready    control-plane   17m   v1.26.7
test-md-0-2-ggc5d    Ready    <none>          17m   v1.26.7
test-md-0-2-h7t7b    Ready    <none>          16m   v1.26.7
test-md-0-2-td9rw    Ready    <none>          16m   v1.26.7
```

As seen above, in our case it is unfortunately only fixed for our worker nodes. This is because we have a `vip` defined on the control plane nodes:
```
        - op: replace
          path: /machine/network/interfaces
          value:
            - deviceSelector:
                busPath: "0*"
              dhcp: true
              vip:
                ip: 172.16.22.4
```

This causes the OperatorSpec to be created by the `configuration` layer, not setting the `skipHostnameRequest`:
```
root@access:~# talosctl -n 172.16.22.118 get operatorspec dhcp4/eth0 -o yaml
node: 172.16.22.118
metadata:
    namespace: network
    type: OperatorSpecs.net.talos.dev
    id: dhcp4/eth0
    version: 3
    owner: network.OperatorMergeController
    phase: running
    created: 2024-04-15T08:17:44Z
    updated: 2024-04-15T08:17:50Z
spec:
    operator: dhcp4
    linkName: eth0
    requireUp: true
    dhcp4:
        routeMetric: 1024
    layer: configuration
root@access:~# talosctl -n 172.16.22.190 get operatorspec -o yaml
node: 172.16.22.190
metadata:
    namespace: network
    type: OperatorSpecs.net.talos.dev
    id: dhcp4/eth0
    version: 2
    owner: network.OperatorMergeController
    phase: running
    created: 2024-04-15T08:16:57Z
    updated: 2024-04-15T08:17:13Z
spec:
    operator: dhcp4
    linkName: eth0
    requireUp: true
    dhcp4:
        routeMetric: 1024
        skipHostnameRequest: true
    layer: platform
```

Possible solutions for this could be to allow us to set it manually or honor `skipHostnameRequest` in the configuration layer for the OpenStack platform.

### Logs
n/a

### Environment

- Talos version: v1.7.0-beta.1
- Kubernetes version: v1.26.7
- Platform: openstack
