### ISSUE TITLE
Go Panic in LinkConfigController when attempting to add bridge

### ISSUE THREAD

**Issue by ruifung** [siderolabs/talos#8626]
### Description
When attempting to add a bridge using the following config fragment, it fails to add a bridge and logs a go panic message to console.
```yaml
machine:
  nodeLabels:
    role: worker
  network:
    interfaces:
      - interface: eth0
        dhcp: true
      - interface: eth1
        dhcp: false
      - interface: br0
        dhcp: false
        bridge:
          interfaces:
            - eth1
```
### Logs
```
 user: warning: [2024-04-22T06:23:22.338896757Z]: [talos] controller failed {"component": "controller-runtime", "controller": "network.LinkConfigController", "error": "controller \"network.LinkConfigController\" panicked: runtime error: invalid memory address or nil pointer
 dereference\n\ngoroutine 502 [running]:\nruntime/debug.Stack()\n\t/toolchain/go/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/cosi-project/runtime/pkg/controller/runtime/internal/rruntime.(*Adapter).runOnce.func2()\n\t/.cache/mod/github.com/cosi-project/runtime@v0.4.1/pkg/
 controller/runtime/internal/rruntime/run.go:67 +0x58\npanic({0x2bc4b60?, 0x526cd90?})\n\t/toolchain/go/src/runtime/panic.go:770 +0x132\ngithub.com/siderolabs/talos/internal/app/machined/pkg/controllers/network.SetBridgeMaster(0xc001b3b500, {0x367f010?, 0xc000813820?})\n\t/src/
 internal/app/machined/pkg/controllers/network/network.go:133 +0x58\ngithub.com/siderolabs/talos/internal/app/machined/pkg/controllers/network.(*LinkConfigController).processDevicesConfiguration(0..
```
### Environment

- Talos version:
```
Client:                                                                                                                                 Tag:         v1.7.0                                                                                                             SHA:         70fb41ff                                                                                                   
        Built:
        Go version:  go1.22.2
        OS/Arch:     windows/amd64
Server:
        NODE:        pathweb-worker-1.servers.home.yrf.me
        Tag:         v1.7.0
        SHA:         70fb41ff
        Built:
        Go version:  go1.22.2
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```
- Kubernetes version:
```
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3
```
- Platform: metal-amd64 (Proxmox)
