### ISSUE TITLE
DRBD/Extension parameters in Image Factory

### ISSUE THREAD

**Issue by soulwhisper** [siderolabs/talos#8629]
## Feature Request
Extension parameters used for fresh install with Image Factory, for example, drbd.
### Description
Hi, I am using talos with [piraeus-operator](https://github.com/piraeusdatastore/piraeus-operator). Before Image Factory, talos extension is configured like below.
```yaml
machine:
  install:
    extensions:
      - image: ghcr.io/siderolabs/drbd:9.2.0-v1.3.6
  kernel:
    modules:
      - name: drbd
        parameters:
          - usermode_helper=disabled
      - name: drbd_transport_tcp
```
There is a parameter for drbd. I can not found method to add it back with a Image Factory install.

**Comment by frezbo** [comment]
This has nothing to do with factory, you'd apply a machine config patch as below:

```yaml
machine:
  kernel:
    modules:
      - name: drbd
        parameters:
          - usermode_helper=disabled
      - name: drbd_transport_tcp
```

**Comment by soulwhisper** [comment]
> This has nothing to do with factory, you'd apply a machine config patch as below:
> 
> ```yaml
> machine:
>   kernel:
>     modules:
>       - name: drbd
>         parameters:
>           - usermode_helper=disabled
>       - name: drbd_transport_tcp
> ```

I did this, but using 'talosctl -n <NODE_IP> read /sys/module/drbd/parameters/usermode_helper' returns nothing.

**Comment by frezbo** [comment]
> > This has nothing to do with factory, you'd apply a machine config patch as below:
> > ```yaml
> > machine:
> >   kernel:
> >     modules:
> >       - name: drbd
> >         parameters:
> >           - usermode_helper=disabled
> >       - name: drbd_transport_tcp
> > ```
> 
> I did this, but using 'talosctl -n <NODE_IP> read /sys/module/drbd/parameters/usermode_helper' returns nothing.

check if the module is loaded first, `talosctl logs controller-runtime` & `talosctl read /proc/modules`

**Comment by soulwhisper** [comment]
![image](https://github.com/siderolabs/talos/assets/26273512/73d11f4a-9c67-48ed-b88d-d55fd3356b6f)

![image](https://github.com/siderolabs/talos/assets/26273512/c5da395a-7a21-41a6-9c71-ff78667d2292)

**Comment by soulwhisper** [comment]
I rebooted a worker. this is its status.
![image](https://github.com/siderolabs/talos/assets/26273512/6b1dfb61-d9e6-4289-ba0f-1ae8d2ad5102)

**Comment by frezbo** [comment]
what does `talosctl logs controller-runtime` show?

**Comment by soulwhisper** [comment]
`talosctl logs controller-runtime | grep drbd` returns nothing. neither `error` or `warn`

**Comment by soulwhisper** [comment]
[support.zip](https://github.com/siderolabs/talos/files/15063569/support.zip)
There is a DNS error during export, just ignore it if you saw it.

**Comment by frezbo** [comment]
I tested with a cluster and everything seems to work as expected:

```bash
❯ talosctl -n 10.5.0.3 read /sys/module/drbd/parameters/usermode_helper
disabled
```
with this patch:

```yaml
machine:
  kernel:
    modules:
      - name: drbd
        parameters:
          - usermode_helper=disabled

```
