### ISSUE TITLE
Ability to rotate secret encryption keys used in apiserver

### ISSUE THREAD

**Issue by ruifung** [siderolabs/talos#8702]
### Description
While trying to implement the procedure as described at
https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#rotating-a-decryption-key

(due to accidental publishing of a full machineconfig to a public github repository)

I was blocked by the inability to modify the encryptionconfig.yaml file to have the older keys in it to transition to a newly generated key.

This seems like something that would be nice to be supported in talosctl, or at least, the ability to add multiple encryption secrets to the machineconfig for the purposes of key rotation. 

I've attempted the procedure manually by trying to specify a custom encryptionconfig file that has been inserted via files[], but apparently that argument is protected by talos and I am unable to override it.

**Comment by clementnuss** [comment]
just for info, I was able to modify the files in `/system/secrets/kubernetes/kube-apiserver` by running a ["node-shell"](https://github.com/kvaps/kubectl-node-shell) pod on the node:

```shell
kubectl node-shell -x -n kube-system <node-name>
```

through doing that you could rotate. It's only a workaround, a proper configuration API would be needed to manage the etcd encryption secrets, but for now it could do the trick.

**Comment by Strainy** [comment]
I figured we could kind of work around this using file patches and following the official rotation process here:
https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#rotating-a-decryption-key

Unfortunately, I couldn't seem to get this working. Is it actually possible to rotate this secret at all?

----------------------

Here’s what I tried to do:

1. Read the original `EncryptionConfig`:
    
    ```bash
    talosctl -n 10.5.0.2 read /system/secrets/kubernetes/kube-apiserver/encryptionconfig.yaml > talos-patch-new-secretbox-key.yaml
    ```
    
2. Then update the encryption configuration to include a new encryption key (inserted **before** the existing one in the list):
    
    ```yaml
    # talos-patch-new-secretbox-key-2.yaml
    machine:
        files:
          - content: |-
              apiVersion: v1
              kind: EncryptionConfig
              resources:
              - resources:
                - secrets
                providers:
                - secretbox:
                    keys:
                    # key1 is a new key we want to rotate to
                    # generated via: head -c 32 /dev/urandom | base64
                    - name: key1
                      secret: mPJAfOEOl2s5ybfp7KqHFUYF8oOeVmvlKK0+ePrrN04=
                    - name: key2
                      secret: nMPsyOh7G7mk0YUEOb15Zti3ORBiyO0kfaxFN218J6c=
                - identity: {}
            permissions: 0o755
            path: /system/secrets/kubernetes/kube-apiserver/encryptionconfig.yaml
            op: overwrite
    ```
    
3. Patch each of the control plane nodes with this file (triggers reboot):
    
    ```bash
    talosctl -n 10.5.0.2 patch mc --patch-file talos-patch-new-secretbox-key.yaml
    # do the same for other nodes...
    ```
    
4. After each control plane node is patched/rebooted, you’ll need to reboot the API servers again (as the static pods might be started **before** Talos applies the file patches).
    
    ```bash
    kubectl -n kube-system delete pod kube-apiserver-groq-controlplane-1
    pod "kube-apiserver-groq-controlplane-1" deleted
    kubectl -n kube-system delete pod kube-apiserver-groq-controlplane-2
    pod "kube-apiserver-groq-controlplane-2" deleted
    kubectl -n kube-system delete pod kube-apiserver-groq-controlplane-3
    pod "kube-apiserver-groq-controlplane-3" deleted
    ```
    
5. Unfortunately, this results in decryption errors. **Unclear how to work around this**.
