### ISSUE TITLE
1.7.1 breaks all network connectivity, working in 1.7.0

### ISSUE THREAD

**Issue by no1here0003** [siderolabs/talos#8711]
### Description
When I upgrade from a working 1.7.0 to 1.7.1 all network connectivity breaks. I can only see what's happening by connecting a display directly to the box. The nodes are nuc13i7's with Sonnet SOLO10G-SFP-T3 USB modems.
### Logs
Unable to retrieve logs due to the network connectivity not being present.
### Environment
The nodes are nuc13i7's with Sonnet SOLO10G-SFP-T3 USB modems.
```
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/i915-ucode
            - siderolabs/intel-ucode
            - siderolabs/thunderbolt
            - siderolabs/usb-modem-drivers
```

To downgrade I hard reboot and select 1.7.0 again and everything happily starts up.

If there are any commands I can issue I'm happy to do the upgrade process as many times as it takes.
