### ISSUE TITLE
Problem with nvidia-device-plugin

### ISSUE THREAD

**Issue by hansom82** [siderolabs/talos#8713]
### Description

Problem with `nvidia-device-plugin` (or `nvidia-container-cli`)

Installer image: `factory.talos.dev/installer/db59a7617844583755851238c13760d095f0072f755497786c08e057608cd476:v1.7.1`

```yaml
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/amdgpu-firmware
            - siderolabs/binfmt-misc
            - siderolabs/bnx2-bnx2x
            - siderolabs/chelsio-drivers
            - siderolabs/chelsio-firmware
            - siderolabs/drbd
            - siderolabs/fuse3
            - siderolabs/i915-ucode
            - siderolabs/intel-ice-firmware
            - siderolabs/intel-ucode
            - siderolabs/iscsi-tools
            - siderolabs/mdadm
            - siderolabs/nonfree-kmod-nvidia
            - siderolabs/nvidia-container-toolkit
            - siderolabs/qlogic-firmware
            - siderolabs/realtek-firmware
            - siderolabs/usb-modem-drivers
            - siderolabs/util-linux-tools
            - siderolabs/zfs
 ```

Cluster configuration generated with:
```bash
talosctl gen config talos-gkuber-cluster https://$CONTROL_PLANE_IP:6443 \
    --output-dir _out \
    --kubernetes-version 1.28.7
```

Apply patch to worker nodes:
```yaml
machine:
  kernel:
    modules:
      - name: nvidia
      - name: nvidia_uvm
      - name: nvidia_drm
      - name: nvidia_modeset
      - name: zfs
  sysctls:
    net.core.bpf_jit_harden: 1
```

and all other steps from [tutorial](https://www.talos.dev/v1.7/talos-guides/configuration/nvidia-gpu-proprietary/)

Create namespace `nvidia-device-plugin` and add label:
```bash
kubectl label --overwrite ns nvidia-device-plugin  pod-security.kubernetes.io/enforce=privileged
```

Install `nvidia-device-plugin` command:
```bash
helm install nvidia-device-plugin nvdp/nvidia-device-plugin --version=0.14.0 --set=runtimeClassName=nvidia --namespace=nvidia-device-plugin
```

### Logs

Finally, I had daemonset pod with permanent "CrashLoopBackOff" status and always restart. Describe of this pod looks like this:
```
Events:
  Type     Reason                  Age                From               Message
  ----     ------                  ----               ----               -------
  Normal   Scheduled               43m                default-scheduler  Successfully assigned nvidia-device-plugin/nvidia-device-plugin-5wf27 to talos-48o-aqn
  Warning  FailedCreatePodSandBox  43m                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "24b3f63a93e73df9500e74bb70652e1e23a62ab6b18df8c5f8253a4d84aa2152": plugin type="flannel" failed (add): failed to find plugin "flannel" in path [/opt/cni/bin]
  Normal   SandboxChanged          43m (x2 over 43m)  kubelet            Pod sandbox changed, it will be killed and re-created.
  Normal   Pulling                 43m                kubelet            Pulling image "nvcr.io/nvidia/k8s-device-plugin:v0.14.0"
  Normal   Pulled                  42m                kubelet            Successfully pulled image "nvcr.io/nvidia/k8s-device-plugin:v0.14.0" in 11.946s (11.946s including waiting)
  Normal   Created                 42m (x4 over 42m)  kubelet            Created container nvidia-device-plugin-ctr
  Warning  Failed                  42m (x4 over 42m)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 127, stdout: , stderr: Auto-detected mode as 'legacy'
/usr/local/bin/nvidia-container-cli: error while loading shared libraries: /usr/local/glibc/lib/libc.so: invalid ELF header: unknown
  Normal   Pulled   41m (x4 over 42m)      kubelet  Container image "nvcr.io/nvidia/k8s-device-plugin:v0.14.0" already present on machine
  Warning  BackOff  3m17s (x186 over 42m)  kubelet  Back-off restarting failed container nvidia-device-plugin-ctr in pod nvidia-device-plugin-5wf27_nvidia-device-plugin(b74f6973-06a7-4b22-96d5-dd8cdfe03e94)
```

### Environment

- Talos version: v1.7.1
- Kubernetes version: 1.28.7
- Platform: metal (Proxmox and Bare Metal)
