### ISSUE TITLE
Etcd don't start after bootstrap

### ISSUE THREAD

**Issue by Minivolk02** [siderolabs/talos#8726]
## Bug Report
Etcd don't start after bootstrap
### Description
Etcd don't start after bootstrap
### Logs
[talos] service[etcd](Failed): Condition failed: context canceled
 user: warning: [2024-05-09T09:20:09.404547126Z]: [talos] service[etcd](Finished): Bootstrap requested
 user: warning: [2024-05-09T09:20:09.405089126Z]: [talos] service[etcd](Starting): Starting service
 user: warning: [2024-05-09T09:20:09.405594126Z]: [talos] service[etcd](Waiting): Waiting for service "cri" to be
 "up", time sync, network, etcd spec
 user: warning: [2024-05-09T09:20:09.406492126Z]: [talos] task startAllServices (1/1): done, 37.871156217s
 user: warning: [2024-05-09T09:20:09.406984126Z]: [talos] phase startEverything (16/16): done, 37.872123767s
 user: warning: [2024-05-09T09:20:09.407507126Z]: [talos] boot sequence: done: 38.463758891s
 user: warning: [2024-05-09T09:20:10.407322126Z]: [talos] service[etcd](Waiting): Waiting for etcd spec
### Environment

- Talos version:
Client:
	Tag:         v1.7.0
	SHA:         70fb41ff
	Built:
	Go version:  go1.22.2
	OS/Arch:     linux/amd64
Server:
	NODE:        10.224.238.2
	Tag:         v1.7.0
	SHA:         70fb41ff
	Built:
	Go version:  go1.22.2
	OS/Arch:     linux/amd64
	Enabled:     RBAC
- Kubernetes version:
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
- Platform:
Vagrant and Libvirt

**Comment by smira** [comment]
Please submit your issues with some logs, or preferably `talosctl support` bundle. 

If I would guess, etcd spec is not built as there are no IPs to assign the etcd cluster to.

**Comment by Minivolk02** [comment]
[support.zip](https://github.com/siderolabs/talos/files/15322405/support.zip)
Here it is

**Comment by smira** [comment]
You specifically configure `etcd` not to advertise the only address you have on the node:

```yaml
metadata:
    namespace: etcd
    type: EtcdConfigs.etcd.talos.dev
    id: etcd
    version: 1
    owner: etcd.ConfigController
    phase: running
    created: 2024-05-15T08:11:54Z
    updated: 2024-05-15T08:11:54Z
spec:
    advertiseExcludeSubnets:
        - 10.224.238.2
    listenExcludeSubnets: []
    image: gcr.io/etcd-development/etcd:v3.5.13
    extraArgs: {}
```

So etcd can't start, as it needs an address to advertise to other peers, and there is none available.

If you hit an issue, it's always a good idea to revert machine config changes and try with plain defaults. If defaults work, the problem might be your config change.
