### ISSUE TITLE
Support source-based routing

### ISSUE THREAD

**Issue by kvaps** [siderolabs/talos#8738]
### Description

I noticed that there is no way to configure source-based routing in Talos, which I really needed.

```
ip route add 11.22.33.224/27 dev bond0.217 table 100
ip route add default via 11.22.33.245 table 100
```

It could be written as:

```yaml
interfaces:
    interface: bond0
    vlans:
        vlanId: 217
        routes:
            network: 11.22.33.224/27
            table: 100
            network: 0.0.0.0/0
            gateway: 11.22.33.245
            table: 100
```

but the table option is not supported.

Is there an API for rules? Or what should it look like:

```
ip rule add from 11.22.33.244/27 table 100
```
