### ISSUE TITLE
`apply-config --dry-run` does not show a diff for multidoc config

### ISSUE THREAD

**Issue by TimJones** [siderolabs/talos#8885]
### Description

When changing multi-doc type config (in this specific case `NetworkDefaultActionConfig` and `NetworkRuleConfig`) and applying to a node using `talosctl apply-config --dry-run` no output diff is shown even when there are changes to be made.

### Logs

```
❯ talosctl get nftableschain ingress -o yaml
1 error occurred:
        * rpc error: code = NotFound desc = resource NfTablesChains.net.talos.dev(network/ingress@undefined) doesn't exist

❯ talosctl apply-config --file machine-config.yaml --dry-run
Dry run summary:
Applied configuration without a reboot (skipped in dry-run).
Config diff:
No changes.

❯ talosctl apply-config --file machine-config.yaml
Applied configuration without a reboot

❯ talosctl -n 10.150.0.18 get nftableschain ingress -o yaml
node: xxx
metadata:
    namespace: network
    type: NfTablesChains.net.talos.dev
    id: ingress
    version: 1
    owner: network.NfTablesChainConfigController
    phase: running
    created: 2024-06-10T09:21:06Z
    updated: 2024-06-10T09:21:06Z
spec:
    type: filter
    hook: input
    priority: filter
    policy: accept
    rules:
        - matchIIfName:
            interfaceName:
                - lo
                - siderolink
                - kubespan
            operator: ==
          anonymousCounter: true
          verdict: accept
        - matchSourceAddress:
            ...
```

### Environment

- Talos version: `v1.7.2`
- Kubernetes version: `v1.30.1`
- Platform: `bare metal`
