### ISSUE TITLE
Add .machine.nodeAnnotations

### ISSUE THREAD

**Issue by jdmarble** [siderolabs/talos#8971]
## Feature Request

I'd like to set a node annotation in the same way that I can currently set a node label using the machine configuration.

### Description

There may be other uses for this feature, but see the [Longhorn documentation for customizing default disks for new nodes](https://longhorn.io/docs/1.6.2/nodes-and-volumes/nodes/default-disk-and-node-config/#customizing-default-disks-for-new-nodes) for the one I'm thinking of. When my cluster comes up, I want Longhorn to be configured to use some dedicated disks on some of the nodes without manual intervention. This way of declaratively configuring Longhorn uses a node label and annotation for the node specific (non-global) parameters.

I can currently configure a single, Longhorn-dedicated disk per node if I mount it to the same place on each node (location configured with Longhorn `default-data-path` global option). If I had a way to add annotations to the node before Longhorn comes up, I could automatically add multiple disks per node to Longhorn when I create the cluster. Then I could set my machine configuration to something like this:

```yaml
machine:
  disks:
    - device: "/dev/sdb"
      partitions:
        - mountpoint: "/var/mnt/disk1"
    - device: "/dev/sdc"
      partitions:
        - mountpoint: "/var/mnt/disk2"
  nodeLabels:
    node.longhorn.io/create-default-disk: config
  nodeAnnotations:  # doesn't exist yet!
    node.longhorn.io/default-disks-config: |
      [
          { 
              "name":"disk1",
              "path":"/var/mnt/disk1"
          },
          { 
              "name":"disk2",
              "path":"/var/mnt/disk2"
          }
      ]
```

Alternatives for my use case:

* `kubectl annotate node ...` before deploying Longhorn works, but I'm trying to deploy the entire cluster and workload declaratively.
* I can just add the disks manually using the Longhorn web UI.
