### ISSUE TITLE
Talos `1.7.5`: Invalid worker configuration generated by `talosctl gen config`

### ISSUE THREAD

**Issue by febus982** [siderolabs/talos#8985]
## Bug Report

`talos gen config` produces a configuration that is invalid on workers.

### Description

I am using this patch to generate the config:

```
machine:
  # Extra certificate subject alternative names for the machine's certificate.
  certSANs:
    - "<REDACTED>"
  network:
    interfaces:
      - interface: eth0
        dhcp: true
        vip:
          ip: <REDACTED>
cluster:
  apiServer:
    # Extra certificate subject alternative names for the API server's certificate.
    certSANs:
      - "<REDACTED>"
```

The VIP config makes workers fail validation when applied. I remember this not happening on `1.6.7` (not sure if the worker generated config did omit the VIP settings or it was the workers just ignoring it)

### Environment

- Talos version: 
```
Client:
	Tag:         v1.7.5
	SHA:         47731624
	Built:
	Go version:  go1.22.4
	OS/Arch:     darwin/arm64
```
- Kubernetes version: N/A
- Platform: darwin/arm64
