### ISSUE TITLE
Ability for controller-manager and Scheduler to bind on POD_IP

### ISSUE THREAD

**Issue by varet80** [siderolabs/talos#9031]
Currently, api server uses an environment variable, which will allow us to bind or set this ip as advertised.
this is achieved by the POD_IP  env variable:
```
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
```

I suggest to add this env variable in scheduler and controller-manager.
By doing so, it allows us to expose these on internalIP and enable prometheus metrics.
