### ISSUE TITLE
KubeSpan compatibility with Cilium's native routing

### ISSUE THREAD

**Issue by stevefan1999-personal** [siderolabs/talos#9043]
There is a [native routing feature in Cilium](https://docs.cilium.io/en/stable/network/concepts/routing/#native-routing) which is based on L3 routing rather than using tunnel encapsulation, because we already have L3 connectivity with KubeSpan (thanks to WireGuard), having another layer of encapsulation is somewhat meaningless, that it contributes more to the MTU reduction. As such I think we should have something like `advertiseKubernetesNetworks: true` but not actually routing the packets automatically, and we could still let Cilium or other CNI handle it. 

I've done this in the past manually, which is done by manipulating wgconf with "AllowedIPs = <Pod CIDR>, <Service CIDR>" and `Table = Off` in every node. 

I think KubeSpan did this already, but all we need to do is make sure the eBPF and nftables rules in KubeSpan can correctly handle the traffic.

**Comment by smira** [comment]
KubeSpan takes care of node-to-node traffic, while CNI should take care of pod-to-pod traffic (and convert it to node-to-node traffic). Native routing makes sense when nodes are directly connected, so no need to use KubeSpan.

**Comment by stevefan1999-personal** [comment]
> KubeSpan takes care of node-to-node traffic, while CNI should take care of pod-to-pod traffic (and convert it to node-to-node traffic). Native routing makes sense when nodes are directly connected, so no need to use KubeSpan.

KubeSpan is sure needed if you run behind NAT gateway for multiple cloud as a hybrid solution :) 

It's simply way too expensive to run VPN Gateway and manually plan out networking for that. We could just leverage KubeSpan's ability to let pod traffic go through node-to-node and thus cloud-to-cloud.

Sure CNI would still take care of pod-to-pod address allocation (the usual `ip route add <pod/cidr> via <kubespan-ip> dev kubespan` stuff), but node-to-node routing using KubeSpan is denied because the pod CIDR is not allowed in the Wireguard config.

**Comment by mentos1386** [comment]
Sorry for (kinda) off topic comment, but @Preisschild you mentioned:

> I ended up implementing this, but not via kubespan, but via a tailscale extension, but I tried it over kubespan before that too.

This is something I'm trying to achieve as well. Using Tailscale for node-node communication and then disable cilium tunnel. Do you mind giving me some help how did you manage to configure this?

**Comment by alexandrem** [comment]
We have a strong interest for this. We run in hybrid cloud mode with control plane nodes on Azure and physical servers elsewhere, so we leverage KubeSpan for this. Cilium native routing reduces the vxlan+wireguard encapsulation overhead between the pods across the nodes.

After digging a bit into the issue, I figured that the simplest way to solve this problem was to have a daemonset that extracts the main cilium pod IP address on `cilium_host` and adds a secondary IP address with the mask size for the whole node, for instance `/24`. 

This in combination with `advertiseKubernetesNetworks` enabled ensures that each node pod CIDR is added to each kubespan `AllowedIPs` peer.

Here's the daemonset that solves the problem:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cilium-host-node-cidr
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: cilium-host-node-cidr
  template:
    metadata:
      name: cilium-host-node-cidr
      labels:
        app: cilium-host-node-cidr
    spec:
      hostNetwork: true
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: Exists
      - key: "node-role.kubernetes.io/control-plane"
        operator: Exists
      containers:
      - name: cilium-host-node-cidr
        image: alpine
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - |
          apk update
          apk add iproute2

          handle_error() {
            echo "$1"
            sleep "$SLEEP_TIME"
          }

          echo "Watching cilium_host IP addresses..."

          while :; do
            # Extract all IPv4 addresses from cilium_host
            ip_addresses=$(ip -4 addr show dev cilium_host |grep inet | awk '{print $2}')

            # Check if any of the IP addresses match the NODE_CIDR_MASK_SIZE
            echo "$ip_addresses" | grep -q "/${NODE_CIDR_MASK_SIZE}" || {

              # Extract the /32 IP address if NODE_CIDR_MASK_SIZE was not found
              pod_ip=$(echo "$ip_addresses" | grep "/32" | cut -d/ -f1)

              if [ -z "$pod_ip" ]; then
                handle_error "Couldn't extract cilium pod IP address from cilium_host interface"
                continue
              fi

              # Add secondary IP address with the proper NODE_CIDR_MASK_SIZE
              echo "cilium_host IP is $pod_ip"
              ip addr add "${pod_ip}/${NODE_CIDR_MASK_SIZE}" dev cilium_host

              echo "Added new cilium_host IP address with mask /${NODE_CIDR_MASK_SIZE}"
              ip addr show dev cilium_host
            }

            sleep "$SLEEP_TIME"
          done
        env:
        # The node cidr mask size (IPv4) to allocate pod IPs
        - name: NODE_CIDR_MASK_SIZE
          value: "24"
        - name: SLEEP_TIME
          value: "30"
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
```

Ideally, I think that Talos Linux should probably do something natively for this somehow.

In the mean time, feel free to deploy the daemonset above with your Cilium native routing setup.

**Comment by stevefan1999-personal** [comment]
no stale

**Comment by alexandrem** [comment]
This shouldn't break any communication flows, including with nodes external to the cluster.

What is your cilium config?

**Comment by bitfactory-henno-schooljan** [comment]
Update: things started working once I disabled eBPF masquerading/host routing, apparently that is conflicting with this. @absolutejam you tried that as well?

**Comment by alexandrem** [comment]
@bitfactory-henno-schooljan  Yes, I remember there was a configuration required in Cilium for this to work, most likely related to eBPF masquerading. I just realized I forgot to mention that earlier in the thread.

**Comment by bitfactory-henno-schooljan** [comment]
@alexandrem Looks like eBPF masquerading actually still works, but at least with the Cilium with the Helm chart it would have the side effect of enabling eBPF host routing as well, so I had to explicitly disable it by enabling the `bpf.hostLegacyRouting` Helm value like this:
```
bpf:
  masquerade: true
  hostLegacyRouting: true
```
I guess otherwise the traffic never hits the networking stack where the kubespan/wireguard intrerfaces live, which makes sense. Props for that DaemonSet by the way, that works perfectly!

**Comment by stevefan1999-personal** [comment]
> [@alexandrem](https://github.com/alexandrem) Looks like eBPF masquerading actually still works, but at least with the Cilium with the Helm chart it would have the side effect of enabling eBPF host routing as well, so I had to explicitly disable it by enabling the `bpf.hostLegacyRouting` Helm value like this:
> 
> ```
> bpf:
>   masquerade: true
>   hostLegacyRouting: true
> ```
> 
> I guess otherwise the traffic never hits the networking stack where the kubespan/wireguard intrerfaces live, which makes sense. Props for that DaemonSet by the way, that works perfectly!

Sadly this will not work with egress gateway

**Comment by choopm** [comment]
I created a working example: <https://github.com/choopm/example-talos-kubespan-cilium-native-routing>

When using the DaemonSet approach of @alexandrem, most things will work, but you will encounter issues when trying to use some cilium features such as Node IPAM LB.

The underlying cause is that few packets sent by cilium from it's cilium_host interface might end up skipping the KubeSpan interception and end up being natively-routed to the host network. I think this was observed by @absolutejam aswell.

In order to fix this:
**Provide a static route to native-routing-cidr to force pod CIDR to kubespan:**
```diff
@@ -50,6 +52,12 @@ cluster:
                     sleep "$SLEEP_TIME"
                   }
 
+                  # Add a static route to NATIVE_ROUTING_CIDR via kubespan
+                  ip route add "${NATIVE_ROUTING_CIDR}" dev kubespan || true
+
+                  echo "Configured a static route for ${NATIVE_ROUTING_CIDR} to kubespan"
+                  ip route show dev kubespan
+
                   echo "Watching cilium_host IP addresses..."
 
                   while :; do
@@ -81,6 +89,9 @@ cluster:
                 # The node cidr mask size (IPv4) to allocate pod IPs
                 - name: NODE_CIDR_MASK_SIZE
                   value: "24"
+                # a superset of node cidr to create a static route for kubespan
+                - name: NATIVE_ROUTING_CIDR
+                  value: "10.244.0.0/16"
                 - name: SLEEP_TIME
                   value: "30"
                 securityContext:
```

I have tested this with Node IPAM LB which is now working properly.
Sorry for the repost, but I want to make sure all people in this thread get notified on the corrected version.

**Comment by choopm** [comment]
somehow related: #12386 and #8364

**Comment by stevefan1999-personal** [comment]
@choopm Well, given that Talos have their netbird extension out, while I would suggest using that as a workaround (given I acutally tested running k0s over netbird with cilium and it works, so I guess the same with Talos too), but I wouldn't mind trying

**Comment by Preisschild** [comment]
Cool, I will test if this works

**Comment by Preisschild** [comment]
fyi with 

```yaml
bpf:
  masquerade: true
  hostLegacyRouting: true
``` 

and `advertiseKubernetesNetworks: true` this should work OOB now on main. Documentation still needs to be edited in [this section](https://github.com/siderolabs/docs/blob/main/public/talos/v1.13/networking/kubespan.mdx#configuration) but then this issue can be closed I think
