### ISSUE TITLE
Request updating "Storage" / "Local Storage" / "Replicated Local Storage" content in "Documentation"

### ISSUE THREAD

**Issue by soulwhisper** [siderolabs/talos#9062]
- OpenEBS Jiva is now deprecated
- new OpenEBS Storage contains both Local Storage ( for talos, it is Local PV Hostpath) and Replicated Storage ( Mayastor only )
- Prep of OpenEBS Storage like below
```yaml
    machine:
      sysctls:
        vm.nr_hugepages: "1024"
      nodeLabels:
        openebs.io/engine: mayastor
      kubelet:
        extraMounts:
          - destination: /var/local/openebs
            type: bind
            source: /var/local/openebs
            options:
              - rbind
              - rshared
              - rw
```
- Installation of OpenEBS storage is simplified, like below
```shell
helm repo add openebs https://openebs.github.io/openebs
helm repo update

helm install openebs \
     --create-namespace \
     --namespace openebs \
     --set engines.local.lvm.enabled=false \
     --set engines.local.zfs.enabled=false \
     --set mayastor.etcd.clusterDomain="cluster.domain.here" \
     openebs/openebs
```
- other details about how to use new OpenEBS Storage, please check new [doc](https://openebs.io/docs/)
