### ISSUE TITLE
FR: Ability to specify one wants to use DHCPv6 AND slaac at the same time

### ISSUE THREAD

**Issue by samip5** [siderolabs/talos#9076]
### Description

I want to be able to tell Talos to get DHCPv6 (/128 address) and as advertised by router advertisement, slaac one too when RA is set to Assisted (M+O+A flags).

Currently setting:
```
networkInterfaces:
  - interface: bond0
    bond:
      mode: active-backup
      interfaces:
        - enp0s31f6
    dhcp: true
    dhcpOptions:
      routeMetric: 4000
      ipv4: true
      ipv6: true
```

Results in DHCPv4 and DHCPv6 only, when I wanted SLAAC and those.
