### ISSUE TITLE
Kube-scheduler Error : extra arg "config" is not allowed

### ISSUE THREAD

**Issue by HOUARIMouhssine** [siderolabs/talos#9091]
## Bug Report
Kube-scheduler Error : extra arg "config" is not allowed after migrating talos from 1.5.6 to 1.6.8

### Description

When trying to upgrade Talos on virtual machine from v1.5.6 to v1.6.8 , kube-scheduler pod is not being created.

After reading the documentation, we can clearly view that there is a new feature called .config under .scheduler but we were not able to set it there 

We are trying to modify the configuration of kube-scheduler using a yaml file already created in previous section ( in files section).

Can you give us the correct way to add our config file inside the scheduler pod in the version 1.6.8
### Logs

`[talos] controller failed {"component": "controller-runtime", "controller": "k8s.ControlPlaneStaticPodController", "error": "error updating static pod for      \"SchedulerConfigs.kubernetes.talos.dev\": extra arg \"config\" is not allowed"} `

### Environment
Virtualmachine on VMware
- Talos version:  v1.6.8
- Kubernetes version: Client Version: v1.22.7
                                  Server Version: v1.27.12
- Platform: Vmware

**Comment by michelaldaher** [comment]
Having the same issue please help

**Comment by smira** [comment]
Talos supports now a  [native way](https://www.talos.dev/v1.7/reference/configuration/v1alpha1/config/#Config.cluster.scheduler)  to submit `kube-scheduler` configuration.

The migration story could have been easier, but that will be hard to fix for 1.6, as it's an old release.

**Comment by smira** [comment]
to make it clear - you don't need `.machine.files` anymore.

**Comment by HOUARIMouhssine** [comment]
Thank you for your respond , How to do that ? can you provide us an example to set up kube-scheduler config ??

**Comment by smira** [comment]
something like that (as a Talos machine config patch):

```yaml
cluster:
  scheduler:
    config:
      apiVersion: kubescheduler.config.k8s.io/v1
      kind: KubeSchedulerConfiguration
      profiles:
        - plugins:
            score:
              disabled:
              - name: PodTopologySpread
              enabled:
              - name: MyCustomPluginA
                weight: 2
              - name: MyCustomPluginB
                weight: 1
```

of course the config should be yours
