### ISSUE TITLE
NVIDIA GPU OSS or proprietary driver install not working on KVM guest

### ISSUE THREAD

**Issue by Joker9944** [siderolabs/talos#9149]
### Description

I'm trying to setup my homelab cluster which is a TrueNAS Scale Server plus some other systems. I have a GTX 1660 S which is installed in the TrueNAS Server where i configured for PCI passthrough. Now I'm trying to install the nvidia drivers for node running on said server. I'm fairly confident the passthrough is working correctly since I can see two VGA PCI devices in dmesg, one as display device, the other one the GPU.

```
grep -r "vga" dmesg.log 
kern:    info: [2024-08-11T12:19:05.867315943Z]: pci 0000:00:02.0: vgaarb: setting as boot VGA device
kern:    info: [2024-08-11T12:19:05.868057943Z]: pci 0000:00:02.0: vgaarb: bridge control possible
kern:    info: [2024-08-11T12:19:05.868802943Z]: pci 0000:00:02.0: vgaarb: VGA device added: decodes=io+mem,owns=io+mem,locks=none
kern:    info: [2024-08-11T12:19:05.869954943Z]: pci 0000:00:07.0: vgaarb: bridge control possible
kern:    info: [2024-08-11T12:19:05.870734943Z]: pci 0000:00:07.0: vgaarb: VGA device added: decodes=io+mem,owns=io+mem,locks=none
kern:    info: [2024-08-11T12:19:05.871260943Z]: vgaarb: loaded
```

After the update the node is stuck in booting displaying `user: warning: [2024-08-11T12:21:17.281882943Z]: [talos] task startAllServices (1/1): service "ext-nvidia-persistenced" to be "up"` forever.

Config excerpt for node. Image generated with the following extensions:
- iscsi-tools
- qemu-guest-agent
- nonfree-kmod-nvidia
- nvidia-container-toolkit

```
machine:
  type: worker
  kubelet:
    image: ghcr.io/siderolabs/kubelet:v1.30.2
    defaultRuntimeSeccompProfileEnabled: true
    disableManifestsDirectory: true
  install:
    disk: /dev/vda
    image: factory.talos.dev/installer/dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586:v1.7.6
    wipe: false
  sysctls:
    net.core.bpf_jit_harden: "1"
  features:
    rbac: true
    stableHostname: true
    apidCheckExtKeyUsage: true
    diskQuotaSupport: true
    kubePrism:
      enabled: true
      port: 7445
    hostDNS:
      enabled: true
  kernel:
    modules:
      - name: nvidia
      - name: nvidia_uvm
      - name: nvidia_drm
      - name: nvidia_modeset
```

### Logs

service-logs/ext-nvidia-persistenced.state
```
ID       ext-nvidia-persistenced
STATE    Waiting
HEALTH   ?
EVENTS   [Waiting]: Waiting for file "/sys/bus/pci/drivers/nvidia" to exist (2m12s ago)
         [Waiting]: Waiting for service "cri" to be "up", file "/sys/bus/pci/drivers/nvidia" to exist (2m13s ago)
         [Waiting]: Waiting for service "cri" to be registered, file "/sys/bus/pci/drivers/nvidia" to exist (2m15s ago)
         [Waiting]: Waiting for service "containerd" to be "up", service "cri" to be registered, file "/sys/bus/pci/drivers/nvidia" to exist (2m19s ago)
         [Waiting]: Waiting for service "containerd" to be "up", service "cri" to be registered, service "udevd" to be "up", file "/sys/bus/pci/drivers/nvidia" to exist (2m21s ago)
         [Waiting]: Waiting for service "containerd" to be "up", service "cri" to be "up", service "udevd" to be "up", file "/sys/bus/pci/drivers/nvidia" to exist (2m22s ago)
         [Starting]: Starting service (2m22s ago)
```

`talosctl read /proc/modules`
```
virtio_balloon 32768 - - Live 0xffffffffc0224000
virtio_pci 28672 - - Live 0xffffffffc0214000
virtio_pci_legacy_dev 12288 - - Live 0xffffffffc020b000
virtio_pci_modern_dev 16384 - - Live 0xffffffffc0201000
```

### Environment

- Talos version: v1.7.6
- Kubernetes version: v1.30.2
- Platform: metal as KVM guest (Host is TrueNAS Scale)
