### ISSUE TITLE
`talosctl time` doesnt work with PTP devices

### ISSUE THREAD

**Issue by Preisschild** [siderolabs/talos#9197]
### Description
When you have a PTP device (such as `/dev/ptp0`) configured as your time server

```
time:
  servers:
    - /dev/ptp0
```

and then execute `talosctl time -n <node>` 

it fails with 

```
rpc error: code = Unknown desc = error querying NTP server "/dev/ptp0": lookup /dev/ptp0: no such host
```

### Logs

apid:

```
<node>: 2024/08/19 06:51:45.251213 log.go:94: Unknown [/time.TimeService/Time] 1.039643ms stream rpc error: code = Unknown desc = error querying NTP server "/dev/ptp0": lookup /dev/ptp0: no such host (:authority=<node>:50000;content-type=application/grpc;grpc-accept-encoding=gzip,gzip;proxyfrom=<endpoint>:50000;runtime=Talos;talos-role=os:admin;user-agent=grpc-go/1.63.2)
```

(node and endpoint replaced with placeholders)

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`] `1.7.6` (both client and server)
- Platform: `hcloud`

**Comment by smira** [comment]
Why would you need this command with `/dev/ptp0` ?

**Comment by smira** [comment]
```yaml
$ talosctl -n 172.20.0.2 get timestatus -o yaml
node: 172.20.0.2
metadata:
    namespace: runtime
    type: TimeStatuses.v1alpha1.talos.dev
    id: node
    version: 2
    owner: time.SyncController
    phase: running
    created: 2024-08-19T10:48:03Z
    updated: 2024-08-19T10:48:06Z
spec:
    synced: true
    epoch: 0
    syncDisabled: false
```
