### ISSUE TITLE
Talos uses wrong subnet for vip | Bare Metal

### ISSUE THREAD

**Issue by Syntax3rror404** [siderolabs/talos#9209]
## Bug Report
Talos assigns a wrong subnet to vip which cannot be reached from the host subnet when dhcp=false
But the subnet is declared in the network configuration.

### Description
This is the relevant network part from the config:

```
network:
    hostname: boss-m1
    nameservers:
        - 192.168.20.1
    interfaces:
        - interface: enp1s0 # The interface name.
          addresses:
              - 192.168.20.141/24
          routes:
              - network: 0.0.0.0/0
                gateway: 192.168.20.1
          dhcp: false
          vip:
              ip: 192.168.20.40
```

Talos assigns the wrong subnet from 24 to 32:
IP           192.168.20.141/24, 192.168.20.40/32
GW           192.168.20.1, fe80::de15:c8ff:fef9:83eb
DNS          192.168.20.1

### Logs
` user: warning: [2024-08-21T21:58:24.473116052Z]: [talos] kubernetes endpoint watch error {"component": "controller-runtime", "controller": "k8s.EndpointController", "error": "failed to list *v1.Endpoints: Get \"https://192.168.20.40/  api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&limit=500&resourceVersion=0\": dial tcp 192.168.20.40:443: connect: connection refused"} `

### Environment

- Talos version: 1.7.6
- Kubernetes version: 1.30.2
- Platform: x64_64
