### ISSUE TITLE
Bare Metal extremly long booting time on Ryzen system

### ISSUE THREAD

**Issue by Syntax3rror404** [siderolabs/talos#9210]
## Bug Report
Extremly long booting time on a 6 systems with the following hardware:

CPU: Ryzen 5700U
MEM: 64GB 3200MHz
NIC: 2.5 gig/s
DISK1: NVME 500GB (SYSTEM)
DISK2: NVME 2TB (DATA)

### Description
Booting talos on the mentioned system takes minutes instead of seconds. Windows, other linux distros etc booting in seconds.
I also tryed without secure boot, but this doesn't change anything.

A full `talosctl reboot` command with a clean install of talos and only a cni on it takes 4 minutes to reconnect and 6 minutes until it exits with healty state. 

### Logs
```
EFI stub: Loaded initrd from LINUX_EFI_INITRD_MEDIA_GUID device path
EFI stub: Measured initrd data into PCR 9
EFI stub: UEFI Secure Boot is enabled
```

(5 Minutes nothing)

Then it slowly boots the dashboard etc ... 

### Environment
System extensions: 
```
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/amdgpu-firmware
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
```

- Talos version: 1.7.6
- Kubernetes version: 1.30.2
- Platform: x86_64
