### ISSUE TITLE
FR: Create Symlink 

### ISSUE THREAD

**Issue by QJoly** [siderolabs/talos#9211]
## Feature Request

Create symlinks in the node configuration.

e.g : 

```yaml
machine:
    symlink:
        - path: '/dev/sdb1'
          dest: '/opt/disks/vol1'
```

### Description

I have a rather specific use case in which I use [local-static-provisioner](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner) to create Block volumes on additional disks. To do this, I need to create a symlink from an additional disk to a directory that will be mapped to the Kubelet (e.g. `ln -s /dev/sdb /opt/disks/sdb`) and used by local-static-provisioner.

I noticed that it wasn't possible to create this symlink from Talos configuration. 

Since @smira works on volume management (#8367), it may have something to do with this epic.

thank you to the Sidero team for your incredible work
