### ISSUE TITLE
Provide a way to delete keys and sequence elements during config strategic merge

### ISSUE THREAD

**Issue by DmitriyMV** [siderolabs/talos#9229]
Given:

```yaml
cluster:
  apiServer:
    auditPolicy:
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
  controlPlane:
    endpoint: https://localhost:6443
```

This:

```yaml
cluster:
  apiServer:
    auditPolicy:
      rules:
        - $patch: delete
          level: Metadata
```

Should work and result in
```yaml
cluster:
  apiServer:
    auditPolicy:
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules: []
  controlPlane:
    endpoint: https://localhost:6443
```
