### ISSUE TITLE
Tailscale Kubernetes operator - is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: modprobe: can't change directory to '/lib/modules': No such file or directory

### ISSUE THREAD

**Issue by phiilu** [siderolabs/talos#9322]
On my test cluster (running on Proxmox) I started testing `1.8.0-beta.0` and noticed that the Tailscale Kubernetes Operator run into a timeout and than the pod restarts.

## Bug Report
Tailscale Kubernetes operator restarts after timeout on `Talos 1.8.0-beta.0`, but worked with `1.7.6`. 
Maybe similar related to https://github.com/siderolabs/talos/issues/9309

### Description
It seems like this is the issue, but I am not sure what exactly changed between `1.8.0` and `1.7.6` or how I could fix this. I am not using the Tailscale Extension, only the [Kubernetes Operator](https://tailscale.com/kb/1236/kubernetes-operator).

```
tailscale 2024/09/13 19:51:19 is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: modprobe: can't change directory to '/lib/modules': No such file or directory                                                 │
```

### Logs

```
| sysctler net.ipv4.ip_forward = 1                                                                                                                                                          │
│ sysctler net.ipv6.conf.all.forwarding = 0                                                                                                                                                 │
│ sysctler net.ipv6.conf.all.forwarding = 1                                                                                                                                                 │
│ tailscale boot: 2024/09/13 20:00:51 skipping file "..data" in tailscaled config directory "/etc/tsconfig": input does not match format                                                    │
│ tailscale boot: 2024/09/13 20:00:51 skipping file "_current-profile" in tailscaled config directory "/etc/tsconfig": input does not match format                                          │
│ tailscale boot: 2024/09/13 20:00:51 skipping file "_machinekey" in tailscaled config directory "/etc/tsconfig": input does not match format                                               │
│ tailscale boot: 2024/09/13 20:00:51 skipping file "_profiles" in tailscaled config directory "/etc/tsconfig": input does not match format                                                 │
│ tailscale boot: 2024/09/13 20:00:51 skipping file "device_fqdn" in tailscaled config directory "/etc/tsconfig": input does not match format                                               │
│ tailscale boot: 2024/09/13 20:00:51 skipping file "device_id" in tailscaled config directory "/etc/tsconfig": input does not match format                                                 │
│ tailscale boot: 2024/09/13 20:00:51 skipping file "device_ips" in tailscaled config directory "/etc/tsconfig": input does not match format                                                │
│ tailscale boot: 2024/09/13 20:00:51 skipping file "profile-3a0d" in tailscaled config directory "/etc/tsconfig": input does not match format                                              │
│ tailscale boot: 2024/09/13 20:00:51 Using tailscaled config file '_' for capability version 'h'                                                                                           │
│ tailscale boot: 2024/09/13 20:00:51 Starting tailscaled                                                                                                                                   │
│ tailscale boot: 2024/09/13 20:00:51 Waiting for tailscaled socket                                                                                                                         │
│ tailscale 2024/09/13 20:00:51 logtail started                                                                                                                                             │
│ tailscale 2024/09/13 20:00:51 Program starting: v1.72.1-tf4a95663c, Go 1.22.5: []string{"tailscaled", "--socket=/tmp/tailscaled.sock", "--state=kube:ts-ingress-nginx-controller-sprbw-0" │
│ tailscale 2024/09/13 20:00:51 LogID: 7cf1c32b65cc6b1b80aed64d374870ad3b1f15e9aa3bd52df8b04c0bf31daf02                                                                                     │
│ tailscale 2024/09/13 20:00:51 logpolicy: using system state directory "/var/lib/tailscale"                                                                                                │
│ tailscale logpolicy.ConfigFromFile /var/lib/tailscale/tailscaled.log.conf: open /var/lib/tailscale/tailscaled.log.conf: no such file or directory                                         │
│ tailscale logpolicy.Config.Validate for /var/lib/tailscale/tailscaled.log.conf: config is nil                                                                                             │
│ tailscale 2024/09/13 20:00:51 dns: [rc=unknown ret=direct]                                                                                                                                │
│ tailscale 2024/09/13 20:00:51 dns: using "direct" mode                                                                                                                                    │
│ tailscale 2024/09/13 20:00:51 dns: using *dns.directManager                                                                                                                               │
│ tailscale 2024/09/13 20:00:51 wgengine.NewUserspaceEngine(tun "tailscale0") ...                                                                                                           │
│ tailscale 2024/09/13 20:00:51 Linux kernel version: 6.6.49-talos                                                                                                                          │
│ tailscale 2024/09/13 20:00:51 is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: modprobe: can't change directory to '/lib/modules': No such file or directory             │
│ tailscale 2024/09/13 20:00:51 wgengine.NewUserspaceEngine(tun "tailscale0") error: tstun.New("tailscale0"): operation not permitted                                                       │
│ tailscale 2024/09/13 20:00:51 flushing log.                                                                                                                                               │
│ tailscale 2024/09/13 20:00:51 logger closing down                                                                                                                                         │
│ tailscale 2024/09/13 20:00:51 getLocalBackend error: createEngine: tstun.New("tailscale0"): operation not permitted                                                                       │
│ tailscale boot: 2024/09/13 20:01:51 Timed out waiting for tailscaled socket 
````

### Environment

- Talos version: [`1.8.0-beta.0`]
- Kubernetes version: [`v1.31.0`]
- Platform: macOS

**Comment by smira** [comment]
See https://github.com/siderolabs/talos/issues/9309

**Comment by phiilu** [comment]
Thanks, I guess this could solve it. Unfortunately, I am using the Tailscale Kubernetes operator Helm chart, and it seems that it is not very configurable.

```bash
❯ helm show values tailscale/tailscale-operator
```

```yaml
# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause

# Operator oauth credentials. If set a Kubernetes Secret with the provided
# values will be created in the operator namespace. If unset a Secret named
# operator-oauth must be precreated.
oauth: {}
  # clientId: ""
  # clientSecret: ""

# installCRDs determines whether tailscale.com CRDs should be installed as part
# of chart installation. We do not use Helm's CRD installation mechanism as that
# does not allow for upgrading CRDs.
# https://helm.sh/docs/chart_best_practices/custom_resource_definitions/
installCRDs: true

operatorConfig:
  # ACL tag that operator will be tagged with. Operator must be made owner of
  # these tags
  # https://tailscale.com/kb/1236/kubernetes-operator/?q=operator#setting-up-the-kubernetes-operator
  # Multiple tags are defined as array items and passed to the operator as a comma-separated string
  defaultTags:
    - "tag:k8s-operator"

  image:
    # Repository defaults to DockerHub, but images are also synced to ghcr.io/tailscale/k8s-operator.
    repository: tailscale/k8s-operator
    # Digest will be prioritized over tag. If neither are set appVersion will be
    # used.
    tag: ""
    digest: ""
    pullPolicy: Always
  logging: "info" # info, debug, dev
  hostname: "tailscale-operator"
  nodeSelector:
    kubernetes.io/os: linux

  resources: {}

  podAnnotations: {}
  podLabels: {}

  tolerations: []

  affinity: {}

  podSecurityContext: {}

  securityContext: {}

  extraEnv: []
  # - name: EXTRA_VAR1
  #   value: "value1"
  # - name: EXTRA_VAR2
  #   value: "value2"


# proxyConfig contains configuraton that will be applied to any ingress/egress
# proxies created by the operator.
# https://tailscale.com/kb/1236/kubernetes-operator/#cluster-ingress
# https://tailscale.com/kb/1236/kubernetes-operator/#cluster-egress
# Note that this section contains only a few global configuration options and
# will not be updated with more configuration options in the future.
# If you need more configuration options, take a look at ProxyClass:
# https://tailscale.com/kb/1236/kubernetes-operator#cluster-resource-customization-using-proxyclass-custom-resource
proxyConfig:
  image:
    # Repository defaults to DockerHub, but images are also synced to ghcr.io/tailscale/tailscale.
    repository: tailscale/tailscale
    # Digest will be prioritized over tag. If neither are set appVersion will be
    # used.
    tag: ""
    digest: ""
  # ACL tag that operator will tag proxies with. Operator must be made owner of
  # these tags
  # https://tailscale.com/kb/1236/kubernetes-operator/?q=operator#setting-up-the-kubernetes-operator
  # Multiple tags can be passed as a comma-separated string i.e 'tag:k8s-proxies,tag:prod'.
  # Note that if you pass multiple tags to this field via `--set` flag to helm upgrade/install commands you must escape the comma (for example, "tag:k8s-proxies\,tag:prod"). See https://github.com/helm/helm/issues/1556
  defaultTags: "tag:k8s"
  firewallMode: auto

# apiServerProxyConfig allows to configure whether the operator should expose
# Kubernetes API server.
# https://tailscale.com/kb/1236/kubernetes-operator/#accessing-the-kubernetes-control-plane-using-an-api-server-proxy
apiServerProxyConfig:
  mode: "false" # "true", "false", "noauth"

imagePullSecrets: []
```

This is my config (using FluxCD) if anyone wants to dig deeper: 

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 30m
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 30m
  timeout: 5m
  chart:
    spec:
      chart: tailscale-operator
      version: ">=1.72.1 <1.73.0"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      interval: 5m
  values:
    operatorConfig:
      hostname: "my-tailscale-operator"
```

**Comment by smira** [comment]
The documentation is published https://www.talos.dev/v1.8/kubernetes-guides/configuration/device-plugins/

That should be enough to get you unblocked

**Comment by kenlasko** [comment]
@phiilu did you ever sort this out? I encountered this on Talos 1.8 and am also using the Tailscale operator. 

I figured out how to fix it via Tailscale proxyClass, if you're still looking for a solution.

**Comment by Santhin** [comment]
@kenlasko Can you share the solution with proxyclass?

**Comment by Santhin** [comment]
```
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: irish-eyes
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          limits:
            squat.ai/tun: "1"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
            add:
              - NET_ADMIN
```
+ https://www.talos.dev/v1.8/kubernetes-guides/configuration/device-plugins/#deploying-the-device-plugin

**Comment by kenlasko** [comment]
I created a proxyClass in my tailscale namespace. I'm using Smarter device manager, because it doesn't require host privileges, but this should work the same with squat.ai/tun:
```
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: tun-access
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          requests:
          limits:
            smarter-devices/net_tun: "1"
```

Then in my service, just add a label referencing the proxyClass:
```
labels:
  tailscale.com/proxy-class: "tun-access"
```
