### ISSUE TITLE
Can't seem to remove `node.kubernetes.io/exclude-from-external-load-balancers` from `machine.nodeLabels`

### ISSUE THREAD

**Issue by michaelbeaumont** [siderolabs/talos#9325]
## Bug Report

In spite of the following patch contents:

```
machine:
  nodeLabels:
    node.kubernetes.io/exclude-from-external-load-balancers:
      $patch: delete
```

apparently being cleanly applied, the node label is not removed from the config and from the Kubernetes node.

### Logs

None

### Environment

- Talos version: v1.8.0-beta.0, terraform provider 0.6.0-beta.0
- Kubernetes version: v1.31.0
- Platform: metal
