### ISSUE TITLE
Panic in block.VolumeManagerController

### ISSUE THREAD

**Issue by maxpain** [siderolabs/talos#9350]
## Bug Report
Hello. I'm trying to install Talos v1.8.0-beta.1 on the bare metal machine with 3 NVMe SSD disks using the following configuration, but getting a Panic error (see screenshot below). There is no such problem when installing v1.7.6 with the same configuration.
```yaml
version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.31.1
        extraConfig:
            maxPods: 512
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network: {}
    install:
        diskSelector:
            size: <= 1TB
        extraKernelArgs:
            - cpufreq.default_governor=performance
        image: ghcr.io/siderolabs/installer:v1.8.0-beta.1
        wipe: false
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
    nodeLabels:
        node.kubernetes.io/exclude-from-external-load-balancers: ""
```

### Logs
<img width="1017" alt="image" src="https://github.com/user-attachments/assets/5f479683-97c2-4778-8c7b-9fe8426234e1">

### Environment
- Talos version: v1.8.0-beta.1
- Platform: Bare metal
