### ISSUE TITLE
VolumeConfig missing documentation

### ISSUE THREAD

**Issue by Syntax3rror404** [siderolabs/talos#9370]
### Description
There is no documentation how to use the new VolumeConfig.

For example I can add this block to the machine config:

This can be created based on this doc: https://www.talos.dev/v1.8/reference/configuration/block/volumeconfig/
```
apiVersion: v1alpha1
kind: VolumeConfig
name: longhorn
provisioning:
  diskSelector:
    match: disk.model == "WD_BLACK SN770 2TB"
  maxSize: 1.8TiB
```

And now?

How to set the format of this volume?
How to mount this volume to the kubelet? 

### Environment

- Talos version: 1.8.0
- Kubernetes version: 1.30.5
- Platform: amd64
