### ISSUE TITLE
Talos in Hetzner on private network only issue

### ISSUE THREAD

**Issue by pashtet04** [siderolabs/talos#9389]
### Description

I am trying to launch Talos on Hetzner with private interfaces only. I am encountering issues with routing and network connectivity. Specifically:

1. Single Interface Configuration:
When I configure a node with only private interfaces, Talos does not initialize properly due to lack of internet access, even after setting up network configurations and routes manually.

2. NAT Configuration:
I tried setting up another machine with NAT. Despite redirecting everything through this setup, Talos fails to find the gateway and I receive a network unreachable error.

### Logs

```yaml
machine:
  certSANs:
    - balancer_ip
  network:
    interfaces:
      - interface: eth0
        dhcp: true
        mtu: 8765
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
  kubelet:
    nodeIP:
      validSubnets:
        - 10.0.0.0/24

cluster:
  etcd:
    advertisedSubnets:
      - 10.0.0.0/24
```

Command used to create servers:

```bash
hcloud server create --name "$CLUSTER_NAME-control-plane-$i" \
  --image ${IMAGE_ID} \
  --type cx22 --location fsn1 \
  --network $CLUSTER_NAME \
  --label "k8s=$CLUSTER_NAME,type=controlplane" \
  --without-ipv6 --without-ipv4 \
  --user-data-from-file "$CLUSTER_NAME/controlplane.yaml"
```

Despite successfully launching the control plane, worker nodes fail to connect. The control plane initializes correctly on the private network through NAT, but the worker node does not, even with identical configurations.

![telegram-cloud-photo-size-2-5447358351127211591-y](https://github.com/user-attachments/assets/21b7ab1a-45a9-4d84-8412-380bc53892dd)
![telegram-cloud-photo-size-2-5447358351127211396-y](https://github.com/user-attachments/assets/0e8680c2-1807-4e1e-892e-80b3e3f8973a)
![telegram-cloud-photo-size-2-5447358351127211394-y](https://github.com/user-attachments/assets/7c6eb812-72c6-4c27-9c50-fe7d85604b1a)
![telegram-cloud-photo-size-2-5447358351127211303-y](https://github.com/user-attachments/assets/3b72ec82-f924-423c-9f75-d1d137344848)
![telegram-cloud-photo-size-2-5447358351127211302-y](https://github.com/user-attachments/assets/f771af6f-7905-4fb5-a3c0-97315539b3e6)
![telegram-cloud-photo-size-2-5447358351127211288-y](https://github.com/user-attachments/assets/714f885b-b8a7-484f-a217-0657b2365f37)

### Environment

- Talos version: 1.7.x-1.8.0
- Kubernetes version: 1.30-1.31
- Platform: Hetzner

**Comment by smira** [comment]
Please search through issues here please, I think it was already discussed with some other problems on Hetzner.

It's not Talos, but rather general networking:

* your machine has IP 10.0.0.6/32, so it can't connect to anything (as /32 means just itself)
* this is how Hetzner loves to set up things, as they want you to go through the gateway even for other machines in the same network
* you need to tell networking stack that your gateway is behind the link, with something like:

```
machine:
  network:
    interfaces:
      - interface: eth0
        dhcp: true
        mtu: 8765
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
         - network: 10.0.0.1/32
```

This will tell the machine that 10.0.0.1 is behind that `eth0` link.

**Comment by pashtet04** [comment]
I managed to get the setup working for the control plane nodes only. Below is the configuration that works for creating control plane nodes:
![telegram-cloud-photo-size-2-5447358351127211396-y](https://github.com/user-attachments/assets/f6d77173-fda3-47dd-986a-041534d10db1)

```bash
  hcloud server create --name "$CLUSTER_NAME-control-plane-$i" \
      --image ${IMAGE_ID} \
      --type cx22 --location fsn1 \
      --network $CLUSTER_NAME \
      --label "k8s=CLUSTER_NAME,type=controlplane" \
      --without-ipv6 \
      --user-data-from-file "$CLUSTER_NAME/controlplane.yaml"
```

However, using a similar configuration for the worker nodes does not work. The worker nodes fail to initialize properly:
![telegram-cloud-photo-size-2-5447358351127211394-y](https://github.com/user-attachments/assets/d2332282-72b4-460e-b1a7-94aa8a0d2916)

```bash
hcloud server create --name $CLUSTER_NAME-worker-$i \
    --image ${IMAGE_ID} \
    --type cx32 --location fsn1 \
    --network $CLUSTER_NAME \
    --label "k8s=$CLUSTER_NAME,type=worker" \
    --without-ipv6 \
    --user-data-from-file "$CLUSTER_NAME/worker.yaml"
```

It seems that the following network configuration is being ignored during the creation of worker nodes, despite working correctly for control plane nodes:

```
machine:
  network:
    interfaces:
      - interface: eth0
        dhcp: true
        mtu: 8765
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
```

This discrepancy between control plane and worker node setup is the primary issue I am facing. Any guidance on how to ensure the network configuration is applied correctly to the worker nodes would be appreciated.

**Comment by smira** [comment]
You ignored what I posted, but also the error is in your screenshot - your machine config is not valid for workers.

**Comment by pashtet04** [comment]
This issue can be easily reproduced on Hetzner:

1. Generate the Talos configuration using the command:

```bash
talosctl gen config
```

2. Apply the following patch to the generated configuration:

```yaml

    machine:
      certSANs:
        - balancer_ip
      network:
        interfaces:
          - interface: eth0
            dhcp: true
            mtu: 8765
            routes:
              - network: 0.0.0.0/0
                gateway: 10.0.0.1
      kubelet:
        nodeIP:
          validSubnets:
            - 10.0.0.0/24

    cluster:
      etcd:
        advertisedSubnets:
          - 10.0.0.0/24
```

3. Create two VMs without public interfaces `--without-ipv4 --without-ipv6`:
- One using controlplane.yaml.
- The other using worker.yaml.

4. Observe that the worker node's network configuration is never applied. Specifically:
- For the worker node, no changes in machine.network are reflected, even after modifying routes and recreating the VM from scratch.
- In contrast, for the control plane node, network changes are correctly applied and visible after Talos boots.

This suggests that `machine.network` configurations are being ignored during the worker node creation process. Any guidance on how to ensure the network settings are correctly applied to the worker nodes would be greatly appreciated.

**Comment by smira** [comment]
Please see my previous replies, it has all the information.

> your machine config is not valid for workers.

Specifically, Talos warns you about `cluster.etcd` being not allowed on worker nodes.

![image](https://github.com/user-attachments/assets/fefd606c-cabd-4696-ab5b-8a1a90396547)

**Comment by pashtet04** [comment]
This is just an example. You can remove etcd for the worker node as it doesn’t affect the result.

**Comment by smira** [comment]
You should remove it, and once machine configuration will be valid, and you will supply proper routes as I posted above, things should work fine.

If there's a problem, please open an issue with the logs.

This issue is solved:

* invalid machine configuration for workers
* missing route to the default gateway.

**Comment by pashtet04** [comment]
Is this a proper and valid configuration for the worker node? 

```
version: v1alpha1
debug: false
persist: true
machine:
    type: worker
    token: hzcepc.zv8kuq7z0t05y5tk
    ca:
        crt: ""
        key: ""
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.31.1
        extraArgs:
            cloud-provider: external
        defaultRuntimeSeccompProfileEnabled: true
        nodeIP:
            validSubnets:
                - 10.0.16.0/20
        disableManifestsDirectory: true
    network:
        interfaces:
          - interface: eth0
            dhcp: true
            mtu: 8765
            routes:
              - network: 0.0.0.0/0
                gateway: 10.0.0.1
    install:
        disk: /dev/sda
        image: ghcr.io/siderolabs/installer:v1.8.0
        wipe: false
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
cluster:
    id: 
    secret: 
    controlPlane:
        endpoint: https://IP:6443
    clusterName: test
    network:
        cni:
            name: none
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: 
    ca:
        crt: ""
        key: ""
    proxy:
        disabled: true
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
    coreDNS:
        disabled: true
    externalCloudProvider:
        enabled: true
```

When creating a VM in Hetzner with `--without-ipv*` and attaching it to a private network, the network configuration never applies to the worker node. However, the same network configuration works fine when creating the control plane VM.

**Comment by pashtet04** [comment]
Why did you close the issue without attempting to reproduce it?
No one has demonstrated successfully launching Talos on Hetzner using only private interfaces.

**Comment by maxpain** [comment]
Hello.

1. You need to configure Talos Linux to send all traffic to the Hetzner Cloud router in your VPC network:
```yaml
machine:
  network:
        interfaces:
            - interface: eth0
              dhcp: true
              routes:
                  - network: 0.0.0.0/0
                    gateway: 10.0.0.1
                  - network: 10.0.0.1/32 # Link-scope route
```

2. Create a route in your Hetzner Cloud network to send all internet traffic to your NAT virtual machine (`10.0.0.2` for example)
![telegram-cloud-photo-size-2-5463149309492059822-y](https://github.com/user-attachments/assets/3dbff26c-749c-46a8-8567-4c9ed161c3ba)

So, this is the actual path:

Talos VM (`10.0.0.3`) -> Hetzner Cloud router (`10.0.0.1`) -> your NAT VM (`10.0.0.2`)
