### ISSUE TITLE
Unable to place EPHEMERAL volume on another disk

### ISSUE THREAD

**Issue by dabo-devconsole** [siderolabs/talos#9394]
### Description
I tried to install talos on an arm64 vps, placing the EPHEMERAL volume on a different disk than the system disk.
The system has two disk /dev/vda (256GB) + /dev/vdb (8GB).
The installation is placed on the smaller disk /dev/vdb and all system partitions (EFI,BIOS,BOOT,META,STATE) are placed and labeled correctly. I tried several VolumeConfig at installation time, e.g. this one

```
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
    diskSelector:
        match: disk.dev_path == '/dev/vda'
    grow: false
    maxSize: 40GiB
```
But unfortunately this has no effect and the system is stuck at installing stage.
### Logs
![Bildschirmfoto 2024-09-28 um 20 27 20](https://github.com/user-attachments/assets/ed9ece2f-63ff-4a41-81f2-f684db87a836)

### Environment

- Talos version: v1.8.0
- Kubernetes version: 1.30.5
- Platform: metal

**Comment by dabo-devconsole** [comment]
I think I found a working VolumeConfig, respectively a working diskSelector.
```
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
    diskSelector:
        match: disk.size > 50u * GiB && !system_disk
    grow: false
    minSize: 25GiB
    maxSize: 40GiB
```
Why does disk.dev_path alone not match?
