### ISSUE TITLE
Cannot install with secureboot and encryption?

### ISSUE THREAD

**Issue by uhthomas** [siderolabs/talos#9415]
### Description

`mapped device is still in use`?

![image](https://github.com/user-attachments/assets/d60a561a-50d7-44c9-b5b4-26b48dc01803)

```yaml
install:
    image: factory.talos.dev/installer-secureboot/63cccc87bd7433e412eb150d89eb047b78faddb1f8c7a666534c411185665a76:v1.8.0
    wipe: true

    diskSelector:
        wwid: eui.1234
...
systemDiskEncryption:
    ephemeral:
        provider: luks2
        keys:
            - slot: 0
                tpm: {}
            - slot: 1
                static:
                    passphrase: abc
    state:
        provider: luks2
        keys:
            - slot: 0
                tpm: {}
            - slot: 1
                static:
                    passphrase: abc
```

### Environment

- Talos version: 1.8.0
- Kubernetes version: N/A
- Platform: bare metal
