### ISSUE TITLE
NVIDIA GPU (OSS drivers) syntax error in nvidia-default-runtimeclass.yaml sample

### ISSUE THREAD

**Issue by jogotcha** [siderolabs/talos#9416]
There is a syntax error in nvidia-default-runtimeclass.yaml sample. 

```yaml
- op: add
  path: /machine/files
  value:
    - content: |
        [plugins]
          [plugins."plugins."io.containerd.cri.v1.runtime"]
            [plugins."io.containerd.cri.v1.runtime".containerd]
              default_runtime_name = "nvidia"        
      path: /etc/cri/conf.d/20-customization.part
      op: create
``` 

[plugins.**"plugins.**"io.containerd.cri.v1.runtime"] 
should be 
[plugins."io.containerd.cri.v1.runtime"]
