### ISSUE TITLE
Talos does not upgrade after applying a machineconfig with a different installer

### ISSUE THREAD

**Issue by spastorclovr** [siderolabs/talos#9438]
## Bug Report

When reading :point_right:  https://www.talos.dev/v1.8/talos-guides/configuration/system-extensions/#example-booting-from-an-iso , my understanding is that Talos should upgrade upon receiving a configuration with an installer pointing to something diffrent from the current version and reboot. 
This is not what I am witnessing. 

- I apply a new patch 

```
machine:
  install:
    image: factory.talos.dev/installer/e048aaf4461ff9f9576c9a42f760f2fef566559bd4933f322853ac291e46f238:v1.7.0
    wipe: true
```

I can see in the dashboard, that the patch is being applied 

```
 apply config request: mode auto(no_reboot)
```
and can confirm the config is there

```
talosctl --talosconfig talosconfig get machineconfig -o yaml -n 116.202.100.70|grep installer -B4 -A4
            disableManifestsDirectory: true
        network: {}
        install:
            disk: /dev/sda
            image: factory.talos.dev/installer/e048aaf4461ff9f9576c9a42f760f2fef566559bd4933f322853ac291e46f238:v1.7.0
            wipe: true
```

But no upgrade is done. Not even after reboot. And upgrade using the talosctl works well. 
Is it me not reading the documentation correctly, an issue in the documentation or a bug?

This is important for me to understand whether a reboot would happen in case we generate an new factory image in our CI using the Terraform module. 

Thx!

Client:
	Tag:         v1.7.7
	SHA:         68794084
	Built:
	Go version:  go1.22.7
	OS/Arch:     linux/amd64
Server:
	NODE:        116.202.100.70
	Tag:         v1.7.7
	SHA:         68794084
	Built:
	Go version:  go1.22.7
	OS/Arch:     linux/amd64
	Enabled:     RBAC
