### ISSUE TITLE
Talos `1.8.0` option `Reset Talos installation and return to maintenance mode` fails

### ISSUE THREAD

**Issue by eugene-marchanka** [siderolabs/talos#9448]
## Bug Report

When option `Reset Talos installation and return to maintenance mode` selected, Talos fails with error: `resource VolumeStatuses.block.talos.dev(runtime/EPHEMERAL@undefined) doesn't exist`

### Description

I am installing Talos using ISO boot and I am using following disk patches:
```
- op: add
  path: /machine/install/diskSelector
  value:
    size: < 900GB
- op: add
  path: /machine/systemDiskEncryption
  value:
    ephemeral:
      keys:
      - nodeID: {}
        slot: 0
      provider: luks2
    state:
      keys:
      - nodeID: {}
        slot: 0
      provider: luks2
```

I also tried to boot with parameter `talos.device.settle_time=2m` and got same error.

### Logs
[maintenance-mode-fails.txt](https://github.com/user-attachments/files/17262262/maintenance-mode-fails.txt)

### Environment

- Talos version: `1.8.0`
- Kubernetes version: [`1.26.1`]
- Platform: `baremetal`. Confirmed on Dell `r340/r740`
