### ISSUE TITLE
Error 'VolumeConfig' 'v1alpha1': not registered when performing Kubernetes upgrade

### ISSUE THREAD

**Issue by eshikhov** [siderolabs/talos#9469]
## Bug Report

failed upgrading kubelet: error updating node "X.X.X.X":  error patching node config: error fetching config resource: "VolumeConfig" "v1alpha1": not registered when updating Kubernetes

### Description

In a cluster, several worker nodes have a VolumeConfig section in the machine config
```
---
apiVersion: v1alpha1
kind:VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: disk.transport == 'nvme' && disk.dev_path == '/dev/nvme0n1'
  minSize: 200GB
  maxSize: 200GB
  grow: false
```
When performing a kubernetes upgrade with the command 
```
talosctl --nodes <controlplane node> upgrade-k8s --to 1.30.3 
``` 
an error occurs "failed upgrading kubelet: error updating node "X.X.X.X": error patching node config: error fetching config resource: "VolumeConfig" "v1alpha1": not registered when updating Kubernetes"

### Environment

- Talos version: v1.8.0
- Kubernetes version: v1.30.3
- Platform: baremetal
