### ISSUE TITLE
2x Lower NVMe SSD IOPS on Talos compared to Debian on the same hardware and Kernel version

### ISSUE THREAD

**Issue by maxpain** [siderolabs/talos#9531]
I did some benchmarks using `fio` in `direct` mode on the `/dev/nvme0n1` block device to compare I/O performance on both Talos Linux and Debian 12, got these results:

<img width="690" alt="image" src="https://github.com/user-attachments/assets/7c499406-d71b-49c0-9613-134a53ac34d9">
<img width="682" alt="image" src="https://github.com/user-attachments/assets/72fdf6ea-213f-44d5-81a4-f938d854fac9">

More charts and numbers is [here](https://docs.google.com/spreadsheets/d/1JICtVO-ubY1GgrYvxnDp4vxi8pc8dHo2N6d-DPoDiqw/edit?gid=688847757#gid=688847757).

**Commands I used:**

```bash
fio -name=randwrite_fsync -filename=/dev/nvme0n1 -output-format=json -ioengine=libaio -direct=1 -runtime=60 -randrepeat=0 -rw=randwrite -bs=4k -numjobs=1 -iodepth=1 -fsync=1
fio -name=randwrite_jobs4 -filename=/dev/nvme0n1 -output-format=json -ioengine=libaio -direct=1 -runtime=60 -randrepeat=0 -rw=randwrite -bs=4k -numjobs=4 -iodepth=128 -group_reporting
fio -name=randwrite -filename=/dev/nvme0n1 -output-format=json -ioengine=libaio -direct=1 -runtime=60 -randrepeat=0 -rw=randwrite -bs=4k -numjobs=1 -iodepth=128
fio -name=write -filename=/dev/nvme0n1 -output-format=json -ioengine=libaio -direct=1 -runtime=60 -randrepeat=0 -rw=write -bs=4M -numjobs=1 -iodepth=16
fio -name=randread_fsync -filename=/dev/nvme0n1 -output-format=json -ioengine=libaio -direct=1 -runtime=60 -randrepeat=0 -rw=randread -bs=4k -numjobs=1 -iodepth=1 -fsync=1
fio -name=randread_jobs4 -filename=/dev/nvme0n1 -output-format=json -ioengine=libaio -direct=1 -runtime=60 -randrepeat=0 -rw=randread -bs=4k -numjobs=4 -iodepth=128 -group_reporting
fio -name=randread -filename=/dev/nvme0n1 -output-format=json -ioengine=libaio -direct=1 -runtime=60 -randrepeat=0 -rw=randread -bs=4k -numjobs=1 -iodepth=128
fio -name=read -filename=/dev/nvme0n1 -output-format=json -ioengine=libaio -direct=1 -runtime=60 -randrepeat=0 -rw=read -bs=4M -numjobs=1 -iodepth=16
```

**Hardware:**
- Dell PowerEdge R6615 with latest BMC and BIOS
- 1x AMD EPYC GENOA 9454 (96 vCPU) with latest microcode
- 12x32GB (384G) DDR5 ECC RAM
- 1x U.2 PCIe NVMe SSD Samsung PM9A3 7.68TB with latest firmware

**Conditions:**
- Debian 12 and Talos Linux v1.8.1
- Linux Kernel 6.6.54 was the same on both OS.
- `amd_pstate=active` and `cpufreq.default_governor=performance` kernel args on both OS.
- The hardware and disk itself were the same
- The latest `fio` version was the same on both OS.
- `blkdiscard -f /dev/nvme0n1` was issued before each `fio` run.
- No additional processes were running on both OS
- Passmark benchmark shows the same CPU performance on both OS

I used a privileged pod on Talos Linux with following manifest:
```yaml
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: fio-test
  namespace: debug
spec:
  selector:
    matchLabels:
      app: fio-test
  template:
    metadata:
      labels:
        app: fio-test
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: fio
          image: maxpain/fio
          command:
            - sleep
            - infinity
          securityContext:
            privileged: true
```
