### ISSUE TITLE
Documentation for kernel performance tuning

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#9539]
Mention:

* CPU scaling governor
* mitigations=off
* iommu.passthrough/strict
* CPU sleep states

**Comment by maxpain** [comment]
I've benchmarked each kernel argument's performance impact on NVMe SSD I/O.

For AMD CPUs, we need to mention [spec_rstack_overflow](https://docs.kernel.org/admin-guide/hw-vuln/srso.html) in the docs, which, in my case, doubles the NVMe SSD I/O performance.

```yaml
machine:
  install:
    extraKernelArgs:
      - cpufreq.default_governor=performance
      - amd_pstate=active
      - iommu=off
      - spec_rstack_overflow=microcode # We need siderolabs/amd-ucode extension. Or just use mitigations=off, which is unsafe
```

![telegram-cloud-photo-size-2-5238108416344450253-y](https://github.com/user-attachments/assets/a9833492-8165-412a-b40b-d7d9eb5c40ae)
![telegram-cloud-photo-size-2-5238108416344450254-y](https://github.com/user-attachments/assets/774839c0-c3e2-45d3-99d2-4d09a8d92f14)
![telegram-cloud-photo-size-2-5238108416344450255-y](https://github.com/user-attachments/assets/ca37ef33-62f3-4246-9a1b-fe82e667cb32)

More info is [in this table](https://docs.google.com/spreadsheets/d/1vO-If2VNpzTzGtLGA8zcuFdE2xfIbQhO7WRl3ikIe-4/edit?usp=sharing).
