### ISSUE TITLE
Zero-address route incorrectly set for IPv6

### ISSUE THREAD

**Issue by trevex** [siderolabs/talos#9624]
### Description

When adding a static route to the interface eth0 for `::/0`, `talosctl get routes` unexpectedly reports an IPv4 route

The configuration added looks as follows:
```
machine:
    network:
        interfaces:
            - interface: eth0
              routes:
                - network: ::/0
                  gateway: ""
                  metric: 1000
```

`talosctl get routes` for the specified route returns:
```
fd01:cafe::5054:ff:fe10:9ad   network     RouteStatus   inet4///1000                                                            1                                                                                   eth0         1000
```

### Environment

- Talos version: v1.8.2
- Kubernetes version: v1.30.5
- Platform: Omni/KubeVirt
