### ISSUE TITLE
Error running phase 2 in install sequence

### ISSUE THREAD

**Issue by laurentpellegrino** [siderolabs/talos#9699]
## Bug Report

![Screenshot From 2024-11-11 20-01-27](https://github.com/user-attachments/assets/b0db541b-eefd-4a52-95e6-28383292faf0)

### Description

Apply configuration before bootstrap to the first control plane node running talos 1.8.2 iso image (with qemu guest agent extension, but the same happens with the raw 1.8.2 iso) with `talosctl --nodes "$IP" patch mc --patch "@$PATCH_FILE";` makes talos upgrade fails

The configuration specifies:

```
install:
  disk: /dev/vda 
  image: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515:v1.8.2 
  wipe: true
```

Note the same configuration with using talos _1.7.7_ instead of Talos _1.8.2_ everywhere works perfectly.

### Environment

- Talos version: 1.8.2 metal
- Platform: virtualized node on HostHatch
