### ISSUE TITLE
Changing kubelet address has no effect on which ip is being listened on for kubelet

### ISSUE THREAD

**Issue by aretecarpe** [siderolabs/talos#9710]
## Bug Report
Changing kubelet IP address from the default `0.0.0.0` to anything else will cause kubelet to still be checked/served on 127.0.0.1. This could be confusion on my end, but I'm unsure why its still being served on that ip addr. Even with the change to 127.0.0.1. I've also checked the csr and it is approved and signed.
### Description
I would expect that if I add address: 192.168.0.2 inside of extraConfig in kubelet it should change the kubelet IP.

The support logs show that the address has been changed to 192.168.0.2  kubeletspecs.kubernetes.talos.dev.yaml I guess it's just not reflected in the system as READY checks for APISERVER, CONTROLLER-MANAGER, and SCHEDULER are saying N/A in the dashboard as well via the command `talosctl get staticpods`. But it is showing ready and is working in the cluster via the command: `kubectl get pods -A`

### Logs
`"component": "controller-runtime", "controller": "k8s.KubeletStaticPodController", "error": "error refreshing pod status: error fetching pod status: Get \"https://127.0.0.1:10250/pods/?timeout=30s\": dial tcp 127.0.0.1:10250: connect: connection refused"`

Below is the command for: `talosctl containers --kubernetes`
```
192.168.0.2   k8s.io      kube-system/cilium-c8dcr                                                                              registry.k8s.io/pause:3.10                                                5054   SANDBOX_READY
192.168.0.2   k8s.io      └─ kube-system/cilium-c8dcr:apply-sysctl-overwrites:a9f99dca34bc                                      sha256:d781bfd0e519b886e895b2253f23aaa958fd0fddb2e6013cabbec79ee3cf775d   0      CONTAINER_EXITED
192.168.0.2   k8s.io      └─ kube-system/cilium-c8dcr:cilium-agent:cd16c6038860                                                 sha256:d781bfd0e519b886e895b2253f23aaa958fd0fddb2e6013cabbec79ee3cf775d   5808   CONTAINER_RUNNING
192.168.0.2   k8s.io      └─ kube-system/cilium-c8dcr:clean-cilium-state:7766b67c56e9                                           sha256:d781bfd0e519b886e895b2253f23aaa958fd0fddb2e6013cabbec79ee3cf775d   0      CONTAINER_EXITED
192.168.0.2   k8s.io      └─ kube-system/cilium-c8dcr:config:8a8ca8f2eb64                                                       sha256:d781bfd0e519b886e895b2253f23aaa958fd0fddb2e6013cabbec79ee3cf775d   0      CONTAINER_EXITED
192.168.0.2   k8s.io      └─ kube-system/cilium-c8dcr:install-cni-binaries:5ab28d7f3d98                                         sha256:d781bfd0e519b886e895b2253f23aaa958fd0fddb2e6013cabbec79ee3cf775d   0      CONTAINER_EXITED
192.168.0.2   k8s.io      └─ kube-system/cilium-c8dcr:mount-bpf-fs:f1c91418e957                                                 sha256:d781bfd0e519b886e895b2253f23aaa958fd0fddb2e6013cabbec79ee3cf775d   0      CONTAINER_EXITED
192.168.0.2   k8s.io      kube-system/cilium-envoy-kjqqg                                                                        registry.k8s.io/pause:3.10                                                5059   SANDBOX_READY
192.168.0.2   k8s.io      └─ kube-system/cilium-envoy-kjqqg:cilium-envoy:fd45eef82fe8                                           sha256:b38a7071cbb74b7dac0cc0d2538c3e57493271b35cd77ff3cc80e301a34ce51a   5917   CONTAINER_RUNNING
192.168.0.2   k8s.io      kube-system/cilium-operator-54ff457fd7-pm8fs                                                          registry.k8s.io/pause:3.10                                                5055   SANDBOX_READY
192.168.0.2   k8s.io      └─ kube-system/cilium-operator-54ff457fd7-pm8fs:cilium-operator:95ee08abec45                          sha256:4fc44954047e80fa5c20901cdce30e504d088a00ec6663af5911d1974692ca18   5915   CONTAINER_RUNNING
192.168.0.2   k8s.io      kube-system/coredns-68d75fd545-lq64r                                                                  registry.k8s.io/pause:3.10                                                7004   SANDBOX_READY
192.168.0.2   k8s.io      └─ kube-system/coredns-68d75fd545-lq64r:coredns:554305dbfb39                                          registry.k8s.io/coredns/coredns:v1.11.3                                   7053   CONTAINER_RUNNING
192.168.0.2   k8s.io      kube-system/coredns-68d75fd545-wtpxq                                                                  registry.k8s.io/pause:3.10                                                7003   SANDBOX_READY
192.168.0.2   k8s.io      └─ kube-system/coredns-68d75fd545-wtpxq:coredns:3870e44bbab0                                          registry.k8s.io/coredns/coredns:v1.11.3                                   7056   CONTAINER_RUNNING
192.168.0.2   k8s.io      kube-system/kube-apiserver-k8s-controlplane-01                                                    registry.k8s.io/pause:3.10                                                4439   SANDBOX_READY
192.168.0.2   k8s.io      └─ kube-system/kube-apiserver-k8s-controlplane-01:kube-apiserver:1e874dd597d4                     registry.k8s.io/kube-apiserver:v1.31.1                                    4545   CONTAINER_RUNNING
192.168.0.2   k8s.io      kube-system/kube-controller-manager-k8s-controlplane-01                                           registry.k8s.io/pause:3.10                                                4447   SANDBOX_READY
192.168.0.2   k8s.io      └─ kube-system/kube-controller-manager-k8s-controlplane-01:kube-controller-manager:6183252946c4   registry.k8s.io/kube-controller-manager:v1.31.1                           0      CONTAINER_EXITED
192.168.0.2   k8s.io      └─ kube-system/kube-controller-manager-k8s-controlplane-01:kube-controller-manager:6d31a816e15a   registry.k8s.io/kube-controller-manager:v1.31.1                           4874   CONTAINER_RUNNING
192.168.0.2   k8s.io      kube-system/kube-scheduler-k8s-controlplane-01                                                    registry.k8s.io/pause:3.10                                                4444   SANDBOX_READY
192.168.0.2   k8s.io      └─ kube-system/kube-scheduler-k8s-controlplane-01:kube-scheduler:8835f4416636                     registry.k8s.io/kube-scheduler:v1.31.1                                    4875   CONTAINER_RUNNING
192.168.0.2   k8s.io      └─ kube-system/kube-scheduler-k8s-controlplane-01:kube-scheduler:cd1831b59581                     registry.k8s.io/kube-scheduler:v1.31.1                                    0      CONTAINER_EXITED
```
```
metadata:
    namespace: k8s
    type: KubeletSpecs.kubernetes.talos.dev
    id: kubelet
    version: 1
    owner: k8s.KubeletSpecController
    phase: running
    created: 2024-11-13T04:05:35Z
    updated: 2024-11-13T04:05:35Z
spec:
    image: ghcr.io/siderolabs/kubelet:v1.31.1
    args:
        - --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubeconfig
        - --cert-dir=/var/lib/kubelet/pki
        - --config=/etc/kubernetes/kubelet.yaml
        - --hostname-override=k8s-controlplane-01
        - --kubeconfig=/etc/kubernetes/kubeconfig-kubelet
        - --node-ip=192.168.0.2
    extraMounts:
        - destination: /var/mnt/storage
          type: bind
          source: /var/mnt/storage
          options:
            - bind
            - rshared
            - rw
          uidmappings: []
          gidmappings: []
    expectedNodename: k8s-controlplane-01
    config:
        address: 192.168.0.2
        apiVersion: kubelet.config.k8s.io/v1beta1
        authentication:
            anonymous:
                enabled: false
            webhook:
                cacheTTL: 0s
                enabled: true
            x509:
                clientCAFile: /etc/kubernetes/pki/ca.crt
        authorization:
            mode: Webhook
            webhook:
                cacheAuthorizedTTL: 0s
                cacheUnauthorizedTTL: 0s
        cgroupRoot: /
        clusterDNS:
            - 10.96.0.10
        clusterDomain: cluster.local
        containerRuntimeEndpoint: unix:///run/containerd/containerd.sock
        cpuManagerReconcilePeriod: 0s
        evictionPressureTransitionPeriod: 0s
        failSwapOn: false
        featureGates:
            LocalStorageCapacityIsolationFSQuotaMonitoring: true
        fileCheckFrequency: 0s
        healthzBindAddress: 192.168.0.2
        httpCheckFrequency: 0s
        imageMaximumGCAge: 0s
        imageMinimumGCAge: 0s
        kind: KubeletConfiguration
        kubeletCgroups: /podruntime/kubelet
        logging:
            flushFrequency: 0
            format: json
            options:
                json:
                    infoBufferSize: "0"
                text:
                    infoBufferSize: "0"
            verbosity: 0
        memorySwap: {}
        nodeStatusReportFrequency: 0s
        nodeStatusUpdateFrequency: 0s
        oomScoreAdj: -450
        port: 10250
        protectKernelDefaults: true
        resolvConf: /system/resolved/resolv.conf
        rotateCertificates: true
        runtimeRequestTimeout: 0s
        seccompDefault: true
        serializeImagePulls: false
        shutdownGracePeriod: 30s
        shutdownGracePeriodCriticalPods: 10s
        staticPodURL: http://127.0.0.1:42563
        streamingConnectionIdleTimeout: 5m0s
        syncFrequency: 0s
        systemCgroups: /system
        systemReserved:
            cpu: 50m
            ephemeral-storage: 256Mi
            memory: 512Mi
            pid: "100"
        tlsMinVersion: VersionTLS13
        volumeStatsAggPeriod: 0s
```
below is the output of: `kubectl get pods -A`
```
NAMESPACE     NAME                                              READY   STATUS    RESTARTS      AGE
kube-system   cilium-c8dcr                                      1/1     Running   0             10m
kube-system   cilium-envoy-kjqqg                                1/1     Running   0             10m
kube-system   cilium-operator-54ff457fd7-mdpml                  0/1     Pending   0             10m
kube-system   cilium-operator-54ff457fd7-pm8fs                  1/1     Running   0             10m
kube-system   coredns-68d75fd545-lq64r                          1/1     Running   0             10m
kube-system   coredns-68d75fd545-wtpxq                          1/1     Running   0             10m
kube-system   kube-apiserver-k8s-controlplane-01            1/1     Running   0             9m22s
kube-system   kube-controller-manager-k8s-controlplane-01   1/1     Running   2 (11m ago)   9m28s
kube-system   kube-scheduler-k8s-controlplane-01            1/1     Running   2 (11m ago)   9m34s
```
below is the output (empty) of: `talosctl get staticpodstatus`
```
```

### Environment
- Talos version: 1.80
- Kubernetes version: 1.31
- Platform: bare metal
