### ISSUE TITLE
Talos 1.8.0+ initial boot fails in phase meta (6/12)

### ISSUE THREAD

**Issue by smauermann** [siderolabs/talos#9776]
## Bug Report
Hi team, I am failing to boot any Talos v1.8.0+ ISO from USB on an HP Elitedesk 800 g5 Mini (i5 9500T with vPro). The boot process fails in the meta phase at step 6/12.

I would really love to switch to Talos but I am at a loss right now on how to proceed. I would love any hints!

### Description
Up until and including v1.7.7 I can boot just fine and apply the machine configs to have a function Kubernetes cluster. However, if I try to boot any Talos version greater than v1.8.0, the boot fails. Please see a screenshot of the failed boot process below.

I have tried various other images to verify nothing is wrong with the node: Debian, Proxmox, CoreOS, and of course different Talos version.

Besides the different versions, I have played with different extensions namely intel-ucode, i915-ucode, mei, utils-linux including all permutations of the selected extensions.

Interestingly, I was able to creat a cluster with 1.7.7 and upgrade to 1.8.0. Another upgrade to 1.8.3 (no extensions) failed, though. The screen just went black after the reboot and never came up. I am trying this now again with different extensions.

EDIT: I was able to upgrade from 1.7.7 without any extensions to 1.8.3 including the following extensions:
```yaml
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/i915-ucode
            - siderolabs/intel-ucode
            - siderolabs/mei
            - siderolabs/util-linux-tools
```

### Logs
"Screenshot" of the boot failure:
![talos-boot-fail](https://github.com/user-attachments/assets/60ac6b21-f605-4bde-a55f-b39cd486b0ec)

### Environment

- Talos version: v1.8.3
- Kubernetes version: na
- Platform: metal on HP Elitedesk 800 g5 Mini (i5 9500T with vPro)
