### ISSUE TITLE
Cannot boot talos 1.8.3

### ISSUE THREAD

**Issue by b1r3k** [siderolabs/talos#9786]
### Description

I've had working Talos setup running on 1.7.5 then I've upgraded motherboard to Asus PRIME N100I-D D4-CSM and tried to install Talos 1.8.3 but machine went into boot loop.

I've cleaned installation drive to get rid on anything from previous setup and still the same. Then I've tried installing from custom ISO prepared via factory.dev:  factory.talos.dev/installer/67e8726af1f89d34f430b7c64b4c08882cbc639389067d2c54d2ba12f96b1576:v1.8.3 according to suggestions from https://github.com/siderolabs/talos/issues/9529 but it did not help.

I suspect it's something with installation drive but can't figure why ISO sees there something that should be wiped long ago. Please help I'm out of ideas.

### Logs

[talos.log](https://github.com/user-attachments/files/17874430/talos.log)

### Environment

- Talos version: 1.8.3
- Kubernetes version: N/A
- Platform: metal on Asus PRIME N100I-D D4-CSM

**Comment by b1r3k** [comment]
> Apparently missing firmware for the network adapter is the culprit:
> 
> ```json
> {"clock":12533367,"facility":"kern","msg":"r8169 0000:02:00.0: Direct firmware load for rtl_nic/rtl8168h-2.fw failed with error -2\n SUBSYSTEM=pci\n DEVICE=+pci:0000:02:00.0\n","priority":"warning","seq":1092,"talos-level":"warn","talos-time":"2024-11-22T17:51:33.594423171Z"}
> {"clock":12533779,"facility":"kern","msg":"r8169 0000:02:00.0: Unable to load firmware rtl_nic/rtl8168h-2.fw (-2)\n SUBSYSTEM=pci\n DEVICE=+pci:0000:02:00.0\n","priority":"err","seq":1093,"talos-level":"error","talos-time":"2024-11-22T17:51:33.594835171Z"}
> ```
> 
> Could you please try preparing an image including `siderolabs/realtek-firmware (20241110)` using the Image Factory and see whether it can find the network and start up?

I'll try of course to test with `siderolabs/realtek-firmware (20241110)` but I'd like to point out that network was working in this case. I know this because logs were delivered through TCP connection according to kernel parameters:

```json
{"clock":0,"facility":"kern","msg":"Command line: BOOT_IMAGE=/boot/vmlinuz talos.platform=metal console=tty0 talos.halt_if_installed=1 init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 printk.devkmsg=on ima_template=ima-ng ima_appraise=fix ima_hash=sha512 earlyprintk=vga nomodeset i915.enable_dc=1 i915.enable_psr=1 talos.logging.kernel=tcp://192.168.1.3:8000/\n","priority":"info","seq":2,"talos-level":"info","talos-time":"2024-11-22T17:51:21.061056171Z"}
```

But maybe there was some race condition between network initialization and talos initialization - I don't know internals enough to judge..

**Comment by b1r3k** [comment]
I've just tried the same setup as before but with `siderolabs/realtek-firmware (20241110)` and this time logs are not sent at all. From what I could see on the screen some startup phase failed and reboot happens

```yaml
customization:
    extraKernelArgs:
        - earlyprintk=vga
        - nomodeset
        - talos.logging.kernel=tcp://192.168.1.3:8000/
    systemExtensions:
        officialExtensions:
            - siderolabs/i915-ucode
            - siderolabs/intel-ucode
            - siderolabs/mei
            - siderolabs/realtek-firmware
```
