### ISSUE TITLE
How to delete data in`/var/mnt/storage`?

### ISSUE THREAD

**Issue by JanBenisek** [siderolabs/talos#9790]
### Description

I am not sure whether this is "a bug or a feature", or me being a noob. I added a disk on `/dev/sda` and mounted it
```yaml
  kubelet:
    extraMounts: 
      - destination: /var/mnt/storage
        type: bind
        source: /var/mnt/storage
        options:
          - bind
          - rshared
          - rw
  disks:
      - device: /dev/sda 
        partitions:
          - mountpoint: /var/mnt/storage 
```
- Everything works, I can create SC, PVCs and PV and I can see that stuff is saved there.
- However, after messing around and removing PVCs, somehow there is data left and **I do not know how to clean up that disk**.
- The disk was empty when I started.
- Perhaps it _may_ be that some of the PVCs did not have `delete` reclaim policy?
```shell
 k get pvc -A
# No resources found

k get pv -A
# No resources found

t mounts -n "192.168.178.39" | grep "/dev/sda1"
# 192.168.178.39   /dev/sda1        499.86     12.30      487.56          2.46%          /var/mnt/storage
```

### Environment

- Talos version: `v1.8.3`
- Kubernetes version: `v1.30.1`
- Platform: Bare metal
