### ISSUE TITLE
Issue loading proxmox cluster api provider cloudinit or cloudinit v2 config

### ISSUE THREAD

**Issue by rouke-broersma** [siderolabs/talos#9804]
### Description

When trying to provision a talos node using cluster-api infrastructure provider proxmox, talos panics during bootstrapping. When I manually create a cloudinit drive in proxmox with similar (host configuration) talos successfully starts.

### Logs

I could not yet gather the exact logs, this is as much as I was able to find.

![image](https://github.com/user-attachments/assets/91fd1ab8-87fb-459f-ad6c-547cfd5d13d6)

### Environment

- Talos version: 1.9.0-alpha.3 (1.8.3 - 1.9.0-alpha.2 have other nocloud issues which are fixed in alpha3, which is why I'm using the alpha)
- Kubernetes version: 1.30
- Platform: nocloud with proxmox clusterapi infrastructure provider and talos bootstrap + control-plane providers

### Additional details

I have secured the cloudinit drive contents as created by cluster-api and I have created a cloudinit drive manually from proxmox for comparison:

#### cluster-api

```yaml
# cat meta-data

instance-id: d674af67-ec6f-4e7f-952d-6bbbf828f091
local-hostname: proxmox-control-plane-machine-template-twnzv

# cat network-config 

network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      match:
        macaddress: BC:24:11:B4:EA:C2
      dhcp4: false
      dhcp6: false
      addresses:
        - 10.0.254.20/24
      routes:
        - to: 0.0.0.0/0
          metric: 100
          via: 10.0.254.1
      nameservers:
        addresses:
          - '10.0.254.1'

# cat user-data 

version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token:
    ca:
        crt:
        key:
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.30.3
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network:
        hostname: embla-talos-control-plane-wn2t2
        interfaces:
            - deviceSelector:
                busPath: 0*
              dhcp: true
              vip:
                ip: 10.0.254.254
    install:
        wipe: false
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
    nodeLabels:
        node.kubernetes.io/exclude-from-external-load-balancers: ""
cluster:
    id:
    secret:
    controlPlane:
        endpoint: https://10.0.254.254:6443
    clusterName: embla
    network:
        cni:
            name: none
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token:
    secretboxEncryptionSecret:
    ca:
        crt: 
        key: 
    aggregatorCA:
        crt: 
        key: 
    serviceAccount:
        key: 
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.30.3
        certSANs:
            - 10.0.254.254
        disablePodSecurityPolicy: true
        admissionControl:
            - name: PodSecurity
              configuration:
                apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                defaults:
                    audit: restricted
                    audit-version: latest
                    enforce: baseline
                    enforce-version: latest
                    warn: restricted
                    warn-version: latest
                exemptions:
                    namespaces:
                        - kube-system
                    runtimeClasses: []
                    usernames: []
                kind: PodSecurityConfiguration
        auditPolicy:
            apiVersion: audit.k8s.io/v1
            kind: Policy
            rules:
                - level: Metadata
    controllerManager:
        image: registry.k8s.io/kube-controller-manager:v1.30.3
        extraArgs:
            bind-address: 0.0.0.0
    proxy:
        disabled: true
        image: registry.k8s.io/kube-proxy:v1.30.3
    scheduler:
        image: registry.k8s.io/kube-scheduler:v1.30.3
        extraArgs:
            bind-address: 0.0.0.0
    discovery:
        enabled: false
        registries:
            kubernetes:
                disabled: true
            service: {}
    etcd:
        ca:
            crt: 
            key:
```

#### Proxmox

```yaml
# cat meta-data 
instance-id: 48982e1e6246f95a5262c1807783e6491d33b2c5

# cat network-config 

version: 1
config:
    - type: physical
      name: eth0
      mac_address: 'bc:24:11:e5:35:7e'
      subnets:
      - type: static
        address: '10.0.254.20'
        netmask: '255.255.255.0'
        gateway: '10.0.254.1'
    - type: nameserver
      address:
      - '10.0.254.1'
      search:
      - 'local'

# cat user-data 

#cloud-config
hostname: test
manage_etc_hosts: true
fqdn: test.local
chpasswd:
  expire: False
users:
  - default
```
