### ISSUE TITLE
nocloud network configuration can't find some interfaces by mac addresses

### ISSUE THREAD

**Issue by vills** [siderolabs/talos#9811]
## Bug Report

While booting "nocloud" variant it can't configure network interfaces correctly, cause nocloud can't see interfaces in list of network interfaces.

### Logs
Logs like this printed to console
```
[ 15.5761051 ] [talos] nocloud: no link with matching MAC address "a0:36:9f:e6:49:32" (available [ 18:66:da:?b:05:de 18:66:da:?b:05:df 18:66:da:7b:05:e0 18:66:da:?b:05:e1 ca:a3:46:0f:38:e4 ] ), defaulted to use name ext0 instead
```

Nocloud network config
```
version: 2
bonds:
  aggi:
    interfaces:
    - int0
    - int1
    addresses:
    - 10.26.98.92/29
    parameters:
      mode: 802.3ad
      lacp-rate: slow
      mii-monitor-interval: 100
      up-delay: 200
      down-delay: 200
      transmit-hash-policy: layer3+4
    routes:
    - to: 10.0.0.0/8
      via: 10.26.98.91
    - to: 192.168.0.0/16
      via: 10.26.98.91
    - to: 188.42.208.0/21
      via: 10.26.98.91
  agge:
    interfaces:
    - ext0
    - ext1
    addresses:
    - 188.42.48.188/29
    parameters:
      mode: 802.3ad
      lacp-rate: slow
      mii-monitor-interval: 100
      up-delay: 200
      down-delay: 200
      transmit-hash-policy: layer3+4
    gateway4: 188.42.48.187
ethernets:
  int0:
    match:
      macaddress: a0:36:9f:e6:49:30
  int1:
    match:
      macaddress: a0:36:9f:e5:06:d4
  ext0:
    match:
      macaddress: a0:36:9f:e6:49:32
  ext1:
    match:
      macaddress: a0:36:9f:e5:06:d6
```

### Environment

- Talos version: 1.8.3
- Kubernetes version: does not apply
- Platform: nocloud
