### ISSUE TITLE
docs: Network Device Selector states wrong driver name of "virtio"

### ISSUE THREAD

**Issue by Sudokamikaze** [siderolabs/talos#9853]
Documentation [example](https://www.talos.dev/v1.8/talos-guides/network/device-selector/#configuring-network-device-using-device-selector) highlights wrong driver name:
```
machine:
  ...
  network:
    interfaces:
      - deviceSelector:
          driver: virtio
          hardwareAddr: "00:00:*"
        address: 192.168.88.21
```

However driver name is `virtio_net`:
```
% talosctl get links enp1s0 -o yaml
node: 10.100.1.2
metadata:
    namespace: network
    type: LinkStatuses.net.talos.dev
    id: enp1s0
    version: 5
    owner: network.LinkStatusController
    phase: running
    created: 2024-11-30T21:13:43Z
    updated: 2024-11-30T21:13:43Z
spec:
    index: 8
    type: ether
    linkIndex: 0
    flags: UP,BROADCAST,RUNNING,MULTICAST,LOWER_UP
    hardwareAddr: "<OMITTED>"
    permanentAddr:"<OMITTED>"
    broadcastAddr: ff:ff:ff:ff:ff:ff
    mtu: 1342
    queueDisc: pfifo_fast
    operationalState: up
    kind: ""
    slaveKind: ""
    busPath: "0000:01:00.0"
    driver: virtio_net
    driverVersion: 1.0.0
    productID: "0x1041"
    vendorID: "0x1af4"
    product: Virtio 1.0 network device
    vendor: Red Hat, Inc.
    linkState: true
    speedMbit: 4294967295
    port: Other
    duplex: Unknown

```
