### ISSUE TITLE
integration test for image cache

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#9860]
## Proposal

Build an image cache out of `talosctl images default`. 

Add wrong registry mirrors (point them to some non-existent endpoint, e.g. 127.0.0.1:2005), and boot Talos from ISO with image cache, configuring also the partition on disk.

Config patch could be:

```
machine:
  features:
    imageCache:
      localEnabled: true
---
apiVersion: v1alpha1
kind: VolumeConfig
name: IMAGECACHE
provisioning:
    diskSelector:
        match: 'system_disk'
```
