### ISSUE TITLE
Allow passing disk ID path to `talosctl wipe disk`

### ISSUE THREAD

**Issue by onedr0p** [siderolabs/talos#9887]
## Feature Request

Hi 👋🏼 

Current it looks like only device names are supported with this command.

I would like to be able to have the ability to pass the entire disk ID path to the `wipe disk` command. This is useful because if you have a system with a ton of hdds or nvmes you have a predictable way to wipe the disks you want instead of looking up what sda or nvme0 points to.

### Description

```
talosctl wipe disk /dev/disk/by-id/nvme-Corsair_MP600_MICRO_A828B4420085JH
```

**Comment by onedr0p** [comment]
Not stale.

**Comment by smira** [comment]
You can already do that outside of Talos:

```yaml
# talosctl -n 172.20.0.2 get disks vda -o yaml 
spec:
    dev_path: /dev/vda
    ...
    symlinks:
        - /dev/disk/by-diskseq/10
        - /dev/disk/by-path/pci-0000:00:07.0
        - /dev/disk/by-path/virtio-pci-0000:00:07.0
```

So this is something scriptable outside of Talos, and doesn't have to be part of Talos.
