### ISSUE TITLE
iscsi image fails to mount iscsi volume: executable file not found in $PATH

### ISSUE THREAD

**Issue by posi74de** [siderolabs/talos#9893]
## Bug Report
I'm trying to mount a iscsi volume on a talos 1.8.2 cluster using image from:
https://factory.talos.dev/?arch=amd64&cmdline-set=true&extensions=-&extensions=siderolabs%2Fiscsi-tools&platform=metal&target=metal&version=1.7.6

Mount fails with:
`  Warning  FailedMount             4s (x5 over 12s)  kubelet                  MountVolume.WaitForAttach failed for volume "iscsi" : executable file not found in $PATH
`

Example pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: iscsi-test
spec:
  containers:
  - image: nicolaka/netshoot
    name: iscsi-test
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
    - mountPath: "/data/iscsi"
      name: iscsi
  volumes:
  - name: iscsi
    iscsi:
      targetPortal: 192.168.178.2:3260
      portals: ['192.168.178.2:3260']
      iqn: iqn.2000-01.com.synology:ds2.default-target.79e9f6cabd3
      lun: 0
      fsType: ext4
      readOnly: true
```

Maybe I'm doiing something wrong and in this the case the bug report might be a misleading/bad error message :-)

### Logs
iscsi binaries seem to be available (but not found? Error does not say what is missing from $PATH):
```
$ talosctl ls -r /usr/local | grep iscsi
192.168.178.106   etc/containers/iscsid.yaml
192.168.178.106   etc/iscsi
192.168.178.106   etc/iscsi/iscsid.conf
192.168.178.106   etc/logrotate.d/iscsiuiolog
192.168.178.106   etc/udev/rules.d/50-iscsi-firmware-login.rules
192.168.178.106   lib/containers/iscsid
192.168.178.106   lib/containers/iscsid/dev
192.168.178.106   lib/containers/iscsid/etc
192.168.178.106   lib/containers/iscsid/etc/hosts
192.168.178.106   lib/containers/iscsid/etc/iscsi
192.168.178.106   lib/containers/iscsid/etc/passwd
192.168.178.106   lib/containers/iscsid/etc/resolv.conf
192.168.178.106   lib/containers/iscsid/lib
192.168.178.106   lib/containers/iscsid/proc
192.168.178.106   lib/containers/iscsid/run
192.168.178.106   lib/containers/iscsid/sys
192.168.178.106   lib/containers/iscsid/usr
192.168.178.106   lib/containers/iscsid/usr/lib
192.168.178.106   lib/containers/iscsid/usr/local
192.168.178.106   lib/containers/iscsid/usr/local/lib
192.168.178.106   lib/containers/iscsid/usr/local/sbin
192.168.178.106   lib/containers/iscsid/var
192.168.178.106   lib/containers/iscsid/var/lib
192.168.178.106   lib/containers/iscsid/var/lib/iscsi
192.168.178.106   lib/libopeniscsiusr.so
192.168.178.106   lib/libopeniscsiusr.so.0
192.168.178.106   lib/libopeniscsiusr.so.0.2.0
192.168.178.106   lib/pkgconfig/libopeniscsiusr.pc
192.168.178.106   sbin/brcm_iscsiuio
192.168.178.106   sbin/iscsi-gen-initiatorname
192.168.178.106   sbin/iscsi-iname
192.168.178.106   sbin/iscsi_discovery
192.168.178.106   sbin/iscsi_fw_login
192.168.178.106   sbin/iscsi_offload
192.168.178.106   sbin/iscsiadm
192.168.178.106   sbin/iscsid
192.168.178.106   sbin/iscsid-wrapper
192.168.178.106   sbin/iscsistart
192.168.178.106   sbin/iscsiuio

```
### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
```
Client:
        Tag:         v1.8.2
        SHA:         88f861a0
        Built:       
        Go version:  go1.22.8
        OS/Arch:     linux/amd64
Server:
        NODE:        192.168.178.106
        Tag:         v1.8.2
        SHA:         88f861a0
        Built:       
        Go version:  go1.22.8
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```
- Kubernetes version: [`kubectl version`]
```
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.31.2
```
- Platform:
x86_64
