### ISSUE TITLE
Talos labels nodes as exclude-from-external-load-balancers despite allowSchedulingOnControlPlanes

### ISSUE THREAD

**Issue by TomyLobo** [siderolabs/talos#9960]
### Description

As @michaelbeaumont noted on #9325, Talos should not label nodes as `node.kubernetes.io/exclude-from-external-load-balancers`, if `cluster.allowSchedulingOnControlPlanes` is set to true.
Those nodes are valid targets for load balancers.

### Environment

- Talos version: 1.8.3
- Kubernetes version: v1.31.1

**Comment by smira** [comment]
This label is generated in the machine configuration provided (it's not dynamic), so you can remove that with a config patch:

```yaml
machine:
  nodeLabels:
    node.kubernetes.io/exclude-from-external-load-balancers:
      $patch: delete
```

```shell
talosctl gen config ... --config-patch-control-plane @label-remove.patch
```
