### ISSUE TITLE
Consider use lowercase when comparing MAC-addresses in nocloud

### ISSUE THREAD

**Issue by vills** [siderolabs/talos#9965]
When i accidentally specified mac-addresses in nocloud's network-config with uppercase letters, Talos can't find this interfaces, although it sees the correct mac-addresses of all interfaces in system. Looks like the problem in `if` matching uppercase with lowercase (generated by Talos itself) mac-addresses. I would like to propose convertations of mac-addresses from nocloud's network-config to lowercase before comparing it with system interfaces.

Logs like this appears:
```
user: warning: [2024-12-16T14:19:05.6467407512]: [talos] nocloud: no link with matching MAC address "A0:36:9F:77:51:92" (available [18:66:da:7a:fd:c2 18:66:da:7a:fd:c3 18:66:da:7a:fd:c4 18:66:da:7a:fd:c5 a0:36:9f:79:40:0c a0:36:9f:79:40:0e a0:36:9f:77:51:90 a0:36:9f:77:51:92]), defaulted to use name ext1 instead
```

### Environment

- Talos version: 1.8.4
- Platform: nocloud

nocloud network-config:
```
version: 2
bonds:
  aggi:
    interfaces:
    - int0
    - int1
    addresses:
    - a.a.a.a/bb
    parameters:
      mode: 802.3ad
      lacp-rate: slow
      mii-monitor-interval: 100
      up-delay: 200
      down-delay: 200
      transmit-hash-policy: layer3+4
    routes:
    - to: 10.0.0.0/8
      via: a.a.a.c
  agge:
    interfaces:
    - ext0
    - ext1
    addresses:
    - x.x.x.x/yy
    parameters:
      mode: 802.3ad
      lacp-rate: slow
      mii-monitor-interval: 100
      up-delay: 200
      down-delay: 200
      transmit-hash-policy: layer3+4
    gateway4: x.x.x.z
ethernets:
  int0:
    match:
      macaddress: A0:36:9F:79:40:0C
  int1:
    match:
      macaddress: A0:36:9F:77:51:90
  ext0:
    match:
      macaddress: A0:36:9F:79:40:0E
  ext1:
    match:
      macaddress: A0:36:9F:77:51:92
```
