### ISSUE TITLE
Raspberry PI does not boot with 1.9.0

### ISSUE THREAD

**Issue by nberlee** [siderolabs/talos#9981]
## Bug Report
A disk image from the factory with only the raspberry pi sbc selected does not boot.

So I made it using this imager:

This imager profile DOES boot:
```
arch: arm64
platform: metal
secureboot: false
version: v1.9.0
input:
  kernel:
    path: /usr/install/arm64/vmlinuz
  initramfs:
    path: /usr/install/arm64/initramfs.xz
  baseInstaller:
    imageRef: ghcr.io/siderolabs/installer:v1.9.0
  overlayInstaller:
    imageRef: ghcr.io/siderolabs/sbc-raspberrypi:v0.1.0-beta.2
overlay:
  name: rpi_generic
  image:
    imageRef: ghcr.io/siderolabs/sbc-raspberrypi:v0.1.0-beta.2
output:
  kind: image
  imageOptions:
    diskSize: 1306525696
    diskFormat: raw
  outFormat: .zst
  ```

with `ghcr.io/siderolabs/sbc-raspberrypi:v0.1.0` it does NOT boot. So i suspect it the [ raspberry pi firmware](https://github.com/siderolabs/sbc-raspberrypi/compare/v0.1.0-beta.2...v0.1.0).

Sorry I have no better error message as I seem to have misplaced the weird hdmi cable that the Pi4 has.

To be clear, this is when flashing a disk-image. For some reason, I updated to talos 1.9.0-beta.1 with the update image fine from the factory.

**Comment by smira** [comment]
I can try to debug this later this week (I have RPi and a serial cable as well).

**Comment by MikeCockrem** [comment]
I have the same issue with the CM4: attaching a HDMI cable I can see the 'rainbow screen' and it does not progress any further. Happy to assist with any testing.

**Comment by nberlee** [comment]
I think I know whats wrong, and I will push an untested PR. I am able to test it, however, u-boot does not crosscompile right now. 

The problem is in https://github.com/nberlee/sbc-raspberrypi/commit/15a683428278f8bf1b7c46110e6cb72d417ad1b8#diff-e03550ab3dd282a9be9b2dd3f1b3432f094bfdff9d9e4fa0efe5960b0c0272adL8

This changes from a source tarball to a release tarball. A release tarball does not contain dtbs files at all.

See dive 0.1.0:
```
├── artifacts
│   └── arm64
│       ├── firmware
│       │   └── boot
│       │       ├── LICENCE.broadcom
│       │       ├── bootcode.bin
│       │       ├── fixup.dat
│       │       ├── fixup4.dat
│       │       ├── fixup4cd.dat
│       │       ├── fixup4db.dat
│       │       ├── fixup4x.dat
│       │       ├── fixup_cd.dat
│       │       ├── fixup_db.dat
│       │       ├── fixup_x.dat
│       │       ├── start.elf
│       │       ├── start4.elf
│       │       ├── start4cd.elf
│       │       ├── start4db.elf
│       │       ├── start4x.elf
│       │       ├── start_cd.elf
│       │       ├── start_db.elf
│       │       └── start_x.elf
│       └── u-boot
│           └── rpi_generic
│               └── u-boot.bin
├── installers
│   └── rpi_generic
└── profiles
    └── rpi_generic.yaml
```

whereas working 0.1.0-beta.2:
```
├── artifacts
│   └── arm64
│       ├── firmware
│       │   └── boot
│       │       ├── COPYING.linux
│       │       ├── LICENCE.broadcom
│       │       ├── bcm2708-rpi-b-plus.dtb
│       │       ├── bcm2708-rpi-b-rev1.dtb
│       │       ├── bcm2708-rpi-b.dtb
│       │       ├── bcm2708-rpi-cm.dtb
│       │       ├── bcm2708-rpi-zero-w.dtb
│       │       ├── bcm2708-rpi-zero.dtb
│       │       ├── bcm2709-rpi-2-b.dtb
│       │       ├── bcm2709-rpi-cm2.dtb
│       │       ├── bcm2710-rpi-2-b.dtb
│       │       ├── bcm2710-rpi-3-b-plus.dtb
│       │       ├── bcm2710-rpi-3-b.dtb
│       │       ├── bcm2710-rpi-cm3.dtb
│       │       ├── bcm2710-rpi-zero-2-w.dtb
│       │       ├── bcm2710-rpi-zero-2.dtb
│       │       ├── bcm2711-rpi-4-b.dtb
│       │       ├── bcm2711-rpi-400.dtb
│       │       ├── bcm2711-rpi-cm4-io.dtb
│       │       ├── bcm2711-rpi-cm4.dtb
│       │       ├── bcm2711-rpi-cm4s.dtb
│       │       ├── bcm2712-rpi-5-b.dtb
│       │       ├── bcm2712-rpi-cm5-cm4io.dtb
│       │       ├── bcm2712-rpi-cm5-cm5io.dtb
│       │       ├── bcm2712-rpi-cm5l-cm4io.dtb
│       │       ├── bcm2712-rpi-cm5l-cm5io.dtb
│       │       ├── bcm2712d0-rpi-5-b.dtb
│       │       ├── bootcode.bin
│       │       ├── fixup.dat
│       │       ├── fixup4.dat
│       │       ├── fixup4cd.dat
│       │       ├── fixup4db.dat
│       │       ├── fixup4x.dat
│       │       ├── fixup_cd.dat
│       │       ├── fixup_db.dat
│       │       ├── fixup_x.dat
│       │       ├── kernel.img
│       │       ├── kernel7.img
│       │       ├── kernel7l.img
│       │       ├── kernel8.img
│       │       ├── kernel_2712.img
│       │       ├── overlays
│       │       │   ├── README
[etc]
```
this contains the dtb

**Comment by nberlee** [comment]
I confirmed this works with:
```
arch: arm64
platform: metal
secureboot: false
version: v1.9.0
input:
  kernel:
    path: /usr/install/arm64/vmlinuz
  initramfs:
    path: /usr/install/arm64/initramfs.xz
  baseInstaller:
    imageRef: ghcr.io/siderolabs/installer:v1.9.0
  overlayInstaller:
    imageRef: ghcr.io/siderolabs/sbc-raspberrypi:v0.1.0-2-ga802dbb
overlay:
  name: rpi_generic
  image:
    imageRef: ghcr.io/siderolabs/sbc-raspberrypi:v0.1.0-2-ga802dbb
output:
  kind: image
  imageOptions:
    diskSize: 1306525696
    diskFormat: raw
  outFormat: .zst
  ```

**Comment by 95gabor** [comment]
I can confirm this with v1.9.1, but I got boot loop with v1.9.3. I think this is u-boot related, because when I press a key during u-boot and stay in UEFI console (same with staying in GRUB) my RPi 4B is rebooting before decompressing the kernel.

Currently my cluster is reverted to v1.9.1 and working fine.

**Comment by guilhermewolf** [comment]
I tried to boot Talos Linux v1.9.3 in my Raspberry Pi 4B yesterday, and I got the same error that @95gabor.

**Comment by 95gabor** [comment]
@guilhermewolf  Rollback didn’t work for me, I think because the BOOT partition was overwritten with the new U-Boot. I had to do a wiped reinstallation.

**Comment by guilhermewolf** [comment]
@95gabor I just did a fresh install using the v1.9.1, and it worked like a charm. Thank you for your comment!

**Comment by nberlee** [comment]
@95gabor @guilhermewolf I feel responsible, as this maybe my fault introducing https://github.com/siderolabs/sbc-raspberrypi/pull/34 as its the only change.

it maybe a lineending problem.

Are you able to upgrade to 1.9.3 and remove the two lines in boot.txt?

I am going to find some time this weekend to understand whats going on, and why I am not affected. (I stil lhave the configTxtAppend: dtparam=watchdog=on` in my image so maybe having it twice makes it no problem.

I am running hexdump on multiple config.txt to find out what is wrong and why its working for me.

**Comment by 95gabor** [comment]
@nberlee No problem, since it is very easy to recreate a node with Talos 🚀

I can upgrade and test it next week. Should I modify the install image or how can I modify a file in the filesystem?

**Comment by simlun** [comment]
I can mention that I have the same issue with 1.9.3, it goes into a boot loop. I’ve tried installing latest 1.8 first via the SD card and then upgrade to 1.9.3 using the image but that gave me the same boot loop.

Quite new to the game but happy to help in any way I can. Glad to hear 1.9.1 works. I’ll try that for now 🙂

**Comment by nberlee** [comment]
@95gabor just mount the sddisk in another system its on partition 1

I haven't been able to replicate this. It does boot from a 1.9.3 freshly created image on a different pi from a thumbdrive, and i have 1.9.3 for a week now on I pi I use in my cluster. So I cannot help you (@simlun , @guilhermewolf , @95gabor ). You would be better of create a new issue

**Comment by simlun** [comment]
For the record I can confirm I got 1.9.3 booting now when booting from a usb disk. Didn't work from SD card before.

**Comment by samip5** [comment]
Just for the record, this also happens with CM4 and it booting from eMMC

**Comment by vicsufer** [comment]
I've used the SD boot method removing `dtparam=watchdog=on` from `config.txt`and it doesn´t loop reboot anymore. 👍 

> [@95gabor](https://github.com/95gabor) just mount the sddisk in another system its on partition 1
> 
> I haven't been able to replicate this. It does boot from a 1.9.3 freshly created image on a different pi from a thumbdrive, and i have 1.9.3 for a week now on I pi I use in my cluster. So I cannot help you ([@simlun](https://github.com/simlun) , [@guilhermewolf](https://github.com/guilhermewolf) , [@95gabor](https://github.com/95gabor) ). You would be better of create a new issue

**Comment by bhuism** [comment]
Release 1.9.4 boots fine on cm4 again

**Comment by chr0n1x** [comment]
@nberlee I just ran into this. I'm using the rpi imager 1.8.5 on an sd card for the rpi4. I've tried flashing 1.8.4, 1.9.5. and 1.9.4

```yaml
overlay:
    image: siderolabs/sbc-raspberrypi
    name: rpi_generic
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
```

any tips on how I can further debug?
