### ISSUE TITLE
GuC firmware fetch failed N100

### ISSUE THREAD

**Issue by clbx** [siderolabs/talos#9986]
### Description
I'm trying to install talos for the first time using 1.9.0 and an image generated from the image factory using this configuration:
```
customization:
  systemExtensions:
    officialExtensions:
    - siderolabs/i915
    - siderolabs/intel-ucode
    - siderolabs/mei
```

Based on #9369, since I'm using an N100 machine I tried the following image on 1.8.4 to the same results

```
# 1.8.4
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/i915-ucode
            - siderolabs/mei
```

### Logs

![IMG_1063](https://github.com/user-attachments/assets/4d486d8c-3087-418a-9b97-db6c102e69d0)
![IMG_1064](https://github.com/user-attachments/assets/8b2bc320-6ddd-424c-bb74-abe962196d34)

### Environment

- Talos version: 1.9.0
- Kubernetes version: not getting that far
- Platform: Beelink S12 N100 16GB Mini PC
